### ISSUE TITLE
Shiro-app like UI for video player

### ISSUE THREAD

**Issue by castrik** [aniyomiorg/aniyomi#100]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

The current UI for video player is lacking taste, I have a really nice recommendation for this, Shiro-app (https://github.com/Blatzar/shiro-app)

### Other details

it has a UI that looks like it what tachiyomi would have if it had anime features, so I believe we should make the video player like this

it does have a netflix feel to it too, feel free to change it however the community responds to this, like giving the next episode button rounded corners lol

here's a screenshot

![Screenshot_20210707-184938_Shiro](https://user-images.githubusercontent.com/84063610/124966210-da4fe880-e044-11eb-9fdb-de38c9dce3dc.jpg)

**Comment by JahinAbrar** [comment]
The resize option in shiro is really helpfull !!
Aniyomi should provide the zoom to fill/resize option too

**Comment by lazerl0rd** [comment]
For what it's worth, the Shiro app got DMCA'd so here's a "legal" revived version if the Aniyomi developer would like to see the source to base these changes off:
https://github.com/BluetoDark/shiro-app

I didn't check if the player is the same, but I don't see why it wouldn't be.

**Comment by ItamiWasTaken** [comment]
![Screenshot_20220809-183225](https://user-images.githubusercontent.com/99271684/183773323-ed39544e-7d99-4f26-92db-4f7cba85711b.png)
the one from Animiru would be a great improvement aswell
