### ISSUE TITLE
Character Profile 

### ISSUE THREAD

**Issue by Artemis03i** [aniyomiorg/aniyomi#1009]
### Describe your suggested feature

Add a Character profile section where we can add in info on a character and make it fully customizable just like in anilist 

### Other details

I'd like it to be linked with the Manga like when viewing Manga chapters of anime episode we get a section where characters can be added and edited in that Manga or Anime  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Use a different app or site for that feature
