### ISSUE TITLE
Download queue pauses and doesn't download episodes.

### ISSUE THREAD

**Issue by IDontKnow218** [aniyomiorg/aniyomi#1016]
### Steps to reproduce

1.  Go to entry
2. Download episode
3. Wait (or don't wait)

### Expected behavior

Downloads should finish

### Actual behavior

Queue pauses

### Aniyomi version

Preview r6150

### Android version

Android 9

### Device

Samsung Galaxy Note 8, SM-N90F

### Other details

I get this sometimes:

List is empty

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Chris1320** [comment]
My download queue pauses too and there is a notification saying `Downloaded file not found`.

I did not change my download location settings prior to this.

**Comment by IDontKnow218** [comment]
> My download queue pauses too and there is a notification saying `Downloaded file not found`.
> 
> I did not change my download location settings prior to this.

Same here. Only fix for this is to downgrade to r6147.

**Comment by YoussefJarray** [comment]
issue still present.
