### ISSUE TITLE
Coding help: How is the database create?

### ISSUE THREAD

**Issue by Naginipython** [aniyomiorg/aniyomi#1025]
### Describe your suggested feature

Hey, I was wonder if I can have some help understanding Aniyomi code. I'm modifying Tachiyomi to be like Aniyomi for learning reasons, and I can't quite figure out how AnimeDatabase is created. I am trying to re-create aniyomi's app > data > source in Tachiyomi, and the AnimeDatabasehandler can't find AnimeDatabase, nor do I know how to add it. Help would be much appreciated

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Join the discord if you wish to understand, its easier to explain there
