### ISSUE TITLE
Episode not found 

### ISSUE THREAD

**Issue by Abhayanime** [aniyomiorg/aniyomi#1029]
### Steps to reproduce

1.open aniyomi app
2. Try to download an episode
3. After few seconds loading
4. Showing "episode not found"
5. Thiss problem showing like 3 days
6. 

### Expected behavior

Fill not found 

### Actual behavior

Evey times happened 

### Aniyomi version

App version: 0.14.3-6150 

### Android version

" Android 11 "

### Device

Vivo y 15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Should be fixed in the latest version, v6151
