### ISSUE TITLE
Crashing System launcher

### ISSUE THREAD

**Issue by CRUXx11** [aniyomiorg/aniyomi#1046]
### Steps to reproduce

I couldn't replicate as now when I install aniyomi system crashes entirely until I somehow uninstall the app but here is what I did just before that
1. Went to Manga extensions page refreshed multiple times
2. Connected to a VPN and refreshed the Manga and anime extensions multiple times 

### Expected behavior

App should load the extensions

### Actual behavior

App is crashing entire UI and not allowing to even browse through home page even after restarting.
It still crashes if I reinstall

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Device

Realme gt Neo 3

### Other details

I am not able to reinstall the app even after I deleted without keeping any data back

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CRUXx11** [comment]
I uninstalled all the extensions all the folders the app made there is no trace of aniyomi anywhere in the device and still after reinstalling system is crashing . I use aniyomi everyday atleast few hours Not sure why this is happening suddenly there were not any software updates either.

**Comment by Quickdesh** [comment]
If you aren't already, switch to the preview and try again on that version

https://aniyomi.org/download/

^ Download the preview version

**Comment by CRUXx11** [comment]
Preview version is working fine Thanks I was a little scared to test on my new device but anything for debugging.

**Comment by Quickdesh** [comment]
Preview is much more ahead in commits, features and tends to be more stable than stable itself lol.

Good to here it's working.

I'll close this issue. If an issue pops up again, open a new one.

**Comment by CRUXx11** [comment]
Hello I got this system UI issue again where uninstalling is the only fix. The issue occurs when aniyomi is kept open in background and I use any type of system search like app search, search feature in settings. I am not sure why but inbuilt phone search is crashing the entire system UI launcher
