### ISSUE TITLE
Anime only version

### ISSUE THREAD

**Issue by Cuckultry** [aniyomiorg/aniyomi#1047]
### Describe your suggested feature

Can you make a version of the app that removes the manga and leaves just the anime?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Chris1320** [comment]
I'm curious, why? You could just ignore the `Manga` tab of the application.

**Comment by Iron-Squid** [comment]
https://github.com/Quickdesh/Animiru

This is a fork of Aniyomi that does exactly that.

**Comment by Maniacsan** [comment]
> I'm curious, why? You could just ignore the `Manga` tab of the application.

Sometimes, you want just the anime side. Personally, I like having things separate. (Not OP just wanted to explain why you would)
