### ISSUE TITLE
Add source ro watch movies 

### ISSUE THREAD

**Issue by Artemis03i** [aniyomiorg/aniyomi#1050]
### Describe your suggested feature

1. Can you add soap2day as a source to watch movies 
https://wvvw.ssoap2day.to/home

2. Also novel updates to read novel versions of manhwas
https://www.novelupdates.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Aniyomi does not support novels.

To add extensions, make a Github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
