### ISSUE TITLE
Auto add from a list

### ISSUE THREAD

**Issue by 3bdullah-3bdeen** [aniyomiorg/aniyomi#1054]
### Describe your suggested feature

So what if the app can import your list from MAL or any other tracker, and would start searching the sources for titles and add them automatically in your library under a tap called MAL imports for example, and before adding it would organize the search results into three categories, one for titles searched and found exact mach, titles with approximate or close match, and titles with no mach but might be what you're looking for under a different name, and an option to add all for each of these categories, that way whenever you add an anime in your list in MAL you can just add all chapters in the app here instead of searching one by one 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
fixed in #1055

**Comment by LittleFreak** [comment]
While this would be a useful feature at first sight, I see 2 big red flags.

1) If you ad trackers manually, you might have had problems finding the respective entry for your library. False positives would be too annoying tbh.
2)my 'plan to watch' at MAL is already so long, that aniyomi would probably be rate limited before it's process is done.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/381
