### ISSUE TITLE
I want you to add the off feature to the subtitle options.

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#1057]
### Describe your suggested feature

The subtitles change to priority every time the animation is switched.
In the first place,Why isn't it in the priority setting item when the subtitle option has OFF?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ayaaop** [comment]
what

**Comment by sabatachi** [comment]
I have no programming knowledge whatsoever, so I will just give you the gist.
Whenever I start the internal video player, the subtitle settings are reset and I have to do the same operation.
I would therefore like to be able to retain the settings.

**Comment by ayaaop** [comment]
So why did you selfclose this issue
