### ISSUE TITLE
Merge Anime Title

### ISSUE THREAD

**Issue by Artemis03i** [aniyomiorg/aniyomi#1058]
### Describe your suggested feature

It would be great if the same Anime title but Season 1 and 2 could be grouped or merge together.
Having so manny anime in 1 category and trying to find movies and other Season among so many other titles is tiring.

### Other details

Creating a folder in a category and have all the seasons and movies related to one Anime title 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/127
