### ISSUE TITLE
JAV extension request

### ISSUE THREAD

**Issue by BlizzardFreeze** [aniyomiorg/aniyomi#1062]
### Describe your suggested feature

Knowing that there's plenty of hentai anime extension, I wonder if we could have a JAV site extension as well?
Particularly an extension to the missav.com website where full duration JAVs are posted there. Sadly that website didn't have the best control buttons for the video. I think aniyomi could cover up for that. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Please open an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose) instead.
