### ISSUE TITLE
[Preview version] Application crashing when attempting to download anime

### ISSUE THREAD

**Issue by Antside** [aniyomiorg/aniyomi#1067]
### Steps to reproduce

Install 9anime, animepahe or aniwatch extension
Add odd taxi or zom 100 or welcome to the nhk anime to your library
Hit the "download all" button or try to download a specific episode

### Expected behavior

The anime should get downloaded.

### Actual behavior

Instead, I get a prompt telling me that the application has crashed and I need to restart it.

### Crash logs

https://pastebin.com/8APub5sm

### Aniyomi version

App version: 0.14.3-6151 (standard, 43e8dcd1f, 94, 2023-06-15T08:44Z)

### Android version

Android version: 12 (SDK 31)

### Device

Samsung Galaxy S10 (SM-G973U)

### Other details

I was told by a mod on the discord server to post the issue here, I apologize if I did a mistake since I've never reported something on github before.

Edit: Idk if this could help, but the download feature appears to work both on stable and on animiru, but not on preview or on luft's aniyomi.
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Antside** [comment]
Ok it seems like my phone using the french language is what caused download issues in the preview version. Someone also had download issues and his phone was also in french. After changing my phone language to english I have so far been able to download a few different animes on the preview version. I'll keep this issue open for a couple of days in case the problem comes back. Please notify me once this bug is fixed (if it even is the bug here)

**Comment by Prin010** [comment]
app is crashing when searching anything in settings.

**Comment by Quickdesh** [comment]
Shouldnt be an error anymore with the new stringresource system
