### ISSUE TITLE
Need a 'Next episode will be released on' timer like of aniyomi beta, in Aniyomi preview and stable version too ✅

### ISSUE THREAD

**Issue by Abhishek4k20** [aniyomiorg/aniyomi#1069]
### Describe your suggested feature

There must me a timer for ongoing anime saying that next episode will be released on "x" time  ......The feature is already available on Aniyomi beta ....but it would be much better if it arrives quickly for aniyomi preview version too ⭐

### Other details

![IMG_20230719_113402_358](https://github.com/aniyomiorg/aniyomi/assets/132100525/3eaa4b7c-147d-4dc6-94c4-804731c7cd55)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Magrid0** [comment]
where can I find aniyomi beta? in on preview at the moment

**Comment by Abhishek4k20** [comment]
Juat search aniyomi beta on google.....but I'll suggest not to use it as it's buggy
