### ISSUE TITLE
Improve the UI of the app....make it look more like Tachiyomi J2K ! 🌻

### ISSUE THREAD

**Issue by Abhishek4k20** [aniyomiorg/aniyomi#1070]
### Describe your suggested feature

The ui of aniyomi looks boring and older ...so it will be much better if devs bring the ui like Tachiyomi J2K in aniyomi......

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by OmdevShastri** [comment]
Tachiyomi J2K does look good!
