### ISSUE TITLE
When will the next Aniyomi stable update be releasing ?? Please add aniyomi preview and beta features to stable version in this update ...🍀📌

### ISSUE THREAD

**Issue by Abhishek4k20** [aniyomiorg/aniyomi#1071]
### Describe your suggested feature

The stable app hasn't been updated for hell 4 months 😖

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Rejoice!
