### ISSUE TITLE
Link to download video

### ISSUE THREAD

**Issue by josefredohd** [aniyomiorg/aniyomi#1073]
### Describe your suggested feature

Is it possible to get the download link of the videos to download them in the browser or in a download manager? 
Please help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Abhishek4k20** [comment]
You can already set external download manager like ADM downloader in the aniyomi app

**Comment by josefredohd** [comment]
@Abhishek4k20 How do I get the download link?

**Comment by LittleFreak** [comment]
You could long press the download button and a menu will appear.
