### ISSUE TITLE
Episode not playing 

### ISSUE THREAD

**Issue by Chickenshrimps** [aniyomiorg/aniyomi#1075]
### Steps to reproduce

Dramacool source is not working properly
Video is not playing and error is showing
Pls fix it and pls make it to support downloading episodes. Every time for seeing I have to see it in webview

### Expected behavior

Video playing with sources and video quality 

### Actual behavior

Failed to load and constant buffering 

### Aniyomi version

Preview r6453

### Android version

Android 12

### Device

Vivo v21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Wrong repo for your Issue... 😉
