### ISSUE TITLE
New features for Aniyomi 

### ISSUE THREAD

**Issue by Chickenshrimps** [aniyomiorg/aniyomi#1076]
### Describe your suggested feature

I think this aniyomi is cool but it could be better if you could add a suggestion or recommendation button so that it can be easy to navigate and explore new animes or movies. Just like Saikou app it has very cool ui and nice features . I suggest dev to look into it and try doing that into this app it could actually increase the download rate and popularity of this app and even could surpass Saikou to be the best anime/movie/series streaming app there is !!! 
Thx to dev for making this app ♥️♥️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/45
