### ISSUE TITLE
HENTAI.LA EXTENSION

### ISSUE THREAD

**Issue by Jipson2003** [aniyomiorg/aniyomi#1080]
### Steps to reproduce

1. open extension
2. search for any series
3. open any chapter

### Expected behavior

I SHOULD LOAD THE CHAPTERS, I'VE BEEN LOOKING FOR A SOLUTION FOR A LONG TIME.

### Actual behavior

WHEN OPENING A CHAPTER IT DOES NOT LOAD

### Aniyomi version

preview r6151

### Android version

Android 11

### Device

Redmi note 9s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Diegopyl1209** [comment]
no aweonao, cierra esto y abrelo en el repositorio de extensiones : https://github.com/aniyomiorg/aniyomi-extensions

**Comment by Jipson2003** [comment]
ya abri ahi el mes pasado pero no da solucion hasta abri otro para que se agregue la extension del hentaila.tv
