### ISSUE TITLE
Can't open anime episodes using VLC

### ISSUE THREAD

**Issue by Kisfay** [aniyomiorg/aniyomi#1085]
### Steps to reproduce

1. Set external media player as VLC
2. Try to open an episode that would otherwise work with the stock player
3. Unable to open the episode

### Expected behavior

Open the episode by using the VLC player 

### Actual behavior

This text pops up:
Unable to find explicit activity class {org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Device

Poco F5 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Has been fixed
