### ISSUE TITLE
Episode/Chapter title and other info

### ISSUE THREAD

**Issue by laxhya-godara** [aniyomiorg/aniyomi#1086]
### Describe your suggested feature

Is it possible for the app to get the episodes/chapter title and filler episodes data from APIs like anilist,etc. If it is available then the app will get the data and if not the data will be taken from the source extension. If this is possible it would be really helpful especially the filler episode data.
Maybe make a toggle in the library to get data from Source or APIs ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Sounds good. Even if that's not possible, I'd like at least the option to mark them manually, like in the fork Animiru.

**Comment by Quickdesh** [comment]
Sadly there is no solid usable api for episode/ chapter names

For fillermarking it was already rejected
