### ISSUE TITLE
Aniyomi crashes when media button from headset is clicked

### ISSUE THREAD

**Issue by mahendranv** [aniyomiorg/aniyomi#1090]
### Steps to reproduce

1. Connect a bluetooth earphone to device
2. Open aniyomi
3. Press play / pause button

### Expected behavior

Priority wise
1. App should not crash
2. Should play / pause the video if currently playing
3. <TBD> Should ignore the event if no video is in front

### Actual behavior

App crashes

### Crash logs

07-31 10:50:13.069  2585  2585 E AndroidRuntime: FATAL EXCEPTION: main
07-31 10:50:13.069  2585  2585 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 2585
07-31 10:50:13.069  2585  2585 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3047)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:15)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
07-31 10:50:13.069  2585  2585 E AndroidRuntime: 	... 8 more

### Aniyomi version

0.12.3.10

### Android version

Android 7

### Device

Redmi Note 5

### Other details

Did Google search and this issue seems to have workaround.

https://stackoverflow.com/questions/51216279/app-crash-on-headset-button-click

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Hi, do you still have this issue on the latest beta?
https://github.com/jmir1/aniyomi-mpv-beta/releases/latest

**Comment by mahendranv** [comment]
It is fixed in latest beta. Thanks!!
