### ISSUE TITLE
failed to get extension list

### ISSUE THREAD

**Issue by JunkyardCat** [aniyomiorg/aniyomi#1101]
### Steps to reproduce

So i navigate to the sidebar then tap on browse then tap on the anime extensions tab 
on the bottom it says failed to get extention list 
Tachiyomi version 0.12.3.10

### Expected behavior

No error message should appear

### Actual behavior

Error message appeared

### Aniyomi version

0.12.3.10

### Android version

12

### Device

poco f3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Gamer750** [comment]
> ### Steps to reproduce
> So i navigate to the sidebar then tap on browse then tap on the anime extensions tab on the bottom it says failed to get extention list Tachiyomi version 0.12.3.10
> 
> ### Expected behavior
> No error message should appear
> 
> ### Actual behavior
> Error message appeared
> 
> ### Crash logs
> _No response_
> 
> ### Aniyomi version
> 0.12.3.10
> 
> ### Android version
> 12
> 
> ### Device
> poco f3
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
> * [x]  I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
> * [x]  I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I will fill out all of the requested information in this form.

Same problem in android 6

**Comment by OmdevShastri** [comment]
I have been experiencing exactly the same issue for both Anime and Manga extensions. I'm on the same app version and using Android 11.

**Comment by Lumb-Chul** [comment]
Having this issue on Android 13.

**Comment by Lix-kun24** [comment]
Android 10

**Comment by AbdUlrahman097** [comment]
And android 12

**Comment by lowmax205** [comment]
Same issue, android 13

**Comment by NodokaHanamura** [comment]
Able to get the Anime extensions, but not manga, Android 13.

**Comment by ShakibMod** [comment]
Same here

**Comment by jmir1** [comment]
see #843
