### ISSUE TITLE
Instead of downloading apk of extension can't we make it like cloudstream

### ISSUE THREAD

**Issue by Gamer750** [aniyomiorg/aniyomi#1106]
### Describe your suggested feature

Instead of downloading apk of extension can't we make it like cloudstream. Downloading via link inside the app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by lewdpatriot** [comment]
But why?

**Comment by Gamer750** [comment]
> But why?

It would be more easier

**Comment by LittleFreak** [comment]
I'd argue, that tachiyomi does a better job, when it comes to a clean and intuitive UI in the addon section.

**Comment by Quickdesh** [comment]
This system has been changed
