### ISSUE TITLE
default media coder HW+ have color issue and when changed to SW then application is crashing 

### ISSUE THREAD

**Issue by NavMitSharma** [aniyomiorg/aniyomi#1109]
### Steps to reproduce

When you play any anime
1. Then you will see HW+ by default on right top side of internal player. Their color have issue 
2. When changed to SW then application is getting crashed 
![Screenshot_2023-08-17-22-16-08-973](https://github.com/aniyomiorg/aniyomi/assets/113800393/3cf69f51-0c43-439e-b184-795bbbd4d46e)

### Expected behavior

When selected SW application should not be  crashed and it should run perfectly fine 

### Actual behavior

When you play any anime
1. Then you will see HW+ by default on right top side of internal player. Their color have issue 
2. When changed to SW then application is getting crashed 
![Screenshot_2023-08-17-22-16-08-973](https://github.com/aniyomiorg/aniyomi/assets/113800393/3cf69f51-0c43-439e-b184-795bbbd4d46e)

### Aniyomi version

Preview version 

### Android version

Android 8.1.0

### Device

Lenovo tab4 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Should be fixed
