### ISSUE TITLE
Random app closure as i watch videos/scrub videos

### ISSUE THREAD

**Issue by TheNightReaper** [aniyomiorg/aniyomi#1133]
### Steps to reproduce

I am not exactly sure what is causing it, and I am not sure how to recreate it, but I noticed that it happens when I watch a video till the end and then press the next button to move onto the next episode as well as sometimes skipping/scrubbing the video, it randomly closes after watching a number of episodes. I feel it is a player issue.

Also, the external player option causes the app to crash.

### Expected behavior

The player should be able to scrub and change episodes without crashing/forcfully closing.

### Actual behavior

The app forcefully closes without showing the screen that normally shows when the app crashes (like when trying to play a video through the external player option). When tried the universal (large sized apk) of the Aniyomi Preview, it would show a dialog popup after it cforcefully closes that says there is a bug in the app and that I should wait for an update to fix it. But since I moved to the apk for my phone (i think arm 8a or something) the dialog doesn't show up anymore.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/12732464/aniyomi_crash_logs.txt)

Searching the logs by date and time, the recent crash can seen at 09-26 @ time: 23:27 

### Aniyomi version

0.14.3-6151 (Aniyomi Preview R6151)

### Android version

12 (SDK 31) 

### Device

Samsung Galaxy Note 10+ 5g (SM-N976B)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Should be fixed
