### ISSUE TITLE
Pongan que se pueda usar varias funciones/filtros de una misma cosa a la vez por favor 

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi#1139]
### Describe your suggested feature

Lo que dice en título 🦅👍🏻

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by christmovies** [comment]
No entendí

**Comment by Diegopyl1209** [comment]
depende del sitio, si el sitio admite varios filtros a la vez entonces es posible agregar esta funcion, tambien depende de quien haya implementado la extension ya que agregar filtros de por si es pajero
