### ISSUE TITLE
episodes and chapters that i download get deleted every day

### ISSUE THREAD

**Issue by siyacool** [aniyomiorg/aniyomi#1143]
### Steps to reproduce

1. i downloas manga chapters and anime episodes
2. 2. they get deletes at midnight

### Expected behavior

when i download any manga chapters or anime episodes they should remain downloaded right

### Actual behavior

however every single one of them gets deleted at midnight every day and i hv to download them all ovee again and its gettinf so annoying

### Crash logs

idk what this means 

### Aniyomi version

idk the preview version

### Android version

android 

### Device

samsung f23

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
you probably have an aggressive security/cleaner app that's removing aniyomi's file to save space
