### ISSUE TITLE
Failed to get manga extensions list

### ISSUE THREAD

**Issue by pjueon** [aniyomiorg/aniyomi#1153]
### Steps to reproduce

Open [Manga Extensions]

### Expected behavior

The manga Extensions list appears

### Actual behavior

Get an error message: "Failed to get extensions list" and extensions list is empty.

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Device

Samsung Galaxy A53 & WSA on windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Illythia** [comment]
I'm having the exact same issue.

**Comment by FarisArabia** [comment]
i have the same issue too

**Comment by Skiestrixx** [comment]
Same issue

**Comment by pjueon** [comment]
Is PR #1147 somehow related to this issue? I have no clue but I'm just guessing from the comments on it. Maybe I'm completely wrong.

Can someone confirm this?

**Comment by pjueon** [comment]
> Is PR #1147 somehow related to this issue? I have no clue but I'm just guessing from the comments on it. (So maybe I'm completely wrong about this.)
> 
> Can someone confirm this? 
> 

Apparently it's not.
