### ISSUE TITLE
Unnatural word choice in the settings

### ISSUE THREAD

**Issue by pjueon** [aniyomiorg/aniyomi#1155]
### Steps to reproduce

1. Open [Settings]-[Tracking]
2. The option name is [Update progress after reading]

### Expected behavior

The option name should be [Update progress after reading/watching] or something like that.

### Actual behavior

The option name is [Update progress after reading]

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Device

Samsung Galaxy A53 & WSA on Windows 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
it isn't
![Screenshot_20231024-102353_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/54363735/a424efdf-d52c-455e-888e-1f7f49f4e722)

**Comment by Quickdesh** [comment]
Would make more sense to make a new issue for this
