### ISSUE TITLE
Corrupted Downloads

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi#1156]
### Steps to reproduce

Whenever a download in the queue is cancelled, it somehow corrupts the file actually being downloaded.

Steps to reproduce:
1. Start downloading at least two episodes of any anime
2. While one episode is being downloaded, cancel any other episode in the queue
3. Try to play the episode from the completed download.

### Expected behavior

The episode which has completed downloading should play just fine.

### Actual behavior

It gives an error saying "Unrecognised file format".

When cancelling download of the other episode, you can see the download progress glitching out somehow...

### Aniyomi version

Preview r6678

### Android version

Android 13

### Device

Realme XT

### Other details

I also tried playing the downloaded file in VLC Media Player, but even it couldn't play it...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
It also tends to restart the download, when the download list is reordered, added  or something gets canceled.

**Comment by YouSummoner** [comment]
Found a similar issue in [tachiyomiorg#9928](https://github.com/tachiyomiorg/tachiyomi/issues/9928)

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/218
