### ISSUE TITLE
Crash when using Volume/Brightness Gestures

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi#1170]
### Steps to reproduce

1. Start playing a video and immediately switch to fullscreen 
2. As soon as the video starts loading, start operating Volume/Brightness gestures at least until the video starts playing.

### Expected behavior

The video should play normally after loading.

### Actual behavior

If the video starts playing when the user is adjusting the Volume/Brightness gestures, the app freezes and crashes.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/13062106/aniyomi_crash_logs.txt)

### Aniyomi version

Preview r6670

### Android version

Android 13

### Device

Realme XT 

### Other details

This issue has actually bugging me probably from the very first time Aniyomi was released, but I'm reporting it just now...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
u could've just edited #1169 instead of closing it smh

**Comment by YouSummoner** [comment]
This is still happening in version of Preview r6676, here's a screen recording. Please reopen this issue...

https://github.com/aniyomiorg/aniyomi/assets/107224555/256f09c0-6ae3-43ce-99d3-fb4c9ac39a51

**Comment by jmir1** [comment]
Can you send your crash logs please?

**Comment by YouSummoner** [comment]
Yepp, here are the logs.
[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/13064718/aniyomi_crash_logs.txt)

**Comment by jmir1** [comment]
My bad, it should be fixed now.
Apparently it was a regression in Android 13...

**Comment by jmir1** [comment]
> Yepp, here are the logs. [aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/13064718/aniyomi_crash_logs.txt)

LOL I just realized they were already in the original post
