### ISSUE TITLE
downloading problem

### ISSUE THREAD

**Issue by BoakyeDarlington** [aniyomiorg/aniyomi#1173]
### Steps to reproduce

1:downloading of an episodes sometimes does not displays where it has reached(0℅-100%)

### Expected behavior

I love to see downloading of any episodes been display in the notification center always

### Actual behavior

I've noticed this,sometimes downloading an episode will not display the percentage of where the episode have reach(0℅-100℅)
It only shows downloading on the notifications panel but when u go to file manager to find the episode been downloading,u will see the episode size is increasing everytime u refresh the file manager page meanwhile in the app its showing downloading.I don't know if u get what am trying to say,it will finish downloading without showing how speed or how it downloaded. Pls fix this bug

### Aniyomi version

App version: 0.14.6-6678 

### Android version

Android 11

### Device

huawei nova 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/238
