### ISSUE TITLE
Fix Blob Issue 

### ISSUE THREAD

**Issue by NewbieAnimeManga** [aniyomiorg/aniyomi#1182]
### Steps to reproduce

Hmm. In some sources where we have to open in webview...
1. Open webview
2. Cloudfare Issue
3. Then suddenly a blob website open automatically
4. After pressing back
5. It open automatically..
6. That's all

### Expected behavior

Maybe Some kinda code isse idk!

### Actual behavior

Well that happen when I tried to solve cloudfare issue!

### Aniyomi version

0.14.6-6678

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
Fixed
