### ISSUE TITLE
(feature request) More automatic update times

### ISSUE THREAD

**Issue by ziomek64** [aniyomiorg/aniyomi#1186]
### Describe your suggested feature

Hello,
I kind of don't understand why minimum automatic update time is 12 hours. That's a lot. Would be great to have 6,3,1 or even custom. I don't see why not at least.

### Other details

I'm on latest preview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
The increased frequency of automatic updates will impose an additional, unnecessary burden on website owners, potentially incentivizing them to hinder extension development or even blacklist Aniyomi from accessing their site.

**Comment by ziomek64** [comment]
@abdallahmehiz still, doesn't seem 12 hours too much? What about 6
