### ISSUE TITLE
Anime Information Inbuilt browser.

### ISSUE THREAD

**Issue by NewbieAnimeManga** [aniyomiorg/aniyomi#1187]
### Describe your suggested feature

The feature I'm requesting it should be work with the tracker if some-one logged into Anilist or myanimelist account they have an Inbuilt browser(Not necessary) in both anime and manga section, anime for anime section and Manga for manga section, Because anilist and myanimelist both provides anime and manga info, so it's use to watch anime when the anime have many seasons or ova etc...
Thanks! If you give a thought on that.

### Other details

![Screenshot_2023-11-01-09-49-37-37_8fdea02c47a76e0fe7eccbf0ee9f2748](https://github.com/aniyomiorg/aniyomi/assets/109711661/2baa4e0d-7338-465e-95ca-8e3d4b6cf57a)
![Screenshot_2023-11-01-09-49-20-29_8fdea02c47a76e0fe7eccbf0ee9f2748](https://github.com/aniyomiorg/aniyomi/assets/109711661/4eeb116b-a62f-477c-b1a6-8d6b5315808d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Sorry, I didn't understand, what you are suggesting. Can you elaborate?

**Comment by fakebhai** [comment]
> Sorry, I didn't understand, what you are suggesting. Can you elaborate? 

as far as I understood suggestion is to add webview or something of anilist and mal in both anime and manga section so it could be checked how many seasons or ovas it got including other information.

**Comment by LittleFreak** [comment]
> > Sorry, I didn't understand, what you are suggesting. Can you elaborate?
> 
> as far as I understood suggestion is to add webview or something of anilist and mal in both anime and manga section so it could be checked how many seasons or ovas it got including other information.

That's not necessary, because u already can access this info, with the tracking section.
Just click at the (f. Example) MAL icon, and the info will be opened.

**Comment by fakebhai** [comment]
> > > Sorry, I didn't understand, what you are suggesting. Can you elaborate?
> > 
> > as far as I understood suggestion is to add webview or something of anilist and mal in both anime and manga section so it could be checked how many seasons or ovas it got including other information.
> 
> That's not necessary, because u already can access this info, with the tracking section.
> Just click at the (f. Example) MAL icon, and the info will be opened. 

yup just track, click on 3 dots and press open in browser. 
@NewbieAnimeManga if this fulfills your issue then you can close it or you may need to give more details about what you actually want here.

**Comment by NewbieAnimeManga** [comment]
Ok! lemme make it more easy just like you said click on three dots and open in webview it kinda hassle to users.. so we need some kinda shortcuts to see information/details about anime/manga when we open the anime/manga.

**Comment by NewbieAnimeManga** [comment]
> > > > Sorry, I didn't understand, what you are suggesting. Can you elaborate?
> > > 
> > > 
> > > as far as I understood suggestion is to add webview or something of anilist and mal in both anime and manga section so it could be checked how many seasons or ovas it got including other information.
> > 
> > 
> > That's not necessary, because u already can access this info, with the tracking section.
> > Just click at the (f. Example) MAL icon, and the info will be opened.
> 
> yup just track, click on 3 dots and press open in browser. @NewbieAnimeManga if this fulfills your issue then you can close it or you may need to give more details about what you actually want here.

It will be Quite helpful. If you Directly add this feature on Aniyomi!

**Comment by fakebhai** [comment]
your suggestion likely won't work unless u track it, and I'm not so sure if someone would need that much "quick access" to information page. regardless of it you'll still need to pick which tracker's webview you want to see. so after all this effort you'll still save only 1 click. I don't see how it could be that useful at this point.

still you can ask for "open in webview" instead of "open in browser"
but again if you have default link set up for mal and anilist apps (if you have them) it'll open directly in their apps. which could be better than using webview.

**Comment by abdallahmehiz** [comment]
there is an UNOFFICIAL Anilist extension thet you can use if you want
it can't play videos tho

**Comment by abdallahmehiz** [comment]
also if a feature affects the manga section you should suggest it to [Tachiyomi](https://github.com/tachiyomiorg/tachiyomi).

**Comment by abdallahmehiz** [comment]
> Link please?
[Anime one](https://cdn.discordapp.com/attachments/395875798399320066/1170919370495631401/en-anilist_1.zip)
[Manga one](https://cdn.discordapp.com/attachments/395875798399320066/1170919427823370250/en-anilist_2.zip)

**Comment by NewbieAnimeManga** [comment]
> > Link please?
> 
> [Anime one](https://cdn.discordapp.com/attachments/395875798399320066/1170919370495631401/en-anilist_1.zip) [Manga one](https://cdn.discordapp.com/attachments/395875798399320066/1170919427823370250/en-anilist_2.zip)

Thanks so now I'm closing this issue okay!
