### ISSUE TITLE
Unable to Create backup on Android TV OS

### ISSUE THREAD

**Issue by fitrimasaan** [aniyomiorg/aniyomi#1194]
### Steps to reproduce

1. Go to "**Backup and restore → Create backup**"
2. Click "**Create**"

### Expected behavior

I want to create backup to transfer all my watch list to the beta version. After clicking **Create**, a backup window should open to ask the user on where to save the backup file.

### Actual behavior

Unable to create backup. After clicking the Create button, an error text showing **"You don't have an app that can do this"** will pop up.

This also happened when you clicked on **Backup location**.

### Aniyomi version

0.12.3.10

### Android version

Android 12 (Android TV OS)

### Device

Mecool KM2 (LEAP-S1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by juniornff** [comment]
This happens because Android TVs do not have the Storage Access Framework (SAF) implemented. Since Aniyomi uses that Framework it cannot access folders (which is the first thing for file creation)

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/162
