### ISSUE TITLE
[🐛BG] CBZ files with a lot of pages takes a long time to open.

### ISSUE THREAD

**Issue by eltonllc** [aniyomiorg/aniyomi#1199]
### Steps to reproduce

1. Import or download a manga/comic in CBZ format.
2. The file should have around 100+ pages (tested with 100+ page files).

### Expected behavior

The file should open immediately.

### Actual behavior

The file takes atleast a minute to open.

### Aniyomi version

r6668 - r6691

### Android version

Android 13

### Device

Realme Pad, Vivo IQOO Neo 7

### Other details

The issue started r6668 onwards. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
have you tried this on tachiyomi?

**Comment by eltonllc** [comment]
> have you tried this on tachiyomi?

Yes, it works fine on the latest Tachiyomi

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
