### ISSUE TITLE
New anime source 

### ISSUE THREAD

**Issue by Artemis03i** [aniyomiorg/aniyomi#1200]
### Describe your suggested feature

Can you please add Animeflix as a new source to watch anime🙏
https://animeflix.live/

![Screenshot_20231108_172312_Chrome](https://github.com/aniyomiorg/aniyomi/assets/130247369/5a862acd-906a-4d6c-ae30-125f0356688c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
please suggest new extensions in the [extensions repo](https://github.com/aniyomiorg/aniyomi-extensions)
