### ISSUE TITLE
Extension Aniwave : Jseondecoding exception 

### ISSUE THREAD

**Issue by ashazalzaman** [aniyomiorg/aniyomi#1204]
### Steps to reproduce

When l open aniwave

>  Open any anime

> Doesn't show episode

> It says

> 
![Screenshot_2023-11-11-12-53-03-195_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/150506687/70bd60cf-f81e-4b14-9e4b-b2fa272bfd57)
JsonDecodingException: Expected start of
the object '{', but had 'EOF' instead at path: S
JSON input: ..... Server at 9anime.e\t'\k.net
Port 80</address>

</body></htm|>

### Expected behavior

This should happen 
![Screenshot_2023-11-11-12-59-20-386_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/150506687/61b8a495-5c39-4c36-9056-40fb114822cd)

### Actual behavior

But this happened 
![Screenshot_2023-11-11-12-53-03-195_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/150506687/7f75d1cc-8c7f-463e-9919-9fcbad43ba87)

### Aniyomi version

Preview r6691

### Android version

Android 10

### Device

Redmi Note 7 pro max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Wrong repo, you're supposed to report extension errors in the [aniyomi-extensions](https://github.com/aniyomiorg/aniyomi-extensions) repo.
Also, it was already reported and it's a known issue (see aniyomiorg/aniyomi-extensions#2483), so this is a duplicate.

**Comment by ashazalzaman** [comment]
> Wrong repo, you're supposed to report extension errors in the [aniyomi-extensions](https://github.com/aniyomiorg/aniyomi-extensions) repo.
> Also, it was already reported and it's a known issue (see aniyomiorg/aniyomi-extensions#2483), so this is a duplicate.

Sorry l didn't know l am using GitHub for 1st time
