### ISSUE TITLE
Add source Extension for TV shows and movies 

### ISSUE THREAD

**Issue by Chickenshrimps** [aniyomiorg/aniyomi#1205]
### Describe your suggested feature

Source 1 : https://tvshows4mobile.org/
Source 2 : https://o2tvseries2.com/
Source 3 : https://hdmp4mania2.com/

### Other details

Pls add this extension asap 
Thank you
 #659 #791 #401 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
please suggest new extensions in the [extensions repo](https://github.com/aniyomiorg/aniyomi-extensions)
