### ISSUE TITLE
Failed to extract videos 

### ISSUE THREAD

**Issue by GamingStrat** [aniyomiorg/aniyomi#1213]
### Steps to reproduce

1.open the app
2.go to anime library
3.open up an anime ep

### Expected behavior

Instead of opening the episode and letting me watch.

### Actual behavior

Instead it says Failed to extract episode and does let me watch and makes I have to open and close the app multiple times to get it working again.

### Aniyomi version

App version: 0.14.6-6691 (standard, 5fd00d4a1, 105, 2023-11-02T23:11Z) 

### Android version

Android 13

### Device

Samsung s23

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
is it on a specific source/extension?

**Comment by PrimeTwister** [comment]
How did you get to fix it?

**Comment by GamingStrat** [comment]
I fixed it using another extension this only happened to me while using aniwatch

**Comment by PrimeTwister** [comment]
> I fixed it using another extension this only happened to me while using aniwatch

Yeah did the same, can I know which extension you use now?

**Comment by GamingStrat** [comment]
> > I fixed it using another extension this only happened to me while using aniwatch
> 
> Yeah did the same, can I know which extension you use now?

I used gogoanime

**Comment by Quickdesh** [comment]
Do not recommend any source extensions. This is to prevent any single one becoming too popular and getting Tachiyomi or Aniyomi blacklisted from using it.

**Comment by GamingStrat** [comment]
> Do not recommend any source extensions. This is to prevent any single one becoming too popular and getting Tachiyomi or Aniyomi blacklisted from using it.

Oh ok that's my bad
