### ISSUE TITLE
Gogo extension not working 

### ISSUE THREAD

**Issue by 47anjithantony** [aniyomiorg/aniyomi#1218]
### Steps to reproduce

Open the gogo extension and you see that it's not opening as intended
![Screenshot_2023-11-26-00-54-22-584_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/85072474/0bde38f3-ca0b-4692-9fb6-af070a423a81)

### Expected behavior

The extension should open like any other available extensions
![Screenshot_2023-11-26-00-56-21-817_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/85072474/ac2f52aa-6c3b-4721-82de-7949633901e4)

### Actual behavior

![Screenshot_2023-11-26-00-54-22-584_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/85072474/72bb0ec0-e7f3-46b3-8911-efee7b50d1a8)

### Aniyomi version

App version: 0.14.6-6691 (standard, 5fd00d4a1, 105, 2023-11-02T23:11Z) Android version: 13 (SDK 33) Android build ID: TP1A.220624.014 Device brand: Xiaomi Device manufacturer: Xiaomi Device name: pissarroin Device model: 21091116I Device product name: pissarroin

### Android version

Android 13

### Device

Xiaomi Mi 11i

### Other details

I think this has to with the existing server not working anymore.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
report extension specific issues in the [extensions repo](https://github.com/aniyomiorg/aniyomi-extensions)
