### ISSUE TITLE
[▶️PL] Player settings not showing statics page options properly

### ISSUE THREAD

**Issue by fakebhai** [aniyomiorg/aniyomi#1234]
### Steps to reproduce

open any anime, tap on 3 dots right above, check the last option.

### Expected behavior

show normal sized options which are readable (just make it scrollable or small) 

### Actual behavior

small buttons, can't read. 
![Screenshot_2023_1208_160457](https://github.com/aniyomiorg/aniyomi/assets/101493467/0e57bc0a-95b9-4308-861e-ed47d1ac308c)

### Aniyomi version

Preview r6691

### Android version

Android 12

### Device

Iqoo 3 5G

### Other details

my phone's Body Dimensions	158.5 x 74.9 x 9.2 mm (6.24 x 2.95 x 0.36 in)
Display size 6.44 inches, 100.1 cm2 (~84.3% screen-to-body ratio)
resolution 1080 x 2400 pixels, 20:9 ratio (~409 ppi density)
I'm using this font size 
![Screenshot_2023_1208_161236](https://github.com/aniyomiorg/aniyomi/assets/101493467/8d1e312e-8b46-4443-88bb-0179555fff07)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
https://cdn.discordapp.com/attachments/1009128186774302761/1192180015933178048/Screenshot_20240103-192608.jpg

**Comment by Quickdesh** [comment]
Will need to be updated to match filter chips and scrollable, yes
