### ISSUE TITLE
App always crash when in background & i recall it

### ISSUE THREAD

**Issue by M7MDE7EGAZY** [aniyomiorg/aniyomi#1236]
### Steps to reproduce

Open manga then go to other app for a while then return scroll fir a while then it crashes 

### Expected behavior

Just continue reading sctolling

### Actual behavior

crashed after some scrolls

### Crash logs

--------- beginning of main
12-12 04:00:32.407  4223 21713 E OpenGLRenderer: Unable to match the desired swap behavior.
12-12 04:00:37.457  4223  4223 E ACRA    : ACRA caught a FileNotFoundException for xyz.jmir.tachiyomi.mi.debug
12-12 04:00:37.457  4223  4223 E ACRA    : java.io.FileNotFoundException: /storage/emulated/0/Android/data/xyz.jmir.tachiyomi.mi.debug/cache/reader_-324874467/034.jpg: open failed: ENOENT (No such file or directory)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at libcore.io.IoBridge.open(IoBridge.java:574)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.loader.DirectoryPageLoader$getPages$4$streamFn$1.invoke(Unknown Source:4)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonPageHolder$setImage$2.invokeSuspend(SourceFile:6)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:107)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(SourceFile:13)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
12-12 04:00:37.457  4223  4223 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fdacf6d, Dispatchers.Main]
12-12 04:00:37.457  4223  4223 E ACRA    : Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at libcore.io.Linux.open(Native Method)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8692)
12-12 04:00:37.457  4223  4223 E ACRA    : 	at libcore.io.IoBridge.open(IoBridge.java:560)
12-12 04:00:37.457  4223  4223 E ACRA    : 	... 9 more
12-12 04:00:37.601 31838 31838 E i.mi.debug:acra: Unknown bits set in runtime_flags: 0x40000000
12-12 04:00:37.663 25643 25643 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@fb14b1f
12-12 04:00:37.711 25643 14419 E OpenGLRenderer: Unable to match the desired swap behavior.
12-12 04:00:37.843 31838 31882 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-12 04:00:37.844 31838 31880 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
App version: 0.14.6-6691 (standard, 5fd00d4a1, 105, 2023-11-02T23:11Z)
Android version: 14 (SDK 34)
Android build ID: RMX3301_14.0.0.89(EX01)
Device brand: realme
Device manufacturer: realme
Device name: RED8ACL1
Device model: RMX3301
Device product name: RMX3301RU

### Aniyomi version

14.6-6691

### Android version

14

### Device

Realme gt 2 pri

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/1066
