### ISSUE TITLE
Arreglen la plataforma de te desde aniyomi

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi#1237]
### Describe your suggested feature

Entras y está todo sobre teología y demás 

### Other details

No funciona 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Diegopyl1209** [comment]
ni puta idea de lo que estas hablando
