### ISSUE TITLE
Default Audio and Sub

### ISSUE THREAD

**Issue by AGA2707** [aniyomiorg/aniyomi#1241]
### Describe your suggested feature

Give as an option to choose a default Playback Quality, Audio language and subtitle language.

### Other details

I prefer watching anime on Japanese audio and with English subtitle. But everytime I watch an anime I always change the Audio in Japanese with HardSub: en-US. It's better if we can change it in default of our choice, so everytime we watch it's always on our choice default and downloading can't give us an option to choose an quality, audio and subtitle. It's always in English audio with no sub.
![Screenshot_2023-12-20-16-56-56-875_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi/assets/148602118/72b65fc2-a223-4c51-879c-6cb8bca408bd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
For the quality option, you can already do that by going into the extension settings
Also, you should switch to [Preview](https://aniyomi.org/download/)

**Comment by AGA2707** [comment]
@abdallahmehiz yeah I see it, thanks man.

**Comment by AGA2707** [comment]
Reopened. I see that not all extension have that feature to select a default audio and sub. And sometimes quality is not always stay on your preferred quality.

**Comment by Claudemirovsky** [comment]
> Not all extension have that feature to select a default audio and sub.

That's not a issue with aniyomi, but with the extensions; so you should create a issue for each extension that you want this feature in the [aniyomi-extensions](https://github.com/aniyomiorg/aniyomi-extensions) repo.

> Sometimes quality is not always stay on your preferred quality.

That's not even our fault. Sources often only offer a single video quality, or only lacks the one you wanted, and we can't do anything about that.
