### ISSUE TITLE
[🐛BG] Add back the bottom navigation / default tab option

### ISSUE THREAD

**Issue by NewbieAnimeManga** [aniyomiorg/aniyomi#1247]
### Describe your suggested feature

Create a feature in appearance in more settings, Create Switch to Anime only, Manga only and both.
When Anime only is clicked, It will hidden all settings and features related to manga same goes to manga only. It will hidden all Anime related settings & features.
Both will make normal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Character95** [comment]
make option to switch anime and manga places for someone who only read manga on phones and sometimes watch anime, when someone  prefer manga displayed first when starting the app

**Comment by abdallahmehiz** [comment]
This feature used to exist in earlier version but got removed to hasten the release of stable. I'll work on bringing it back soon

**Comment by abdallahmehiz** [comment]
since general settings were obliterated on merging stable, it got caught in the crossfire.
i am working on bringing it back at this very moment :+1:
