### ISSUE TITLE
[Feature Request] Add play internal feature 

### ISSUE THREAD

**Issue by X-Oracle** [aniyomiorg/aniyomi#1250]
### Describe your suggested feature

as you know in anime episode lists we can hold download button and open a list where we can download external or internal or play external. It is a fantastic feature.

What I requested is that adding play internal in the list .
Why? Because we can select quality in the menue in this way (sometimes I'm in low bandwidth network and I want to play in 360 but going to change global is too much for just one episode)

Thanks for your works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
you can just enter the player and change it in video settings within the player
