### ISSUE TITLE
Adding individual refresh button

### ISSUE THREAD

**Issue by Taihanonhub** [aniyomiorg/aniyomi#1255]
### Describe your suggested feature

For each anime, there should be a refresh button. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
You can swipe down to refresh

**Comment by fakebhai** [comment]
and if you want a button then you can switch to preview version and go to 3 dots and click on refresh
