### ISSUE TITLE
Low Frame Rate on 1080p/doodstream mirror

### ISSUE THREAD

**Issue by memejames** [aniyomiorg/aniyomi#1256]
### Steps to reproduce

Go to any anime and select 1080p or doodstream mirror
Watch for 5 or more
U will experience low frame rate 

### Expected behavior

We should not experience Frame drops on 1080p / doodstream mirror

### Actual behavior

When I watch animes on 1080p or doodstream mirror
I see frame drops alot of time

### Aniyomi version

0.12.3.10

### Android version

Android 12

### Device

Samsung Tablet A7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Should be fixed in new update
