### ISSUE TITLE
Tachiyomi Removed All Of It's Extensions 

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi#1258]
### Describe your suggested feature

Add the option to allow user addable extension repos.
And change the default manga repo to [tachiyomiorg/extensions](https://github.com/tachiyomiorg/extensions)

### Other details

This change is added to the original Tachiyomi app in [tachiyomiorg#10289](https://github.com/tachiyomiorg/tachiyomi/issues/10289)

Please make this change quickly as currently the Aniyomi app isn't able to lookup any manga extensions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Arthur-Stuhl** [comment]
@YouSummoner On top of that It would probably be better to point it towards the web-archive older version of the Tachiyomi  website that did have the extensions and fetch it from there as a temporary solution so you can still access the extensions directly from within the app without much to any user input.

**Comment by YouSummoner** [comment]
Web archive doesn't actually save the extensions or any of the backend
files, it just saved how an website looked at a certain time.
So it isn't possible, we'll just have to fine alternate repositories.

**Comment by Arthur-Stuhl** [comment]
@YouSummoner They actually do and I would love to provide a link as proof if it isn't against the repositories rules.

**Comment by Arthur-Stuhl** [comment]
I haven't been able to read the code of conduct yet is what I mean by that.

**Comment by hollowshiroyuki** [comment]
good bot

The fix is actually being worked on with an undefined ETA. Please do not share links for extensions.

**Comment by YouSummoner** [comment]
Ohh, it actually works, but it isn't a real repository on github, dunno if
they will actually be able to implement this, also even if they do users
won't be able to get updates from the extension's devs that way...

**Comment by Arthur-Stuhl** [comment]
@hollowshiroyuki I am deeply sorry I did not mean to go against the rules it it won't happen again.
