### ISSUE TITLE
Failed to get extention list 

### ISSUE THREAD

**Issue by Artemis03i** [aniyomiorg/aniyomi#1260]
### Steps to reproduce

Extention list doesn't load 
![Screenshot_20240109_143429_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/130247369/5f8b79eb-9c61-45e1-a1f1-618689f4149b)

### Expected behavior

Load extention list

### Actual behavior

 Doesn't load extention list 

### Aniyomi version

0.14.6-6691

### Android version

13

### Device

SM-A236U

### Other details

App version: 0.14.6-6691 (standard, 5fd00d4a1, 105, 2023-11-02T23:11Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.A236USQS4CWJ5
Device brand: samsung
Device manufacturer: samsung
Device name: a23xq
Device model: SM-A236U
Device product name: a23xqsq

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by matiasramirez1601** [comment]
Tachiyomi deleted his repository and only has his own extensions. You can still find the other extensions from this repository but since aniyomi does not have support for changing repositories you have to search for them manually 
https://github.com/keiyoushi/extensions?tab=readme-ov-file

**Comment by Secozzi** [comment]
@matiasramirez1601 Do not share third party extension repositories.

**Comment by Arthur-Stuhl** [comment]
I wonder if it would be a possibility to add these extensions back through the web archive which would be a pretty safe official way to do so.

**Comment by v1shaL-b** [comment]
I am getting same issue.
I don't know any other ways to add mangas. 
How do I do it ?

**Comment by eferreira2** [comment]
Same issue. Latest preview broke ALL manga extensions. The app has been rendered completely useless.
