### ISSUE TITLE
KissKH new episodes are not playable anymore gives error

### ISSUE THREAD

**Issue by SouravPaul553h** [aniyomiorg/aniyomi#1262]
### Steps to reproduce

![Screenshot_20240110-210655_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/76051387/f056a385-7897-46e3-bda6-fa5be3a681b2)
Gives this error on the newer episodes when refreshing a series for new episodes

### Expected behavior

It should play the new episodes fine as usual

### Actual behavior

So instead it shows the above error "loading failed"

### Aniyomi version

Preview r6691

### Android version

Android 12

### Device

Samsung Galaxy M31

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by darxtat** [comment]
Happening again with all episodes even older ones
