### ISSUE TITLE
[▶️PL] Audio cracking a lot 

### ISSUE THREAD

**Issue by Samson8976** [aniyomiorg/aniyomi#1265]
### Steps to reproduce

Everytime I play any video it starts to crack the audio . I have been facing this issues for months and I have been hoping it would get fixed in the next update please help me fix it . I think it's the hardware decoding something. I switch to HW+ and the issues gets worse . Even in SW it's bad . The audio cracks a lot .

### Expected behavior

I hoped the audio would be more clear but it isn't 

### Actual behavior

The audio cracks a lot 

### Aniyomi version

version 0.14.6-6691

### Android version

Android 12

### Device

Realme c12 

### Other details

https://github.com/aniyomiorg/aniyomi/assets/116457473/8fc7de2d-e045-4146-bdb4-1622fdf5bf3a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by joshuak91** [comment]
Please this is very important

**Comment by fakebhai** [comment]
> Please this is very important 

can try `settings - player - advanced player settings - debanding` change your debanding according to your need or try them all.

also you can try updating your app to see if that solves it.

**Comment by joshuak91** [comment]
How can I change it . Can u give me an example

**Comment by joshuak91** [comment]
Alright I have found it . Let me try it out

**Comment by joshuak91** [comment]
It's still cracking. The sound itself is the issue or probably the decoding issues . It's the first time i am ever facing this kind of issue.

**Comment by joshuak91** [comment]
Tried it but it's still not working

**Comment by nacho00112** [comment]
Me too right now I'm reinstalling the old version from [releases](https://github.com/aniyomiorg/aniyomi/releases) since it was working fine.

**Comment by nacho00112** [comment]
Indeed, I did make a backup before uninstalling but had the fear that the backup wouldn't work on the old version but it worked, and the player is working too

**Comment by joshuak91** [comment]
Really. Which version are you using and can u send me the version

**Comment by nacho00112** [comment]
Aniyomi v0.12.3.9

**Comment by abdallahmehiz** [comment]
You should update

**Comment by nacho00112** [comment]
> You should update

Yeah I agree but the bug make me stick to the old version,
I'm gonna be trying the new ones

**Comment by Secozzi** [comment]
This is most likely an issue with mpv. Use mpv as an external player and see if the problem still persists. If it does, there's not much we can do. If it doesn't please open a new issue.
