### ISSUE TITLE
[⭐FR] add option to efault to "all" search instead of "pinned"

### ISSUE THREAD

**Issue by jeyjai** [aniyomiorg/aniyomi#1266]
### Describe your suggested feature

Currently it defaults to only searching pinned sources every time you open the global search, so it would be nice if you could add the option to disable this and set the default search to "all" instead.
TachiJ2k has this option, but without the "pinned", "all" and "has results" buttons on the search screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Makrennel** [comment]
Yeah, this was the previous behaviour, now the pinning system has forced an extra button press to get this behaviour back unless you just pin all the sources which renders pinning pointless. Would be nice to have this as an option – also perhaps an option for defaulting to only showing those which have results now that's an option.

**Comment by ThunderousLeft** [comment]
Seriously, why is this still a thiing? Pinned filter should not be default. Trash.

**Comment by Secozzi** [comment]
Pin the sources you want to do a global search on.

**Comment by Makrennel** [comment]
> Pin the sources you want to do a global search on.

So just pin everything if you want to default search every source and make pinning pointless to begin with?

**Comment by Secozzi** [comment]
That's one way to use it, but not everyone will use it that way and those will benefit from the separation between pinned and all.
