### ISSUE TITLE
[🐛BG] Crashed when switching from anime extension tab to manga extension tab

### ISSUE THREAD

**Issue by ahmedziyaanmuhamed** [aniyomiorg/aniyomi#1267]
![aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/13915566/aniyomi_crash_logs.txt)

How to recreate

https://github.com/aniyomiorg/aniyomi/assets/86360363/878b8836-db8f-42c1-8d14-392335e6a662

**Comment by ahmedziyaanmuhamed** [comment]
Sorry i posted this on the wrong repo

**Comment by Quickdesh** [comment]
Does this keep happening or was it just this once?
sometimes quick movements crash the app

**Comment by ahmedziyaanmuhamed** [comment]
> Does this keep happening or was it just this once?
> sometimes quick movements crash the app

No

**Comment by ahmedziyaanmuhamed** [comment]
A similar bug was in Tachiyomi preview a few updates before

**Comment by jmir1** [comment]
Why did you mark it as completed?
