### ISSUE TITLE
[🐛BG] Reader Tap Zones not registering correctly

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#1268]
### Steps to reproduce

1. Open Aniyomi
2. Open the manga you want to read.

### Expected behavior

It should be able to tap the side instead of scrolling. This makes it easier to read with one hand.

### Actual behavior

But for some reason in left and right tap mode the top edge moves up, but nowhere else. 

### Aniyomi version

Preview r7443

### Android version

Android 10 

### Device

Pixel 2

### Other details

I think it is a problem caused by the last update. There was no such problem before.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by shinobs** [comment]
Hello,

Same issue for me.

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
