### ISSUE TITLE
Add alternative to SAF for Android TV.

### ISSUE THREAD

**Issue by juniornff** [aniyomiorg/aniyomi#1271]
### Steps to reproduce

1. Update to the latest version of Aniyomi (Aniyomi Preview r7443)
2. Open the app
3. Select the color theme and press next
4. Try to select a forder for Aniyomi

### Expected behavior

Shows the user interface to select the desired folder 

### Actual behavior

Get a error message "there is no app to select files"
[IMG_20240112_002223](https://github.com/aniyomiorg/aniyomi/assets/33964836/dc527a43-4047-4ca9-9649-ca0f0ea533f8)

### Aniyomi version

Aniyomi Preview r7443

### Android version

Android TV 11

### Device

TCL Smart TV

### Other details

Have to do the setup process with a mouse because  of the navigation issues.

I was able to bypass the setup process by selecting the color theme (not clicking next) and pressing the back button on the remote control.

Even though **I can not longer play videos from local source** because I couldn't select a Aniyomi Forder to begin with 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by juniornff** [comment]
At the end I had to rollback to **Aniyomi Preview r6691** because without the SAF I can't even play a local video.

**Comment by jmir1** [comment]
We need to implement a custom file picker for Android TV. Putting this here as an example of how to do it.
I'll keep it in mind as one of the things that need fixing.
https://github.com/moneytoo/Player/commit/1a98142fd0a83a2e45ec222fb14976e531d2e242

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/162
