### ISSUE TITLE
[🐛BG] App crashing when scrolling in download menu

### ISSUE THREAD

**Issue by jyash8** [aniyomiorg/aniyomi#1273]
### Steps to reproduce

1. Add about 20 downloads to anime.
2. Go to download menu and scroll down.
3. When you reach the end app will crash

### Expected behavior

App should not crash.

### Actual behavior

App crashed.

### Crash logs

App version: 0.15.2.0-7443 (standard, a009b7e07, 118, 2024-01-12T00:17Z)
Android version: 13 (SDK 33; build TP1A.220624.014)
Android build ID: TP1A.220624.014
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: xagain (xagain)
Device model: 22041216I
WebView: Android System WebView 120.0.6099.210

--------- beginning of main
01-13 10:56:06.160 19312 19312 E hiyomi.mi.debug: Not starting debugger since process cannot load the jdwp agent.
01-13 10:56:06.325 19312 19341 E SQLiteLog: (283) recovered 47 frames from WAL file /data/data/xyz.jmir.tachiyomi.mi.debug/databases/tachiyomi.animedb-wal
01-13 10:56:06.325 19312 19342 E SQLiteLog: (283) recovered 36 frames from WAL file /data/data/xyz.jmir.tachiyomi.mi.debug/databases/tachiyomi.db-wal
01-13 10:56:06.400 19312 19353 E chromium: [0113/105606.400175:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
01-13 10:56:07.172 19312 19403 E SQLiteLog: (284) automatic index on C(anime_id)
01-13 10:56:07.172 19312 19403 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
01-13 10:56:07.236 19312 19312 E FBI     : Can't load library: dlopen failed: library "libmagtsync.so" not found
01-13 10:56:07.256 19312 19346 E libMiGL : libmigl:This GPU version is note support Variable Shading Rate
01-13 10:56:07.258 19312 19346 E libEGL  : pre_cache appList: ,,
01-13 10:56:13.741 19312 19445 E SQLiteLog: (284) automatic index on C(manga_id)
01-13 10:56:13.741 19312 19445 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-13 10:56:57.624 19312 19346 E libEGL  : pre_cache appList: ,,
01-13 10:57:31.029 19312 19312 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (19744) crash detected (code -1).
--------- beginning of crash
01-13 10:57:54.171 19312 19312 E AndroidRuntime: FATAL EXCEPTION: main
01-13 10:57:54.171 19312 19312 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi.debug, PID: 19312
01-13 10:57:54.171 19312 19312 E AndroidRuntime: java.util.concurrent.CancellationException
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at androidx.compose.foundation.pager.DefaultPagerNestedScrollConnection.onPostScroll-DzOQY0M(SourceFile:21)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at androidx.compose.ui.input.nestedscroll.NestedScrollNode.onPostScroll-DzOQY0M(SourceFile:6)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at androidx.compose.ui.input.nestedscroll.NestedScrollNode.onPostScroll-DzOQY0M(SourceFile:25)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at androidx.compose.ui.input.nestedscroll.NestedScrollNode.onPostScroll-DzOQY0M(SourceFile:25)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at androidx.compose.ui.viewinterop.AndroidViewHolder.onNestedScroll(SourceFile:11)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at com.github.junrar.io.RawDataIo.dispatchNestedScrollInternal(SourceFile:102)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(SourceFile:210)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:904)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8136)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
01-13 10:57:54.171 19312 19312 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
01-13 10:57:54.322 19977 19977 E g:error_handler: Not starting debugger since process cannot load the jdwp agent.
01-13 10:57:54.421 19977 20033 E SQLiteLog: (283) recovered 5 frames from WAL file /data/data/xyz.jmir.tachiyomi.mi.debug/databases/tachiyomi.animedb-wal
01-13 10:57:54.422 19977 20034 E SQLiteLog: (283) recovered 164 frames from WAL file /data/data/xyz.jmir.tachiyomi.mi.debug/databases/tachiyomi.db-wal
01-13 10:57:54.510 19977 20051 E chromium: [0113/105754.507335:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
01-13 10:57:54.510 19977 20051 E chromium: [ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
01-13 10:57:55.067 19977 19977 E FBI     : Can't load library: dlopen failed: library "libmagtsync.so" not found
01-13 10:57:55.077 19977 20037 E libMiGL : libmigl:This GPU version is note support Variable Shading Rate
01-13 10:57:55.078 19977 20037 E libEGL  : pre_cache appList: ,,
01-13 10:57:55.103 19977 20037 E libEGL  : pre_cache appList: ,,

### Aniyomi version

r7443

### Android version

Android 13

### Device

Redmi k50i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GL513** [comment]
Same here. Will provide additional information

**Comment by Quickdesh** [comment]
Known issue, it is currently being looked into

**Comment by GL513** [comment]
App version: 0.15.2.0-7447 (standard, b8515be09, 118, 2024-01-13T21:34Z)
Android version: 14 (SDK 34; build UQ1A.240105.004.A1)
Android build ID: UQ1A.240105.004.A1
Device brand: google
Device manufacturer: Google
Device name: husky (husky)
Device model: Pixel 8 Pro
WebView: Android System WebView 120.0.6099.194

https://github.com/aniyomiorg/aniyomi/assets/83085846/4d78ac47-df89-4330-9908-4f81681a75c5

https://github.com/aniyomiorg/aniyomi/assets/83085846/a7c4ac6b-50e0-4b30-8a18-ee86dd77d94f

![aniyomi_crash_logs (3).txt](https://github.com/aniyomiorg/aniyomi/files/13930135/aniyomi_crash_logs.3.txt)

![aniyomi_crash_logs (1).txt](https://github.com/aniyomiorg/aniyomi/files/13930137/aniyomi_crash_logs.1.txt)

![aniyomi_crash_logs (2).txt](https://github.com/aniyomiorg/aniyomi/files/13930136/aniyomi_crash_logs.2.txt)



Crashes when scrolling quickly, but not slowly

**Comment by GL513** [comment]
Of course github cuts my recordings

**Comment by abdallahmehiz** [comment]
fixed in 00883792cd9db419f0cc517e1d5124945099775a
