### ISSUE TITLE
Bottom navigation style

### ISSUE THREAD

**Issue by Illythia** [aniyomiorg/aniyomi#1283]
### Steps to reproduce

I can not change the bottom navigation style anymore.

### Expected behavior

There use to be an option to change that.

### Actual behavior

I have two manga sections instead of an history section once I click more

### Aniyomi version

preview r7447

### Android version

Android 13

### Device

Realme 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/1247
