### ISSUE TITLE
[❓QS] I am infinitely too stupid for update

### ISSUE THREAD

**Issue by JackDSRS** [aniyomiorg/aniyomi#1286]
### Steps to reproduce

To reproduce this, perhaps getting old.

The only documentation is for Tachiyomi, not TachiyomiSY, and I'm having these exact same problems. I searched Githubv search engines, Discord (which is a hot mess) and could come up with nothing like an Aniyomi or TachiyomiSY specific upgrade guide.

Do I restore first, then change the settings, then delete the old resouces, and install the new APK repos? What happens to my old libraries? If I do all that, why am I restoring in the first place or should I be restoring something specific only?

Fortunately I had backed up my old APK's and could restore everything, but this is embarrassing. I've been using computers since punch card programming and have never struggled like this.

### Expected behavior

This should be able to be easy to upgrade.

I used to be able to download to a custom directory on my SD card. I could backup to  different directory that holds all my app backups on my SD  card. Even an idiot like me could install, remove, and uninstall extensions. I could easily change thumbnails and descriptions. There were things I thought could use improvement, but overall, I loved it and used the hell out of it.

### Actual behavior

Now I understand nothing. Upgrading and restoring brought nothing over, especially not the download and backup settings. Trying the new APK repos didn't show squat and I only used the official APK's. All my old sources show as untrusted.

### Aniyomi version

0.15.2.0

### Android version

Android 12

### Device

Samsung Tab A and Note 10+

### Other details

Went off for bourbon, cold compress, pipe, and a long nap after hours of screwing with these...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
The way I'm interpreting this issue is, you didn't use the backup feature in the app but just backed up the apk file?

**Comment by ziomek64** [comment]
I don't even understand what are you trying to do man XD
Make backup, install aniyomi or whatever and restore with that file

**Comment by JackDSRS** [comment]
> The way I'm interpreting this issue is, you didn't use the backup feature in the app but just backed up the apk file?

I used the backup feature. I went back to the old version with the old APK.

**Comment by JackDSRS** [comment]
> I don't even understand what are you trying to do man XD Make backup, install aniyomi or whatever and restore with that file

Welp, planned to try it again today.

**Comment by ziomek64** [comment]
> > I don't even understand what are you trying to do man XD Make backup, install aniyomi or whatever and restore with that file
> 
> Welp, planned to try it again today. Still have bourbon left.

Stop drinking first

**Comment by JackDSRS** [comment]
> > > I don't even understand what are you trying to do man XD Make backup, install aniyomi or whatever and restore with that file
> > 
> > 
> > Welp, planned to try it again today. Still have bourbon left.
> 
> Stop drinking first

Ouch!

**Comment by jmir1** [comment]
Oh i get it now. Try reading this guide, maybe it helps you understand. https://aniyomi.org/docs/faq/storage
In earlier versions, you could move your download directory to any directory (outside of the Aniyomi directory where other files are kept.) Now, you need to set one directory for everything.
And I guess that the extensions showing untrusted is normal because tachiyomi recently removed almost all of their extensions.

**Comment by JackDSRS** [comment]
I'm off to try again. I'll use a sync program to move the backups. You gave me some ideas. Thank you.

If something makes this easier for senile farts like me, I'll share it.
