### ISSUE TITLE
update_check_no_new_updates pop up not working

### ISSUE THREAD

**Issue by fakebhai** [aniyomiorg/aniyomi#1298]
### Steps to reproduce

go to `more - about` click on `check for updates`

### Expected behavior

it should show pop up of no new updates

### Actual behavior

nothing popped up 

### Aniyomi version

r7454

### Android version

Android 12

### Device

Iqoo 3 5G

### Other details

there's still string for update_check_no_new_updates in every language so I suppose it's intended to show this and not removed. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.1](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by thegreatwhite0801** [comment]
I think i see the problem."GetApplicationRelease.Result.NoNewUpdate" in AboutScreen retrieves the string resource but no toast msg.
