### ISSUE TITLE
Chapter info not aligned in the center like before

### ISSUE THREAD

**Issue by yousifmuhammad544** [aniyomiorg/aniyomi#1299]
### Steps to reproduce

1. Open a manga
2. Read a chapter
3. At the end it writes info about previous and next chapter (is not aligned also wrong font ) 

### Expected behavior

1. Open a manga
2. Read a chapter
3. At the end of the chapter it should write previous and next chapter names ( aligned in the middle with old font

### Actual behavior

The text is aligned left and the font sucks i think its also bigger the older one was better please revert
![Screenshot_20240115-223253_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/84289536/08a6be13-a446-4bfe-9c44-deb34483ec30)

### Aniyomi version

0.15.2.0-7443

### Android version

Android 12

### Device

Samsung galaxy a23

### Other details

Please align the text and revert to the old font for chapter transitions i love you guys soooo much thanks in advance hope you guys have an awesome day <3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.1](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
intended design change
