### ISSUE TITLE
Maybe a feature named "backup option" is missing in recent versions.

### ISSUE THREAD

**Issue by Livid96** [aniyomiorg/aniyomi#1301]
### Steps to reproduce

There is a feature named Back option that offered us custom options for automatic backup is  maybe missing in new version. I think because of this, automated backup files are not containing trucker login info token.
![orca-image-625408090](https://github.com/aniyomiorg/aniyomi/assets/128045849/21b15feb-e5a6-4c59-9c72-492b4af219bd)

### Expected behavior

Nothing to say

### Actual behavior

Nothing to say

### Crash logs

Nothing to say

### Aniyomi version

0.15.2.1

### Android version

9

### Device

Nothing to say

### Other details

Nothing to say

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.1](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mostidaniel** [comment]
I think that option now gets asked when you create a backup. Although I don't think this applies to automatic backups.
