### ISSUE TITLE
Important suggestion 

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi#1304]
### Describe your suggested feature

Although this may seem a bit demanding, you could create an automated system for custom sources where we can copy the page link and paste it into AniYomi, and the system takes care of adding it as a source for anime or manga. We would only be responsible for small tasks, and if by chance the source works well, we can upload it to the AniYomi extension repository to make it public, and you can take care of the maintenance. This way, the app will grow faster in terms of obtaining extensions, and the automated system can improve with each AniYomi and Tachiyomi update.

### Other details

Please I hope you take my suggestion into account in the future.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.1](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
Coming soon in AniYomi AI (TM)

**Comment by jmir1** [comment]
It isn't possible since every source website is different, there is no way to create an extension just by knowing its URL.
