### ISSUE TITLE
correction of an important suggestion

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi#1314]
### Describe your suggested feature
Brothers, don't suck my balls 😠🤬 What I wanted was to be able to convert any URL from any page into an Aniyomi extension, and now they tell me that they removed the manga from the app and that if I want manga extensions, I have to use external repositories. Plus, if I want a manga extension for a specific site, that repository must have that extension. So there's no freedom at all, what's the point? Please fix this shit.

### Other details

please and thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Sadwhy** [comment]
Is this what y'all have to deal with daily? @Secozzi

**Comment by Secozzi** [comment]
Unfortunately

**Comment by abdallahmehiz** [comment]
lol didn't even know this exists

**Comment by Secozzi** [comment]
@Alex178190282 manga extensions are beyond our control, we have nothing to do with this and there is nothing we can do about it. Also, converting any URL to an extension isn't technically possible, each extension needs to be hand-crafted for each site.

**Comment by jmir1** [comment]
Btw @Alex178190282 please don't be rude and don't open any more issues with bad titles like "important suggestion".
It really doesn't help anyone and I'll have to block you from opening issues if you don't stop this...

**Comment by Sadwhy** [comment]
> > ### Describe your suggested feature
> > Brothers, don't suck my balls 😠🤬 What I wanted was to be able to convert any URL from any page into an Aniyomi extension, and now they tell me that they removed the manga from the app and that if I want manga extensions, I have to use external repositories. Plus, if I want a manga extension for a specific site, that repository must have that extension. So there's no freedom at all, what's the point? Please fix this shit.
> > ### Other details
> > please and thank you
> > ### Acknowledgements
> > 
> > * [x]   I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> > * [x]   I have written a short but informative title.
> > * [x]   If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
> > * [x]   I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> > * [x]   I will fill out all of the requested information in this form.
> 
> It sounds like you're frustrated with the recent changes in Aniyomi regarding manga extensions and repositories. Here's a breakdown of your concerns and some possible steps to address them:
> 
> ### Understanding the Issue
> 1. **Removed Manga from the App**: It seems that Aniyomi has removed the built-in manga sources from the app.
> 2. **External Repositories**: Now, you need to use external repositories to get manga extensions.
> 3. **Specific Site Extensions**: The repositories must contain the specific manga site extensions you need.
> 
> ### Possible Solutions
> 1. **Find and Add Repositories**:
>    
>    * Look for trusted repositories that host the manga extensions you need. Some popular repositories might already include a wide range of extensions.
>    * To add a repository, go to Aniyomi settings, find the "Extensions" section, and add the URL of the repository.
> 2. **Creating Custom Extensions**:
>    
>    * If the specific manga site you want isn't available in existing repositories, you might consider creating a custom extension. This requires some technical knowledge of how Aniyomi extensions work.
>    * Aniyomi extensions are generally based on the Tachiyomi extension framework. You can refer to Tachiyomi's [developer documentation](https://tachiyomi.org/extensions/) to learn how to create and manage extensions.
> 3. **Community Support**:
>    
>    * Engage with the Aniyomi community. There might be other users who have faced similar issues and can offer solutions.
>    * Join forums, Discord channels, or Reddit threads related to Aniyomi or Tachiyomi to get help from experienced users and developers.
> 
> ### Steps to Add a Repository in Aniyomi
> 1. **Open Aniyomi**: Launch the app on your device.
> 2. **Go to Settings**: Navigate to the settings menu.
> 3. **Extensions**: Find the section related to extensions.
> 4. **Add Repository**: Input the URL of the repository you want to add.
> 
> ### Resources for Help
> * **Aniyomi GitHub**: Check the official Aniyomi GitHub page for updates and documentation.
> * **Aniyomi Discord**: Join the Aniyomi Discord server for real-time help from the community.
> * **Reddit**: Visit subreddits like r/Tachiyomi or r/Aniyomi for community support and advice.
> 
> By following these steps and utilizing community resources, you should be able to find or create the manga extensions you need for Aniyomi. If you have any specific URLs or more detailed requirements, feel free to share, and I can guide you further on how to integrate them into Aniyomi.

ChatGPT ahhh reply

**Comment by abdallahmehiz** [comment]
> * **Reddit**: Visit subreddits like r/Tachiyomi or r/Aniyomi for community support and advice.

We don't have an official subbredit
