### ISSUE TITLE
video not playing !!

### ISSUE THREAD

**Issue by soulreaper006** [aniyomiorg/aniyomi#1317]
### Steps to reproduce

1.open the app.
2.go to any extensions app.
3.select a show then any episode.
4.just press play.

### Expected behavior

to play the video.

### Actual behavior

when i press play at first its loading for 3s the it got stack . no buffering no visuals just a black screen.

### Aniyomi version

0.15.2.2

### Android version

android 13

### Device

wsa v2311.40000.5.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
You are using WSA. Make sure you have downloaded the correct APK for your architecture.

**Comment by Samiul011** [comment]
Try changing the Hardware decoding mode in Player Settings to HW or SW. Worked for me.

**Comment by soulreaper006** [comment]
> Try changing the Hardware decoding mode in Player Settings to HW or SW. Worked for me.

Thanks for replay. 
I tried decoding setting HW to SW and it work,
