### ISSUE TITLE
Invalid Image Due to & Character in DataSaver.kt (Line 84)

### ISSUE THREAD

**Issue by Afam007** [aniyomiorg/aniyomi#1319]
### Steps to reproduce

1. Use any extension that has Image Urls containing the & character  with the bandwidthhero data saver in the reader

### Expected behavior

The & character in the image Url should be encoded and not used with the bandwidth hero request as an additional parameter In the file [DataSaver.kt](https://github.com/aniyomiorg/aniyomi/blob/master/app/src/main/java/aniyomi/util/DataSaver.kt), at line 84, 

### Actual behavior

The & character in the $imageUrl variable is used  as an additional parameter to the bandwidthhero server, causing an invalid image

### Aniyomi version

App version: 0.15.2.2-7473 

### Android version

Android 12

### Device

Samsung m11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Afam007** [comment]
@jmir1 🥲🥲🥲

**Comment by jmir1** [comment]
https://github.com/aniyomiorg/aniyomi/commit/39ba4324e2d0283d87e7d6b84b91e4846fa3639c
