### ISSUE TITLE
Setting 1DM as downloader app preference fails to download

### ISSUE THREAD

**Issue by krispykiq** [aniyomiorg/aniyomi#132]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Aniyomi version

0.12.1.1

### Android version

Android 9

### Device

Redmi Note 8

### Steps to reproduce

1. Go to settings and set downloader app preference to 1DM
2. Download any episode of any anime

### Expected behavior

Add download to 1DM and start to download episode.

### Actual behavior

The download button becomes a red error sign which means download failed.

### Other details

This may be related to the fact setting downloader app preference to None the app gives you options to browsers for some reason instead of the actual download manager.

**Comment by davidzh7** [comment]
this happen to me as well, need some answer

**Comment by Quickdesh** [comment]
This has been fixed/added in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"
