### ISSUE TITLE
[BUG] App not compatible with recent versions of miui

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi#1320]
### Describe your suggested feature

Could you make the app compatible with my phone? I recently switched cell phones and now I have Hyper OS and Android 14, and the app no longer works.

### Other details

Please, I need the app, it's the best one I've found for multimedia content in my whole life.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by musab-olurode** [comment]
What's the issue specifically? I currently use hyperos and android 14 too and the app works just fine.

**Comment by jmir1** [comment]
What exactly isn't working, we need more info.

**Comment by abdallahmehiz** [comment]
can you try updating your webview through the playstore?

**Comment by Secozzi** [comment]
Create a new issue and include more info.
