### ISSUE TITLE
drag down update to check for new chapters not working

### ISSUE THREAD

**Issue by hachem39** [aniyomiorg/aniyomi#1322]
### Steps to reproduce

none

### Expected behavior

n ew chapters in the update manga tab

### Actual behavior

drag down update to check for  my favorites manga  new chapters not working but If i update each manga separately i get updates 

### Aniyomi version

latest

### Android version

8

### Device

GR 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It's either an extension issue, or it's related to [smart updates](https://aniyomi.org/docs/faq/updates/smart)
