### ISSUE TITLE
Video speed playback

### ISSUE THREAD

**Issue by tom2411** [aniyomiorg/aniyomi#1323]
### Describe your suggested feature

Hello, 
I think it's great that you've added the option to increase the speed of the video you're watching. However, I think that adding a slider is not the most practical option.
In my opinion, it would be useful to be able to add predefined speeds underneath that you could save, so that you'd just have to click on them and not use the slider. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
I you press the playback speed, you can already cycle between 0.5 and 2.0 in 0.25 increments. Only if you long-press, the slider comes up.

**Comment by tom2411** [comment]
Yes but maybe could it be practical to be able to define what increment we want and also if we want to speed up even more than 2x the slider is nothing than precise.
