### ISSUE TITLE
Subtitles are not offset when crop to fit option is used

### ISSUE THREAD

**Issue by Nek-12** [aniyomiorg/aniyomi#1324]
### Steps to reproduce

1. Open a sub stream
2. Select "cropped to screen"

### Expected behavior

Subtitles are offset by crop amount to be visible

### Actual behavior

Subtitles are cut because they are positioned for the uncropped stream

### Aniyomi version

0.15.2.2

### Android version

14

### Device

OnePlus 11 

### Other details

There is also no option to specify subtitle offset manually in sub settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
for my own reference: https://github.com/mpv-player/mpv/issues/11714

**Comment by jmir1** [comment]
I added some options that achieve this for subtitle tracks that aren't in the ASS format: https://github.com/aniyomiorg/aniyomi/commit/02c5672d29887ce6b5f2214778417f42675c179c
If you want the same behaviour for ASS subtitles, you need to enable "Override ASS subtitles" here: 
![grafik](https://github.com/aniyomiorg/aniyomi/assets/43830312/cf042d93-ef51-4a1f-b530-a99a3b51be0d)
