### ISSUE TITLE
 [🚀DL] known multithread issues

### ISSUE THREAD

**Issue by giorgionegro** [aniyomiorg/aniyomi#1325]
### Steps to reproduce

Problems with mt downloads

### Expected behavior

1. pause and resume should work
2. aniyomi should delete partial temp file
3. should not crash, should not create a toast in a non ui thread

### Actual behavior

    Issue 1: Unable to Pause and Resume a Multi-Threaded Download
        Description: The application is currently unable to pause and resume a multi-threaded download.

    Issue 2: AniYomi Unable to Restart Download if Temporary Files Exist
        Description: AniYomi is unable to restart a download if temporary files (e.g., partn.tmp files) still exist in the download folder.

    Issue 3: NullPointerException when Toast is Created on Unauthorized Thread
        Description: Encountering a java.lang.NullPointerException when there is an error during the download process. It appears that the application is attempting to create a toast from an unauthorized thread, leading to the exception.

### Aniyomi version

0.15.2.2

### Android version

android 13

### Device

should be device agnostic 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Also the download fails or completes with an empty (`0MB`) / unfinished file when:

- adding new downloads
- deleting existing downloads
- Reordering download list
No matter the extension source.

**Comment by giorgionegro** [comment]
with the new download rewrite I can no longer reproduce this issues, hopefully they do not come back

**Comment by LittleFreak** [comment]
> with the new download rewrite I can no longer reproduce this issues, hopefully they do not come back

Is the rewite still pre-release only?

**Comment by fakebhai** [comment]
> > with the new download rewrite I can no longer reproduce this issues, hopefully they do not come back
> 
> Is the rewite still pre-release only?

yes, preview only
