### ISSUE TITLE
edit (mark previous as read) from the one you tap on

### ISSUE THREAD

**Issue by Character95** [aniyomiorg/aniyomi#1327]
### Describe your suggested feature

hold on chapter and mark previous as read from the one you tap on to all previous

### Other details

when you need to migrate manga/anime to another source you need to mark all chapters as read and for that you need to mark as read two times when you tap on last chapter
![Screenshot_2024-01-19-19-38-14-790_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/25694091/6e1c1e95-9a2c-47d0-ab09-350b969e49dd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Character95** [comment]
![IMG_20240119_200349](https://github.com/aniyomiorg/aniyomi/assets/25694091/ddcb56a7-a656-487b-b1cd-c1bc97eb4829)

**Comment by jmir1** [comment]
you can click the select all button in the top right after selecting an item and then mark all as read.

**Comment by Character95** [comment]
ok i forgot that option
 thanks
