### ISSUE TITLE
Library updating issue

### ISSUE THREAD

**Issue by Shohu1** [aniyomiorg/aniyomi#1333]
### Steps to reproduce

When I update the library for new anime, it just loads some of them and leaves all other thus new animes never get updated and i need to update all of them manually by going to each anime's episode view section.

### Expected behavior

It should update all the new animes eposodes and also send a notification about the updated episode.

### Actual behavior

It loads 5 animes and never updates the rest even tho new episode is out.

### Aniyomi version

0.15.2.2

### Android version

Android 12

### Device

Samsung galaxy tab S6 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Prin010** [comment]
Same problem

**Comment by sayedhfatimi** [comment]
https://github.com/aniyomiorg/aniyomi/issues/1346#issuecomment-1907149996

This solution fixed this same problem reported in another issue for me

**Comment by Secozzi** [comment]
It's either an extension issue, or it's related to [smart updates](https://aniyomi.org/docs/faq/updates/smart)
