### ISSUE TITLE
I only have 4 manga extensions 3 of those are repeated 3 times

### ISSUE THREAD

**Issue by HippiePanda1** [aniyomiorg/aniyomi#1335]
![Screenshot_20240120_193231_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/157237093/c4a9e040-4928-4bb0-8633-0a8f6d29c399)
### Steps to reproduce

1. Open app
2. Go to Browse
3. Go to Manga Extensions

### Expected behavior

All manga extensions should be there like the last time I used it.

### Actual behavior

However when I open Manga Extensions it only shows these 4 (and their duplicates)

### Crash logs

I don't know what to put in here but I've got a Samsung A54 5g.

### Aniyomi version

Stable 0.15.2.2

### Android version

Android 13

### Device

Samsung Galaxy A54 5G

### Other details

I don't know if this is a feature or and Update I missed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by HippiePanda1** [comment]
![Uploading Screenshot_20240120_193231_Aniyomi.jpg…]()

**Comment by Diegopyl1209** [comment]
enter in this link to add the new repo: https://diegopyl1209.github.io/tachiyomi-working-repo/tachiyomi/vO8HlVwaZw4.index.min.json

**Comment by fakebhai** [comment]
> enter in this link to add the new repo: https://diegopyl1209.github.io/tachiyomi-working-repo/tachiyomi/vO8HlVwaZw4.index.min.json

damn, it works, I clicked on it and I can see like 400 extensions. THANKS!!

**Comment by HippiePanda1** [comment]
> enter in this link to add the new repo: https://diegopyl1209.github.io/tachiyomi-working-repo/tachiyomi/vO8HlVwaZw4.index.min.json

I've probably been trolled but that takes me to a club penguin video

**Comment by abdallahmehiz** [comment]
@Diegopyl1209 do not share 3rd party extensions

**Comment by abdallahmehiz** [comment]
Looks like i've been mega trolled

**Comment by abdallahmehiz** [comment]
Sorry diego lol

**Comment by HippiePanda1** [comment]
So I mean is there a way to fix this or no.

**Comment by abdallahmehiz** [comment]
There is... You have to add 3rd party extensions repos to get access to extensions not provided by aniyomi. We will not give you such repos, but they're out there so search for them and they're easy to find.

**Comment by HippiePanda1** [comment]
> There is... You have to add 3rd party extensions repos to get access to extensions not provided by aniyomi. We will not give you such repos, but they're out there so search for them and they're easy to find.

I'm new to this whole thing so I don't know how to do that. Can you tell me how.

**Comment by Lesjerkun** [comment]
Same 🥲
