### ISSUE TITLE
Cannot update manga extensions

### ISSUE THREAD

**Issue by anishkn04** [aniyomiorg/aniyomi#1338]
### Steps to reproduce

1. Go to Browse
2. Go to Manga Extensions
3. Update any extension

### Expected behavior

After clicking the update button, should download and update the latest version of that extension

### Actual behavior

The latest version is downloaded but doesn't get installed.

### Crash logs

App version: 0.15.2.2-7473 (standard, 70efdd8f0, 120, 2024-01-17T12:35Z)
Android version: 12 (SDK 31; build SP1A.210812.016)
Android build ID: SP1A.210812.016
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: merlin (merlin_eea)
Device model: M2003J15SC
WebView: Android System WebView 121.0.6167.71

Problematic extensions:
- MadaraDex
  Installed: 1.4.33 / Available: 1.4.34
  Obsolete: false
- MangaForFree.net
  Installed: 1.4.33 / Available: 1.4.34
  Obsolete: false

### Aniyomi version

0.15.2.2-7473

### Android version

Android 12

### Device

Redmi Note 9

### Other details

I use Shizuku as installation method.
I can install new extensions, but can't update the already available ones

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.2](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Kojirremer** [comment]
They do get updated. It's just it got awkward AF. After you download and install the extension, you MUST close the program completely. When you restart the program, it will be installed and marked as untrusted. Allow it and you are done.

**Comment by aemogie** [comment]
If this is due to using a third party extension repo, I found out that you should uninstall the old tachiyomi extension first then reinstall it from the third party repo.

**Comment by DuPont9029** [comment]
> If this is due to using a third party extension repo, I found out that you should uninstall the old tachiyomi extension first then reinstall it from the third party repo.

this solved the problem for me:
- I uninstalled and reinstalled aniyomi (I recommend backing up read manga EXCLUDING SOURCES AND EXTENSIONS)
- I uninstalled the old extensions previously installed
- I downloaded the new extensions from the repo of: https://github.com/keiyoushi/extensions?tab=readme-ov-file (lifesaver) 
- I re-downloaded the extensions and authorized them
-now everything works

**Comment by abdallahmehiz** [comment]
@DuPont9029 do not share 3rd party extensions

**Comment by DuPont9029** [comment]
> @DuPont9029 do not share 3rd party extensions

I'll rewrite the comment in a better way that doesn't create issues.
this solved the problem for me:
- I uninstalled and reinstalled aniyomi (I recommend backing up read manga EXCLUDING SOURCES AND EXTENSIONS)
- I uninstalled the old extensions previously installed, to do this you have to go to the phone settings, search for the installed extensions and uninstall them
- I installed the new extensions from the internet
- I re-downloaded the extensions and authorized them
-now everything works
