### ISSUE TITLE
[FR/Bug] Back Gesture to Custom Start Screen

### ISSUE THREAD

**Issue by mostidaniel** [aniyomiorg/aniyomi#1343]
### Describe your suggested feature

In current versions of Aniyomi, there is an option to set a "Start Screen". This option modifies the behavior of the application such that on startup, instead of the "Anime" tab menu being displayed, it will be the chosen custom Start Screen.

### The Issue

As of Aniyomi Preview version r7477, when doing the "back gesture" on the top page of any tab, it will disregard the custom Start Screen setting and navigate to the "Anime" tab. This is true even after restarting the app.

#### Suggested Behavior

When initiating the back gesture on any tab, it will change the tab to the custom start screen chosen.

#### Actual Behavior

The back gesture navigates to the "Manga" tab, ignoring the chosen Start Screen setting.

Just to be clear, here's an image summarizing everything:
![](https://i.imgur.com/YERk7DT.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
so you want the back gesture to go back to the the start screen set by the user? got it.

**Comment by mostidaniel** [comment]
Yes, that is correct. Thank you!
