### ISSUE TITLE
[Bug] More tab screen's back button doesn't navigate to the home screen.

### ISSUE THREAD

**Issue by ArthurFGrillo** [aniyomiorg/aniyomi#1345]
### Steps to reproduce

If **"Start Screen"** is set to **"Manga"** and **"Navigation Style"** is set to **"Move Manga to the More tab"** when you open the app, it softlocks you to the manga library with no way to open the settings and change it, the only way I found to open it is to create a widget shortcut to the anime tab and open the app from there. The **"<-"** button doesn't even seem to work

### Expected behavior

There should be a button or something to open the setting in these conditions

### Actual behavior

You get softlocked

### Crash logs

It did not crash, so only prevents you from exiting the gallery

### Aniyomi version

0.15.2.3

### Android version

Android 13

### Device

Motorola edge 30 ultra

### Other details

I could not find this in another issue, sorry if is a dupe : /

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
you can use the back gesture on your phone, or press the back button next to the title of the screen to go back to the home screen

**Comment by ArthurFGrillo** [comment]
Thanks for the reply, I just tested and that's true, must have missed it since I use the gesture back button. Still, the in-app back button should still be made to work.

**Comment by mostidaniel** [comment]
I am using Aniyomi Preview r7477. It appears that if I reproduce the steps above, there is a non-functional back button on the action bar area. Fixing the button should resolve this issue.
