### ISSUE TITLE
Library doesn't update 

### ISSUE THREAD

**Issue by neptune2716** [aniyomiorg/aniyomi#1346]
### Steps to reproduce

1. Add mangas/anime to your library
2. Scroll down in the update tab
3. Issue here

### Expected behavior

Library should update automatically and in the update tab, not only on the tab of the specific manga

### Actual behavior

 Issue here : nothing append when i scroll down in tje update tab, i don't have the updating library notification and my library doesn't update at all neither.
4. Manga/anime still update if i scroll down in their specific detailled tab.

### Crash logs

No crash

### Aniyomi version

App version: 0.15.2.3 (standard, 5e4ea90, 120, 2024-01-21T18:44Z) Android version: 12 (SDK 31; build SKQ1.210908.001 test-keys) Android build ID: SKQ1.210908.001 test-keys Device brand: Redmi Device manufacturer: Xiaomi Device name: sweet (sweet_eea) Device model: M2101K6G WebView: Android System WebView 120.0.6099.210

### Android version

Android 12

### Device

Xiaomi note 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ErikTorres1133** [comment]
Desmarca esta opcion en actualizaciones inteligentes:
![Screenshot_2024-01-23-18-34-28-389_xyz jmir tachiyomi mi debug-edit](https://github.com/aniyomiorg/aniyomi/assets/77590891/556e9d00-eb9f-4fd7-94f6-edcc5e822f03)

**Comment by sayedhfatimi** [comment]
> Desmarca esta opcion en actualizaciones inteligentes:
> 
> ![Screenshot_2024-01-23-18-34-28-389_xyz jmir tachiyomi mi debug-edit](https://github.com/aniyomiorg/aniyomi/assets/77590891/556e9d00-eb9f-4fd7-94f6-edcc5e822f03)
> 
> 

This fixed the issue for me

**Comment by Prin010** [comment]
Thanks it worked for me too

**Comment by V4G4X** [comment]
Unfortunately turning on "Predict next release time" in Smart Updates didn't fix it for me.

**Comment by CapZeus30** [comment]
Vaya conque era eso. Nunca note qué esa opción existia. Disculpa las molestias y gracias por informarme

**Comment by CapZeus30** [comment]
> Desmarca esta opcion en actualizaciones inteligentes:
> ![Screenshot_2024-01-23-18-34-28-389_xyz jmir tachiyomi mi debug-edit](https://github.com/aniyomiorg/aniyomi/assets/77590891/556e9d00-eb9f-4fd7-94f6-edcc5e822f03)
> 

Vaya conque era eso. Nunca note qué esa opción existia. Disculpa las molestias y gracias por informarme

**Comment by Secozzi** [comment]
It's either an extension issue, or it's related to [smart updates](https://aniyomi.org/docs/faq/updates/smart)

**Comment by Pol354** [comment]
> Desmarca esta opcion en actualizaciones inteligentes:
> ![Screenshot_2024-01-23-18-34-28-389_xyz jmir tachiyomi mi debug-edit](https://github.com/aniyomiorg/aniyomi/assets/77590891/556e9d00-eb9f-4fd7-94f6-edcc5e822f03)
> 

GRACIAS!!!
