### ISSUE TITLE
Player Turned Purple While Playing 

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi#1354]
### Steps to reproduce

1. Play an episode 

### Expected behavior

Stream should play normally

### Actual behavior

Don't know why, but while in the middle of playing the episode, the entire stream turns purple, and seeking back or forward at any point doesn't help either.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/14041477/aniyomi_crash_logs.txt)

### Aniyomi version

Preview r7479

### Android version

Android 13

### Device

Realme XT

### Other details

This wasn't the problem with any previous version of Aniyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Rudiculous0798** [comment]
The app for video is essentially unusable . Manga works fine.

**Comment by Rudiculous0798** [comment]
The update didn't work

**Comment by galathinius** [comment]
this also happens to me, and I was able to continue watching normally by exiting the video player when the purple screen happens and then tapping the resume button on the anime page

**Comment by SchuwiUee** [comment]
when you put the timer to negative (remaining time left) of the video, purple screen always occur at -7:05.

what the h-ll is happening?

**Comment by fakebhai** [comment]
didn't see this issue, it's gpu-next issue you can turn it off in `more - settings - player - advanced player settings`

**Comment by jmir1** [comment]
I'm pretty sure this was already fixed by making gpu-next opt-in
