### ISSUE TITLE
suggestion to address as soon as possible

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi#1358]
### Describe your suggested feature

Could you add an external premium extension repository to the app, such as Netflix, Amazon, Disney+, Funimation, and a host of books?

### Other details

please and thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
extension issue.
