### ISSUE TITLE
Separate Skip Intro for every series

### ISSUE THREAD

**Issue by zerakori** [aniyomiorg/aniyomi#1360]
### Describe your suggested feature

It should work like this, that at first the skip intro should have the default skip time but we can change it for the series while watching the episode of that series, and it changes the skip time for only that series

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Diegopyl1209** [comment]
https://github.com/aniyomiorg/aniyomi/assets/80992641/cfbdf8cc-95a3-4d12-a4da-bba4408e9985

**Comment by zerakori** [comment]
Ohhhhhh thank you sooo much
