### ISSUE TITLE
Video turns deep purple when watching 

### ISSUE THREAD

**Issue by Rudiculous0798** [aniyomiorg/aniyomi#1362]
### Steps to reproduce

Just click episode and watching show few minutes later turns to purple screen 

### Expected behavior

When watching an episode after few minutes go by randomly it turn to purple
![Screenshot_20240126-023946_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/157885984/824bd1ec-c497-46a1-bd1d-305a99f0ab79)

### Actual behavior

The screen turn purple and nothing is viewable .

### Aniyomi version

0.15.2.3-7479 (standard, b505d5965, 120, 2024-01-23T23:21Z)

### Android version

Android 12

### Device

Samsung s10e

### Other details

![Screenshot_20240126-023946_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/157885984/9f253ada-3ac6-489b-81dd-3c1f2d9a3003)
 This happened in the new update . Basically unusable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Rudiculous0798** [comment]
It happens to every episode extension and anime site. Etc

**Comment by Rudiculous0798** [comment]
It's still purple

**Comment by Rudiculous0798** [comment]
The issue still persist . Update didn't fix the issue.

**Comment by abdallahmehiz** [comment]
cause by `gpu-next` in the advanced player settings.
