### ISSUE TITLE
Duplicate chapter/episode on import/update

### ISSUE THREAD

**Issue by mm12** [aniyomiorg/aniyomi#1366]
### Steps to reproduce

This bug seems to be either transient or already fixed, however the after- effects of it are persistent - they still exist. 
For some time a few days ago, all chapter/episode updated produced **2** entries rather than one. While this issue no longer occurs, any items updated in that time retain their duplicates. 

### Expected behavior

- Updates should make one chapter/episode for each identical chapter/episode 
- Importing should ignore identical chapter/episode instead of accepting them

### Actual behavior

- duplicates are retained 

### Aniyomi version

0.15.2.3

### Android version

Android 14

### Device

Google Pixel 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

edit: error on import is `ResultSet returned more than 1 row for chapters.sq:getChapterByUrl`

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
