### ISSUE TITLE
Aniyomi Myanimelist tracking issue HTTP error 401

### ISSUE THREAD

**Issue by Reichlandia** [aniyomiorg/aniyomi#1368]
### Steps to reproduce

1. If you have tracking on via myanimelist, go ahead to any anime with tracking on and press "tracking"
2. under the myanimlist tracker, it says MyAnimeList error: HTTP error 401
3. Tried going to the actual MyAnimelist site to see if the site is down (The website is working)
4. Tried logging out on myanimelist on the aniyomi app and tried logging in, but the log in feature changed and asked for username and password instead of connecting me to the google account where I originally registered myanimelist account
5. The login feature for the myanimelist stuck in a loop, despite entering correct username and password
![Screenshot_2024 01 28_15 25 23 485](https://github.com/aniyomiorg/aniyomi/assets/77231780/b6c1d005-860d-4c16-97d2-9c224c633a57)
![Screenshot_2024 01 28_15 25 32 835](https://github.com/aniyomiorg/aniyomi/assets/77231780/83f757d5-18fc-459d-a485-710faf79868d)
![Screenshot_2024 01 28_15 25 40 001](https://github.com/aniyomiorg/aniyomi/assets/77231780/5f4c555c-a27a-4c96-b51a-ab69d1cc7992)
![420651078_845055810719774_2597041734684849041_n](https://github.com/aniyomiorg/aniyomi/assets/77231780/46b4c5e1-1572-4e5a-896f-395a04e402d4)

### Expected behavior

Myanimelist tracker should not return any error and when watching anime or reading manga, it should automatically update my progress

### Actual behavior

Aniyomi  returns the error with Myanimelist tracking issue HTTP error 401
![Screenshot_2024 01 28_15 25 23 485](https://github.com/aniyomiorg/aniyomi/assets/77231780/dcc3c34a-ba8a-4902-8a72-604dd45134ed)
![Screenshot_2024 01 28_15 25 32 835](https://github.com/aniyomiorg/aniyomi/assets/77231780/100e5651-e9c2-47f0-a179-4d16ca5e7001)
![Screenshot_2024 01 28_15 25 40 001](https://github.com/aniyomiorg/aniyomi/assets/77231780/a6750569-d144-4bf6-917e-a083ee555cc6)

### Aniyomi version

App version: 0.15.2.3-7479 (standard, b505d5965, 120, 2024-01-23T23:21Z)

### Android version

13 (SDK 33; build RMX3085_11_F.09) [My actual android device); 7.1.1 (SDK 25; build ONEPLUS A5000_23_171031) [Bluestacks]

### Device

ONEPLUS A5000 (Bluestacks); Realme RMX3085 (My actual android device)

### Other details

I use two devices, one on my Android phone and one for Bluestacks on my PC. Both return the same error and both are updated to the latest version (both using the preview version)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Lesjerkun** [comment]
Same issue 😭

**Comment by s2r** [comment]
Confirm same issue.

**Comment by P10situo** [comment]
As the #anime-extension-status on the Discord server said:

> The **MAL** tracker that aniyomi uses has been deleted. Please wait until the next update to continue using the **MAL** tracker.

**Comment by jmir1** [comment]
fixed by 0d1ce0dcdc1c7dedc5887a1195618f33436e6e60
