### ISSUE TITLE
If its possible make something like backup that is connected to google acount

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#137]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Should work like sync so that when we transfer from tachiyomi to aniyomi we will not have to restore it every time.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/1065
