### ISSUE TITLE
optimize the app

### ISSUE THREAD

**Issue by Alex178190282** [aniyomiorg/aniyomi#1378]
### Describe your suggested feature

Aniyomi people used to work perfectly for me to watch my anime and movie content. However, since I updated it, it does not work for me with any Internet connection. Even though my Internet connection is not very fast, I have 40 megabytes, which would be 5 megabytes (I think). All other apps work fine, even Anime Cast, which was the first app I used to watch anime before Aniyomi. Anime Cast even works in 1480p quality, but in Aniyomi I can't even play content in 360p quality since the changes were included in the mpv player.

### Other details

["Please I would like to use Aniyomi as soon as possible"]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
> ### Describe your suggested feature
> 
> Aniyomi people used to work perfectly for me to watch my anime and movie content. However, since I updated it, it does not work for me with any Internet connection. Even though my Internet connection is not very fast, I have 40 megabytes, which would be 5 megabytes (I think). All other apps work fine, even Anime Cast, which was the first app I used to watch anime before Aniyomi. Anime Cast even works in 1480p quality, but in Aniyomi I can't even play content in 360p quality since the changes were included in the mpv player.
> 
> ### Other details
> 
> ["Please I would like to use Aniyomi as soon as possible"]
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> - [X] I have written a short but informative title.
> - [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
> - [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> - [X] I will fill out all of the requested information in this form.

You aren't making any sense

**Comment by Dr01000111** [comment]
been using external player to help with performance on my nintendo switch. If I use the app for about 3 episodes or more then it starts to lagg to a point where touching the screen freezes and I cant make any inputs weather touch or volume buttons.
