### ISSUE TITLE
Manga extensions no more available to download

### ISSUE THREAD

**Issue by purono** [aniyomiorg/aniyomi#1379]
### Steps to reproduce

1. Open aniyomi
2. Go to browse
3. Go to manga extensions

### Expected behavior

Normally a vast variety of manga extensions should be shown to download. 

### Actual behavior

The only mamga extensions to download are: kavita, komga, lanraragi, suwayomi. 

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Device

Samsung galaxy s22 ultra

### Other details

Its only the manga extension list

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by yuty06** [comment]
Yep same here.

**Comment by kaubu** [comment]
I have this too. They've marked all my old manga extensions as obsolete.

**Comment by Illythia** [comment]
Good to the link above and follow the instructions.

**Comment by EfeDevirgen** [comment]
​**No source/repo recommendations, or sharing APKs.** Recommendations increases the load on extensions, leading to potential bans. 

Third-party repositories are not affiliated with us in any way, are not supported here, should not be shared here, and their security cannot be guaranteed.
|| shamelessly copied from tachi ||

**Comment by abdallahmehiz** [comment]
@yuty06 do not share 3rd party extensions repositories

**Comment by purono** [comment]
Why did u close this as completed? I did not get any help to fix it, nor any answer why its happening.

**Comment by EfeDevirgen** [comment]
Due to extenuating circumstances, we've purged our list of extensions. Tachiyomi is now fully bring-your-own-content, but we still offer a few extensions that support connecting to your own Plex-like systems like Komga. For the list of available extensions, see <https://tachiyomi.org/extensions/>.

Existing extensions will continue to work, until they don't (yes, my nickname is Dr. Obvious).
As always, be diligent in what you install and trust to run on your devices.

This server nor our GitHub repos' issues do not offer support for unofficial extensions.

(News post: <https://tachiyomi.org/news/2024-01-09-extensions-removal>)

**Comment by EfeDevirgen** [comment]
from tachiyomi

**Comment by abdallahmehiz** [comment]
> Why did u close this as completed? I did not get any help to fix it, nor any answer why its happening.

cause this is not a bug nor a problem
