### ISSUE TITLE
App not installing?

### ISSUE THREAD

**Issue by inokiii** [aniyomiorg/aniyomi#138]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Aniyomi version

0.12.1.1

### Android version

Android 11

### Device

Samsung Galaxy A01

### Steps to reproduce

1. I tap assets to locate the apk file
2. I download the apk file
3. Once action is completed, I'm given the option to install the app
4. When I proceed with the following instructions, a message appears stating the app I'd not installed.

### Expected behavior

I want to be able to download and install aniyomi.

### Actual behavior

Instead, it allows me to download the apk file but not install the app.

### Other details

I'm not sure if it's because of my phone or its version but I really want to be able to utilize this fabulous app. I'm a big fan of anime and manga. Especially a fan to the creators of this app. Please help me with my problem and send feedback.

**Comment by jmir1** [comment]
Not sure what the issue might be, I'm also on android 11 and can install the app fine...
If anyone else has this issue, please comment.

**Comment by AB-69** [comment]
> Not sure what the issue might be, I'm also on android 11 and can install the app fine...
> If anyone else has this issue, please comment.
i have the same issue , i can't install the app on Android 10

**Comment by exilvm** [comment]
I'm having the same issue.

**Comment by Venyon** [comment]
Same, I'm also having this problem.

I tried downloading aniyomi on my other device (Coby, Android 10), and it installed just fine. But when I download the apk file on my phone (Oppo A37, Android 5.1) it showed me an error saying 'Cannot install because apk file is damaged'

**Comment by exilvm** [comment]
Freeing up storage space on my phone fixed the problem.

**Comment by Isitsmd** [comment]
> Same, I'm also having this problem.
> 
> I tried downloading aniyomi on my other device (Coby, Android 10), and it installed just fine. But when I download the apk file on my phone (Oppo A37, Android 5.1) it showed me an error saying 'Cannot install because apk file is damaged'
The last v0.10 verison is only compatible with Android 5.x

**Comment by Quickdesh** [comment]
The app works only for Android 6+
