### ISSUE TITLE
(🙏🙏🙏) pleasse sir this feature is godly

### ISSUE THREAD

**Issue by Unknown07070** [aniyomiorg/aniyomi#1384]
### Describe your suggested feature

Instead of manually making an info.json file in the folder of manga/anime the user wants to edit the metadata of, the user can edit info from inside the app like TachiyomiSY or TachiyomiJ2K
This would be useful since now, Local source anime is a viable options
I've been creating a lot of issues/feature requests the past few days, hope it doesn't bother you much + Ty for the app bro(Much appreciation)

### Other details

TachiyomiJ2K's metadata editing screen

![142888627-1aa27e24-9b6c-4006-8c9f-f6d9cfa652b4](https://github.com/aniyomiorg/aniyomi/assets/131685490/a1f9af9d-acb2-4612-b5bb-138f526d4de1)

TachiyomiJ2K's metadata editing screen

![142888699-d5b3d56a-d484-429a-8774-e66f060d03c0](https://github.com/aniyomiorg/aniyomi/assets/131685490/ff6b39e4-db14-4c64-a675-2dab8b32b02b)

					( Godly Feature )

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Please don't open duplicate requests.

**Comment by Unknown07070** [comment]
> Please don't open duplicate requests.

Sir please i am not a programmer but this feature have so mush potential.
Please add it to aniyomi.

**Comment by sinnghabhay80** [comment]
Bro it's a already open FR. They'll work on it when they get a chance.
https://github.com/aniyomiorg/aniyomi/issues/237
You can close this.
