### ISSUE TITLE
Add feature that makes it easier to find scanlator in my language.

### ISSUE THREAD

**Issue by Vhiniz** [aniyomiorg/aniyomi#1389]
It's very unpleasant having to look for scanlator in my language because they are not identified in any way.  To solve this, I imagine that if the language was just written next to the scanlator it would solve everything.  Example: Mixscans (pt br).  Or if there was a feature in the extension options that had already been programmed to only open scanlators for a certain language, as already exists for subtitles in anime.
![Screenshot_20240202-023454](https://github.com/aniyomiorg/aniyomi/assets/115049368/26b684c1-84d6-4217-84ec-ae69f9d39cfa)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
That's a extension issue, not the main app's. Send a Feature request to your extension maintainer instead (also, don't forget to say the extension which you want this to be added!).

**Comment by Vhiniz** [comment]
I don't want to add a new extension. I just want a feature that makes it
easier to find scanlators in my language to read manga that are in multiple
extensions.

Em sex., 2 de fev. de 2024 03:58, Claudemirovsky ***@***.***>
escreveu:

**Comment by Secozzi** [comment]
> I don't want to add a new extension. I just want a feature that makes it easier to find scanlators in my language to read manga that are in multiple extensions.

Such a feature would have to come from the extension, not the app.
