### ISSUE TITLE
extensions and app taping area not working properly 

### ISSUE THREAD

**Issue by akbarsoft0** [aniyomiorg/aniyomi#1390]
### Steps to reproduce

This is the alert is showing whenever we refresh shoebox extension.
![Screenshot_2024-02-02-15-59-31-80_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi/assets/57284714/437d2a2d-a4d6-4a7a-9eb5-35bceb411c44)

### Expected behavior

Image 

### Actual behavior

Image 

### Aniyomi version

Letest stable 

### Android version

11

### Device

Oppo A5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
I think you're trying to mention extension issue? but your issue title is saying something else. also extension name and screenshot doesn't match. 

too many issues with information and no entry is filled properly so I think it should get closed.

**Comment by akbarsoft0** [comment]
![Screenshot_2024-06-30-18-44-44-60_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi/assets/57284714/9d70a463-7600-456b-bb9b-9e06c02eeb26)


Super stream This is the extension that I use mostly fix this issue please.
