### ISSUE TITLE
Entire Screen Goes Black While Reading

### ISSUE THREAD

**Issue by light-striker** [aniyomiorg/aniyomi#1391]
### Steps to reproduce

1. Open Manga
2. Try to scroll up or down, tap left/right in any reading mode

### Expected behavior

When I open a manga to read  I should be able to read the manga with the screen going black.

### Actual behavior

When I open a manga to read the screen loads a black screen first, when I scroll the expected image pops im and out with a black screen.

https://github.com/aniyomiorg/aniyomi/assets/106634060/6df97b8e-c12b-44e0-8852-52ec03d62907

### Aniyomi version

0.15.2.4

### Android version

Android 10/ One UI 2.5

### Device

Samsung Galaxy Note 9

### Other details

 This bug appears in all reading modes(paged, longstrip).

Issue appearant with any manga of any extension.

Makes part of the app unusable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Either you have turned on flash on page change like the earlier comment says, or it has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
