### ISSUE TITLE
[⭐FR] Preference in media type or merge of it

### ISSUE THREAD

**Issue by Drownbywind** [aniyomiorg/aniyomi#1392]
### Describe your suggested feature

Make an option to merge anime and manga or switch anime and manga places making manga the default
![he ndjof](https://github.com/aniyomiorg/aniyomi/assets/29250530/bbc4a9f4-8308-4772-a253-6e3fcdee137c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by sinnghabhay80** [comment]
You can make manga default by, 
More>settings>appearance>start screen

**Comment by Drownbywind** [comment]
I mean that it would be the first one change places
![vodncke](https://github.com/aniyomiorg/aniyomi/assets/29250530/e2e2dae0-8916-493d-816c-cc7b7e02cb8c)

**Comment by Secozzi** [comment]
Closing in favour of #1692
