### ISSUE TITLE
Mal tracking not working 

### ISSUE THREAD

**Issue by Nikus-maximus** [aniyomiorg/aniyomi#1397]
### Steps to reproduce

1. Settings 
2. Tracking
3. Allow for tracking
4. Back to app no tracking

### Expected behavior

1. Settings 
2. Tracking
3. Allow tracking
4. Tracking

### Actual behavior

1. Settings 
2. Tracking
3. Allow for tracking
4. Back to app no tracking

### Aniyomi version

0.15.2.4

### Android version

Andriod 13

### Device

Samsung galaxy A51

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by shinobs** [comment]
Hello, a thread about it is already opened : https://github.com/aniyomiorg/aniyomi/issues/1381.

**Comment by SiamRin33** [comment]
Mine not working too

**Comment by anggikjk** [comment]
This might help
https://github.com/aniyomiorg/aniyomi/issues/1381#issuecomment-1937225516

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
