### ISSUE TITLE
Backup Restoration Problem

### ISSUE THREAD

**Issue by SanFerndes** [aniyomiorg/aniyomi#1401]
### Steps to reproduce

Example:
1. Go to "More" section and click on "Data and Storage" and "Restore backup"
2. Then choose your backup file and click on "Restore"

### Expected behavior

Should restore data without any problems.

### Actual behavior

Crashes when restoring backup file.

### Crash logs

App version: 0.15.2.4 (standard, 16361e5, 121, 2024-01-28T19:30Z)
Android version: 11 (SDK 30; build RKQ1.200826.002 test-keys)
Android build ID: RKQ1.200826.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: raphaelin (raphaelin)
Device model: Redmi K20 Pro
WebView: Android System WebView 121.0.6167.143

--------- beginning of main
02-06 04:08:50.224  9200  9200 E ir.tachiyomi.m: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
02-06 04:08:50.643  9200  9251 E SQLiteLog: (28) double-quoted string literal: ""
02-06 04:08:50.644  9200  9253 E SQLiteLog: (28) double-quoted string literal: ""
02-06 04:08:55.586  9200  9802 E SQLiteLog: (284) automatic index on C(anime_id)
02-06 04:08:55.586  9200  9802 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
02-06 04:08:57.591  9200  9200 E ActivityInjector: get life cycle exception
02-06 04:08:57.591  9200  9200 E ActivityInjector: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to android.app.servertransaction.ClientTransaction
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.ActivityInjector.checkAccessControl(ActivityInjector.java:24)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.Activity.onResume(Activity.java:1995)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at androidx.fragment.app.FragmentActivity.onResume(SourceFile:6)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1457)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.Activity.performResume(Activity.java:8282)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4555)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4597)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5564)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.ActivityThread.access$3500(ActivityThread.java:258)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.os.Looper.loop(Looper.java:236)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at android.app.ActivityThread.main(ActivityThread.java:8061)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
02-06 04:08:57.591  9200  9200 E ActivityInjector: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
02-06 04:09:06.491  9200  9200 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
02-06 04:09:06.491  9200  9200 E libc    : Access denied finding property "ro.vendor.knock.type"
02-06 04:09:29.605 11084 11084 E i:error_handle: Not starting debugger since process cannot load the jdwp agent.
02-06 04:09:29.806 11084 11108 E SQLiteLog: (283) recovered 357 frames from WAL file /data/data/xyz.jmir.tachiyomi.mi/databases/tachiyomi.db-wal
02-06 04:09:29.823 11084 11109 E SQLiteLog: (283) recovered 501 frames from WAL file /data/data/xyz.jmir.tachiyomi.mi/databases/tachiyomi.animedb-wal

### Aniyomi version

14.6-6693

### Android version

Android 11

### Device

Redmi K20 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
