### ISSUE TITLE
Aniwave Extension Cloudflare Looping

### ISSUE THREAD

**Issue by Scorcher100** [aniyomiorg/aniyomi#1405]
### Steps to reproduce

1. Go to Browse
2. Click Aniwave extension
3. Open in Webview
![Screenshot_2024-02-07-14-09-42-491_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/159228365/1e1db0c6-d348-4913-bee1-75f9955f53c1)

### Expected behavior

After open in Webview, it will verify if you are human and check the box and it will redirect to Aniwave website.

### Actual behavior

What happen instead is just looping on the cloudflare after checking the box, even if I changed my wifi or mobile data or even restarting the app of phone.
![Screenshot_2024-02-07-13-51-50-394_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/159228365/b54278d7-32b2-4829-936d-406cf6689b52)

### Aniyomi version

App version: 0.15.2.4-7493 (standard, 89795945a, 121, 2024-01-31T13:51Z) Android version: 12 (SDK 31; build SKQ1.211006.001 test-keys) Android build ID: SKQ1.211006.001 test-keys Device brand: POCO Device manufacturer: Xiaomi Device name: vayu (vayu_global) Device model: M2102J20SG WebView: Android System WebView 121.0.6167.143

### Android version

Android 12

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Read the cloudflare section in the troubleshooting guide that you acknowledged you read. If it doesn't work, migrate to other sources or wait until they lower their protection.

**Comment by Scorcher100** [comment]
> Read the cloudflare section in the troubleshooting guide that you acknowledged you read. If it doesn't work, migrate to other sources or wait until they lower their protection.

I read it before posting it and it doesn't work so maybe I'll just wait then until they lower it down. I'll try other days on connecting to different kinds of wifi maybe I passed the cloudflare eventually. Thx for the comment!

**Comment by goliv04053** [comment]
Change the user agent (https://aniyomi.org/docs/guides/troubleshooting/#changing-your-user-agent) and it will work the verification at Cloudflare. But after this you may still have some issues (I do). It gives me 404 error when try to open a episode of any anime.
