### ISSUE TITLE
Reader Tap Zones not working

### ISSUE THREAD

**Issue by Exonymos** [aniyomiorg/aniyomi#1407]
### Steps to reproduce

1. Open Aniyomi
2. Set desired Tap Zone
3. Open a manga 

### Expected behavior

The tap zones should be registered correctly

### Actual behavior

The tap zones no matter which ones I use do not work

### Aniyomi version

0.15.2.4

### Android version

Android 13.1.0

### Device

Infinix GT10 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by shinobs** [comment]
Almost same issue for me. Only when I aim and tap perfectly in a small area around the middle of the screen that tapping to the next page works on manhwa. No issue on manga where it's one page per screen. 

Was working fine in Tachiyomi in any zone.

**Comment by ShoyebOP** [comment]
@https://github.com/aniyomiorg/aniyomi/issues/1294


This issue fixed and will be added in version 0.15.3
