### ISSUE TITLE
Anime4up dosn't open the episode

### ISSUE THREAD

**Issue by 3bakri** [aniyomiorg/aniyomi#1408]
### Steps to reproduce

When I run the episode of the aniyomi , it does not work, but when I enter from a site, it works

### Expected behavior

1- The episode must work when I enter it
**2- All must be added Viewing Servers So that this problem does not happen again**

### Actual behavior

I enter an episode of any anime from Anime4up it tells me the application video list is empty although when I enter the site and run it works

### Aniyomi version

0.15.2.4

### Android version

Android 8

### Device

Huawei 7y pro 2019

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
✅ If this is an issue with an official extension, I should be opening an issue in the extensions repository.

**Comment by abdallahmehiz** [comment]
A no longer supported extension.
