### ISSUE TITLE
Default Search Settings

### ISSUE THREAD

**Issue by BatDevil** [aniyomiorg/aniyomi#1413]
### Describe your suggested feature

a Feature whereby users can set a default search mode being Pinned or All and whether it has results or not, both options should ideally be choices as default search settings

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by REFLEXGAMING007** [comment]
That's a good one

**Comment by Amonimus** [comment]
Considering users don't use that many Sources that some need a pin, Sources search, anime search, and migrations all defaulting to "Pinned" tab is an odd behavior, and it's rather bothersome to switch to "All" every time. Since there may still be users who need it, this can be a setting.

**Comment by Secozzi** [comment]
Pin the sources you want to do a global search on.
