### ISSUE TITLE
Download disappears when episode languages are changed

### ISSUE THREAD

**Issue by cracktorio** [aniyomiorg/aniyomi#1419]
### Steps to reproduce

1: download a new episode from yomiroll or another source with languages
2: wait for there to be added another language
3: the file still exists but the episode isn't downloaded in the app

### Expected behavior

Download should persist

### Actual behavior

Download disappears inside app, persists in the file system

### Aniyomi version

r7493

### Android version

13

### Device

poco x3 pro

### Other details

It seems like renaming the folder containing the video fixes the issue, example:
"En, ja_Season 1 Episode 1_ episode name"
Doesn't work after french has been added, renaming to "en, fr, ja_Season 1 Episode 1_ episode name" fixes the issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This happens because the scanlator field changes, which is supposed to happen
