### ISSUE TITLE
[Feature Request] add subtitles features 

### ISSUE THREAD

**Issue by rd-cpu** [aniyomiorg/aniyomi#142]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I think it could look like the vlc subtitle feature, we just make a search on the app (by informing : the name of the anime, the season, the episode) and we find what subtitle we need while to watch the video. There are sites that makes subtitles like OpenSubtitles (for example), we just download the subtitles and put it on the video (I know it won't be that simple to automate that on a app). The advantage will be that we will be able to watch the video even if we don't understand english.

But all this can be use only if there aren't already subtitles so we first need japanese source...

### Other details

https://www.opensubtitles.org (OpenSubtitles)

**Comment by Millmascok** [comment]
Yeah same thoughts. I should be needed to see anime in English with English subtitles. But that place if i Played anime English language,it was not showing the English subtitles. Better then atleast we need to add feature like subtitles add From our local storage device. Kindly consider this request.

**Comment by Millmascok** [comment]
Seriously, I have latest version aniyomi (V 12.3.10 )I checked whole application and setting.. But I can't see Opensubtitle Anyplace.. Could you tell me how I would use that feature..

**Comment by dillon481** [comment]
I don't know where to have the subtitles

**Comment by crissssi** [comment]
plsss i need an open subtitles or a subtitle on a English movie plsss
