### ISSUE TITLE
Sflix is not working 

### ISSUE THREAD

**Issue by JacNorma** [aniyomiorg/aniyomi#1420]
### Steps to reproduce

Sflix extension is not working, when I try to watch a movie it keeps showing 'video list is empty' 

### Expected behavior

If you open click on any movie it will show this message ' video list is empty' 

### Actual behavior

The extension crashed 

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Device

Google Pixel 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Extensions related issues should be reported in the extensions repo
