### ISSUE TITLE
DopeBox not working

### ISSUE THREAD

**Issue by reiko-u** [aniyomiorg/aniyomi#1422]
### Steps to reproduce

1. Open any show/movie on with dopebox extention
2. open episode
3. video player closes
4. "Video list is empty." message appears

### Expected behavior

Episode plays when opened

### Actual behavior

Video player closes and "Video list is empty." message appears

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Device

Samsung Z Fold 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Extensions related issues should be reported in the extensions repo
