### ISSUE TITLE
Preload Amount

### ISSUE THREAD

**Issue by Vincracked** [aniyomiorg/aniyomi#1423]
### Steps to reproduce

1. Start An episode .
2. Preload amount Keeps Increasing.

### Expected behavior

Is there Any option to change the Preload Amount?

### Actual behavior

Keeps Preloading Till the end of episode .

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Device

Infinix Smart 6 Hd

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
`more - settings  - player - advanced player settings - mpv config`
demuxer-max-bytes=25MiB
demuxer-max-back-bytes=1MiB
you can ignore or not use the second one unless you want to specify it
