### ISSUE TITLE
Sync error with myanimelist.

### ISSUE THREAD

**Issue by Vhiniz** [aniyomiorg/aniyomi#1430]
### Steps to reproduce

1 - open any anime
2 - click on monitoring 
3 - select myanimelist 

### Expected behavior

Find the anime you want

### Actual behavior

The search gives no results and you receive the message "unknown error

### Aniyomi version

r7507

### Android version

Android 11

### Device

Moto e40 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Try re-adding MAL tracker in your settings.

**Comment by Vhiniz** [comment]
> Tente adicionar novamente o rastreador MAL em suas configurações.

The problem has not been resolved

**Comment by Vhiniz** [comment]
> Try re-adding MAL tracker in your settings.

The problem has not been resolved

**Comment by Nintenstation** [comment]
To anyone still here: this issue can be potentially fixed by changing the user agent.

1. Go to "settings" and "advanced"
2. Scroll down to "user agent" erase what's there and paste this instead:

Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.164 Mobile Safari/537.36

3. Last step, click "ok" and restart the app.

Now log in the MAL tracker again and it'll hopefully work

**Comment by Nintenstation** [comment]
> > To anyone still here: this issue can be potentially fixed by changing the user agent.
> > 
> > 1. Go to "settings" and "advanced"
> > 2. Scroll down to "user agent" erase what's there and paste this instead:
> > 
> > Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.164 Mobile Safari/537.36
> > 
> > 3. Last step, click "ok" and restart the app.
> > 
> > Now log in the MAL tracker again and it'll hopefully work
> 
> When I click "ok" nothing happens. The "user agent" screen remains open and does not modify what is written. 

Hmm, interesting. Maybe tap the background instead? Maybe clear cookies of the app (not user data, just cookies) and then try again?

**Comment by Vhiniz** [comment]
> > > To anyone still here: this issue can be potentially fixed by changing the user agent.
> > > 
> > > 1. Go to "settings" and "advanced"
> > > 2. Scroll down to "user agent" erase what's there and paste this instead:
> > > 
> > > Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.164 Mobile Safari/537.36
> > > 
> > > 3. Last step, click "ok" and restart the app.
> > > 
> > > Now log in the MAL tracker again and it'll hopefully work
> > 
> > 
> > When I click "ok" nothing happens. The "user agent" screen remains open and does not modify what is written.
> 
> Hmm, interesting. Maybe tap the background instead? Maybe clear cookies of the app (not user data, just cookies) and then try again?

Did not work. But I just put "Mozilla/5.0 (Linux; Android 14) Applewebkit/537.36 (Khtml, like Gecko) Chrome/121.0.6167.164 Safari" and it worked. Anyway thank you.

**Comment by Nintenstation** [comment]
> > > > To anyone still here: this issue can be potentially fixed by changing the user agent.
> > > > 
> > > > 1. Go to "settings" and "advanced"
> > > > 2. Scroll down to "user agent" erase what's there and paste this instead:
> > > > 
> > > > Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.164 Mobile Safari/537.36
> > > > 
> > > > 3. Last step, click "ok" and restart the app.
> > > > 
> > > > Now log in the MAL tracker again and it'll hopefully work
> > > 
> > > 
> > > When I click "ok" nothing happens. The "user agent" screen remains open and does not modify what is written.
> > 
> > Hmm, interesting. Maybe tap the background instead? Maybe clear cookies of the app (not user data, just cookies) and then try again?
> 
> Did not work. But I just put "Mozilla/5.0 (Linux; Android 14) Applewebkit/537.36 (Khtml, like Gecko) Chrome/121.0.6167.164 Safari" and it worked. Anyway thank you.

I'm very sorry that I was useless, but I'm glad you finally found a solution! Have a good rest of your day :)

**Comment by Vhiniz** [comment]
> > > > > To anyone still here: this issue can be potentially fixed by changing the user agent.
> > > > > 
> > > > > 1. Go to "settings" and "advanced"
> > > > > 2. Scroll down to "user agent" erase what's there and paste this instead:
> > > > > 
> > > > > Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.164 Mobile Safari/537.36
> > > > > 
> > > > > 3. Last step, click "ok" and restart the app.
> > > > > 
> > > > > Now log in the MAL tracker again and it'll hopefully work
> > > > 
> > > > 
> > > > When I click "ok" nothing happens. The "user agent" screen remains open and does not modify what is written.
> > > 
> > > 
> > > Hmm, interesting. Maybe tap the background instead? Maybe clear cookies of the app (not user data, just cookies) and then try again?
> > 
> > 
> > Did not work. But I just put "Mozilla/5.0 (Linux; Android 14) Applewebkit/537.36 (Khtml, like Gecko) Chrome/121.0.6167.164 Safari" and it worked. Anyway thank you.
> 
> I'm very sorry that I was useless, but I'm glad you finally found a solution! Have a good rest of your day :)

You helped me a lot! I only managed to resolve it thanks to you

**Comment by Senshi2005** [comment]
I was having the same problem.

> > > > > To anyone still here: this issue can be potentially fixed by changing the user agent.
> > > > > 
> > > > > 1. Go to "settings" and "advanced"
> > > > > 2. Scroll down to "user agent" erase what's there and paste this instead:
> > > > > 
> > > > > Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.164 Mobile Safari/537.36
> > > > > 
> > > > > 3. Last step, click "ok" and restart the app.
> > > > > 
> > > > > Now log in the MAL tracker again and it'll hopefully work
> > > > 
> > > > 
> > > > When I click "ok" nothing happens. The "user agent" screen remains open and does not modify what is written.
> > > 
> > > 
> > > Hmm, interesting. Maybe tap the background instead? Maybe clear cookies of the app (not user data, just cookies) and then try again?
> > 
> > 
> > Did not work. But I just put "Mozilla/5.0 (Linux; Android 14) Applewebkit/537.36 (Khtml, like Gecko) Chrome/121.0.6167.164 Safari" and it worked. Anyway thank you.
> 
> I'm very sorry that I was useless, but I'm glad you finally found a solution! Have a good rest of your day :)

I was having the same problem. but thanks to you it's solved. I didn't even realize what a hassle it is to track my anime without this feature

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
