### ISSUE TITLE
Watching anime orientation not properly fixed on screen

### ISSUE THREAD

**Issue by Lawwse** [aniyomiorg/aniyomi#1433]
### Steps to reproduce

Playing a episode of fire force, JJK, and AOT to test if it was only specified for a single anime but it wasn't ( i am using GOGOAnime extension ) The screen is not properly oriented and half of the subtitles are not visible. 
I looked through the settings to check if there was a fix for this and there wasn't. ( maybe im blind please enlighten me. )
Edit: I tried it with sao and it has the same effect. On a different extension too

### Expected behavior

I expect it to be centered and proper like this
![Screenshot_2024-02-17-00-50-00-41_f9ee0578fe1cc94de7482bd41accb329](https://github.com/aniyomiorg/aniyomi/assets/160262990/ea549e43-472d-4ef0-977e-1cfa9701a843)

### Actual behavior

![Screenshot_2024-02-17-00-37-32-99_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi/assets/160262990/f61326c1-2dc9-48f3-8bef-3fefbfba23c0)
![Screenshot_2024-02-17-00-36-15-77_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi/assets/160262990/991150e8-e469-4796-8d80-f42b0b046366)
![Screenshot_2024-02-17-00-38-04-32_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi/assets/160262990/4ebce3e6-50d8-4923-b755-3a1558522ee5)

### Aniyomi version

0.15.2.4

### Android version

Android 12

### Device

Realme 8 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
(https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Square button, bottom right

**Comment by Loleman11** [comment]
Fíjate el botón que está abajo a la derecha, el que se parece al de darle a pantalla completa en youtube. Ese boton lo que hace es proporcionar la pantalla, pero si eso no te funciona, anda a las opciones del reproductor y al principio creo que te aparece algo de ajustes avanzados que dice "Editar mpv.conf" o algo así, ahí dentro colocas el comando "video-aspect="Número" ". Donde dice "Numero" colocas la relación de aspecto de tu pantalla (por ejemplo, "video-aspect=16:9").

**Comment by Loleman11** [comment]
Look at the button at the bottom right, the one that looks like the full screen button on youtube. That button is what it does is provide the screen, but if that doesn't work, go to the player options and at the beginning I think you will see something in advanced settings that says "Edit mpv.conf" or something like that, there you put the command "video-aspect="Number" ". Where it says "Number" you put the aspect ratio of your screen (for example, "video-aspect=16:9").

**Comment by Secozzi** [comment]
This happened because you turned on "cropped to screen", and it's doing what it's supposed to do.
