### ISSUE TITLE
Manga images are unable to load

### ISSUE THREAD

**Issue by Chanki33** [aniyomiorg/aniyomi#1435]
### Steps to reproduce

1. Open any manga one desires to read
2. Open any chapy

### Expected behavior

The manga should be loaded normally showing the pages.

### Actual behavior

As soon I open a chapter, the screen loaded for a few seconds and the it showed. No matter what page i go.
![Screenshot_20240217-113424](https://github.com/aniyomiorg/aniyomi/assets/133442063/e50c1c49-dea1-4f03-befd-d25d91903cc1)

### Crash logs

App version: 0.15.2.4 (standard, 16361e5, 121, 2024-01-28T19:30Z)
Android version: 12 (SDK 32; build JIO.LS1542QWN.001.06.035.200123-193954)
Android build ID: JIO.LS1542QWN.001.06.035.200123-193954
Device brand: Jio
Device manufacturer: Jio
Device name: LS1542QWN (JioPhoneNext)
Device model: LS1542QWN
WebView: Android System WebView 121.0.6167.164

Problematic extensions:
- 999Hentai
  Installed: 1.4.5 / Available: ?
  Obsolete: true
- Bato.to
  Installed: 1.4.32 / Available: ?
  Obsolete: true
- MangaClash
  Installed: 1.4.35 / Available: ?
  Obsolete: true
- MangaForFree.net
  Installed: 1.4.33 / Available: ?
  Obsolete: true
- MangaReader
  Installed: 1.4.4 / Available: ?
  Obsolete: true
- Mangakakalot
  Installed: 1.4.8 / Available: ?
  Obsolete: true
- Manganato
  Installed: 1.4.7 / Available: ?
  Obsolete: true
- OnlyManhwa
  Installed: 1.4.32 / Available: ?
  Obsolete: true
- VIZ
  Installed: 1.4.20 / Available: ?
  Obsolete: true

### Aniyomi version

15.2.4

### Android version

Android 12

### Device

Jio Phone Next 

### Other details

Yes, I know I am using third-party extensions, but they work fine in other devices. For unknown reasons it my device is not showing it. It works if I open it in 'Web View' option it opens.
I uploaded extensions from Tachiyomi.
If there is something I would do in settings pls help me out.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is either an issue with the extension, or you didn't follow the troubleshooting guide in the acknowledgement section
