### ISSUE TITLE
Crash When Entering PiP Mode.

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi#1445]
### Steps to reproduce

1. Start playing an episode.
2. Tap the PiP icon on the bottom right.

### Expected behavior

The playback should continue in a mini PiP window.

### Actual behavior

Aniyomi Crashes.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/14333280/aniyomi_crash_logs.txt)

### Aniyomi version

Preview r7509

### Android version

Android 14

### Device

Realme XT

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This has most likely been fixed in a newer version of preview. If the issue still persists, please open a new issue.
