### ISSUE TITLE
Crash When Tapping Back Button In The Player

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi#1446]
### Steps to reproduce

1. Start playing an episode
2. Tap the top left back button 

### Expected behavior

Aniyomi should go to the screen that it was on before the episode started playing.

### Actual behavior

Aniyomi just closes itself.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/14334260/aniyomi_crash_logs.txt)

### Aniyomi version

Preview r7509

### Android version

Android 14 

### Device

Realme XT

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by warior456** [comment]
Found this on my device as well a52s5g

**Comment by fakebhai** [comment]
for anyone working on it or wants temporary solution: it happens when you have auto rotation enabled. if you horizontal your device and vertical again, it should close/crash the app.

**Comment by warior456** [comment]
@fakebhai  auto rotation in app or on phone?

**Comment by fakebhai** [comment]
> > @fakebhai  auto rotation in app or on phone?
> 
> phone, as app has it enabled by default 

by app I mean player here

**Comment by fakebhai** [comment]
is this issue still relevant?

**Comment by abdallahmehiz** [comment]
Oh ye this is fixed too
