### ISSUE TITLE
Jellyfin Missing Items Message Display Bug

### ISSUE THREAD

**Issue by REFLEXGAMING007** [aniyomiorg/aniyomi#1447]
### Steps to reproduce

1. Setup Jellyfin normally in Windows 10
2. Download & activate the metadata scraper plugin called "TheTVDB" (see 👇) 
![Screenshot_4503](https://github.com/aniyomiorg/aniyomi/assets/56241882/b2677a0d-aada-462d-b5cf-64a8bb74629c)
3. Download Overlord batch including the special episodes from any source ( you can only download the season 4 with special eps & the same thing should happen as well)
4. Put & name those episodes correctly using TVDB website in their Jellyfin folder (👇) 
![Screenshot_4502](https://github.com/aniyomiorg/aniyomi/assets/56241882/125b45ed-ec84-44dd-b590-597354e863df)
5. Now open Jellyfin go to library < open folder settings of that folder where u put Overlord < select only TVDB as the metadata downloader < click ok (see below 👇)
![image (5)](https://github.com/aniyomiorg/aniyomi/assets/56241882/bc25bdac-721e-40be-9945-9ab6b7c98bc1)
6. Now connect Jellyfin with Aniyomi & try to view it from there

### Expected behavior

It should just appear normally like any other anime without any missing items message. 
Example 👇
![Screenshot_20240219-214602283](https://github.com/aniyomiorg/aniyomi/assets/56241882/8cca985c-7c1c-4fed-baea-b0277d1ee641)

### Actual behavior

I creates hundreds of missing items messages in between the episodes even though they are perfectly arranged with no missing episodes or anything. (I mean literally 👇) 
![Screenshot_20240219-204557928](https://github.com/aniyomiorg/aniyomi/assets/56241882/2c30e4a3-6b33-4699-8f76-3ec8681a9177)

### Aniyomi version

App version: 0.15.2.4-7493 (standard, 89795945a, 121, 2024-01-31T13:51Z) Android version: 12 (SDK 31; build SKQ1.210821.001.WW_Phone-31.0210.0210.309-0 release-keys) Android build ID: SKQ1.210821.001.WW_Phone-31.0210.0210.309-0 release-keys Device brand: asus Device manufacturer: asus Device name: ASUS_I003_1 (WW_I003D) Device model: ASUS_I003DD WebView: Android System WebView 121.0.6167.178

### Android version

Android 12

### Device

Asus Rog Phone 3

### Other details

The same thing happens with Re Zero or any other anime whose special episodes don't follow the main episode number or arrangement. 
![Screenshot_20240219-220457130](https://github.com/aniyomiorg/aniyomi/assets/56241882/f304c3af-c224-44b0-94f8-1d020111e0b2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [x] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
how is it sorted? 
![Screenshot_2024_0228_012349.jpg](https://github.com/aniyomiorg/aniyomi/assets/101493467/56ce5e96-24db-434c-ad17-02c6fa0ab687)

**Comment by REFLEXGAMING007** [comment]
It sorted exactly like that ![Screenshot_20240303-015141634.jpg](https://github.com/aniyomiorg/aniyomi/assets/56241882/56a9fee3-3d9b-4a9c-a6dd-259d25094eed)

**Comment by REFLEXGAMING007** [comment]
I believe it's happening because the system is detecting & treating special episodes as real episodes

Maybe just remove the special episodes ( Episode S00E01 ) from the missing items argument. Like it doesn't matter even if the special episodes are missing 

Or just make a toggle button inside anime box to turn off missing items warning in case they show it wrong or you just make a global toggle button as well.

**Comment by Secozzi** [comment]
This isn't an issue with the app.
