### ISSUE TITLE
HELLO DEV WHERE EXE FILE????!!!111

### ISSUE THREAD

**Issue by meowmeowofthemeows** [aniyomiorg/aniyomi#1448]
### Describe your suggested feature

HI DEV I A M WONDERING WHERE EXE FILE IS IT IS DISCRIMINATION TO NOT INCLUDE EXE FILE ON THIS ANIYOMI APPP I WILL BE CONTACTING TACHIYOMI TOO SHGUT DOWN ANIYOMI AND THIS WILL BE THE END
![Screenshot from 2024-02-19 15-04-30](https://github.com/aniyomiorg/aniyomi/assets/157843704/ca29e81d-9b7f-40cc-986d-da8734fec213)
SEE RIGHT HERE .AOPK NOI IT NEEDS EXE
I ALSO AM HERE TO REQUEST THESE FEATURES
-WAY TO MAKE VIDEOS DOWNLOAD FASTER
- HUE LIGHT BULB SUPPORT FOR RGB EFFECT
- APPLE VERSION OF ANIYOMI
- THANK YOU FOR YOUR TIME

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Coming soon™ with the multiplatform port

**Comment by hollowshiroyuki** [comment]
Don't close as "Completed" until multiplatform is released 🔫

**Comment by fakebhai** [comment]
> Don't close as "Completed" until multiplatform is released 🔫

yeah, close it as not planned

**Comment by 12ohit** [comment]
Troll issue in reference to https://www.reddit.com/r/github/s/dud9gylWa8 ??
