### ISSUE TITLE
Unable to update manga extensions from external repositories

### ISSUE THREAD

**Issue by Bioblade** [aniyomiorg/aniyomi#1450]
### Steps to reproduce

1. Navigate to "Manga Extensions" tab under "Browse"
2. Identify an extension with an available update, or wait for one to be available
3. Select the icon indicating to download the update
4. Upon completing the download, select "update" on the popup and wait for installation

### Expected behavior

The installation window closes, the extension is no longer marked as needing an update and is moved to it's respective position in the extension list, and the extension is listed as being a higher version than it was prior to updating

### Actual behavior

The installation window closes, the extension remains marked as having an update available, and the extension version remains unchanged, regardless of refreshing or restarting the app. 

### Aniyomi version

Preview r7507

### Android version

Android 14

### Device

Google Pixel 7 Pro

### Other details

I've uninstalled and reinstalled as well without success. Manga extensions from the same repos seem to successfully update when done in TachiyomiSY. I have not yet tried testing updating in other forks due to the limiting circumstances that would allow me to be able to (namely there being available updates). As a workaround for within the app, I have been uninstalling and then reinstalling extensions that need an update, and then re-marking them as trusted, as fresh installs from aniyomi seems to work fine. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We will never provide manga extensions, and please do not share third party extension repos.

**Comment by Bioblade** [comment]
> I think this is the reason: https://tachiyomi.org/news/2024-01-09-extensions-removal

That is not the reason. This is an issue regarding updating from an external repository.

**Comment by hyd3r** [comment]
I fixed mine by reinstalling the extension that has updates

**Comment by Bioblade** [comment]
> I fixed mine by reinstalling the extension that has updates

As I mentioned in my report, uninstalling and reinstalling is what I've had to do as a workaround. It doesn't fix the issue for me, though, since the same extension can need an update later on and still not be able to be updated.

**Comment by erickyun** [comment]
İs there fix planned for this issue?

I have exactly the same problem and have to follow the same workaround to update the extensions?

**Comment by Bioblade** [comment]
It seems like the most recent update fixed the issue on my end. Thank you, devs!
