### ISSUE TITLE
MAL Tracking Not working 

### ISSUE THREAD

**Issue by striker561** [aniyomiorg/aniyomi#1451]
### Steps to reproduce

1. Select and add anime to library
2. Click on tracking
3. Select my anime list and login to your account (I logged into MAL using Google)
4. The app doesn't save MAL token and my anime isn't tracked

### Expected behavior

It should be able to automatically tracked my anime to MAL account after the connection 

### Actual behavior

After signing in to MAL account, the apps doesn't save it and keeps telling me to login again. It happened after the latest update. I have been unable to track ever since then. 
I only tired My Anime List btw 

### Aniyomi version

0.15.2.4

### Android version

HyperOs - Android 14

### Device

Poco F5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Naginipython** [comment]
I had a similar issue, the fix that I used was going into Setting > Advanced > Default user agent string and instead I used:
`Mozilla/5.0 (Linux; Android 13; SM-S901U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36`

**Comment by Andreyf20** [comment]
I was having similar problems with MAL (for reference i tested AniList and it was working fine), and i can also confirm that @Naginipython solution worked like a charm. 10/10

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
