### ISSUE TITLE
Video list is empty

### ISSUE THREAD

**Issue by Zhyroxq** [aniyomiorg/aniyomi#1458]
### Steps to reproduce

1. Find an anime
2. Click an episode
3. The video will close and say the video list is empty

### Expected behavior

The video should play

### Actual behavior

The video did not play and close immediately saying that the video list is empty

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Device

Infinix note 30 5g 

### Other details

It's only a bug/issue on aniwave extension for me other extension/s work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DrZoidDusty** [comment]
Same issue/bug

**Comment by Udar96** [comment]
Same issue

**Comment by FlanMan04** [comment]
Same issue
Happened already on 2 extensions, likely to happen again

**Comment by Pojinku** [comment]
It's happening in every extension for me

**Comment by fakebhai** [comment]
> It's happening in every extension for me

try [troubleshooting](https://aniyomi.org/docs/guides/troubleshooting/) , also irrelevant to this issue. as it clearly states

> Other details
> It's only a bug/issue on aniwave extension for me other extension/s work

**Comment by Pojinku** [comment]
I tried trouble shooting but not a single thing listed was related to that
specific issue

**Comment by RhoChizuka** [comment]
Try going to settings (in your desired extension) and select your preferred server, switch to other servers until you finally get what you're going to watch.

I have two solutions for that one (both are in settings)
1. Preferred server 
2. Enable/Disable hosts (turn it all on)

**Comment by fakebhai** [comment]
@abdallahmehiz
