### ISSUE TITLE
wrong episode number when dotted

### ISSUE THREAD

**Issue by Fura-Fir** [aniyomiorg/aniyomi#1461]
### Steps to reproduce

Watch a list wih an intermediate episode numbered like 7.5 
This episode is tipicaly a summary or an secondary scene from episode 7 before of 8.

### Expected behavior

this episode should be considered its Integer part.
episode 7.5 is like episode 7

### Actual behavior

the point is not considered by transforming the units into tens
Epsiode 7.5 is associate to episode 75
this has impacts on the calculation of missing episodes and tracking

### Aniyomi version

0.15.2.4

### Android version

Android 10

### Device

M40

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is an issue with the extension not handling .5 episodes properly, not with the app.
