### ISSUE TITLE
Comikey Download endless loop

### ISSUE THREAD

**Issue by Dragoon91786** [aniyomiorg/aniyomi#1465]
### Steps to reproduce

Log in to Comikey via extension w/ browser.
Search for comic with license owned by user account.
Save comic.
Attempt to download chapters.
Endless loop crash at startup of app.
Break by turning off WiFi and stopping download at start of app.

### Expected behavior

Ideally, downloads pages to local for ease of viewing. Error happens on both last version of Tachiyomi and Aniyomi. The website and Comikey app are unideal viewers due to limitations in their controls, particularly on mobile devices.
[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/14397601/aniyomi_crash_logs.txt)
[aniyomi_crash_logs (2).txt](https://github.com/aniyomiorg/aniyomi/files/14397602/aniyomi_crash_logs.2.txt)
[aniyomi_crash_logs (3).txt](https://github.com/aniyomiorg/aniyomi/files/14397603/aniyomi_crash_logs.3.txt)
[aniyomi_crash_logs (4).txt](https://github.com/aniyomiorg/aniyomi/files/14397604/aniyomi_crash_logs.4.txt)
[aniyomi_crash_logs (5).txt](https://github.com/aniyomiorg/aniyomi/files/14397605/aniyomi_crash_logs.5.txt)

### Actual behavior

Everything works up until you turn on the downloader, at which point the app crashes. I presume local viewing also causes it to crash, but haven't checked. 

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/14397607/aniyomi_crash_logs.txt)
[aniyomi_crash_logs (2).txt](https://github.com/aniyomiorg/aniyomi/files/14397608/aniyomi_crash_logs.2.txt)
[aniyomi_crash_logs (3).txt](https://github.com/aniyomiorg/aniyomi/files/14397609/aniyomi_crash_logs.3.txt)
[aniyomi_crash_logs (4).txt](https://github.com/aniyomiorg/aniyomi/files/14397610/aniyomi_crash_logs.4.txt)
[aniyomi_crash_logs (5).txt](https://github.com/aniyomiorg/aniyomi/files/14397611/aniyomi_crash_logs.5.txt)

### Aniyomi version

App version: 0.15.2.4-7509 (standard, ab30b43d5, 122, 2024-02-19T09:08Z) Android version: 10 (SDK 29; build QKQ1.191222.002) Android build ID: QKQ1.191222.002 Device brand: lge Device manufacturer: LGE Device name: timelm (timelm) Device model: LM-V600 WebView: Android System WebView 123.0.6312.3 MPVLib version: mpv c6ccabe (Jan 28 2024 15:38:16) Libplacebo version: v7.342.0 FFmpeg version: n6.1.1

### Android version

Android 10

### Device

LG V60

### Other details

Given this is a system crash, I wasn't sure if this should go in extensions or not. Also, I'm coming over from Tachiyomi and their recommended secondary extensions list via https://raw.githubusercontent.com/keiyoushi/tachiyomi-extensions/repo/index.min.json so I don't know if I should also be sending a crash notice to their bug report list also given this is one of their extensions.

[I'm currently trapped on OG Tachiyomi since my app fails to complete a backup file (and I have no way of manually copying/transferring the entire database so far as I know; unless copying everything would magically work), so I'm having to do some mix & match on things. 🙄🤦🏾‍♂️😅 So apologies if this is more complicated. It crashed on this and the last/final version of Tachiyomi Preview.]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dragoon91786** [comment]
My main confusion on where to post was due to it causing an endless loop crash. Normally, when a download fails, it doesn't crash the app. Just gives us the error. 😅

**Comment by Secozzi** [comment]
This appears to be an extension issue, not an app issue
