### ISSUE TITLE
unable to update/install extension

### ISSUE THREAD

**Issue by Viethiel** [aniyomiorg/aniyomi#1467]
### Steps to reproduce

Look for extension you want to install then tap download/install.

### Expected behavior

The extension to be installed.

### Actual behavior

But it will load for a second then go back to the download button and the extension being unable to be installed.

### Aniyomi version

preview r7509

### Android version

android 14

### Device

Redmi k20 pro

### Other details

I have also tried to install normal aniyomi version and app like mihon which is like tachiyomi and they do the same thing. Maybe an issue with android version. Will wait for a fix.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
try turning off miui optimizations or use different installer in `more - settings - advanced - installer` and if it's only about manga/external extensions then already reported in #1450

**Comment by Viethiel** [comment]
> try turning off miui optimizations or use different installer in `more - settings - advanced - installer` and if it's only about manga/external extensions then already reported in #1450

Similar but his can be worked around by uninstalling and installing the extension but mine cannot be installed at all wether it be an external repo or the ones it came with, so any extension cannot be installed. Additional info I have a custom ROM that is android 14, it's not an miui. Maybe it's and issue with android 14 as the qouted issue also run an android 14.

**Comment by Viethiel** [comment]
Okay I tried changing the installer to legacy but now it says there is a problem parsing the package.

**Comment by Viethiel** [comment]
> > Okay I tried changing the installer to legacy but now it says there is a problem parsing the package.
> 
> use private then, if you're not using your extensions in other 3rd party apps (note: u need to uninstall old extensions if you're using 3rd party repo or it may cause installation issues)
> 
> > Similar but his can be worked around by uninstalling and installing the extension
> 
> if it's only about manga/external extensions then u can close this issue as it's already reported

It's not only about the manga/external extensions but all of it even the aniyomi extensions, I can't install any of the extensions within the app. A workaround I did is go to the 3rd party repo and download the extension apk there but I can't find the aniyomi movies/anime repo apk extensions.

**Comment by Toffua** [comment]
Hi! I have the same problem. Did you find the solution?

**Comment by Secozzi** [comment]
If none of the solutions that fakebhai mentioned works, it's most likely an issue with the ROM, not aniyomi.

**Comment by Ven84XD** [comment]
I just changed the installer from package installer to legacy and it worked
