### ISSUE TITLE
Unable to update anime/manga Library 

### ISSUE THREAD

**Issue by ShoyebOP** [aniyomiorg/aniyomi#1468]
### Steps to reproduce

1. Open aniyomi.
2. Go to anime/manga tab.
3. Try to update library through pulling down from top screen or tap on the three dots on the top left of the screen and then tap update library.

### Expected behavior

The app should start updating the library and there should be a notification showing the progress.

### Actual behavior

It shows a pop up saying "updating the library" but nothing actually happens.

### Aniyomi version

0.15.2.4-7509 (standard, ab30b43d5, 122, 2024-02-19T09:08Z)

### Android version

13 (SDK 33; build lineage_cheeseburger-userdebug 13 TQ3A.230901.001 c666ad56da) Android build ID: lineage_cheeseburger-userdebug 13 TQ3A.230901.001 c666ad56da

### Device

OnePlus5 (OnePlus5) Device model: ONEPLUS A5000 WebView: Android System WebView 120.0.6099.144 MPVLib version: mpv c6ccabe (Jan 28 2024 15:38:16) Libplacebo version: v7.342.0 FFmpeg version: n6.1.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
## Smart updates
**Aniyomi** intelligently works to reduce the number of series in a global update to reduce the load on sources. To be updated, a series has to meet the following conditions:
1. The series has been **started**, you've read at least one chapter.
2. The series is **not marked Completed** by the source, there's an expectation of more chapters in the future.
3. The series has **no unread chapters**, you've read all the chapters you already have,
4. There's been enough time since the last update for the series that **the app predicts a new chapter is available**. You can see how often the app predicts a new chapter for a series by looking at the hourglass. After that many days, the app will alow that series to check for updates.

**Comment by ShoyebOP** [comment]
> ## Smart updates
> **Aniyomi** intelligently works to reduce the number of series in a global update to reduce the load on sources. To be updated, a series has to meet the following conditions:
> 
> 1. The series has been **started**, you've read at least one chapter.
> 2. The series is **not marked Completed** by the source, there's an expectation of more chapters in the future.
> 3. The series has **no unread chapters**, you've read all the chapters you already have,
> 4. There's been enough time since the last update for the series that **the app predicts a new chapter is available**. You can see how often the app predicts a new chapter for a series by looking at the hourglass. After that many days, the app will alow that series to check for updates.

I now understand how it works. But can you tell me how accurate the prediction of the app is? I mean how does it predict? From source or tracker etc?

**Comment by rktfier** [comment]
> ## Smart updates
> 
> **Aniyomi** intelligently works to reduce the number of series in a global update to reduce the load on sources. To be updated, a series has to meet the following conditions:
> 
>     1. The series has been **started**, you've read at least one chapter.
> 
>     2. The series is **not marked Completed** by the source, there's an expectation of more chapters in the future.
> 
>     3. The series has **no unread chapters**, you've read all the chapters you already have,
> 
>     4. There's been enough time since the last update for the series that **the app predicts a new chapter is available**. You can see how often the app predicts a new chapter for a series by looking at the hourglass. After that many days, the app will alow that series to check for updates.

How the hell does one disable auto updates? I've been struggling with this since it was introduced and not even a single time the anime/manga gets updated without requiring manual updates. I swear I'm about to start a fork off and undo that damned commit that introduced this.

**Comment by rktfier** [comment]
I found the way, you just have to search for smart updates and disable predict chapter release. It's the dumbest thing ever as before I disabled it i refreshed my library 10 times for new episodes and only got a single chapter, after disabling it and refreshing i now have 11 new chapters (from multiple series/animes) instantly, some released a week ago.

**Comment by sBaydin** [comment]
I was just looking for why I can't get an update, and the reason was smart renewal. :) Those who can't get updates should turn it off ;)
