### ISSUE TITLE
Error when searching 

### ISSUE THREAD

**Issue by Vhiniz** [aniyomiorg/aniyomi#1471]
### Steps to reproduce

1 - do a global search 
2 - Click on an anime that will appear in the search

### Expected behavior

You should open the anime page

### Actual behavior

unexpected error 

### Aniyomi version

0.15.2.4

### Android version

Android 11

### Device

Moto e40

### Other details

![Screenshot_20240301-082107](https://github.com/aniyomiorg/aniyomi/assets/115049368/d492e3bf-2054-405d-a5b2-0041a01c6abb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
can't reproduce this error please attach crash logs file and if possible attach screen recording as well.
and make sure you did all acknowledgement steps like troubleshooting and updating your extensions.

**Comment by Vhiniz** [comment]
The error is happening because of the Betteranime extension. It is not working properly.

**Comment by Secozzi** [comment]
This is an extension issue, not an app issue.
