### ISSUE TITLE
Crash after returning from the video player on latest preview

### ISSUE THREAD

**Issue by griffi-gh** [aniyomiorg/aniyomi#1473]
### Steps to reproduce

1. Play a video from the main page
2. Try to return back (On android 14 with enabled predictive back gesture, the app crashes like half a second after starting (but without completing) the gesture)
3. The app should crash

### Expected behavior

The app should... not crash

### Actual behavior

The app crashes (by hitting an assert inside mpv) after returning from the video player (or randomly while using the back gesture with predictive back gesture enabled)

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/14472751/aniyomi_crash_logs.txt)

### Aniyomi version

0.15.2.4-7509 (preview)

### Android version

Android 14

### Device

Samsung Galaxy A52s (SM-A528B)

### Other details

Crash (Predictive back gesture):  

https://github.com/aniyomiorg/aniyomi/assets/45996170/c9303609-ce3f-47bb-b7ca-ce83420b38c2  

Crash (Back button):

https://github.com/aniyomiorg/aniyomi/assets/45996170/c0c52de9-5a7b-47c9-86ea-db4a949d622b

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by griffi-gh** [comment]
(seemingly already fixed, needs testing :p)

**Comment by Secozzi** [comment]
This has most likely been fixed in a newer release of preview. If the issue still persists, please open a new issue.
