### ISSUE TITLE
Aniyomi's Video Player needs a Sleep Timer

### ISSUE THREAD

**Issue by Kroody** [aniyomiorg/aniyomi#1476]
### Describe your suggested feature

I've been using aniyomi a lot recently and noticed that it doesn't have a sleep timer. 

It's a feature that'll allow users to set a timer that automatically stops video playback after a specified period of time. It's ideal for bedtime viewing and will enhance user experience by offering convenient playback management. It'll also help with energy conservation, and add more versatility to the video player. Importantly, the feature should offer customizable durations rather than being constrained to fixed ones. 

Thanks in advance😄

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
You could just deactivate the autoplay for the next episode, and the screen will turn off after the current episode is done 😉

**Comment by Kroody** [comment]
> Seems out of scope

How is it out of scope? A lot of video players have it. This is 2024 dammit.

**Comment by Secozzi** [comment]
As mentioned in the comments, all you need to do is turn off autoplay and it will turn itself off when finished playing

**Comment by LittleFreak** [comment]
> > As mentioned in the comments, all you need to do is turn off autoplay and it will turn itself off when finished playing
> 
> What if it's a 2-3hr long video. This method won't suffice and won't help conserve battery power.

There are apps for that... I loke Caffeine, just the other way around...
I'm sure you'll find your sleeptimer quicktile somewhere in your favourite app store.
