### ISSUE TITLE
Episodes not updating in Gogoanime

### ISSUE THREAD

**Issue by vermaabhinav04** [aniyomiorg/aniyomi#1478]
### Steps to reproduce

1.Upon entering in that specific wall.
2.Trying to refresh for new episode.
3.It isn't refreshing and showing some error or No new episodes.
![Screenshot_2024-03-04-02-55-17-532_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi/assets/156640602/952e8d67-e2ca-4340-8128-b5c63b9c88d3)

### Expected behavior

Episodes should be refreshed.

### Actual behavior

Episodes are not refreshing, and showing some error or No new episodes.

### Aniyomi version

0.15.2.4

### Android version

Android 12

### Device

Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by PrashantNath** [comment]
its same for me .

**Comment by avinave14102001** [comment]
![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi/assets/151993381/acfc2bf2-387c-4708-be53-b3546fe92a18)


I face same problem

Please 🙏🙏🥺🥺 some one solve this problem please I request for my heart

**Comment by avinave14102001** [comment]
> its same for me .

![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi/assets/151993381/33dc598b-a9e8-4e88-9d26-20e4f85f6b4f)


I am face same problem

**Comment by avinave14102001** [comment]
> ### Steps to reproduce
> 1.Upon entering in that specific wall. 2.Trying to refresh for new episode. 3.It isn't refreshing and showing some error or No new episodes. ![Screenshot_2024-03-04-02-55-17-532_xyz jmir tachiyomi mi](https://private-user-images.githubusercontent.com/156640602/309583112-952e8d67-e2ca-4340-8128-b5c63b9c88d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDc5MDQsIm5iZiI6MTcwOTU0NzYwNCwicGF0aCI6Ii8xNTY2NDA2MDIvMzA5NTgzMTEyLTk1MmU4ZDY3LWUyY2EtNDM0MC04MTI4LWI1YzYzYjljODhkMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxMDIwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDEyYmI5MTQxMmMzNGY2YjA4OTRhZWJhMjBkMmU2NjA1ZGI1ZGNmM2JkYTQwY2JlMTU1ZWRiNmMxMzFhYjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o7hh_qlKBkOzL-ICosTWjtMu_eFJw5cZxww_p3G6gsY)
> 
> ### Expected behavior
> Episodes should be refreshed.
> 
> ### Actual behavior
> Episodes are not refreshing, and showing some error or No new episodes.
> 
> ### Crash logs
> _No response_
> 
> ### Aniyomi version
> 0.15.2.4
> 
> ### Android version
> Android 12
> 
> ### Device
> Redmi Note 9
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
> * [x]  If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
> * [x]  I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
> * [x]  I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I will fill out all of the requested information in this form.




![Screenshot_2024-03-04-07-12-49-29_dd604340c1d7941d42aee14dd16e00e8](https://github.com/aniyomiorg/aniyomi/assets/151993381/a39ef184-21b0-40b0-9a2d-f43ea9f774a3)



I am face same problems  

I request please someone solve this problem oh my kind request for my heart please give us solution for this problem we have an accept extremely request anyone please solve this problem as a anime fan please solve this problem

If any solution are coming please share everyone for as anime fan

**Comment by avinave14102001** [comment]
> ### Steps to reproduce
> 1.Upon entering in that specific wall. 2.Trying to refresh for new episode. 3.It isn't refreshing and showing some error or No new episodes. ![Screenshot_2024-03-04-02-55-17-532_xyz jmir tachiyomi mi](https://private-user-images.githubusercontent.com/156640602/309583112-952e8d67-e2ca-4340-8128-b5c63b9c88d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDgxMzMsIm5iZiI6MTcwOTU0NzgzMywicGF0aCI6Ii8xNTY2NDA2MDIvMzA5NTgzMTEyLTk1MmU4ZDY3LWUyY2EtNDM0MC04MTI4LWI1YzYzYjljODhkMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxMDIzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTkyYzFjYjFhZmM0OWM5ZDNlZmQ2MWUzNTRhN2I1MDg3NjllMWMyZTUyYzkwZDE5Nzk0ZDNjNDFjNmFkYzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s8OF0MOhoebWu0-1HRVO4m04Q8G99r4OVndukP8Jfj0)
> 
> ### Expected behavior
> Episodes should be refreshed.
> 
> ### Actual behavior
> Episodes are not refreshing, and showing some error or No new episodes.
> 
> ### Crash logs
> _No response_
> 
> ### Aniyomi version
> 0.15.2.4
> 
> ### Android version
> Android 12
> 
> ### Device
> Redmi Note 9
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
> * [x]  If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
> * [x]  I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
> * [x]  I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I will fill out all of the requested information in this form.



Do have solution about manga related exception

Please provide solutions

**Comment by abdallahmehiz** [comment]
Extensions related issues should reported in the extensions repository
