### ISSUE TITLE
An option to auto select custom resolution/highest

### ISSUE THREAD

**Issue by Jeskoh** [aniyomiorg/aniyomi#1491]
### Describe your suggested feature

I found that on some animes the default resolution was set to lowest which needs to then be set manually to the highest available.

There should be an option to set the default resolution to the highest option with the preferred audio if available (ex :in case of  resolution set to highest and preferred audio English if the watched anime only has from 240p to 1080p but jp audio only then it will put the video to 1080 up since no English dubs). If the option can also be chosen for preferred subs it would be insane.

To be even more precise on the feature :
Default resolution : max/min/custom(closest highest if not found)
Default dub : scroll down bar with all supported dub options (OV if not found)
Defaut sub : same as dub but english if not found ?

Please let me know if you need more details and if the feature exists already please teach me how to activate it.

Thanks for your work so far !!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
> Please let me know if you need more details and if the feature exists already please teach me how to activate it.

go to `browse - anime extensions - settings - settings again` there you can set your resolution.
or you can just

open your extension and click on 3 dots above then click on settings

**Comment by Jeskohpandapowa** [comment]
Thanks for letting me know. 
I have the settings alrd put to 1080p and English but in the case there are no 1080p it takes the lowest quality (ex black cat on yomiroll that has a max of 480 is shown with 240p per default).

**Comment by Secozzi** [comment]
The order of video qualities is managed by extensions, not the app.
