### ISSUE TITLE
Remember last selected subtitle language on multi-sub video

### ISSUE THREAD

**Issue by nikitaluger** [aniyomiorg/aniyomi#1492]
### Steps to reproduce

1. Play multi-subbed video in library.
2. Select preferred video subtitle.
3. Play video to confirm correct subtitle.
4. Return to library.
5. Continue watching video.

### Expected behavior

Video should continue playing from timestamp you last stopped watching with the previous selected subtitle option, in this case #12: English.
![Screenshot_2024-03-11-17-24-03-841_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/20486047/9627392e-56ac-41fb-bf50-638403fb711a)
 

### Actual behavior

Video continues to play from timestamp you last stopped watching but the subtitle goes back to the default subtitle, in this case #1: Albanian.
![Screenshot_2024-03-11-17-23-53-991_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/20486047/314362f9-bc8e-42eb-8dee-6af37e8f85ab)

### Aniyomi version

0.15.2.4

### Android version

Android 14

### Device

POCO F4 GT

### Other details

Video used for this particular issue is Aquaman 2 downloaded via Fmovies extension but same issue happens with other movies with multiple subtitles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
