### ISSUE TITLE
Phone heats too much while downloading large amount of chapters.

### ISSUE THREAD

**Issue by ShoyebOP** [aniyomiorg/aniyomi#1495]
### Steps to reproduce

1. Open aniyomi.
2. Choose a manga (that has more than 300 chapters).
3. Select the download button.
4. Select unread.

### Expected behavior

I know this might not be an issue that can be fixed, so if this could be fixed then phone should not heat that much. If not it should at least show a warning about the heating issue (as it pops up a notification warning about source block).

### Actual behavior

While downloading large amount of chapters the phone quickly starts to heat up and it keeps heating up. When I first found out about it I was so scared to think my phone is going to be damaged as it heated up the phone so much that I can't even touch the screen and I had to shut the phone down for 5 minutes.

### Aniyomi version

App version: 0.15.2.1-7454 (standard, 61c70597a, 119, 2024-01-14T23:36Z)

### Android version

13 (SDK 33; build lineage_cheeseburger-userdebug 13 TQ3A.230901.001 c666ad56da) Android build ID: lineage_cheeseburger-userdebug 13 TQ3A.230901.001 c666ad56da

### Device

Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus5 (OnePlus5) Device model: ONEPLUS A5000

### Other details

As I said I don't know if it is an issue only with my phone nor if it could even be fixed but if it is universal issue a warning is must. As someone who doesn't know about it may download a lot chapters while keeping phone idle and it could damage the phone

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by meowmeowofthemeows** [comment]
I recommend putting your phone in the freezer, run water over it, or you could also just place an ice cube on the back. :+1:

**Comment by giorgionegro** [comment]
there is the download speed limiter for this very reason, just limit the speed to something your phone can handle without overheating

**Comment by ShoyebOP** [comment]
> there is the download speed limiter for this very reason, just limit the speed to something your phone can handle without overheating

Thanks, I never knew something like that existed😅
