### ISSUE TITLE
Anime updates not working 

### ISSUE THREAD

**Issue by NKJibu02** [aniyomiorg/aniyomi#1498]
### Steps to reproduce

1. Entered the app
2. Drag down global updates or drag down update for an anime
3. After a while Shows socket handle timeout 

### Expected behavior

Anime should update

### Actual behavior

Socket handle timeout 

### Aniyomi version

0.15.2.4

### Android version

Android 10 

### Device

Infinix SMART 6/X657C 

### Other details

![Screenshot_20240314-052834](https://github.com/aniyomiorg/aniyomi/assets/148685320/3464088f-97cc-45ea-ad86-a5bc62eb65fd)
![Screenshot_20240314-052822](https://github.com/aniyomiorg/aniyomi/assets/148685320/9d558dcf-782e-4966-b264-74e5c9ab7910)
![Screenshot_20240314-052744](https://github.com/aniyomiorg/aniyomi/assets/148685320/b4bec511-60fa-4493-b50e-4a0e95f763ed)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Not an app issue, it's either with your internet or the extension.
