### ISSUE TITLE
Yomiroll not working 

### ISSUE THREAD

**Issue by Purushottamkeshari** [aniyomiorg/aniyomi#1499]
### Steps to reproduce

1. Open aniyomi 
2. Select yomiroll 
3. Open yomiroll play any episode 
4. Episode not playing 
![Screenshot_20240315_235915_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/163583525/de0c6b05-cce1-44d9-bc6d-ff62237f2f05)
![Screenshot_20240315_235915_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/163583525/25eefa3c-9ef5-4cb5-8862-6edb4b7eff5a)

### Expected behavior

0

### Actual behavior

0

### Crash logs

.0

### Aniyomi version

0.15.2.4

### Android version

Android 14

### Device

Samsung galaxy a23 5g

### Other details

Yomiroll not work .
I am first time create account on github sorry for 
Mistake I don't no how to create report .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by edmxn** [comment]
Broken rn

**Comment by fakebhai** [comment]
this repo isn't for extensions + it's already reported
