### ISSUE TITLE
From every extension the download multi-tread not work

### ISSUE THREAD

**Issue by Domipoke** [aniyomiorg/aniyomi#1504]
### Steps to reproduce

If I download using multitread the result is sometimes an unrecognized file, others is a Standalone Caroutine error message

### Expected behavior

.

### Actual behavior

.

### Aniyomi version

.

### Android version

.

### Device

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
use safe downloading mode if it gives you any error, also fill necessary details you can't just "." in them.
