### ISSUE TITLE
App update not working in-app

### ISSUE THREAD

**Issue by jeyjai** [aniyomiorg/aniyomi#1505]
### Steps to reproduce

1. wait for new update to release
2. open app and press download on the "new version" popup or manually check for update i  settings->about and start download that way

### Expected behavior

The update downloads completely and you can install the update

### Actual behavior

The download starts and after a few seconds it disappears. No fail message or anything, the notification showing it downloading just disappears, so I'm not sure what's causing it.

### Crash logs

App don't crash so i have no logs, but video shows
1. Checking for update and start download, wait for download icon in notification bar to disappear
2. Show notification panel that it's gone.
3. Start download again and have notification panel open to show it disappearing.
(did the same thing twice)
4. Lastly i try to download it by clicking download on the notification itself with the same result

https://github.com/aniyomiorg/aniyomi/assets/7854537/7c768f2f-c6b1-4a7a-bef4-6eac14f0d806

### Aniyomi version

Preview r7509 and 0.15.2.3

### Android version

Android 14

### Device

Samsung Galaxy A52s 5G

### Other details

This is also happening on the regular version and have been for some time now, i even downloaded 1.5.2.3 a minute ago to confirm it's still happening on normal version as well.

There have been times where it failed countless times and after trying a bunch of times, it suddenly worked, so i have no idea what's causing it.

Also want to point out that it's not my device because downloading and installing extensions through aniyomi works just fine, and so does all other apps when downloading updates in-app. So it's only happening on aniyomi. Tachiyomi and all different tachiyomi forks I've tried downloads updates just fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
