### ISSUE TITLE
[PIC] I propose a little change to the UI for consideration: move the browse extension tab to More and Manga to the home tab

### ISSUE THREAD

**Issue by shortbach** [aniyomiorg/aniyomi#1512]
### Describe your suggested feature

![Screenshot_20240326-130341](https://github.com/aniyomiorg/aniyomi/assets/75778648/4a273ba0-7b95-4877-b323-075b66c23586)

as shown in the picture above, just move the tab around and I think this way it makes more sense and I dont imagine it would be too much work for the dev team

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
The feature already exists, check the "Navigation Style" setting in Settings -> Appearance

**Comment by fakebhai** [comment]
> The feature already exists, check the "Navigation Style" setting in Settings -> Appearance

I think they want to move extensions to more tab which isn't available

**Comment by abdallahmehiz** [comment]
Ah, sure adding it should be easy. I'll try to make a PR later.

**Comment by shortbach** [comment]
> The feature already exists, check the "Navigation Style" setting in Settings -> Appearance

I would like to move the "browse extension" to the more tab since I and I assume many other users dont use extension much after we have set up our addon and library. All other tabs are used much more frequently.

But the option to move the extension to more tab is not available

**Comment by REFLEXGAMING007** [comment]
Brother..... I use browse extension feature wwar too frequently tgan everything else because of Jellyfin 😐

Don't change it if possible please or atleast make it as a toggle so that we can choose to move it more tab

**Comment by abdallahmehiz** [comment]
Navigation bars in material 3 cannot have more than 5 items, so your suggestion cannot be granted.
This feature is not mandatory for everyone, you can change which tab to put in the more tab in Settings -> Appearance -> Navigation Style.

**Comment by REFLEXGAMING007** [comment]
Okay if it's optional then I'm fine

thnx for the clarification
