### ISSUE TITLE
JsonDecoding exception error help please. 

### ISSUE THREAD

**Issue by helpme12321** [aniyomiorg/aniyomi#1516]
### Steps to reproduce

Help i keep getting a json error and it wont let me watch or download anime but manga works just fine. All anime show up as 0 episodes 

Here is error: 

JsonDecodingException: Unexpected JSON token at offset 23: Expected string literal but 'null
literal was found at path: $.result
Use 'coercelnputValues = true' in 'Json 0' builder to coerce nulls to default values.
JSON input: (status",403,"result".null,'message"."Request is invalid."'"'messages".["Request is
invalid."]

### Expected behavior

I have tried uninstalling and reinstalling but the error did not go away. 

### Actual behavior

No anime show up and i cannot watch or download anime.

### Aniyomi version

most recent from website 

### Android version

android 13

### Device

galaxy z fold 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
this repo isn't for extensions, read acknowledgements before marking them.

**Comment by helpme12321** [comment]
> this repo isn't for extensions, read acknowledgements before marking them.

How would i know if this is a problem with the extension or not? I dont know coding. I dont think this is a problem with the extension all anime extensions are giving that error.

**Comment by helpme12321** [comment]
Could someone please give advice on how to fix this

**Comment by abdallahmehiz** [comment]
Try with other extensions ig, and if the issue persists, you can try [Troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
If you haven't been able to solve it consider making an issue in [The extensions repo](https://github.com/aniyomiorg/aniyomi-extensions).
