### ISSUE TITLE
Title language not changing from Romaji to English.

### ISSUE THREAD

**Issue by R-iscool** [aniyomiorg/aniyomi#1518]
### Steps to reproduce

1. Open an anime source( I used hianime).
2. Go to settings and click on preferred title language.
3. Click on English and it will instruct you to restart the app.
4. Restart the app and open the anime source again.
5. Check if title is changed or not.It should not have been changed.

### Expected behavior

The title wont change.

### Actual behavior

The title doesn't change 

### Aniyomi version

0.15.2.4

### Android version

Android 12

### Device

Redmi  Power 9

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by SquadCraftFTW** [comment]
I have the same issue

**Comment by Secozzi** [comment]
Not an app issue.

**Comment by Sai-9305** [comment]
Has this been resolved or anyone found a solution?
