### ISSUE TITLE
Add a hindi extension.

### ISSUE THREAD

**Issue by Coolboy067** [aniyomiorg/aniyomi#1519]
### Describe your suggested feature

There are two extension animeworldindia and animesaga in aniyomi but both doesn't work fine so I request you to add hindi extension like animerulz.to to stream anime in hindi language too. 

Otherwise please fix animeworld india and animesaga extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment]
> If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).

Have you read this?
!close

**Comment by Lolen10** [comment]
> > If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
> 
> Have you read this? !close

I think he just checkt it without reading it. Some type like stuff as "I've read and agree to the TOS" or something like that.

**Comment by lasersPew** [comment]
> > > > If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
> > > 
> > > 
> > > Have you read this? !close
> > 
> > 
> > I think he just checked it without reading it. Some type like stuff as "I've read and agree to the TOS" or something like that.
> 
> Typical Lindians

Typically anyone

**Comment by fakebhai** [comment]
@abdallahmehiz
