### ISSUE TITLE
Aniwave JsonDecodingException 

### ISSUE THREAD

**Issue by Roy-zd** [aniyomiorg/aniyomi#1522]
### Steps to reproduce

1. Open aniwave
2. Click any anime
3. Episodes don't load and error message appears

### Expected behavior

Episodes should load and be streamable 

### Actual behavior

While trying to load error message appears extension version 14.66

### Crash logs

JsonDecodingException: Unexpected JSON token at

offset 23: Expected string literal but 'null' literal was found at path: $.result

Use 'coerceInputValues = true' in 'Json {}' builder to

coerce nulls to default values.

JSON input:

{"status":403,"result":null,"message":"Request is invalid.","messages":["Request is invalid."]}

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Device

Redmi note 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by R-N** [comment]
Same here. It has been at least a week or two

**Comment by R-N** [comment]
Wait this isn't the correct repo. Should be https://github.com/aniyomiorg/aniyomi-extensions
