### ISSUE TITLE
Anilist

### ISSUE THREAD

**Issue by Mynameluis** [aniyomiorg/aniyomi#1525]
### Steps to reproduce

1
![Screenshot_20240408-004801](https://github.com/aniyomiorg/aniyomi/assets/145807935/7a85cb24-8031-4d99-8bd3-752c5b413e37)

2
![Screenshot_20240408-004951]

3

![Screenshot_20240408-005024](https://github.com/aniyomiorg/aniyomi/assets/145807935/f4575f6a-f333-4656-b738-4454f97d75c6)

![Screenshot_20240408-005109](https://github.com/aniyomiorg/aniyomi/assets/145807935/09efed40-2a0f-4bcc-a21b-e55faa818e94)

![Screenshot_20240408-005139](https://github.com/aniyomiorg/aniyomi/assets/145807935/5d17cec7-ebee-4686-af8b-77adf8df652a)

### Expected behavior

Achar normalmente 

### Actual behavior

Não tá achando algumas coisas 

### Aniyomi version

0.15.2.4

### Android version

10

### Device

moto e(7) plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mynameluis** [comment]
![Screenshot_20240408-004819](https://github.com/aniyomiorg/aniyomi/assets/145807935/59cf5cfb-c5d7-448f-b0b5-85e3d0e3676f)
![Screenshot_20240408-004951](https://github.com/aniyomiorg/aniyomi/assets/145807935/29642ef1-9adc-4640-af21-e589c6c7c619)

**Comment by Secozzi** [comment]
Most likely some temporary issue on anilist's end, please open a new issue if the problem persists.
