### ISSUE TITLE
Crash on start in the latest preview

### ISSUE THREAD

**Issue by Verl4ssener** [aniyomiorg/aniyomi#1527]
### Steps to reproduce

I don't know why it crashes and how to recreate it. I just watched anime on HiAnime wanted to leave the player and the the app crashed. Ever since then I can't acces the app.

### Expected behavior

The app should start.

### Actual behavior

Instant crash.

Screen record:
https://github.com/aniyomiorg/aniyomi/assets/101367476/2bf1b494-8bcb-4538-8585-6fe35b0b26ec

### Crash logs

![aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/14906042/aniyomi_crash_logs.txt)

### Aniyomi version

0.15.2.4-7513 or r7513 

### Android version

Android 13

### Device

Motorola edge 30 fusion

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
can you try clearing app cache and force stopping it? 
**do not clear app data**

**Comment by Verl4ssener** [comment]
Already tried that and didn't do anything

**Comment by Verl4ssener** [comment]
> can you try clearing app cache and force stopping it? 
> **do not clear app data**

Already tried that and didn't do anything

**Comment by Verl4ssener** [comment]
> Should be fixed with #1526 

Didn't do anything:/

**Comment by abdallahmehiz** [comment]
> Didn't do anything:/

Cause it wasn't merged yet

**Comment by jmir1** [comment]
Should be fixed now
