### ISSUE TITLE
Windows version 

### ISSUE THREAD

**Issue by phoenix02023** [aniyomiorg/aniyomi#1528]
### Describe your suggested feature

I really like the aniyomi app . It would be really nice to have a windows version for it so I could watch in pc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Kaidyn-Doshi** [comment]
You can run the aniyomi app on windows 11 or windows  10 by installing it through ADB with windows subsystem for android. Tone of the comments also says how to push files to your mock android device, so you can even restore a backup. 

https://gist.github.com/HimDek/eb8704e2da1d98240153165743960e17#Enable-Hyper-V

**Comment by Secozzi** [comment]
We don't have any plans on making a windows version anytime soon.
