### ISSUE TITLE
Nfc file transfer for syncing device info

### ISSUE THREAD

**Issue by puffpuff289** [aniyomiorg/aniyomi#1529]
### Describe your suggested feature

Like the title says, The idea is to use NFC to quickly sync backup information between multiple devices that have the app. Presets for what specific information can be synced when within proximity and in addition with a list of what devices are allowed to sync up data to prevent hacking or data theft.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Can't you just move the backup file via nfc outside of aniyomi?
