### ISSUE TITLE
Automatic update is not working properly

### ISSUE THREAD

**Issue by Night0Fury** [aniyomiorg/aniyomi#1538]
### Steps to reproduce

If I open aniyomi it only updates some of manga, manhwa and anime, others are left out.
I have already put the automatic update in the global update at library settings set to update each 12hr but it update only few only, after few days later it updates it or I should reload each mangas and manhwas each time I want to read. Or it does not update the library and I should reload everytime and check the the new chapter came or not. I also have set no restriction on the update and include all the library to update each 12hrs but it is not updating. Is there a fix?

### Expected behavior

Update every library category 

### Actual behavior

Only some of mangas are getting updated from each category 

### Aniyomi version

App version: 0.15.2.4-7519 (standard, cffb5a8ae, 122, 2024-04-12T07:34Z) 

### Android version

Android 11

### Device

Realme 6 pro

### Other details

![Screenshot_2024-04-16-02-50-21-16_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi/assets/115478378/e8b62c33-c99d-4a4e-b330-6a0d770d2255) 

if it is only for me tell me how to fix it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Night0Fury** [comment]
I think I solved it by disabling smart update

**Comment by Luffyirl** [comment]
> I think I solved it by disabling smart update

dont disable smart updates , keep all the options on exept predict next chapter.

**Comment by joaoalejandro** [comment]
> > I think I solved it by disabling smart update
> 
> dont disable smart updates , keep all the options on exept predict next chapter.

This worked for me

**Comment by abdallahmehiz** [comment]
> I think I solved it by disabling smart update

I think I'll consider it solved then.
