### ISSUE TITLE
Default skip intro length setup issue

### ISSUE THREAD

**Issue by fakebhai** [aniyomiorg/aniyomi#1539]
### Steps to reproduce

open aniyomi go to `more - settings - player - default skip intro length`
set it to any number it'll show -1 of actual preference number

https://github.com/aniyomiorg/aniyomi/assets/101493467/a7698469-02e9-4ae9-9f0f-d40db1eb631d

### Expected behavior

85s should show/set 85s
86s should show/set 86s and so on

### Actual behavior

85s shows/sets 84s
86s shows/sets 85s

### Aniyomi version

r7519

### Android version

Android 12

### Device

Iqoo 3 5G

### Other details

it also causes some other issues like if you long press on +85 inside the player it becomes 86 without touching it, not sure if it's completely relevant or not. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by SoniKarsh** [comment]
FYI: Looking into this issue.

**Comment by abdallahmehiz** [comment]
should be fixed in #1598
