### ISSUE TITLE
Hentais tube

### ISSUE THREAD

**Issue by Gui02789** [aniyomiorg/aniyomi#1543]
### Steps to reproduce

The extension show the Episodes but when is select happen this error
![Screenshot_2024-04-20-23-21-29-262_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi/assets/95433594/8fbce67a-f166-4817-93b6-8de0c93400f8)

### Expected behavior

...

### Actual behavior

...

### Aniyomi version

0.15.2.4

### Android version

Android 14

### Device

Redmi note 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
this repo isn't for extensions. don't mark acknowledgements before reading them.
