### ISSUE TITLE
An Option to have my preferred Language and Subs in Local anime sources 

### ISSUE THREAD

**Issue by PrimeTwister** [aniyomiorg/aniyomi#1545]
### Describe your suggested feature

A setting which allows you to set ur default language and subs in local anime sources. So that you don't have to manually do it for every episode or series.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
You can set your preferences in players config file and it will apply for any source, go to: `Settings > Player > Advanced player settings > Edit MPV configuration file for further player settings` and put this in there 

```
alang = jpn,en,eng
slang = en,eng
```

**Comment by PrimeTwister** [comment]
Thanks didn't know there was a feature like that
