### ISSUE TITLE
Is it possible to bring back the custom download option that has been removed?

### ISSUE THREAD

**Issue by ShoyebOP** [aniyomiorg/aniyomi#1546]
### Describe your suggested feature

There is five option available now when you tap on the download button -
~next chapter
~next 5 chapters 
~next 10 chapters 
~next 25 chapters 
~unread

But there was another option named custom(maybe it called something else I don't remember) which allowed to download any amount of chapters in one click.

### Other details

I don't know why it was removed or in which version it got removed. But I really want this feature back if possible as it will make the downloads so much easier.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It was removed with the Mihon merge, neither we nor MIhon have any plans on bringing it back.
