### ISSUE TITLE
Shikimori tracking anime - HTTP error 404 (+ example how to fix it)

### ISSUE THREAD

**Issue by Froxim** [aniyomiorg/aniyomi#1553]
### Steps to reproduce

1. Anime should be added to the list on Shikimori
2. Select this anime to track in the application
3. API returns HTTP error 404

### Expected behavior

Anime should start tracking without errors

### Actual behavior

HTTP error 404

### Aniyomi version

0.15.2.4

### Android version

Android 12

### Device

Xiaomi Redmi Note 9 Pro

### Other details

I examined the request creation code in the ShikimoriApi.kt file and discovered the cause of the error:
![IMG_20240425_093443](https://github.com/aniyomiorg/aniyomi/assets/81477641/094147c6-712b-401f-8756-8de4383aedee)
If replace "**mangas**" with "**animes**" the tracking will work.
I checked it on a copy - HTTP error 404 no longer appeared.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Diehardboy1722** [comment]
**_Same problem and don't know how to solve_**.

**Comment by Froxim** [comment]
I described the fix in Other details.  But I've never used Github, and I don't know how to add it to the project.  The screenshot shows the place in the code that needs to be replaced with "animes".  This will solve the problem.
![IMG_20240508_212856](https://github.com/aniyomiorg/aniyomi/assets/81477641/e1c5dfd8-fadc-4f1e-a3c5-af6473928a00)

**Comment by fakebhai** [comment]
> I described the fix in Other details.  But I've never used Github, and I don't know how to add it to the project.  The screenshot shows the place in the code that needs to be replaced with "animes".  This will solve the problem.

I tried to login my account today but password reset didn't work, I'll try again tomorrow and see if that change fixes it

**Comment by Froxim** [comment]
> > I described the fix in Other details.  But I've never used Github, and I don't know how to add it to the project.  The screenshot shows the place in the code that needs to be replaced with "animes".  This will solve the problem.
> 
> I tried to login my account today but password reset didn't work, I'll try again tomorrow and see if that change fixes it

You can create a temporary email for a test account on Shikimori. For example, https://temp-mail.org/ru/

**Comment by fakebhai** [comment]
> You can create a temporary email for a test account on Shikimori. For example, https://temp-mail.org/ru/

no need, I already resolved it. I'll probably PR tomorrow. I fixed that and labels.

**Comment by fakebhai** [comment]
should be fixed with https://github.com/aniyomiorg/aniyomi/commit/58817c724e2808072ff273329cee261d12084927
