### ISSUE TITLE
Add a Subtitle Downloader Option below the choose video Quality!

### ISSUE THREAD

**Issue by yuvsama001** [aniyomiorg/aniyomi#1557]
### Describe your suggested feature

Add a Subtitle Downloader Option below the choose video Quality, and add a title like choose/select a subtitle you want to download and make a batch link for external downloader! And for internal downloader just embedded the subtitle with the video really needed because of hianime and kaido! They have softsub instead of sub...
It will be a big new feature.

### Other details

Just add it!
And also if possible add a option for download all subtitle!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Subtitles are already downloaded and embedded in the video.
