### ISSUE TITLE
[Feature Request] Mono-Audio setting

### ISSUE THREAD

**Issue by sami155** [aniyomiorg/aniyomi#1563]
### Describe your suggested feature

Some video streams/Series (especially old Animes) sometimes have bad audio quality when played in Stereo mode. A setting for Mono-Audio playback would be very helpful. 

I know I can turn it off in my Device's system settings but I only need it for certain series, and you may also forget to turn it off again.

I imagined following settings: 
Mono-Mode for whole Aniyomi (on/off)
Mono-Mode for a certain series (on/off)
Mono-Mode for a certain extension (?) (On/off)

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
This setting is already available for the preview version of the app
