### ISSUE TITLE
app crashes when search on search bar of all extensions

### ISSUE THREAD

**Issue by gabriel-batistuta** [aniyomiorg/aniyomi#1567]
### Steps to reproduce

1. Go to browse
2. Click on search bar
3. Type the name of anime
4. search in all extensions 

### Expected behavior

This shoud show all animes of extensions
![photo_2024-05-05_18-55-41](https://github.com/aniyomiorg/aniyomi/assets/96501194/733554ea-3796-438d-8734-5ddf4f4a016c)

### Actual behavior

the app crachs and asks to restart
![photo_2024-05-05_18-55-50](https://github.com/aniyomiorg/aniyomi/assets/96501194/03d10b7a-d05f-4275-92cf-9a5e56d9c39c)

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/aniyomiorg/aniyomi/files/15214666/aniyomi_crash_logs.txt)

### Aniyomi version

0.15.2.4

### Android version

Android 13

### Device

Samsung Galaxy A14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
try uninstalling betteranime

**Comment by AndrehRicardo** [comment]
this is happening to me too

**Comment by AndrehRicardo** [comment]
> try uninstalling betteranime

It worked!

**Comment by gabriel-batistuta** [comment]
@fakebhai it worket here too! thanks a lot

**Comment by fakebhai** [comment]
@abdallahmehiz I suppose this should be closed
