### ISSUE TITLE
When installing a recent version of aniyomi, it labels what I see "today" as "yesterday".

### ISSUE THREAD

**Issue by ayaxSRE** [aniyomiorg/aniyomi#1568]
### Steps to reproduce

1- install aniyomi
2- read a chapter/episode or update a series
3- be correctly added to history or updates

### Expected behavior

Episodes watched must record the exact date.

### Actual behavior

When installing a recent version (I think it's version r6691 onwards), any episode I read appears as read "yesterday". and this affects history and series updates (it also modifies these sections in a backup)

https://github.com/aniyomiorg/aniyomi/assets/138622506/b02c9db9-0776-4f36-8d6a-d944424bc587

### Aniyomi version

stable v0.15.2.4 and preview r7519

### Android version

Android 11

### Device

Xiaomi redmi 8 note

### Other details

I don't know if the problem is mine (a bad time zone configuration) but the preview version r6691 works fine for me :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
That's expected, because aniyomi is always a step ahead into the future.

**Comment by Secozzi** [comment]
This has most likely been fixed in a new release of preview, if the issue still persists please open a new issue.
