### ISSUE TITLE
Requesting domain change for fmovies

### ISSUE THREAD

**Issue by Glitched027** [aniyomiorg/aniyomi#1585]
### Describe your suggested feature

So fmovies is not working for I'll suggest a new domain below 
https://thefmovies.org/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Glitched027** [comment]
Waiting for any feedback for this

**Comment by Secozzi** [comment]
> If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
