### ISSUE TITLE
Please help aniwave 

### ISSUE THREAD

**Issue by BlackMosss** [aniyomiorg/aniyomi#1586]
### Steps to reproduce

1. No results found 2. It only works when I'm using a VPN and but I'm disconnecting from a Vpn it's not working and it gives me the error of no results found 1

### Expected behavior

![20240524_091901](https://github.com/aniyomiorg/aniyomi/assets/170400147/fea1697f-c281-4c0e-ad4d-c1813aafb98b)

### Actual behavior

![20240521_085917](https://github.com/aniyomiorg/aniyomi/assets/170400147/bd0cd86b-a182-41f5-bf91-8d3804dac505)

### Aniyomi version

0.15.3.0

### Android version

Android 8

### Device

Samsung tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
check webview and also try changing domains in extension settings. it's not aniyomi's or Aniwave extension's issue.

also don't just mark acknowledgements without reading them.

**Comment by BlackMosss** [comment]
I've tried checking the webview and changing the domain but it's still not working

**Comment by fakebhai** [comment]
> I've tried checking the webview and changing the domain but it's still not working and Nullpointerexception: null

nullpoint is fixable by letting it finish security check up in the webview. also it falls into troubleshooting which you acknowledged without following all acknowledgements. if you're still having trouble with it consider going to aniyomi's discord server for support

**Comment by fakebhai** [comment]
@abdallahmehiz
