### ISSUE TITLE
Remove useless mpv files in apk

### ISSUE THREAD

**Issue by SkyD666** [aniyomiorg/aniyomi#1587]
### Steps to reproduce

![image](https://github.com/aniyomiorg/aniyomi/assets/32453770/2fcd4ded-db98-4358-bd9c-7b1d3eba7c93)

For example, the files under the is.xyz.filepicker package should all be useless

### Expected behavior

These useless files should not be included.

### Actual behavior

A lot of useless mpv files are included in the apk

### Aniyomi version

0.15.3.0

### Android version

None

### Device

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by endersgergo** [comment]
The classes in the `is.xyz.*` packages are not useless, but legitimate dependencies of Aniyomi. The `is.xyz.mpv` provides the implementation for video playback using libmpv and my educated guess is that the filepicker package is a dependency pulled in by mpv.

**Comment by abdallahmehiz** [comment]
> The classes in the `is.xyz.*` packages are not useless, but legitimate dependencies of Aniyomi. The `is.xyz.mpv` provides the implementation for video playback using libmpv and my educated guess is that the filepicker package is a dependency pulled in by mpv.

The file picker in the files is the one mpv-android uses, not mpv itself. It's not required to run the player so i see his point in asking for them to be removed.

Sure removing them will give us back 8kb but i think that's quite insignificant compared to the stability that their existence provides when merging from upstream mpv-android in my opinion.

**Comment by SkyD666** [comment]
The developer only needs to remove useless files when packaging the mpv-android, and if done properly, this will not reduce the stability of the app.

Details of how to do this can be found here: https://github.com/jarnedemeulemeester/libmpv-android

**Comment by SkyD666** [comment]
Also I'm a developer, I use aniyomi's mpv library, but gradle doesn't support removing files from 3rd party libraries, so I can't remove these useless files in my apk, I hope the developer can remove them when upstream packaged with mpv-android, thank you very much!

**Comment by abdallahmehiz** [comment]
I've made a similar lib to aniyomi-mpv-lib
But with minimal amount of classes and resources (you'll probably notice ~2mb decrease in apk size if you use it)
https://github.com/abdallahmehiz/mpv-android
