### ISSUE TITLE
Add new source

### ISSUE THREAD

**Issue by Chickenshrimps** [aniyomiorg/aniyomi#1593]
### Describe your suggested feature

Source link - 
https://tvshows4mobile.org/ 
https://hdmp4mania2.com

### Other details

Make the source stable and downloadable 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
your second source looks different and seems pretty slow, do you really want it as an extension?

and for different sources open different issue

**Comment by fakebhai** [comment]
oh didn't notice. you're in the wrong repo, don't mark acknowledgements before reading them, this repo isn't for extensions.
