### ISSUE TITLE
[Suggestion]: dual language subtitle support

### ISSUE THREAD

**Issue by nacho00112** [aniyomiorg/aniyomi#1596]
### Describe your suggested feature

I've read that it is possible to extract subtitles from episodes as it is standarized for them to be "soft-coded" rather than "hard-coded". This suggestion is to support people like me who like to learn language through content, this would involve many things like finding a source for translation, like google, and a settings panel where you can configure basic things, for example, in the subtitles, which language is above and which one is below.

Another suggestion, which is related, is to be able to quickly select text on the subtitles, just like you do with any other text, so you can copy it and stuff, a plus would be to be able to quickly look up that word in a dictionary window.

please take the LingoTube app as an example of this suggestion, the whole app is dedicated to this, it is a video player which has all of the features I mentioned and more, but for youtube, they even have different modes for subtitles, depending on your language level, whether the translation is hidden until you pause the video, or even the whole subtitles, in that case, you would only see the original subtitle if you pause.

I would love this features so please take me into account, the power of aniyomi and its extensions, together with LingoTube-like subtitle powers, would make it a really useful.

sorry for my bad english.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
1. Extracting subtitles from hard-subbed videos with OCR is not happening, not even close to feasible on a smartphone and way out of scope of this app.
2. I don't think making the subtitles is a good idea, it would require a lot of work for a feature not many people would use. If you still want it though, feel free to open a new issue.
