### ISSUE TITLE
Aniyomi crashes and not opening and purple screen problem while watching anime

### ISSUE THREAD

**Issue by rajinstar** [aniyomiorg/aniyomi#1605]
### Steps to reproduce

When I open Aniyomi, It's showing crashes and not when ever I restart the app the pop up showing with some error and not showing the home page (Anime Tab). And If I close the app and reopen the app again. It shows again. Similarly when I watch anime for long time a Purple Screen showing in the screen and not going. Only audio coming through. When I back to the Anime's tab and click on the episode again then the problem goes.

### Expected behavior

App should Open and I can start watching anime. Purple screen not supposed to showing and only anime screen showing.

### Actual behavior

![Screenshot_2024-06-10-01-26-07-643_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi/assets/62995823/dd85de86-f101-4d2d-90e3-23f60989300b)
![Screenshot_2024-06-10-01-26-12-321_xyz jmir tachiyomi mi](https://github.com/aniyomiorg/aniyomi/assets/62995823/e9b1a4e5-5e93-401e-968b-c756a388e5e5)

### Aniyomi version

0.15.3.0

### Android version

Android 12

### Device

POCO M2 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Disable `gpu-next` in the advanced player settings to avoid the purple color while watching.

**Comment by rajinstar** [comment]
> Disable `gpu-next` in the advanced player settings to avoid the purple color while watching.

But, The main problem is aniyomi crashes like this and I cannot watch any anime. What should I do!?

**Comment by Secozzi** [comment]
Open a new issue and please send the crash logs file, not a screenshot of the crash screen.
