### ISSUE TITLE
Google login

### ISSUE THREAD

**Issue by Kimphunh** [aniyomiorg/aniyomi#1606]
### Steps to reproduce

1.Anime Sakura source required Google login to access google drive
2.Enter Gmail

### Expected behavior

It should let me enter Password like another browser

### Actual behavior

I got thís message "This browser or application may not be secure" even thought i changed user agent to my Browser (Samsung Internet)

### Aniyomi version

 0.15.3.0

### Android version

Android 13

### Device

Samsung S24 Ultra

### Other details

I suggest you should add "Cookie Importer", It will be an option that will always work even if they make changes to the user agent, browser signature, etc..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by RuDru-OP** [comment]
This is expected to happen. Google has security codes that check whether the browser you are using is safe to login or not... There is literally no way you can bypass this, same is with facebook....

**Comment by Kimphunh** [comment]
> This is expected to happen. Google has security codes that check whether the browser you are using is safe to login or not... There is literally no way you can bypass this, same is with facebook....

Even importing cookies doesn't work?how crazy

**Comment by RuDru-OP** [comment]
I m not a coder... But for sure I know one thing, google doesn't work on cookies... Instead it works in special keys that must be allotted to every browser you are logging in from. For example go into a new browser and login... Then go to google security and see a new device is added... Its that browser that google recognises and allows it to appear as a new device, So that you can logout anytime you want without worrying about the browser

**Comment by abdallahmehiz** [comment]
This seems like an extension issue, so I am closing it.
