### ISSUE TITLE
Playing the largest file on downloaded folder

### ISSUE THREAD

**Issue by glaicodes** [aniyomiorg/aniyomi#1614]
### Describe your suggested feature

External downloader sometimes can't override the empty file and there can be 2 files in the download folder. Aniyomi can't figure out which one to open and gives"unrecognized file format" error.

A way to fix it can be to make aniyomi check the folder contents and play the largest file there.

### Other details

![Screenshot_20240615-161658](https://github.com/aniyomiorg/aniyomi/assets/75806392/b8b6c21d-e37c-4423-8102-6d30262d5531)
This can happen sometimes while using external downloader

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
The filename must be specific for the app to recognize it. If the external downloader is causing issues, rename them manually.
