### ISSUE TITLE
All the anime extensions aren't there

### ISSUE THREAD

**Issue by Playwithme-69** [aniyomiorg/aniyomi#1615]
### Steps to reproduce

No response 

### Expected behavior

All the extensions should be available for download 
![Screenshot_2024-06-16-00-47-09-23_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/aniyomiorg/aniyomi/assets/172931852/d7cfb3a2-ea12-4ab0-9a2b-f0e5d67d30d6)

### Actual behavior

All the extensions aren't available for download 

### Aniyomi version

Preview r7567

### Android version

Android 23

### Device

OnePlus Nord ce 3

### Other details

No available extensions for download 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
Due to a DMCA takedown notice, most anime extensions have been removed from the official extensions list.

**Comment by Roswaal12** [comment]
Wise enough to complain on GitHub
Too dumb to read announcement on discord 😔
