### ISSUE TITLE
Can't install extensions from app

### ISSUE THREAD

**Issue by Hasan-Arif** [aniyomiorg/aniyomi#1616]
### Steps to reproduce

1. Extension download
2. App chashes

### Expected behavior

The extensions should download.

### Actual behavior

But it crashes everytime

### Crash logs

App version: 0.15.3.0 (standard, c91fb86, 123, 2024-05-10T08:46Z)
Android version: 12 (SDK 31; build SP1A.210812.016)
Android build ID: SP1A.210812.016
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: rembrandt (rembrandt)
Device model: 22122RK93C
WebView: Android System WebView 127.0.6533.2
MPV version: c6ccabe
Libplacebo version: v7.349.0
FFmpeg version: n6.1.1

--------- beginning of system
06-16 23:30:13.336 13880 13880 E MQSEventManagerDelegate: failed to get MQSService.
06-18 00:10:10.493  3882  3882 E MQSEventManagerDelegate: failed to get MQSService.
--------- beginning of crash
06-18 01:10:50.131  3882  4220 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-20
06-18 01:10:50.131  3882  4220 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 3882
06-18 01:10:50.131  3882  4220 E AndroidRuntime: java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at android.widget.Toast.getLooper(Toast.java:184)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at android.widget.Toast.<init>(Toast.java:169)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at android.widget.Toast.makeText(Toast.java:518)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at android.widget.Toast.makeText(Toast.java:506)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.system.ToastExtensionsKt.toast(SourceFile:19)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.system.ToastExtensionsKt.toast$default(SourceFile:4)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity$$ExternalSyntheticLambda9.uncaughtException(SourceFile:16)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle6432.aab-beta-653300242:32)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:21)
06-18 01:10:50.131  3882  4220 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
06-18 01:10:50.134  3882  4220 E MQSEventManagerDelegate: failed to get MQSService.
06-18 01:10:54.211  3882  8529 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-73
06-18 01:10:54.211  3882  8529 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 3882
06-18 01:10:54.211  3882  8529 E AndroidRuntime: java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167)
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at android.widget.Toast.getLooper(Toast.java:184)
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at android.widget.Toast.<init>(Toast.java:169)
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at android.widget.Toast.makeText(Toast.java:518)
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at android.widget.Toast.makeText(Toast.java:506)
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.system.ToastExtensionsKt.toast(SourceFile:19)
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.system.ToastExtensionsKt.toast$default(SourceFile:4)
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity$$ExternalSyntheticLambda9.uncaughtException(SourceFile:16)
06-18 01:10:54.211  3882  8529 E AndroidRuntime: 	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-Trich

### Aniyomi version

0.15.3.0

### Android version

Android 12

### Device

Redmi K60E 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by s1nistr4** [comment]
https://torrentfreak.com/sony-dmca-notice-nukes-200-aniyomi-extensions-as-tachiyomi-fork-feels-heat-240617/

Basically S*ny DCMAd all the extensions

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
