### ISSUE TITLE
Smart update days are wrong

### ISSUE THREAD

**Issue by Zaratiel** [aniyomiorg/aniyomi#1623]
### Steps to reproduce

Enter Aniyomi, go to the library, tap on the anime and check days left from the anime/manga

### Expected behavior

Tell how many days are left since the next update and update on said day

### Actual behavior

The days left are wrong and even after those days it doesn't update, I have to do it manually
![Screenshot_20240622_134958_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/72154363/f1525d5e-ee97-4e28-b4ca-1673dc2d4a63)
![Screenshot_20240622_135111_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/72154363/fea1dec9-b1bb-48f4-8bf1-ed5316c9fb0b)

### Aniyomi version

Preview r7567 and Stable 0.15.3.0

### Android version

Android 14

### Device

Samsung Galaxy A54

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [x] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [x] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
These are approximations, they can't be 100% right. The one you're sharing is 1 day off... I'd consider that acceptable tbh...

**Comment by Zaratiel** [comment]
> These are approximations, they can't be 100% right. The one you're sharing is 1 day off... I'd consider that acceptable tbh...

Still I have to do it manually and doesn't update on 12 hrs like it should be through settings because of the smart update

**Comment by abdallahmehiz** [comment]
> I remember a version where I could choose the days left, now I can't

You *can* choose the days left, just tap on the hour glass icon in the library entry you want to change the update rate of.
