### ISSUE TITLE
Replace update tab in Bottom bar

### ISSUE THREAD

**Issue by suraj3486** [aniyomiorg/aniyomi#163]
### Describe your suggested feature

Please make an option in setting by which bottom bar update can be replaced by history tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Oxeda** [comment]
Or add both and add an option to display only their icons without labels. :D

**Comment by Aahnafwifi212** [comment]
![Screenshot_20220102-083407_Aniyomi](https://user-images.githubusercontent.com/95229081/147864598-4360afe0-b3b2-4936-8843-2d2f944d7b39.jpg)

Add history In start scr3en view will be helpful

**Comment by Jantelinus** [comment]
Any update on this?

**Comment by ccrsxx** [comment]
I use this feature a lot back when I was using tachiyomi. Now, I need to click two times to get there. Having the option to change in between would be perfect.

**Comment by Aahnafwifi212** [comment]
I see it's one of the common requests, I hope the developers will  look into this issue

**Comment by Quickdesh** [comment]
This has been fixed/added in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"
