### ISSUE TITLE
Can't access extensions list

### ISSUE THREAD

**Issue by Lordsaski** [aniyomiorg/aniyomi#1643]
### Steps to reproduce

Even tho i added the repos correctly on Aniyomi , the app refuses to make me gain access to the extensions list 

### Expected behavior

The app should make me gain access to the extensions list after i added the repos

### Actual behavior

The app refuses to let me gain access to the extensions list

### Crash logs

I haven't experienced any crashes

### Aniyomi version

0.15.3.0

### Android version

Android 13 

### Device

Readmi note 12

### Other details

There is no other details 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GokulSamraj** [comment]
due to DMCA , alots of extension has been taken down
try to change extension source which are still available somehow `(like some repo on my profile)`

**Comment by quickdesh** [comment]
The repo link should contain a .json file with all the apks listed out

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
