### ISSUE TITLE
Can't intall extentions or open chapters 

### ISSUE THREAD

**Issue by Artemis03i** [aniyomiorg/aniyomi#1650]
### Steps to reproduce

1. Extentions that I had downloaded uninstalled out of no where? and when I try to install again it doesn't install 
2. Unless the chapter is already downloaded I can't open any chapter from any other source that hasn't been uninstalled 
3. Extentions that where available in the last version are not available in this one 

### Expected behavior

I should be able to open chapters and install extentions

### Actual behavior

Issue 1: when I install an extension it shows that it's updating but it's not added to my extentions list. It's still shows that it need to be downloaded. No matter how many ties I try it's the same. 
Issue 2: when I open a chapter it shows this
![Screenshot_20240630_194916_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/130247369/6ed2437a-832b-4517-a399-e210dacd6873)
I tried all extentions that still remain and it's all the same I littery can't read anything only the ones that I have downloaded. 

### Aniyomi version

0.16.4.0-7646

### Android version

14

### Device

SM-A236U

### Other details

App version: 0.16.4.0-7646 (standard, 53686808b, 124, 2024-06-30T21:37Z)
Android version: 14 (SDK 34; build UP1A.231005.007.A236USQU6EXE6)
Android build ID: UP1A.231005.007.A236USQU6EXE6
Device brand: samsung
Device manufacturer: samsung
Device name: a23xq (a23xqsq)
Device model: SM-A236U
WebView: Android System WebView 126.0.6478.133
MPV version: 4d32db2
Libplacebo version: v7.349.0
FFmpeg version: n7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Bioblade** [comment]
Same issue, though mine is limited to a small number of extensions. Checking from the system app manager, it seems like they are installing, and other Mihon forks are registering these extensions, but Aniyomi just doesn't seem to detect them. I saw in the preview patch notes that it mentioned "Fix new extension install not registering in app", which could be relevant, since this issue only started with this update.

**Comment by Bioblade** [comment]
The latest update seems to have fixed it.

**Comment by Secozzi** [comment]
Please don't create one issue for multiple bug reports. Separate them into one issue per report.
