### ISSUE TITLE
Extensions are gone 

### ISSUE THREAD

**Issue by Mubin4025** [aniyomiorg/aniyomi#1653]
### Steps to reproduce

Extensions are gone 

### Expected behavior

All t extension apps ar gone.. what's the meaning of this app then ?

### Actual behavior

Extensions are gone 

### Aniyomi version

0.16.4.2

### Android version

13

### Device

Realme note 50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
not all of the extensions are gone.
check https://github.com/github/dmca/blob/master/2024/06/2024-06-11-sonypictures.md.
