### ISSUE TITLE
No funciona de manera correcta en mi dispositivo móvil 

### ISSUE THREAD

**Issue by FrankieD777** [aniyomiorg/aniyomi#1654]
### Steps to reproduce

1:abrir la app

2: ir al apartado de extensiones

3: usarlas normalmente 

### Expected behavior

Que se presenten las imágenes de las extensiones y se instalen las nuevas extensiones 

### Actual behavior

La imagen de una de las extensiones se multiplica en muchas otras varias y hay algunas extensiones que aunque se supone que instalé no se me presentan como tal

### Crash logs

![Screenshot_20240701-161615](https://github.com/aniyomiorg/aniyomi/assets/174386970/60a98de9-9b72-415e-9c32-14ad302609ca)

### Aniyomi version

0.16.4.2

### Android version

Android 13

### Device

TECNO SPARK 10 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
