### ISSUE TITLE
El anterior problema persiste y creo que hasta empeoró 

### ISSUE THREAD

**Issue by FrankieD777** [aniyomiorg/aniyomi#1655]
### Steps to reproduce

1: abrir la app

2: ir hacia el apartado de extensiones 

### Expected behavior

Que se muestre el icono de cada extensiones 

### Actual behavior

El icono de monos chinos se duplico en todas las extensiones 
![Screenshot_20240702-101817](https://github.com/aniyomiorg/aniyomi/assets/174386970/cc6bcd4f-a160-472a-a294-77d6d92e721d)

### Aniyomi version

0.16.4.3

### Android version

Android 13(Hios Basado en AndroidV12.6.0)

### Device

TECNO SPARK 10 Pro

### Other details

Por favor arreglar esto 😿

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FrankieD777** [comment]
Gracias por arreglar el problema en las extensiones de manga pero el de anime está igual también (osea con el error todavía 😞)

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
