### ISSUE TITLE
Fallo al actualizar la biblioteca. 

### ISSUE THREAD

**Issue by CapZeus30** [aniyomiorg/aniyomi#1659]
### Steps to reproduce

Cuando entro a la app e intento actualizar la biblioteca para revisar los mangas con nuevos capítulos no funciona, carga pero no salen los nuevos capítulos, tengo que ir manga por manga o anime por anime actualizando directamente desde la info del manga o anime para saber si hay nuevo episodio porque la app no avisa ni muestra cuando hay algo nuevo. Sería increíble si pudieran repararlo por favor y gracias. 

### Expected behavior

Lo que espero es que una vez entro en la app y actualizo la biblioteca se actualize todo el contenido si es que hay algo nuevo, no tener que entrar anime por anime actualizando uno por uno. 

### Actual behavior

Ninguno de los animes / Mangas se actualizan Juntos para saber si hay algo nuevo debes de actualizar directamente en la info del anime/manga 

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/16078311/aniyomi_crash_logs.txt)

### Aniyomi version

App version: 0.16.4.3

### Android version

Android 13

### Device

Tecno spark 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by perokhe** [comment]
https://github.com/aniyomiorg/aniyomi/issues/1346#issuecomment-1907149996

**Comment by Secozzi** [comment]
This happens because of [smart updates](https://aniyomi.org/docs/faq/updates/smart), it's intended behavior
