### ISSUE TITLE
I can't install it on Android 7

### ISSUE THREAD

**Issue by Abuzzpoet** [aniyomiorg/aniyomi#1666]
### Steps to reproduce

Cannot be installed

### Expected behavior

The previous version can still be installed on my cellphone

### Actual behavior

Cannot be installed

### Aniyomi version

0.16.4.3

### Android version

Android 7

### Device

Redmi Note 4X

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Support for android 7 and lower has been dropped.
