### ISSUE TITLE
Episode thumbnail for source that supports it

### ISSUE THREAD

**Issue by f1998f1998** [aniyomiorg/aniyomi#167]
### Describe your suggested feature

Many sources support thumbnail for episodes. So it will be convenient if there is a option to enable thumbnail in aniyomi. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2.2](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
not feasible
