### ISSUE TITLE
Add the video filters found in original mpv app

### ISSUE THREAD

**Issue by ISnatchLs** [aniyomiorg/aniyomi#1670]
### Describe your suggested feature

The original android MPV has the option to adjust these settings, Brightness, Gamma, Contrast, Saturation.

### Other details

My phone suffers from an effect which I don't know the real name of but I've seen people call it black crush online. Slightly dark areas become pitch black, being able to adjust the brightness and gamma kind of helps me mitigate this issue. Here is a video example. https://streamable.com/lmffc0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
> The original android MPV has the option to adjust these settings, Brightness, Gamma, Contrast, Saturation.

you can change all this in mpv config. and by using Keyboard too iirc.

> Slightly dark areas become pitch black

try disabling anti-flicker options if you have that enabled in your phone's display settings.

**Comment by abdallahmehiz** [comment]
This is a good feature request even if you can use mpv conf to achieve its effect.
I am reopening it.

**Comment by fakebhai** [comment]
we better kiss Abdallah for this
