### ISSUE TITLE
Extension obsolete

### ISSUE THREAD

**Issue by hatimurni** [aniyomiorg/aniyomi#1671]
### Steps to reproduce

After update aniyomi to latest version, im find that all my anime extension become obsolete 

### Expected behavior

It should be fine, because when i updated it last time my anime extension still fine

### Actual behavior

But now in latest version all my anime extension become obsolete 
![Uploading Screenshot_2024-07-09-19-24-17-80_dd604340c1d7941d42aee14dd16e00e8.jpg…]()

### Aniyomi version

0.16.4.3

### Android version

Android 11

### Device

Oppo a5 2020

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Most our anime extensions have been purged, consider checking 3rd party extensions repos to get more extensions.

**Comment by hatimurni** [comment]
Where i can find 3rd party extension repos?

**Comment by Secozzi** [comment]
> Where i can find 3rd party extension repos?

Aniyomi does not associate or endorse any third party extension repository. We will not share any so you need to find them yourself.
