### ISSUE TITLE
French Translation Advanced Settings Error

### ISSUE THREAD

**Issue by mobby45** [aniyomiorg/aniyomi#1673]
### Steps to reproduce

1. Install Aniyomi
2. Go into appearance and set the language into french
3. Go into the advanced and scroll to the bottom of the page
4. It crash

### Expected behavior

We should be able to see all the settings in the advanced settings page

### Actual behavior

Aniyomi crash with an error

### Crash logs

![Screenshot_2024-07-09-21-37-12-016_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/68152858/b3b0aa5e-76d5-4493-8c01-0ed513b792ec)
![Screenshot_2024-07-09-21-37-19-894_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/68152858/23c7dc06-22a2-47a4-a8d1-45d390f668c2)
![Screenshot_2024-07-09-21-37-27-521_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/68152858/50634107-9a2c-4eaf-a3ce-993269a83ed9)
![Screenshot_2024-07-09-21-37-04-413_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/68152858/0e55a9a0-d5ef-4964-9fbf-b148e8c7a17a)

### Aniyomi version

Preview r7656 (69b9db4e8)

### Android version

Android 11

### Device

Xiaomi Redmi Note 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This issue has most likely been resolved in a newer release of preview. If the issue still persists, please open a new issue.
