### ISSUE TITLE
Resume starts over instead of resuming

### ISSUE THREAD

**Issue by muneebusmani** [aniyomiorg/aniyomi#1677]
### Steps to reproduce

1. Open the manga or anime you were recently watching
2. click on resume
3. it won't resume from where you left off but it will start from ep 1 or chapter 1

### Expected behavior

it should resume from where i left off previously

### Actual behavior

it starts over

### Aniyomi version

0.16.4.3 stable 

### Android version

Android 13

### Device

Redmi note 7, VGOTEL Note 24, Emulator in pc

### Other details

whichever device i open aniyomi in, it has this problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
> it should resume from where i left off previously

it resumes from first unread chapter/episode. mark them read/watched to use resume button.

otherwise go to history tab and click on whatever episode you were on.

**Comment by muneebusmani** [comment]
@fakebhai bro i have to use history to continue, ik it resume button should open the first unread/unwatched chapter/episode but it doesn't, i starts from chapter/episode 1

**Comment by fakebhai** [comment]
> @fakebhai bro i have to use history to continue, ik it resume button should open the first unread/unwatched chapter/episode but it doesn't, i starts from chapter/episode 1

ok i just installed stable version (16.4.3) and it seems to work as intended. when you have no episodes watched it'll show button labeled "START" and if you watch any whole episode or mark it watched it'll be labeled "resume". and it opens first unwatched episode.

it works completely fine even if you press it from library or entry itself.

note: I haven't tested manga side.

can you send screen recording? as I can't reproduce the issue.

**Comment by muneebusmani** [comment]
oh sorry now i know the problem, i sometimes change sources , so i skip the episodes and chapters which i previously watched/read, i forget to mark them as watched/read, i just marked that and now it works as expected, thanks for telling ke that
