### ISSUE TITLE
Can't see any extention

### ISSUE THREAD

**Issue by Osix99** [aniyomiorg/aniyomi#1678]
### Steps to reproduce

![WhatsApp Image 2024-07-10 at 22 18 50](https://github.com/aniyomiorg/aniyomi/assets/175063204/3a25b111-210e-4bfb-afd3-dc3e9a082b31)

I just cant see \ download any anime extention ( even on the website https://aniyomi.org/extensions/ )

### Expected behavior

I expect a list of extentions i can download. this ahppened after an update

### Actual behavior

No extentions
![WhatsApp Image 2024-07-10 at 22 18 50](https://github.com/aniyomiorg/aniyomi/assets/175063204/839e71f7-781f-4cf5-8337-775af3b97cf9)

### Aniyomi version

v0.16.4.3

### Android version

Android 14

### Device

Google pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Due to a dmca notice, we've had to remove almost all of the extensions.
