### ISSUE TITLE
Crash after adding anime ext repos

### ISSUE THREAD

**Issue by Ero-gamer** [aniyomiorg/aniyomi#1680]
### Steps to reproduce

1. Added Anime extensions.
2. Install extensions.
3. Crash on "extensions" tab.

### Expected behavior

App shouldn't crash.

### Actual behavior

App crash.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/16178077/aniyomi_crash_logs.txt)

### Aniyomi version

0.16.4.3

### Android version

Android 9

### Device

Oppo A11k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
The crash log is empty.

**Comment by Ero-gamer** [comment]
> The crash log is empty.

I uploaded crash log text file generated from Aniyomi app which is not the actual crash log. I couldn't select to copy actual crash log within app so I had to take screenshots:

![Screenshot_2024-07-11-15-50-53-52](https://github.com/aniyomiorg/aniyomi/assets/146583787/90384c0c-6dc7-4296-9e56-af8b1d5807e7)
![Screenshot_2024-07-11-15-50-23-50](https://github.com/aniyomiorg/aniyomi/assets/146583787/ddfdbc7d-c884-4951-af83-a3e339e32f3e)
![Screenshot_2024-07-11-15-51-37-52](https://github.com/aniyomiorg/aniyomi/assets/146583787/50a12d5b-8779-4a04-a1fb-309ef3c2968d)
![Screenshot_2024-07-11-15-51-23-54](https://github.com/aniyomiorg/aniyomi/assets/146583787/85668208-6c61-4464-827f-e9c641fbea92)

**Comment by Secozzi** [comment]
This has most likely been fixed in the [preview](https://github.com/aniyomiorg/aniyomi-preview/releases/) version with the merge from Mihon. If the issue still persists even after switching to preview or in the next stable update, please open a new issue.
