### ISSUE TITLE
Extension not showing 

### ISSUE THREAD

**Issue by MrBarui** [aniyomiorg/aniyomi#1688]
### Steps to reproduce

Aniyomi Anime, Manga Extensions are not showing.
![Screenshot_2024-07-12-13-43-51-965_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/45e3d1f9-d174-4527-8865-fb3425a4b88c)

### Expected behavior

All Anime Extension not showing/ loading 

### Actual behavior

All anime Extension shows when Browse on Aniyomi.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/16190822/aniyomi_crash_logs.txt)

### Aniyomi version

Stable 0.16.4.3 (01/07/24 10:25 pm)

### Android version

Android 14

### Device

Poco X6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
We got hit by a dmca notice, so we removed almost all of our extensions, and we don't provide manga extensions either. You will need to source extensions yourself.
