### ISSUE TITLE
Image in manga could not be loaded 

### ISSUE THREAD

**Issue by Chickenshrimps** [aniyomiorg/aniyomi#1697]
### Steps to reproduce

Choose a manga you like to read
Open the manga by any extension in aniyomi
The page doesn't load 
![Screenshot_20240714_011118](https://github.com/user-attachments/assets/53f4e18e-f15b-406f-91c7-09eb359d7795)

### Expected behavior

The page should load 

### Actual behavior

The page couldn't be loaded 

### Crash logs

App version: 0.16.4.3 (standard, 959f84a, 124, 2024-07-01T22:25Z) Android version: 12 (SDK 31; build SP1A.210812.003 release-keys) Android build ID: SP1A.210812.003 release-keys Device brand: vivo Device manufacturer: vivo Device name: 2111 (2111i) Device model: V2111 WebView: Android System WebView 126.0.6478.134 MPV version: 4d32db2 Libplacebo version: v7.349.0

### Aniyomi version

0.16.4.3

### Android version

Android 12

### Device

V2111

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is an issue with the extension, there's nothing we can/will do about that.
