### ISSUE TITLE
Sugerencia de fusión 

### ISSUE THREAD

**Issue by FrankieD777** [aniyomiorg/aniyomi#1704]
### Describe your suggested feature

Hola saludos buenas noches se me ocurrio una idea mientras usaba mi nuevo teléfono ya que se puede editar casi toda la información de los manga y animes Podrían hacer hacer una función que permita funcionar un manga o anime osea la vaina es que tienes el mismo manga repetido en la biblioteca verdad? Entonces la opción de fusión lo que hace es sobre escribir los datos de dicho manga poniendo la portada más actualizada la sinopsis más detallada y eligiendo de la fuente que tienes dicho manga el que tenga más capitulos 😸🍀

### Other details

Por favor y muchas gracias y que tengáis una bonita velada 👻🌹

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Duplicate of #1595
