### ISSUE TITLE
Anime ext Episode count showing 0 not loading futher

### ISSUE THREAD

**Issue by pillayee** [aniyomiorg/aniyomi#1705]
### Steps to reproduce

1.in anime section search globally 
2. Dragon ball z 
3. Choose any repo you use for anime 
4. Open it and it won't showing list of episodes

### Expected behavior

Should show number of episodes and the ability to play them when clicked on

### Actual behavior

Shows 0 episodes
![Screenshot_2024-07-17-18-28-16-39_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/user-attachments/assets/dab5922a-dfb0-471b-8538-99cab4cf86c9)

### Aniyomi version

0.16.4.3-7801

### Android version

11

### Device

Realme XT

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by pillayee** [comment]
![Uploading Screenshot_2024-07-17-18-36-55-25_423fe07c33ed17f15a4e92e5e3a15972.jpg…]()

**Comment by pillayee** [comment]
![Screenshot_2024-07-17-18-36-31-89_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/user-attachments/assets/dfad1849-fe30-45b6-910e-812907d1020e)

**Comment by pillayee** [comment]
![Screenshot_2024-07-17-18-39-40-13_423fe07c33ed17f15a4e92e5e3a15972](https://github.com/user-attachments/assets/286ec207-6153-4b3b-81b6-c51c833a91e2)

**Comment by Secozzi** [comment]
> [x] If this is an issue with an extension, I should be opening an issue in the extension's repository.

These are extension issues
