### ISSUE TITLE
Doesn't play, update, download from aniwave extension.

### ISSUE THREAD

**Issue by Ridwan155-Akasake** [aniyomiorg/aniyomi#1707]
### Steps to reproduce

Open AniWave source
Select any anime
Error toast

### Expected behavior

AniWave should load all episodes as normal.

### Actual behavior

Json error toast
![Screenshot_20240717-231000](https://github.com/user-attachments/assets/0a84c40c-4af1-4532-9f55-556bbc754c9f)

### Aniyomi version

App version: 0.16.4.3

### Android version

Android 14

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Please contact the extension maintainers for such issues.

**Comment by abdallahmehiz** [comment]
I don't know what extensions repository you're using so I can't really guide you here.

**Comment by Ridwan155-Akasake** [comment]
> I don't know what extensions repository you're using so I can't really guide you here.

Thanks that comment itself helped me understand what i had to do, i checked with the repository maintener's git and saw there was already a open case? Issue? over there, i will delete this one here. Thanks for helping.
