### ISSUE TITLE
Preview version keeps crashing

### ISSUE THREAD

**Issue by Artimoo-Foxtrot** [aniyomiorg/aniyomi#1711]
### Steps to reproduce

I try to start up the preview version... It crashes... I reboot it... It crashes... I reboot my phone.... It crashes....

### Expected behavior

It shouldn't crash

### Actual behavior

It crashes

### Crash logs

Doesn't even let me enter to see the crash logs...

### Aniyomi version

Idk, I just updated to the latest preview version and it started doing it

### Android version

Android 11

### Device

Oppo a16k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
we can't really do much without crash logs.
