### ISSUE TITLE
Automatically Trust Resource option for specific repo

### ISSUE THREAD

**Issue by Samarth170102** [aniyomiorg/aniyomi#1714]
### Describe your suggested feature

So when we install a new resource or update a resource it goes into untrusted resource and we have to manually select one by one to trust the resource, so a button to trust new and updated resource of the specific repo, so if we update or install new one we do not have to manually trust each resource

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is already fixed in preview [r7798](https://github.com/aniyomiorg/aniyomi-preview/releases/tag/r7798) or later
