### ISSUE TITLE
Add a new tracking website 

### ISSUE THREAD

**Issue by Chickenshrimps** [aniyomiorg/aniyomi#1716]
### Describe your suggested feature

Tracking website: IMDb
https://www.imdb.com/

### Other details

For tracking anime, movies, and tv series 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Duplicate of #769
