### ISSUE TITLE
[BUG] The library update section is messed up.

### ISSUE THREAD

**Issue by ShoyebOP** [aniyomiorg/aniyomi#1724]
### Steps to reproduce

1. Open aniyomi.
2. Update anime library.
3. Have at least one anime or manga where expect two or more chapters to release.

### Expected behavior

The new episodes that are updated at the same time should have been under the same time stamp. Like this
![Screenshot_20240724-120453_Trebuchet](https://github.com/user-attachments/assets/4a944030-69ca-48bd-b186-4e12346cb49a)

### Actual behavior

The time stamp getting before every episodes it updated. Like this-
![Screenshot_20240724-120648_Trebuchet](https://github.com/user-attachments/assets/fbf31cc2-d2c8-4878-a9a7-8e8800e8671f)

### Crash logs

No crash.

### Aniyomi version

App version: 0.16.4.3-7801 (standard, 58817c724, 125, 2024-07-16T21:32:24Z)

### Android version

13 (SDK 33; build lineage_cheeseburger-userdebug 13 TQ3A.230901.001 c666ad56da) Android build ID: lineage_cheeseburger-userdebug 13 TQ3A.230901.001 c666ad56da

### Device

Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus5 (OnePlus5) Device model: ONEPLUS A5000

### Other details

I'm not sure if it's also happens with manga updates.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Fixed in https://github.com/aniyomiorg/aniyomi/commit/c83ebf322f48d41ca1ad0105262160ecb7cde991
