### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Pankaj3509** [aniyomiorg/aniyomi#1731]
### Steps to reproduce

Extension is not working like Fmovies and Superstream

### Expected behavior

Extentions should work properly 

### Actual behavior

Extention not working properly or you can say not opening like Fmovies and Superstream

### Aniyomi version

0.16.4.3

### Android version

Android 13

### Device

Xiaomi 11i 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
We don't manage those extensions anymore.

**Comment by Pankaj3509** [comment]
1.So can you let me know which extentions you are handling
2. Most of the Extentions are not working
3. From which extentions i can watch All Tv series

**Comment by abdallahmehiz** [comment]
The extensions available in [the official repository](https://github.com/aniyomiorg/aniyomi-extensions) which are: Jellyfin and Google Drive.

If you're using an extension other than these 2, you've probably downloaded them from a 3rd party repository and should report issues related to such extensions to them, not us.

If you're not using any repository then you probably have a deprecated extension that was removed due to a DMCA.

**Comment by abdallahmehiz** [comment]
Also, don't ask for extensions recommendations.

**Comment by Pankaj3509** [comment]
If you talking about jellyfin and Google Drive those are also not working.
So kindy solve this issue

**Comment by abdallahmehiz** [comment]
If so, report any issue plaguing them in the [official repository](https://github.com/aniyomiorg/aniyomi-extensions).

Make sure you know how to actually use them first and that it's not a user issue.

**Comment by Pankaj3509** [comment]
Not helpful answer at all

**Comment by abdallahmehiz** [comment]
What answer were you expecting?

**Comment by fakebhai** [comment]
> Not helpful answer at all

It is your responsibility for not reading the "acknowledgements" before marking them. If you had followed them correctly, this issue might not have taken place in the first place. Be thankful that moderators made an effort to help you.
