### ISSUE TITLE
Failure to auto-delete chapters for some categories when set on auto-delete

### ISSUE THREAD

**Issue by Brand2204** [aniyomiorg/aniyomi#1733]
### Steps to reproduce

1. Open the app
2. Set the auto delete chapters/episodes for second to last read chapter in settings>downloads (For me, it's already set)
3. Read a chapter in a particular category. For me it's "Manga: reading (ongoing)"
4. After reading the chapter, the previous chapter doesn't delete. I now have to delete it manually.
![IMG_20240728_231827](https://github.com/user-attachments/assets/b2ed8c45-8625-49cf-8452-77a4e3ac52cd)

### Expected behavior

The second to last read previous chapter should be deleted automatically, without me having to manually delete it after I read a chapter.

### Actual behavior

The second to last chapter doesn't delete after reading the next chapter. For example, I was reading Record of Ragnarok manga chapter 91; chapter 90 should delete on its own once i finished reading chapter 91, but nothing happened. I had to go and delete chapter 90 manually.

### Aniyomi version

Stable 0.16.4.3

### Android version

Android 10

### Device

Redmi 9c 

### Other details

I've tried toggling the options. It works for other categories, but once I try it on the manga: reading (ongoing) category it doesn't work. I didn't exclude the category from deleting whatsoever.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by VIPlearner** [comment]
Hi @Brand2204, I just tested on my device and the feature works fine here
I also tried to use the same manga(Record of Ragnarok) that you have used and it works fine
Can I know what extension you used?

**Comment by Brand2204** [comment]
Mangasee and mangalife

**Comment by Brand2204** [comment]
Mangasee and mangalife

**Comment by abdallahmehiz** [comment]
@Brand2204 please don't mention unofficial/3rd party extensions/repos.

**Comment by Brand2204** [comment]
Alright, don't worry. It has been resolved. It occurred because I was opening the manga from the update section instead of opening it directly. Thanks
