### ISSUE TITLE
Some of the manga will not auto-update

### ISSUE THREAD

**Issue by tyqche** [aniyomiorg/aniyomi#1734]
### Steps to reproduce

1. Not all the manga i added in the library will auto-update
2. I have to go to the saved manga and will do manual update instead

### Expected behavior

All the manga saved in the library should auto-update

### Actual behavior

Already set my restriction/exclusion to none but still facing the issue.

![Screenshot_20240730-083255](https://github.com/user-attachments/assets/c0b621cb-c6d7-47b2-8437-7cb22aaea6ca)

### Aniyomi version

0.16.4.3

### Android version

14

### Device

TECNO CAMON 20s Pro

### Other details

I'm using different extensions and it's all the same.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Have you checked smart updates?
What about battery optimizations?

**Comment by tyqche** [comment]
> Have you checked smart updates? What about battery optimizations?

for smart update I only checked the predict next release time and  battery opti is disabled

**Comment by abdallahmehiz** [comment]
Well then it won't update on an interval it will try to check for updates based on its predictions that you see under the hourglass when seeing the entry in the library.

**Comment by tyqche** [comment]
> Well then it won't update on an interval it will try to check for updates based on its predictions that you see under the hourglass when seeing the entry in the library.

thank you
