### ISSUE TITLE
Old anime websites 

### ISSUE THREAD

**Issue by ParsonsPT** [aniyomiorg/aniyomi#1735]
### Describe your suggested feature

Hello aniyomi your recent update just got rid of the best websites that I like this websites are hianime,aniwave,animension and etc.Please return the websites back in aniyomi.

### Other details

The only information have is the app does not have old websites.
![Screenshot_20240731-222622](https://github.com/user-attachments/assets/e1912fc6-501f-43d2-816d-eb018b7bd5d4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
They were removed due to a DMCA notice, they're not coming back.
