### ISSUE TITLE
Can't add Jellyfin to tracking - "No match found"

### ISSUE THREAD

**Issue by HawaiianPizza** [aniyomiorg/aniyomi#1739]
### Steps to reproduce

1. Go to any anime in your library.
2. Click on **Tracking**
3. Next to Jellyfin, click on **Add tracking**

### Expected behavior

Aniyomi should be able to add tracking for Jellyfin.

### Actual behavior

A message saying **No match found** appears, and tracking is not added for Jellyfin.

![signal-2024-08-04-114403_002](https://github.com/user-attachments/assets/7f662cb5-b20e-4ab5-94f1-a588fdeaed0c)

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/16502118/aniyomi_crash_logs.txt)

### Aniyomi version

0.16.4.3

### Android version

Android 11

### Device

Samsung Galaxy Tab A (SM-T510)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Crash logs would be very helpful here, so can you do:
1. Go to settings -> more -> advanced -> turn on verbose logging
2. Try to add jellyfin tracking to an entry
3. Share crash logs from settings -> more -> advanced -> share crash logs

**Comment by HawaiianPizza** [comment]
> Crash logs would be very helpful here, so can you do:
> 
>     1. Go to settings -> more -> advanced -> turn on verbose logging
> 
>     2. Try to add jellyfin tracking to an entry
> 
>     3. Share crash logs from settings -> more -> advanced -> share crash logs
> 
> 
> (It may include the url of your jellyfin server, so censor out the domain if you want, but please don't remove anything else)

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/16502118/aniyomi_crash_logs.txt)

No mentions of Jellyfin in the crash logs. I made sure **Verbose logging** was enabled before producing the crash log.

**Comment by HawaiianPizza** [comment]
I gave Aniyomi all the permissions I can via Android settings: Music & Audio, Notifications, and Photos & Videos. Still no changes. Is there another place where I can give Aniyomi storage permissions?

**Comment by Secozzi** [comment]
Give it "Allow management of all files" under storage permissions

**Comment by 12ohit** [comment]
In one of the last few commits for Jellyfin's **extension** the authentication part was updated, instead of passing API key through url now it is passed in headers.

You can do one of the following to solve the problem:
* Install Aniyomi preview 
* Downgrade the Jellyfin's **extension**
* Wait for Aniyomi to get new stable update

**Comment by HawaiianPizza** [comment]
> In one of the last few commits for Jellyfin's **extension** the authentication part was updated, instead of passing API key through url now it is passed in headers.
> 
> You can do one of the following to solve the problem:
> 
>     * Install Aniyomi preview
> 
>     * Downgrade the Jellyfin's **extension**
> 
>     * Wait for Aniyomi to get new stable update

Thank you! This explains it for me. I'll wait for a new update. Glad to know it wasn't on my end.
