### ISSUE TITLE
1flix extension 

### ISSUE THREAD

**Issue by Perpendiculr** [aniyomiorg/aniyomi#1745]
### Describe your suggested feature

I am not code guy i want extensions and one new extension for 1flix

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by hollowshiroyuki** [comment]
damn, sucks to be u  
this is the app repo, and we don't make non self-hosted extensions for copyright reasons anyways
you'll need this : https://kotlinlang.org/docs/getting-started.html glhf

**Comment by Perpendiculr** [comment]
But all extensions are gone app is literally without extensions even
original website doesn't show extensions
