### ISSUE TITLE
Episode Countdown doesnt work

### ISSUE THREAD

**Issue by SouravPaul553h** [aniyomiorg/aniyomi#1746]
### Steps to reproduce

There used to be a countdown when you track an anime with Mal or Anilist
Now, when you open a tracked anime series, it doesn show that next episode timer anymore

### Expected behavior

When you track an anime series with Mal / Anilist it should show a timer for next episode releasing

### Actual behavior

The timer doesnt exist anymore on the app after tracking an anime with tracking service API

### Aniyomi version

v0.16.4.3-7801

### Android version

Android 12

### Device

Samsung Galaxy M31

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Fixed and should be coming in the next preview.
