### ISSUE TITLE
The Anitube extension has stopped working on Aniyomi. But the site is still up.

### ISSUE THREAD

**Issue by Rafilipes** [aniyomiorg/aniyomi#1759]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/f5e4b1fb-fd92-477b-aa88-7d2d3175f575)
1 Open the aniyomi.
2 Try opening any
anime from the Anitube Library

### Expected behavior

Should open the episode

### Actual behavior

![image](https://github.com/user-attachments/assets/bf21a3a1-c704-4ed8-ba82-a49c2120aed5)

### Crash logs

Episodes don't open

### Aniyomi version

0.16.4.3

### Android version

Android 14 

### Device

Samsung 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with an extension, I should be opening an issue in the extension's repository.
