### ISSUE TITLE
The Anitube extension has stopped working on Aniyomi. But the site is still up.

### ISSUE THREAD

**Issue by Rafilipes** [aniyomiorg/aniyomi#1760]
### Steps to reproduce

![image](https://github.com/user-attachments/assets/d0d6f339-8eae-4305-be65-7b1d550d5c70)
1- Open Aniyomi.
2- Open any anime from the Anitube Library.
3- Try starting an episode.     

### Expected behavior

Start the episode.

### Actual behavior

![LDPlayer 26_08_2024 19_59_22](https://github.com/user-attachments/assets/304861fc-81de-4e97-b491-d39165f86f0d)
![LDPlayer 26_08_2024 20_02_57](https://github.com/user-attachments/assets/f8803780-ae41-46a7-af50-8769683b60d9)
Video keeps loading and gives error.

### Aniyomi version

0.16.4.3

### Android version

Android 14 

### Device

Samsung 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with an extension, I should be opening an issue in the extension's repository.

**Comment by Rafilipes** [comment]
> > Se isso for um problema com uma extensão, devo abrir um problema no repositório da extensão.

I don't understand

**Comment by Secozzi** [comment]
Your opening an issue about an extension in the repo for the app. You're in the wrong place

**Comment by Secozzi** [comment]
Open an issue in a repo where that extension is being maintained. We don't associate with extensions anymore, so we can't/won't tell you where exactly

**Comment by Rafilipes** [comment]
> Open an issue in a repo where that extension is being maintained. We don't associate with extensions anymore, so we can't/won't tell you where exactly

GitHub correct?

**Comment by Secozzi** [comment]
If the people maintaining the extensions are using github, sure

**Comment by Rafilipes** [comment]
> Se as pessoas que mantêm as extensões estiverem usando o github, claro

So you are telling me to talk about my problem on the website where I downloaded the anime extension "Anitube". for Aniyomi?

**Comment by Rafilipes** [comment]
> Eu já disse para você perguntar onde está sendo mantido

How the hell am I supposed to know where this extension is being kept!?

**Comment by Secozzi** [comment]
That's up to you to find. I already told you that we don't associate with extensions anymore and will not say where they're being maintained
