### ISSUE TITLE
weird issue causing http error 400 when trying to add MAL tracker specifically for anime with long names (64 characters limit?)

### ISSUE THREAD

**Issue by huang-junwei** [aniyomiorg/aniyomi#1761]
### Steps to reproduce

use this title as example:
"Akuyaku Reijou Level 99: Watashi wa Ura-Boss desu ga Maou dewa Arimasen"
1. go to this anime inside the library
2. Click on "tracking" and try to add MAL tracker
3. Tracker search query will auto fill with full anime title

### Expected behavior

The MAL tracker should return a list of matched anime for user to select tracking as per normal

### Actual behavior

the MAL tracker returns http 400 error;

however the below search query works completely fine: 
"Akuyaku Reijou Level 99: Watashi wa Ura-Boss desu ga Maou dewa A"
Notice the query is exacrly 64 characters.

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Device

Xiaomi 14

### Other details

Seem to only affect the anime library, The same query string works completely fine if done under the manga library.

sample error screenshot:

![Img](https://github.com/user-attachments/assets/513d1f3c-e42b-41df-ba40-ef9580ef4581)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It's a limit with the API, it's nothing the app can do. As a workaround, you could shorten the search query or use the id: prefix, like `id:54837`
