### ISSUE TITLE
Animepahe Not working

### ISSUE THREAD

**Issue by PavelPonce** [aniyomiorg/aniyomi#1763]
### Steps to reproduce

Any animepahe anime throws a "HTTP 404, check website in WebView" error when i try to reload to check for new episodes (in this case i know there is new episodes on the anime I'm in). Some of the "loaded" episodes runs (usually for the animes i usually watch) but others just throws "HTTP error 404". When i try to search for anything in the searchbar it throws "HTTP 500, check website in WebView" (this time 500).

When i go check the webView the webView works just fine.

Thank you in advance of your answer.

### Expected behavior

Should work...

### Actual behavior

Throws Error 404 and 505

### Aniyomi version

0.16.4.3

### Android version

13 TP1A.220624.014

### Device

Xiaomi Redmi Note 11 Pro

### Other details

![After-reloading-imageonline co-5050735](https://github.com/user-attachments/assets/eb7b33f8-d637-49b9-b545-d820a1d73a84)
![When-searching-imageonline co-8573923](https://github.com/user-attachments/assets/a7ddccc4-e837-499a-897d-ba98aacaf2d1)
![When-loading-some-anime-imageonline co-2146419](https://github.com/user-attachments/assets/246f219e-0e49-4081-810a-b2ac72e27da9)
![WebView-imageonline co-9371944](https://github.com/user-attachments/assets/fd5cbe57-013a-494d-9fc0-549114cce809)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Extension issues should be opened in the exten maintainers' repository.
