### ISSUE TITLE
Playback Speed

### ISSUE THREAD

**Issue by hxrssh** [aniyomiorg/aniyomi#1765]
### Describe your suggested feature

Bring back the playback speed option. It was available in the previous versions but now you have removed it. Please add these🙏🏻🙏🏻🙏🏻

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
it was never removed
