### ISSUE TITLE
Add Extension in previous versions

### ISSUE THREAD

**Issue by hxrssh** [aniyomiorg/aniyomi#1766]
### Steps to reproduce

I have been using older version of aniyomi for 3 years. I accidentally updated it to new version which I don't like as much as the older version of it. The extensions which were installed in the previous version I reinstalled it in the new version and they are working fine. But when I am downloading the older version of the app, none of the extension are showing except 1 because that I didn't reinstall. Please give me a solution so that other extension can also be shown in the older version of aniyomi. Please🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

### Expected behavior

I have been using older version of aniyomi for 3 years. I accidentally updated it to new version which I don't like as much as the older version of it. The extensions which were installed in the previous version I reinstalled it in the new version and they are working fine. But when I am downloading the older version of the app, none of the extension are showing except 1 because that I didn't reinstall. Please give me a solution so that other extension can also be shown in the older version of aniyomi. Please🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

### Actual behavior

I have been using older version of aniyomi for 3 years. I accidentally updated it to new version which I don't like as much as the older version of it. The extensions which were installed in the previous version I reinstalled it in the new version and they are working fine. But when I am downloading the older version of the app, none of the extension are showing except 1 because that I didn't reinstall. Please give me a solution so that other extension can also be shown in the older version of aniyomi. Please🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Device

Samsung galaxy S20 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Extensions support for older versions has been dropped.
You should format your bug reports correctly.
This is not a bug.
