### ISSUE TITLE
Audio tracks missing from audio tab in local anime

### ISSUE THREAD

**Issue by perokhe** [aniyomiorg/aniyomi#1767]
### Steps to reproduce

1. Open an episode
2. Go to audio tab

### Expected behavior

It should list all audio tracks of said episode

### Actual behavior

There's no audio track, only "None"

### Aniyomi version

0.16.4.3-7809

### Android version

Android 10

### Device

Samsung Note 9

### Other details

There is audio playing, I just can't change the track because it doesn't show any.
In the subtitles tab all subtitle tracks are listed and it shows the correct one on the video, but it says "None" is selected.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
The tracks loading logic should he redone in my opinion, it's pretty jank, sometimes duplicating or missing some tracks in the ui.

**Comment by fakebhai** [comment]
> The tracks loading logic should he redone in my opinion, it's pretty jank, sometimes duplicating or missing some tracks in the ui.

#1721 's comment may help if someone wanna work on it

**Comment by perokhe** [comment]
Ok, found the problem. I was using "jp" for lang instead of "ja," which caused the function to throw an exception.
Also, it seems that it doesn't work well when the track has a two-letter code lang.
For example, given a track "Full (eng)", it will work with lang "en" and "eng", but with the track "Full (en)" neither work.

**Comment by perokhe** [comment]
Also, I think it would be better not to use the app's language by default if no lang is set. Sometimes I change the videos' default track and now it chooses a different one. If people need it they can always add their language to lang.
