### ISSUE TITLE
Extensions say obsolete/No other extensions can be downloaded apart from ones i already have

### ISSUE THREAD

**Issue by Jifyjcyi** [aniyomiorg/aniyomi#1773]
### Steps to reproduce

1. When going to ANIME EXTENSIONS, all extensions that have been downloaded all say OBSOLETE. 
2. When scrolling down past that to download other extensions, it doesn't show any others.

### Expected behavior

I should be able to see other extensions to download along with the ones I have. 

### Actual behavior

When clicking the extensions that have obsolete on them, it says it is no longer available. But when I open them in the ANIME SOURCES tab they work fine.

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Device

Samsung s22 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Aniyomi does not offer extensions in the app any more. You'll have to find and install them yourself.

**Comment by Jifyjcyi** [comment]
Do you know where i can get them?

**Comment by Secozzi** [comment]
I've alread told you we have nothing to do with extensions. We will not provide any, nor give support to them.
