### ISSUE TITLE
While using HW+ decoder resuming after pausing in player causes the player freeze

### ISSUE THREAD

**Issue by ShoyebOP** [aniyomiorg/aniyomi#1778]
### Steps to reproduce

1. Open aniyomi.
2. Open any anime from Library.
3. Play an episode.
4. Select HW+ decoder from the three dot menu in player.
5. Pause then resume.

### Expected behavior

The player should start playing the episode normally. 

### Actual behavior

The player freezes completely not allowing to do anything and using the back button crashes the player and sends back episode list.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/16893259/aniyomi_crash_logs.txt)

### Aniyomi version

0.16.4.3-7809 (standard, 1dd04fc5f, 125, 2024-08-29T08:35:29Z)

### Android version

Android version: 14 (SDK 34; build lineage_cheeseburger-userdebug 14 AP2A.240705.005 0b7ea3f132) Android build ID: lineage_cheeseburger-userdebug 14 AP2A.240705.005 0b7ea3f132

### Device

 Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus5 (OnePlus5) Device model: ONEPLUS A5000 WebView: Android System WebView 125.0.6422.165 MPV version: 4d32db2 Libplacebo version: v7.349.0 FFmpeg version: n7.0

### Other details

I previously reported this issue in #1750 but I didn't know what was causing it but now I found out that this only occurs in HW+ decoder. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Why did you close #1750 and open this?

**Comment by Secozzi** [comment]
Yes please do that instead
