### ISSUE TITLE
Video list is empty.

### ISSUE THREAD

**Issue by CahyaXyZp** [aniyomiorg/aniyomi#1779]
### Steps to reproduce

1. Select Anime
2. Choose episode
3. Issue happen (see the video)

https://github.com/user-attachments/assets/400df4ff-a441-4334-a444-3175c5ce0a0b

### Expected behavior

It's should I'm watching Anime. LOL

### Actual behavior

This happened instead I should have watched the anime, but I couldn't

### Crash logs

App version: 0.16.4.3 (standard, 959f84a, 124, 2024-07-01T22:25Z)
Android version: 11 (SDK 30; build CPH2269_11_A.35)
Android build ID: CPH2269_11_A.35
Device brand: OPPO
Device manufacturer: OPPO
Device name: OP4F97 (CPH2269T2)
Device model: CPH2269
WebView: Android System WebView 129.0.6668.31
MPV version: 4d32db2
Libplacebo version: v7.349.0
FFmpeg version: n7.0

--------- beginning of main
09-08 18:10:07.537  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:08.930  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
--------- beginning of system
09-08 18:10:09.717  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:09.744  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:09.784  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:09.823  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:09.856  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:09.897  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:09.951  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:09.966  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.325  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.364  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.380  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.411  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.424  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.463  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.480  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.496  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.512  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.529  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.546  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.597  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:11.641  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.343  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.369  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.388  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.402  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.412  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.444  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.464  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.489  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.495  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.511  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.528  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.545  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.561  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.577  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.594  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.611  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.643  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.668  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.679  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:12.954  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.433  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.460  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.475  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.494  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.518  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.535  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.551  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.566  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.579  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.597  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.620  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.632  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.654  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.675  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:13.689  7954  8230 E FrameEvents: updateAcquireFence: Did not find frame.
09-08 18:10:15.047  7954  8196 E DatabaseUtils: Writing exception to parcel
09-08 18:10:15.047  7954  8196 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=16229, uid=1000 requires the provider be exported, or grantUriPermission()
09-08 18:10:15.047  7954  8196 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
09-08 18:10:15.047  7954  8196 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
09-08 18:10:15.047  7954  8196 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
09-08 18:10:15.047  7954  8196 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
09-08 18:10:15.047  7954  8196 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1161)
09-08 18:10:15.047  7954  8196 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1130)
09-08 18:10:25.361  7954  8051 E DatabaseUtils: Writing exception to parcel
09-08 18:10:25.361  7954  8051 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/aniyomi_crash_logs.txt from pid=16229, uid=1000 requires the provider be exported, or grantUriPermission()
09-08 18:10:25.361  7954  8051 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
09-08 18:10:25.361  7954  8051 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
09-08 18:10:25.361  7954  8051 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
09-08 18:10:25.361  7954  8051 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
09-08 18:10:25.361  7954  8051 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1161)
09-08 18:10:25.361  7954  8051 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1130)

### Aniyomi version

0.16.4.3

### Android version

Android 11

### Device

Oppo A16

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with an extension, I should be opening an issue in the extension's repository.
