### ISSUE TITLE
Regarding adding a new website to the extensions repo

### ISSUE THREAD

**Issue by 0dusk** [aniyomiorg/aniyomi#1786]
### Describe your suggested feature

There's a new website and it's quite good it's called Yukiwatch. Url: https://yukiwatch.fr/home

Please consider adding this to the extensions repo 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
1. This repo is about the app, not extensions.
2. We don't manage extensions anymore, so we won't add any more.

**Comment by 0dusk** [comment]
@Secozzi then if it's alright, can you tell me where or who can I contact for the extensions related stuff?

**Comment by folkeishii** [comment]
> @Secozzi then if it's alright, can you tell me where or who can I contact for the extensions related stuff?

We don't endorse/associate with any repo

**Comment by Secozzi** [comment]
> @Secozzi then if it's alright, can you tell me where or who can I contact for the extensions related stuff?

We don't associatie with, or endorse any repo. Find them yourself
