### ISSUE TITLE
Doesn't restores repos from backup file

### ISSUE THREAD

**Issue by JDKamalakar** [aniyomiorg/aniyomi#1798]
### Steps to reproduce

1) restore backup from file. 

### Expected behavior

It should restore repo. 

### Actual behavior

It doesn't restores repo. 

### Aniyomi version

0.16.4.3-7814

### Android version

15

### Device

Google pixel 6A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> It should restore repo.
It shouldn't, as extension repos aren't included in backups atm
