### ISSUE TITLE
Add cloudflare capatcha skip

### ISSUE THREAD

**Issue by kk800925** [aniyomiorg/aniyomi#1799]
### Describe your suggested feature

When I open Manga website in anyiomi not open but when I open in my browser it order from me cloudflare human verification after that manga website open normally then can you add cloudflare human verification skip feature to app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Follow our guide for cloudflare related issues: https://aniyomi.org/docs/guides/troubleshooting/#cloudflare.
