### ISSUE TITLE
Multiple subtitles at the same time

### ISSUE THREAD

**Issue by reagag** [aniyomiorg/aniyomi#1801]
### Describe your suggested feature

Requesting ability to display multiple _embedded_  subtitles at the same time .
Would be great for people trying to learn a language, for example.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
I think you can do it using mpv-config. or try mpvKt it supports secondary subtitles through gui

**Comment by reagag** [comment]
Mpv config seems to only be able to do that for external subs.

For things like using torrential with embedded subs, I'm not sure if there's a way to select multiple in the first place?
