### ISSUE TITLE
Adicionar Fonte local em nuvem 

### ISSUE THREAD

**Issue by delfreitas** [aniyomiorg/aniyomi#1802]
### Describe your suggested feature

Um local em nuvem seria mais uma ótima opção pro aplicativo, assim colocaríamos nossos animes e mangas  em um armazenamento em nuvem, e acesaariamos pelo aplicativo 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
No, that's what extensions are for

**Comment by delfreitas** [comment]
Então não será adicionado, porque já temos as extensões que nos oferecem os
animes e os mangas de fora do aplicativo, é isso?

Em seg., 28 de out. de 2024 13:10, Secozzi ***@***.***>
escreveu:

**Comment by delfreitas** [comment]
> Não, é para isso que servem as extensões



> Não, é para isso que servem as extensões

Então não será adicionado, porque já temos as extensões que oferecemos aos animes e aos mangás de fora do aplicativo, é isso?

**Comment by delfreitas** [comment]
> Não, é para isso que servem as extensões

@Secozzi, então não será adicionado porque já temos as extensões que oferecem os animes e aos mangás de fora do aplicativo, é isso?

**Comment by delfreitas** [comment]
Now I understand, I go to extension options then 👍🏻 @Secozzi

**Comment by delfreitas** [comment]
> It won't be added to be app because it should be added as an extension

It's because I'm new to these resource matters, but thanks for your attention.
