### ISSUE TITLE
http 404 error

### ISSUE THREAD

**Issue by aggreyas** [aniyomiorg/aniyomi#1803]
### Steps to reproduce

Source information
Cimaleel 14.1

Source language
Arabic

Steps to reproduce
Open Cimaleel

### Expected behavior

Expected:
"should load Latest movies"

### Actual behavior

Actual behavior
shows "http 404 message check web page in webview"
![Screenshot_2024-10-30-15-28-08-427_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/10b36903-63d6-467c-825d-48c8e8c03716)
![Screenshot_2024-10-30-15-28-19-887_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/58cef9d4-88af-4395-9889-02a3a1f2bdc4)

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Device

Poco x6 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with an extension, I should be opening an issue in the extension's repository.

**Comment by aggreyas** [comment]
So when can you solve the problem?

**Comment by Secozzi** [comment]
It's not our problem to solve

**Comment by aggreyas** [comment]
Oh, so I have a question, the site has changed its URL, How can I change the source link? I can in manga sources but not in anime.

**Comment by Secozzi** [comment]
As you've already been told, this isn't the place to report extension issues. It's for the main app and main app only.

**Comment by aggreyas** [comment]
Sorry, this is my first time reporting a bug. Where can I report such problems?
