### ISSUE TITLE
Unable to watch anime

### ISSUE THREAD

**Issue by Naqz001** [aniyomiorg/aniyomi#1806]
### Steps to reproduce

1. I was trying to watch some anime but some anime cannot be open
2. it said "video list empty"
3. I've tried watching other anime and its fine 

### Expected behavior

Anime can be watched

### Actual behavior

listed as "video list empty"

### Aniyomi version

0.16.4.3

### Android version

miui 14

### Device

redmi note 9s

### Other details

I've tried searching on how to fix it but didn't find any useful information. Any help is appreciated tysm.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
"video list empty" is an extension issue, not an app issue. Report it to the extension maintainers instead.
