### ISSUE TITLE
Anilist Authorization Request Error

### ISSUE THREAD

**Issue by YuiitsunoYoake** [aniyomiorg/aniyomi#1821]
### Steps to reproduce

anilist does not sign in within aniyomi

### Expected behavior

When you sync anilist to aniyomi you could see the progress of the anime or manga you followed.

### Actual behavior

When I try to log in to anilist it immediately redirects me to aniyomi without going through the login process, I didn't have this error two days ago where could anilist be logged in to aniyomi.

### Aniyomi version

0.16.4.3-8019

### Android version

Android 14

### Device

Moto G24 Power

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It's an issue on anilist's side, there's nothing we can do about it.
