### ISSUE TITLE
Anime Filler list

### ISSUE THREAD

**Issue by ShoaibKhanali** [aniyomiorg/aniyomi#1823]
### Describe your suggested feature

Is it possible for the app to get the filler episodes data from APls like https://github.com/xsunzukz/anime-filler-episodes-api
If it is available then the app will get the data and if not the data will be taken from the source extension. If this is possible it would be really helpful especially the filler episode data. Maybe make a toggle in the library to get data from Source or APls ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
The main problem with this is that no filler list site seems to have any official api. The one you provided is just a scraper of animefillerlist.com. We don't want to scrape sites in the main app like this, and there is no good way to map each entry in your library to an entry on the sites.

**Comment by ShoaibKhanali** [comment]
What you think about this  

https://github.com/Kabir-Sidhu/anime-filler-list-api

**Comment by ShoaibKhanali** [comment]
What about this

https://github.com/falcon71181/Anime-API?tab=readme-ov-file

**Comment by Secozzi** [comment]
> What about this
> 
> https://github.com/falcon71181/Anime-API?tab=readme-ov-file

We're not adding this either. Instead of being a scraper of some random filler list site, it scrapes piracy streaming sites instead.

**Comment by ShoaibKhanali** [comment]
Simkl support anime filler it is possible to scrap it
https://simkl.com/anime/38636/one-piece/filler-list/

**Comment by Secozzi** [comment]
> Simkl support anime filler it is possible to scrap it https://simkl.com/anime/38636/one-piece/filler-list/

Unlike all the other links youve provided, this one is actually viable. Create a new issue about it.
