### ISSUE TITLE
Tap and hold to 2x speed 

### ISSUE THREAD

**Issue by DRAGO0700** [aniyomiorg/aniyomi#1825]
### Describe your suggested feature

Can you guys add tap and hold to 2x speed just like YouTube 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Duplicate of #1660

**Comment by DRAGO0700** [comment]
So When will be this feature implemented

**Comment by Secozzi** [comment]
Whenever someone feels like implementing it, there's no ETA.
