### ISSUE TITLE
Gogoanime problems

### ISSUE THREAD

**Issue by Khansiam44** [aniyomiorg/aniyomi#1836]
### Steps to reproduce

In gogoanime there is no new episodes no matter how much I refresh it or update it and there is no new animes also 🥺
![Screenshot_2024-12-03-01-21-50-963_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/23b719c1-ce2c-4fbb-ba94-ca003dc2b58c)
![Screenshot_2024-12-03-01-22-20-872_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/927b2b3f-addf-407d-9781-f5f26a2a4d8f)
![Screenshot_2024-12-03-01-22-34-751_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/0f1a2654-f8b6-4b31-a47f-836645661434)
![Screenshot_2024-12-03-01-31-02-237_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/3d1c0e9a-e920-4ad1-b7ac-32bef8227114)
![Screenshot_2024-12-03-01-31-45-749_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/f6c07663-c79b-4359-b1df-cac63866ee73)
![Screenshot_2024-12-03-01-31-51-535_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/2a875ed2-4d7d-4dfd-8dd2-60a1064dbf1c)
![Screenshot_2024-12-03-01-32-26-148_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/a256c60d-3e1d-417b-bc00-f9432f1ad7b3)
![Screenshot_2024-12-03-01-32-35-763_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/b4965a6d-8ef4-4100-9b17-32824289ca50)
It's been 10 days already please help me fix this problem 😭 and my library update also not working 😭

### Expected behavior

In gogoanime there is no new episodes no matter how much I refresh it or update it and there is no new animes also 🥺 please help me fix this problem please 

### Actual behavior

I can see anime on gogoanime but there is no new episodes there no matter how much I refresh it 

### Aniyomi version

0.16.4.3-8019

### Android version

11 RP1A.200720.011

### Device

Redmi Note 8 Pro

### Other details

Besides gogoanime problems there are also Library update problem please fix this problem 😭
![Screenshot_2024-12-03-01-21-50-963_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/95633baa-704a-4da2-b071-152cc46e7437)
![Screenshot_2024-12-03-01-22-20-872_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/237910e5-b815-4140-a7df-db80895dbb2a)
![Screenshot_2024-12-03-01-22-34-751_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/833a7b96-2345-4549-b805-1ece7d159b98)
![Screenshot_2024-12-03-01-31-02-237_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/bbbf6cbb-29d7-48f7-a8b1-6dd16352d434)
![Screenshot_2024-12-03-01-31-45-749_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/b4e8cf47-7915-48cc-8edf-f667e607d4cc)
![Screenshot_2024-12-03-01-31-51-535_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/f62566ae-7319-4462-8b1d-423be0ee23f4)
![Screenshot_2024-12-03-01-32-26-148_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/68357cae-c5ae-43fb-95b3-c2aef0da67a1)
![Screenshot_2024-12-03-01-32-35-763_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/cdcf8322-c206-4989-a68e-5f8522b1043a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with an extension, I should be opening an issue in the extension's repository.

**Comment by mauryamj** [comment]
It has been like this for last 3 days for me and need to be fixed

**Comment by SkyWarriorXd** [comment]
Is this being fixed?
