### ISSUE TITLE
Gogoanime ( anitaku.to) 

### ISSUE THREAD

**Issue by avinave14102001** [aniyomiorg/aniyomi#1839]
### Steps to reproduce

They are not working
Showing error 522 

### Expected behavior

Loading in gogoanime( anitaku.to) showing error 522

### Actual behavior

Socket timeout exception: timeout
As be come 

### Aniyomi version

0.16.4.3

### Android version

Android 11

### Device

Relame 6pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
We don't support this extension.

**Comment by avinave14102001** [comment]
> We don't support this extension.

Ok but gogoanime or anitaku.to not yesterday or today 
And showing error 522 anitaku.to 
Can tell how much time to solve this problem

**Comment by avinave14102001** [comment]
> We don't support this extension.

Please reply

**Comment by abdallahmehiz** [comment]
We don't know.
We are not the ones responsible for maintaining the extension, you should ask that to your the maintainers of the repository you're using.

**Comment by avinave14102001** [comment]
> We don't know. We are not the ones responsible for maintaining the extension, you should ask that to your the maintainers of the repository you're using.

I am not maintaining
I am just a watch anime in GoGoAnime other anitaku.to they are not working yesterday or today and showing error 522

**Comment by Secozzi** [comment]
We will not address or look into any issues with this extension. If you want help, go ask whoever's maintaining the extension.

**Comment by avinave14102001** [comment]
> We will not address or look into any issues with this extension. If you want help, go ask whoever's maintaining the extension.

I don't know we're i am go to ask help someone can tell me

**Comment by Secozzi** [comment]
> I don't know we're i am go to ask help someone can tell me

Not here
