### ISSUE TITLE
My anime list error 401

### ISSUE THREAD

**Issue by Liametekudasai** [aniyomiorg/aniyomi#1841]
### Steps to reproduce

Try adding a manga/anime to anime list
Realise you can't 

### Expected behavior

Try adding a manga/anime to anime list
It works

### Actual behavior

When trying to add the media MAL responds with a 401 error code

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Device

Samsung galaxy A34 5G ; SM-A346B/DSN

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Log out and back in.
