### ISSUE TITLE
Extension (memory  )leakage 

### ISSUE THREAD

**Issue by shreyanshjain1915** [aniyomiorg/aniyomi#1845]
### Steps to reproduce

When I tried to download anything  it shows something is wrong. And gives a crash log
 I post the crash log on discord they say problem is in extension or memory leakage.

### Expected behavior

It Stops the app or make it slow 
Then I have to restart the app 

### Actual behavior

When I tried to download anything  it shows something is wrong. And gives a crash log
 Then I have to restart the app . 

### Crash logs

App version: 0.16.4.3 (standard, 959f84a, 124, 2024-07-01T22:25Z)
Android version: 14 (SDK 34; build CPH2585_14.0.0.832(EX01))
Android build ID: CPH2585_14.0.0.832(EX01)
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OP5D35L1 (CPH2585IN)
Device model: CPH2585
WebView: Android System WebView 131.0.6778.104
MPV version: 4d32db2
Libplacebo version: v7.349.0
FFmpeg version: n7.0

--------- beginning of crash
12-04 18:02:28.031 26305 26447 E AndroidRuntime: FATAL EXCEPTION: binder:26305_7
12-04 18:02:28.031 26305 26447 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 26305
12-04 18:02:28.031 26305 26447 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 36784 free bytes and 35KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
12-04 18:02:28.031 26305 26447 E AndroidRuntime: 	at android.app.servertransaction.ClientTransaction$1.createFromParcel(ClientTransaction.java:209)
12-04 18:02:28.031 26305 26447 E AndroidRuntime: 	at android.app.servertransaction.ClientTransaction$1.createFromParcel(ClientTransaction.java:207)
12-04 18:02:28.031 26305 26447 E AndroidRuntime: 	at android.os.Parcel.readTypedObject(Parcel.java:4055)
12-04 18:02:28.031 26305 26447 E AndroidRuntime: 	at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:1212)
12-04 18:02:28.031 26305 26447 E AndroidRuntime: 	at android.app.ActivityThread$ApplicationThread.onTransact(ActivityThread.java:2238)
12-04 18:02:28.031 26305 26447 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1362)
12-04 18:02:28.031 26305 26447 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1288)
12-05 10:42:00.820 23185 23309 E AndroidRuntime: FATAL EXCEPTION: Okio Watchdog
12-05 10:42:00.820 23185 23309 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 23185
12-05 10:42:00.820 23185 23309 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 39936 free bytes and 39KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
12-05 10:42:00.820 23185 23309 E AndroidRuntime: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1746)
12-05 10:42:00.820 23185 23309 E AndroidRuntime: 	at okio.AsyncTimeout$Companion.awaitTimeout(Unknown Source:63)
12-05 10:42:00.820 23185 23309 E AndroidRuntime: 	at okio.AsyncTimeout$Watchdog.run(Unknown Source:7)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: FATAL EXCEPTION: main
12-05 10:42:03.397 23185 23185 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 23185
12-05 10:42:03.397 23185 23185 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 31712 free bytes and 30KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at android.app.OplusActivityThreadExtImpl.callGcSupression(OplusActivityThreadExtImpl.java:1448)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2711)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:255)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:364)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8979)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
12-05 10:42:03.397 23185 23185 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)
12-05 10:42:03.397 23185 23720 E AndroidRuntime: FATAL EXCEPTION: Thread-0
12-05 10:42:03.397 23185 23720 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 23185
12-05 10:42:03.397 23185 23720 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 3072 free bytes and 3072B until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
12-05 10:42:03.397 23185 23720 E AndroidRuntime: 	at java.util.logging.LogManager.reset(LogManager.java:1321)
12-05 10:42:03.397 23185 23720 E AndroidRuntime: 	at java.util.logging.LogManager$Cleaner.run(LogManager.java:231)
12-05 10:42:03.400 23185 23332 E AndroidRuntime: FATAL EXCEPTION: OkHttp TaskRunner
12-05 10:42:03.400 23185 23332 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 23185
12-05 10:42:03.400 23185 23332 E AndroidRuntime: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
12-05 14:47:57.786  9024  9024 E AndroidRuntime: FATAL EXCEPTION: main
12-05 14:47:57.786  9024  9024 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 9024
12-05 14:47:57.786  9024  9024 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 2220032 free bytes and 2168KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at java.lang.Float.valueOf(Float.java:469)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.getAnimatedValue(PropertyValuesHolder.java:1359)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.ValueAnimator.getAnimatedValue(ValueAnimator.java:944)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.viewer.components.DoubleTapSecondsView$CustomValueAnimator$$ExternalSyntheticLambda0.onAnimationUpdate(Unknown Source:7)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.Animator$AnimatorCaller.lambda$static$4(Animator.java:866)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda6.call(Unknown Source:4)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.Animator.callOnList(Animator.java:677)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1664)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1405)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1582)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1523)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1534)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:975)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1508)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:255)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:364)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8979)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
12-05 14:47:57.786  9024  9024 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)
12-05 14:49:57.319 18836 19126 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 19126 (Thread-59), pid 18836 (ir.tachiyomi.mi)
12-05 14:49:58.076 19475 19475 F DEBUG   : Process name is xyz.jmir.tachiyomi.mi, uid is 10337, not key_process
12-05 14:49:58.076 19475 19475 F DEBUG   : keyProcess: 0
12-05 14:49:58.076 19475 19475 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-05 14:49:58.076 19475 19475 F DEBUG   : Build fingerprint: 'OnePlus/CPH2585IN/OP5D35L1:14/TP1A.220905.001/U.R4T3.1a1ae71_4160-15c:user/release-keys'
12-05 14:49:58.076 19475 19475 F DEBUG   : Revision: '0'
12-05 14:49:58.076 19475 19475 F DEBUG   : ABI: 'arm64'
12-05 14:49:58.076 19475 19475 F DEBUG   : Timestamp: 2024-12-05 14:49:57.576863274+0530
12-05 14:49:58.076 19475 19475 F DEBUG   : Process uptime: 121s
12-05 14:49:58.076 19475 19475 F DEBUG   : Cmdline: xyz.jmir.tachiyomi.mi
12-05 14:49:58.076 19475 19475 F DEBUG   : pid: 18836, tid: 19126, name: Thread-59  >>> xyz.jmir.tachiyomi.mi <<<
12-05 14:49:58.076 19475 19475 F DEBUG   : uid: 10337
12-05 14:49:58.076 19475 19475 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
12-05 14:49:58.076 19475 19475 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
12-05 14:49:58.076 19475 19475 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
12-05 14:49:58.076 19475 19475 F DEBUG   : Abort message: 'No pending exception expected: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 294144 free bytes and 287KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
12-05 14:49:58.076 19475 19475 F DEBUG   :   at java.util.Iterator java.util.ArrayList.iterator() (ArrayList.java:1036)
12-05 14:49:58.076 19475 19475 F DEBUG   :   at void is.xyz.mpv.MPVLib.event(int) (SourceFile:-1)'
12-05 14:49:58.076 19475 19475 F DEBUG   :     x0  0000000000000000  x1  0000000000004ab6  x2  0000000000000006  x3  0000006ed65fb400
12-05 14:49:58.076 19475 19475 F DEBUG   :     x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
12-05 14:49:58.076 19475 19475 F DEBUG   :     x8  00000000000000f0  x9  0000007112876d58  x10 0000000000000001  x11 00000071128fc104
12-05 14:49:58.076 19475 19475 F DEBUG   :     x12 0000006ed65fa140  x13 00000000000001c3  x14 0000006ed65fa1f0  x15 00000164cb3b8be1
12-05 14:49:58.076 19475 19475 F DEBUG   :     x16 0000007112967090  x17 000000711293fd50  x18 0000006ecf14c000  x19 0000000000004994
12-05 14:49:58.076 19475 19475 F DEBUG   :     x20 0000000000004ab6  x21 00000000ffffffff  x22 0000000000000000  x23 b400006f2fbf4000
12-05 14:49:58.076 19475 19475 F DEBUG   :     x24 0000000000fffff9  x25 000000005a000000  x26 0000006ed65fc000  x27 0000006ed65fb74c
12-05 14:49:58.076 19475 19475 F DEBUG   :     x28 b4000070846d4f00  x29 0000006ed65fb480
12-05 14:49:58.076 19475 19475 F DEBUG   :     lr  00000071128ecde4  sp  0000006ed65fb3e0  pc  00000071128ece10  pst 0000000000001000
12-05 14:49:58.076 19475 19475 F DEBUG   : 15 total frames
12-05 14:49:58.076 19475 19475 F DEBUG   : backtrace:
12-05 14:49:58.076 19475 19475 F DEBUG   :       #00 pc 000000000009ce10  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: f5f7a5dceb6ab17a1a448521eb52ce18)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #01 pc 000000000093075c  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+344) (BuildId: 3f7d5a016e08d528f129bdd336d81168)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #02 pc 00000000000160fc  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80) (BuildId: 42d41ca7c77853791d096606e7186547)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #03 pc 00000000000156d0  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+516) (BuildId: 42d41ca7c77853791d096606e7186547)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #04 pc 000000000024ea9c  /apex/com.android.art/lib64/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+8400) (BuildId: 3f7d5a016e08d528f129bdd336d81168)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #05 pc 00000000003ee2d0  /apex/com.android.art/lib64/libart.so (NterpGetClass+1048) (BuildId: 3f7d5a016e08d528f129bdd336d81168)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #06 pc 0000000000784a70  /apex/com.android.art/lib64/libart.so (nterp_get_class+48) (BuildId: 3f7d5a016e08d528f129bdd336d81168)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #07 pc 0000000000776f50  /apex/com.android.art/lib64/libart.so (nterp_op_check_cast+80) (BuildId: 3f7d5a016e08d528f129bdd336d81168)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #08 pc 0000000000776bea  /data/app/~~ZFnZM8AngTZ3N397AGf_SQ==/xyz.jmir.tachiyomi.mi-moRsnaiQGBNPLObSkw6kbw==/oat/arm64/base.vdex (is.xyz.mpv.MPVLib.eventProperty+34)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #09 pc 000000000036de40  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 3f7d5a016e08d528f129bdd336d81168)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #10 pc 000000000073f120  /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+984) (BuildId: 3f7d5a016e08d528f129bdd336d81168)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #11 pc 0000000000004604  /data/app/~~ZFnZM8AngTZ3N397AGf_SQ==/xyz.jmir.tachiyomi.mi-moRsnaiQGBNPLObSkw6kbw==/base.apk!libplayer.so (offset 0x2ae0000) (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116) (BuildId: 614bd579d565b81e4bcd69ddd15b35264102d9d2)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #12 pc 0000000000004520  /data/app/~~ZFnZM8AngTZ3N397AGf_SQ==/xyz.jmir.tachiyomi.mi-moRsnaiQGBNPLObSkw6kbw==/base.apk!libplayer.so (offset 0x2ae0000) (event_thread(void*)+848) (BuildId: 614bd579d565b81e4bcd69ddd15b35264102d9d2)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #13 pc 0000000000104fe4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: f5f7a5dceb6ab17a1a448521eb52ce18)
12-05 14:49:58.076 19475 19475 F DEBUG   :       #14 pc 000000000009e77c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: f5f7a5dceb6ab17a1a448521eb52ce18)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-22
12-05 17:34:55.118 17212 17351 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 17212
12-05 17:34:55.118 17212 17351 E AndroidRuntime: java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at android.widget.Toast.getLooper(Toast.java:187)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at android.widget.Toast.<init>(Toast.java:172)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at android.widget.Toast.makeText(Toast.java:504)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at android.widget.Toast.makeText(Toast.java:493)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.system.ToastExtensionsKt.toast(Unknown Source:18)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.system.ToastExtensionsKt.toast$default(SourceFile:4)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity$$ExternalSyntheticLambda1.uncaughtException(Unknown Source:10)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:20)
12-05 17:34:55.118 17212 17351 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:62)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: FATAL EXCEPTION: OkHttp TaskRunner
12-05 23:52:44.909 20845 21014 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 20845
12-05 23:52:44.909 20845 21014 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 1444464 free bytes and 1410KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okio.Segment.<init>(SourceFile:2)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okio.SegmentPool.take(Unknown Source:33)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okio.Buffer.writableSegment$okio(Unknown Source:11)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okio.InputStreamSource.read(Unknown Source:20)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okio.AsyncTimeout$source$1.read(Unknown Source:12)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okio.RealBufferedSource.request(Unknown Source:24)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okio.RealBufferedSource.require(Unknown Source:0)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Reader.nextFrame(Unknown Source:18)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(SourceFile:4)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(SourceFile:1)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(Unknown Source:2)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okhttp3.internal.concurrent.TaskRunner.access$runTask(Unknown Source:15)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(Unknown Source:48)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
12-05 23:52:44.909 20845 21014 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
12-06 09:10:11.409 32738 32738 E AndroidRuntime: FATAL EXCEPTION: main
12-06 09:10:11.409 32738 32738 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 32738
12-06 09:10:11.409 32738 32738 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 3691104 free bytes and 3604KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
12-06 09:10:11.409 32738 32738 E AndroidRuntime: 	at androidx.compose.ui.graphics.Matrix.constructor-impl$default(Unknown Source:2)
12-06 09:10:11.409 32738 32738 E AndroidRuntime: 	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.getMatrix-sQKQjiQ(Unknown Source:51)
12-06 09:10:11.409 32738 32738 E AndroidRuntime: 	at androidx.compose.ui.platform.GraphicsLayerO

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Device

One plus 12 r

### Other details

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/18134187/aniyomi_crash_logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Check with whoever's maintaining the extensions you're using.
