### ISSUE TITLE
Kaido updated site

### ISSUE THREAD

**Issue by euijoonyeo** [aniyomiorg/aniyomi#1846]
### Steps to reproduce

Kaido site updated to https://aniwatchtv.to/

### Expected behavior

.

### Actual behavior

.

### Crash logs

.

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Device

Galaxy a15 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with an extension, I should be opening an issue in the extension's repository.
