### ISSUE TITLE
YoMovies extension

### ISSUE THREAD

**Issue by Purushottamkeshari** [aniyomiorg/aniyomi#1854]
### Steps to reproduce

1. Open aniyomi and download YoMovies extension 
2. Open YoMovies extension 
3. Play any movies 
4. Movies not play with error.
5. I am provide screenshot the
![Screenshot_20241224_115017_Aniyomi](https://github.com/user-attachments/assets/067f3a41-bbd9-4b8c-b1f0-3c8b9e215110)
 error

### Expected behavior

YoMovies extension opens but the movie does not play

### Actual behavior

Movies used to play in the old version. 
Version 0.15.3.0 
New version 0.16.4.3 extension not work 
Extension name is YoMovies

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/18236725/aniyomi_crash_logs.txt)

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Device

Samsung galaxy a23 5g 

### Other details

 extension not working in new version 0.16.4.3
![Screenshot_20241224_122045_Aniyomi](https://github.com/user-attachments/assets/2e8c8216-74c4-4839-aa89-0edc62bea2c6)
![Screenshot_20241224_115017_Aniyomi](https://github.com/user-attachments/assets/bfff41d2-d025-45f9-ab37-35552f2b057d)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
> If this is an issue with an extension, I should be opening an issue in the extension's repository.
