### ISSUE TITLE
Problem with External Players

### ISSUE THREAD

**Issue by nabileus** [aniyomiorg/aniyomi#193]
### Steps to reproduce

1)Enable External Player
2)Set always open Mx player 
3)Then just open any episode

### Expected behavior

Play in MX player Normally 

### Actual behavior

Mx sends an error "Can't play this link"

### Aniyomi version

0.12.3.1

### Android version

Android 10

### Device

Infinix hot 9 play

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Benhirer** [comment]
> ### Steps to reproduce
> 1)Enable External Player 2)Set always open Mx player 3)Then just open any episode
> 
> ### Expected behavior
> Play in VLC or any other player
> 
> ### Actual behavior
> Receive an error "Can't play this link"
> 
> ### Crash logs
> _No response_
> 
> ### Aniyomi version
> 0.12.3.1
> 
> ### Android version
> Android 7.0
> 
> ### Device
> Lenovo Tab 7
>

**Comment by Benhirer** [comment]
Steps to reproduce
 1)Enable External Player
 2)Set always open Mx player 
 3)Then just open any episode
 
     Expected behavior
 1)Play in VLC and MX player.
 2)Any other video players.

     Actual behavior
 1)Receive an error "Can't play this link"

     Aniyomi version
 1)0.12.3.1

     Android version
 1)Android 7.0
 
     Device
 1)Lenovo Tab 7

**Comment by AyAt786M** [comment]
Device: Realms 3 pro
Aniyomi version: 0.12.3.1
Android version: 11

I have same problem with external players.

**Comment by erickyun** [comment]
gogoanime can be played with mpv-android 
use a referer

I did try myself it works

@jmir1 mpv-android should be added as an external player

**Comment by Chickenshrimps** [comment]
> gogoanime can be played with mpv-android use a referer
> 
> I did try myself it works

What about vlc?

**Comment by juniornff** [comment]
Check this comment [Here](https://github.com/jmir1/aniyomi/issues/427#issuecomment-1207860980)

**Comment by JebinBrightson** [comment]
How to change video quality while using external player?

**Comment by Quickdesh** [comment]
> How to change video quality while using external player?

Hold on download icon and it shows options
