### ISSUE TITLE
[Feature Request] Tie an anime to multiple sources

### ISSUE THREAD

**Issue by JoonasC** [aniyomiorg/aniyomi#223]
### Describe your suggested feature

Currently if I add an anime from gogoanime to my collection it will always be tied to gogoanime, it would be nice to have the ability to tie an anime to multiple sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
You can migrate to another source, or did I misunderstand what you mean by "tying an anime to a source"?

**Comment by JoonasC** [comment]
@jmir1 What I am suggesting is that when you search for an anime on a specific source, you can link or "tie" that search result to an anime which you already have in your library. And then when you select the anime from your library you could maybe have a dropdown, which lets you select the source.

**Comment by jmir1** [comment]
I see... It would be a bit more convenient than having to migrate sources.

**Comment by FrixBOX** [comment]
Oh….TachiyomiSY has that feature

**Comment by AbdullahMehiz** [comment]
So, what're you saying... You want to search an anime from a database, like MAL or AL, add it to library
Then select the source?

**Comment by JoonasC** [comment]
It could work like that as well.

**Comment by Ugaog123** [comment]
Thats kinda like how animixplay works, where you can choose a stream but you can easily change the stream from a list provided

**Comment by JoonasC** [comment]
Yeah, this would be nice to have since sometimes a source will suddenly stop working, and I don't want to add the same anime two times to my library.

**Comment by Quickdesh** [comment]
Would not be feasible with new system
