### ISSUE TITLE
Calander and more option in categories 

### ISSUE THREAD

**Issue by Kxnzord** [aniyomiorg/aniyomi#224]
### Describe your suggested feature

Ex

### Other details

Ex

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
Please elaborate
