### ISSUE TITLE
Trigger navigation bar with remote tv and add more navigation bar function

### ISSUE THREAD

**Issue by FrixBOX** [aniyomiorg/aniyomi#229]
### Describe your suggested feature

Currently, you can only use navigation bar function when it shows shortly after you open a video, when it's hide you can't trigger it using remote tv. you can only reopen video and wait for navigation bar to show itself before using it again.

and since you can't double tap on android tv please add jump forward button on navigation bar.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/162
