### ISSUE TITLE
Hide from recent tab

### ISSUE THREAD

**Issue by AO124** [aniyomiorg/aniyomi#269]
### Describe your suggested feature

A special setting,
if i on it
it won't show the app preview when i press the recent button

and to completely exit the app either i have to off the feature or manually exit the app with another button(extra feature) in the app

### Other details

Though it has a security feature, where a black preview is shown but I think if Hide is possible it would be much better.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
At that point just exit the app, there is no reason for this feature to exist.

Plus how you described it means you get locked in the app
