### ISSUE TITLE
[Feature request] Add anime or manga shortcut to homescreen

### ISSUE THREAD

**Issue by ChinoKaffu** [aniyomiorg/aniyomi#279]
### Describe your suggested feature

An option to create shortcut selected anime or manga to the home screen. When clicked, the shortcut links the anime/manga in aniyomi

### Other details

similar to what AnymeX does

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MoonLGH** [comment]
that would require tachiomi to implement it first, then aniyomi will do it i gues....

**Comment by 12ohit** [comment]
# If you mean like this
![1657261213792](https://user-images.githubusercontent.com/53574579/177929397-493af1eb-b549-49ae-a805-e0f0ac27fad2.jpg)
# Then you can add them from here
![1657261213803](https://user-images.githubusercontent.com/53574579/177929508-707ff03e-c5cb-4181-9186-08c5b4651d2a.jpg)
