### ISSUE TITLE
Error in playing episode

### ISSUE THREAD

**Issue by Skmustaq12** [aniyomiorg/aniyomi#309]
### Steps to reproduce

1 click on the episode
2 start to load 
3 video can't load 

### Expected behavior

Automatic play the episode

### Actual behavior

Episode takes long time to reload but can't play

### Crash logs

--------- beginning of system
--------- beginning of main
01-06 13:36:41.301  1952  1952 E ir.tachiyomi.m: Not starting debugger since process cannot load the jdwp agent.
01-06 13:36:42.111  1952  2046 E SQLiteLog: (284) automatic index on C(anime_id)
01-06 13:36:42.111  1952  2046 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
01-06 13:36:42.410  1952  2025 E LB      : fail to open file: Permission denied
App version: 0.12.3.6 (standard, 67c506d, 72, 2022-01-06T02:47Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweetin
Device model: M2101K6I
Device product name: sweetinpro

### Aniyomi version

0.12.4.6

### Android version

11

### Device

Redmi note 10 pro max

### Other details

Please take some measure on this issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by dm699** [comment]
For me the episode plays in external player(I use mpv)

**Comment by TypicalCode1** [comment]
> For me the episode plays in external player(I use mpv)

How do you even access the external player?

**Comment by Skmustaq12** [comment]
The episode is playing at external play stop

**Comment by Skmustaq12** [comment]
> > For me the episode plays in external player(I use mpv)
> 
> How do you even access the external player?

You have to go to settings then player then turn on the external player

**Comment by TypicalCode1** [comment]
> > > For me the episode plays in external player(I use mpv)
> > 
> > 
> > How do you even access the external player?
> 
> You have to go to settings then player then turn on the external player

Oh ok, thank you.

**Comment by TypicalCode1** [comment]
> > > For me the episode plays in external player(I use mpv)
> > 
> > 
> > How do you even access the external player?
> 
> You have to go to settings then player then turn on the external player

I have another problem, none of my external players seem to work even though I turned the setting on. I have MPV and VlC

**Comment by Skmustaq12** [comment]
Some episode can't playable by any player so you have to watch it by the
web
We need a update about this problem be the developer
So if their is any developer please work on this player episode

**Comment by twintailer** [comment]
Same for me even when i use external player it says "couldnt find any video links"

**Comment by MechaStreisand91** [comment]
I have this issue too. It was working fine on VLC this morning and now suddenly I get The Location "address" cannot be played. Doesn't work on amy other external apps and if I download it the aniyomi app crashes

**Comment by Quickdesh** [comment]
This has been fixed/added in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"
