### ISSUE TITLE
Fullscreen potrait mode

### ISSUE THREAD

**Issue by Herzheys** [aniyomiorg/aniyomi#322]
### Describe your suggested feature

You can watch anime in landscape fullscreen i want watch anime with with my phone straight so can u please add potrait fullscreen in video player

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Added in mpv version wait for an update

**Comment by Quickdesh** [comment]
This has been fixed/added in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"
