### ISSUE TITLE
The latest version is not playing any anime extensions , or downloading.

### ISSUE THREAD

**Issue by anifanthefist** [aniyomiorg/aniyomi#324]
I had just recently downloaded this app on my phone, and was truly amazed at the potential that it had. I was able to download at least 84 episodes of my favorite anime. I started to see that the app was having problems playing new links. I also saw that my episodes that to around a minute to download we're now going to take 2 to 3 hours to download. I played around and uninstalled the app to see if that would fix it. The issue continued so I went to back on the web page to see what was up with the app. It turns out that the latest version had come out v0.12.3.6 had come out, and I installed it. The issue was even worse because now you can't stream anime or download them. I had been reading recent messages from others, and it appears to be the new version.

**Comment by Reigen441** [comment]
I have the same issue. None of the anime extensions are working. The manga ones are completely fine though.

**Comment by juliannotanerd** [comment]
This happens to me to, it says "couldn't find any video links"

**Comment by anifanthefist** [comment]
Ok. It's good to hear that I'm not the only one that has the problems with the app. I tried downloading the app on five different devices, and the same extension error for anime happens. I really hope that the app gets fixed so that I can continue watching Naruto shippuden. I tried using a vpn to change my location to Germany. But it turned out that the show was in German lol. With that being said, hopefully that app gets fixed.

**Comment by Reigen441** [comment]
Yeah so I downgraded to the previous version 0.12.3.5 and it's working perfectly. So this seems an issue with the new version only.

**Comment by anifanthefist** [comment]
See I tried to downgrade but when I press the install button the older version does install. It gives you the app not installed message.

**Comment by anifanthefist** [comment]
> Yeah so I downgraded to the previous version 0.12.3.5 and it's working perfectly. So this seems an issue with the new version only.

Where did you download the previous version from. The app or online.

**Comment by anifanthefist** [comment]
> Yeah so I downgraded to the previous version 0.12.3.5 and it's working perfectly. So this seems an issue with the new version only.

I managed to downgrade to the previous version and it is indeed working. Now I can continue with Naruto yea.

**Comment by Reigen441** [comment]
Sorry I went offline for a few hours. I had download the previous version from github itself and uninstalled the latest one before installing the 0.12.3.5 package. 

Glad it's working now. I'm convinced it's an issue with the new version. Hope the devs fix it.

**Comment by shshnk13** [comment]
> I had just recently downloaded this app on my phone, and was truly amazed at the potential that it had. I was able to download at least 84 episodes of my favorite anime. I started to see that the app was having problems playing new links. I also saw that my episodes that to around a minute to download we're now going to take 2 to 3 hours to download. I played around and uninstalled the app to see if that would fix it. The issue continued so I went to back on the web page to see what was up with the app. It turns out that the latest version had come out v0.12.3.6 had come out, and I installed it. The issue was even worse because now you can't stream anime or download them. I had been reading recent messages from others, and it appears to be the new version.

I'm facing the very same issue.

**Comment by shshnk13** [comment]
> 

I'm facing the very same issue.

**Comment by Kimarnic** [comment]
Happening to me in 2024 :(
