### ISSUE TITLE
video not playing after adding anime to the list

### ISSUE THREAD

**Issue by gluon007** [aniyomiorg/aniyomi#328]
### Steps to reproduce

1. I added the anime (demon slayer) from genoanime source 
2. after that I watched the 1 episode
3. next day when I played the video I is not playing and showing errors

### Expected behavior

the video should play by clicking it

### Actual behavior

it is showing error, sometimes link is not found and sometimes url

### Aniyomi version

0.12.3.6

### Android version

android 11

### Device

samsung galaxy m21 

### Other details

please tell me how to fix it

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [ ] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [ ] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [ ] I have updated all installed extensions.
- [ ] I will fill out all of the requested information in this form.

**Comment by mathmul** [comment]
`Browse > Anime extensions > Update all` worked for me.

**Comment by gluon007** [comment]
> `Browse > Anime extensions > Update all` worked for me.

yes it is working now
