### ISSUE TITLE
Remove manga aspects of the app and keep only anime sections 

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#33]
stuff like the library section at the bottom, manga section in updates tab, and manga extensions

**Comment by joseph619** [comment]
Agreed, most users would prefer if this app was anime only. Either removing all manga would be ideal, or an option to disable anything manga related.

**Comment by jmir1** [comment]
idk if "most users" is accurate, because i have gotten a lot of feedback that says they like having an "all in one app". but in the future i will add this.

**Comment by Memezaa** [comment]
> Agreed, most users would prefer if this app was anime only. Either removing all manga would be ideal, or an option to disable anything manga related.

This is not most users, this is your opinion. The app is fine how it is because finding an all in one app like this is practically impossible and convenient. I'd say add an option to remove the manga section if it bothers people that much

**Comment by Retro410** [comment]
> idk if "most users" is accurate, because i have gotten a lot of feedback that says they like having an "all in one app". but in the future i will add this.



> idk if "most users" is accurate, because i have gotten a lot of feedback that says they like having an "all in one app". but in the future i will add this.

I prefer All in one, That is the main reason i downloaded this app

**Comment by tom2411** [comment]
It only miss the light novel and it's an perfect app

**Comment by GabenRulez** [comment]
Agreed. App name is "Aniyomi", which suggests it's for the anime, not for manga/anime/light novels.

An all in one app wouldn't be a bad idea, but it certainly doesn't fit here.

**Comment by jmir1** [comment]
> Agreed. App name is "Aniyomi", which suggests it's for the anime, not for manga/anime/light novels.
> 
> An all in one app wouldn't be a bad idea, but it certainly doesn't fit here.

https://jisho.org/search/yomi

**Comment by ImRyley** [comment]
Maybe an option to hide the Manga icon from the nav bar would be enough.

**Comment by suhan-paradkar** [comment]
A toggle option to disable manga seems like a really good option... still waiting for it tho......

**Comment by Jacekun** [comment]
Tbh, I lost interest on Aniyomi. Feel free to either continue this or scrap the implementation entirely.
Sorry.

**Comment by jmir1** [comment]
😂

**Comment by Johnny5sword** [comment]
For those seeking an anime only version, there is:
#### [Animiru](https://github.com/Quickdesh/Animiru) (unofficial fork of Aniyomi)
