### ISSUE TITLE
Please include sources from here

### ISSUE THREAD

**Issue by suraj3486** [aniyomiorg/aniyomi#357]
### Describe your suggested feature

This app [Anime boya](https://github.com/Tu2l/AnimeBoya) uses some really good sources and is also free source. Please include some feature from it like
Its anime source
Llike the layout it put for any series with sources. And many more

### Other details

Before using aniyomi i was using seprate app for anime and manga.
So thank you for this wonderful app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
App was taken down
