### ISSUE TITLE
Stripped down anime only version

### ISSUE THREAD

**Issue by MF-Debug** [aniyomiorg/aniyomi#358]
### Describe your suggested feature

Is there any chance to get a version of the app which includes anime stuffs only? I don't read manga so it would be really good to have manga related stuffs stripped off from this version. In this way, the app will be more light-weighted to install & use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by YashG000** [comment]
No because this app is based on Tachiyomi, a manga reader app. So I don't see think dev will chnage whole code to just make it an anime only app.

**Comment by abdallahmehiz** [comment]
Aniyomi will probably never remove the manga features. If you want an Aniyomi version with only anime features, checkout [Animiru](https://github.com/quickdesh/animiru)
