### ISSUE TITLE
Forced stop

### ISSUE THREAD

**Issue by akbarsoft0** [aniyomiorg/aniyomi#359]
### Steps to reproduce

![Screenshot_20220122-202004](https://user-images.githubusercontent.com/57284714/150643664-9622aa12-c136-4738-8442-e6094799a71f.png)

### Expected behavior

Open by tapping.

### Actual behavior

Doesn't open.

### Aniyomi version

Letest

### Android version

Android 7

### Device

Gionee X1s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
Can you try to generate some crash logs for me?
Otherwise solving this issue is pretty much impossible.
Has the app ever worked for you or did this issue appear recently?

**Comment by Zerotwo-Chan002** [comment]
Uhmm hello i had same issue as him i also have android 7(vivo a83) and i already tried all various thing but it's always the same it's keep crashing

**Comment by Sr6376** [comment]
I don't know how to do it. If tell me how it can be done I will try.

https://user-images.githubusercontent.com/57284714/152709415-9cc6dcde-134c-42ce-9f15-3a7a37735550.mp4

**Comment by prorounak2005** [comment]
> Can you try to generate some crash logs for me? Otherwise solving this issue is pretty much impossible. Has the app ever worked for you or did this issue appear recently?

I am having the same issue with motorola gk40 and this problem still persists :( any clue?

**Comment by prorounak2005** [comment]
I am using android 7.11 and the app keeps stopping idk what to do :(
