### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by Tapabrata561** [aniyomiorg/aniyomi#360]
### Describe your suggested feature

It would be awesome if i would be able to cast anime to my smart tv using Chromecast. I would be very happy if it is added.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by tortendes** [comment]
#162 
Its already in there.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/78
