### ISSUE TITLE
Error Getting Link message

### ISSUE THREAD

**Issue by gmoney316** [aniyomiorg/aniyomi#366]
### Steps to reproduce

I load Aniyomi, click on a series and an episode, and I get a message saying "error getting links" (this mainly happens on the Animepahe server and GenoAnime server)

### Expected behavior

The episode should load and play

### Actual behavior

The episode will not load and I receive "error getting link" message

### Aniyomi version

Preview r4506 and Stable 0.12.3.6

### Android version

9

### Device

Galaxy Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jsom25** [comment]
I have this exact same issue. I'm guessing those extensions are broken for the meantime

**Comment by Hellokittymaster09** [comment]
I get the same problem but do we know how to fix it or what do we need to do ?

**Comment by glokta1** [comment]
The only temporary workaround known to me is this: https://github.com/jmir1/aniyomi/issues/166#issuecomment-920590545. Also, next time, please post issues related to the extensions in https://github.com/jmir1/aniyomi-extensions
