### ISSUE TITLE
Manga update 

### ISSUE THREAD

**Issue by jhasantosh1515** [aniyomiorg/aniyomi#367]
### Steps to reproduce

Make a manga library of more than 80 manga.
Go to update feature.
Update manga.

### Expected behavior

Only 15 to 17 manga is updated in notification like 5/17 however I have more than 80 manga.

### Actual behavior

Only 15 to 17 manga is updated in notification like 5/17 however I have more than 80 manga.

### Aniyomi version

0.12.3.6-4506

### Android version

Android 11

### Device

Vivo y12

### Other details

Taking screenshot is unavailable that's why no photo are attached.
But this issue started with latest version of this app released few days ago.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by glokta1** [comment]
Do you have a screenshot?
