### ISSUE TITLE
Dreamsub problems

### ISSUE THREAD

**Issue by ed0fl3da** [aniyomiorg/aniyomi#373]
### Steps to reproduce

Open dreamsub
Search an anime
Press play

### Expected behavior

Anime episode starts

### Actual behavior

Anime episode doesn't start

### Aniyomi version

Latest

### Android version

Latest

### Device

Redmi Note 10 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
