### ISSUE TITLE
Downloader Error

### ISSUE THREAD

**Issue by Razorior** [aniyomiorg/aniyomi#377]
### Steps to reproduce

Downloading a episode
1. Suppose I opened Attack on Titans (Shingeki no kyojin) in animepahe extension
2. I selected the episode i wanted to download
3. It's shows Downloader unexpected / HTTP ERROR 404

### Expected behavior

I wanted to download episodes of Attack on titans using Animepahe extension

### Actual behavior

A notification came from aniyomi downloader that "Could not able to download chapter due to unexpected error" And the next day it shows HTTP ERROR 404

### Crash logs

"Could not able to download chapter due to unexpected error" & "HTTP ERROR 404"

### Aniyomi version

aniyomi-arm64-v8a-r4506.apk

### Android version

Android 10

### Device

Poco M3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by YashG000** [comment]
whenever HTTP ERROR 404 comes, just refresh the anime page in Aniyomi (before downloading too).

but for now animepahe is broken.

**Comment by MechaStreisand91** [comment]
I downloaded episodes on gogoanime and whenever I try to watch it after downloading Aniyomi crashes.
