### ISSUE TITLE
Logging to MAL returns Error 400

### ISSUE THREAD

**Issue by lasersPew** [aniyomiorg/aniyomi#379]
### Steps to reproduce

1. Click More> Settings> Tracking> MyAnimeList.
2. Log onto MyAnimeList.

### Expected behavior

Should log in to MyAnimeList and return to the app afterwards with a check on MyAnimeList on the Tracking Services.

### Actual behavior

Returns Error 400 on the site.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by glokta1** [comment]
I tried it just now and it works perfectly for me. Not sure what's causing the issue

**Comment by raeespulikkal** [comment]
So I checked a lot and found out that if the name of the anime you are searching is too big or too small it shows this error. Just reduce the words in the anime to make it work properly.

**Comment by lasersPew** [comment]
> I tried it just now and it works perfectly for me. Not sure what's causing the issue

I used Firefox as browser to trigger this. It works normally on Chrome though.
