### ISSUE TITLE
Comment Section

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#380]
### Describe your suggested feature

The comment section should be added under the video in portrait mode, so when we would wanna go full screen we could double tap the video or add an option to go full screen. Basically a UI like YouTube. First if you click an episode it should start in portrait, and not automatically in full screen/landscape. The comment section would go under the video.
![IMG_20220204_164335](https://user-images.githubusercontent.com/97095824/152523502-9a0aa353-471e-4355-8631-27d5a169e6f5.jpg)
Basically a UI like this 👆🏻
The video would start in portrait like this..
. Add the comment section
. Add portrait mode

### Other details

The comment section would be from the extension..
Like if I am watching Anime in the Gogoanime extension, the comments would be from the Gogoanime website. So when someone would upload a comment from the aniyomi app, it would get uploaded in the gogoanime website aswell.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
not feasible
