### ISSUE TITLE
Can we get an ios version of this app

### ISSUE THREAD

**Issue by H3LLB0Y101** [aniyomiorg/aniyomi#384]
### Describe your suggested feature

ios version

### Other details

im considering switching to ios and i will really like to have this app on there too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Curstantine** [comment]
Ask paperback lol 😅
Jokes aside try [NineAnimator](https://github.com/SuperMarcus/NineAnimator)

**Comment by abdallahmehiz** [comment]
an ios version will probably never happen
