### ISSUE TITLE
Dramanice Extension not working!!

### ISSUE THREAD

**Issue by Retro410** [aniyomiorg/aniyomi#387]
### Steps to reproduce

1. Go to Dramanice and choose any drama.
2. Play any episode.

### Expected behavior

It should play episode normally like other extensions does.

### Actual behavior

so when i click any episode i get connection reset every time. 
![Screenshot_2022-02-09-03-19-49-41_dd604340c1d7941d42aee14dd16e00e8](https://user-images.githubusercontent.com/86734225/153098486-008ecb1d-593b-49b5-aac0-6945a884b932.jpg)

### Aniyomi version

0.12.3.6

### Android version

Android 11

### Device

Realme 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add extensions, make a Github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
