### ISSUE TITLE
Add drag and drop

### ISSUE THREAD

**Issue by Realppp** [aniyomiorg/aniyomi#388]
### Describe your suggested feature

Able to drag and drop anime titles similiar to the feature in tachiyomi sy and sort them accordingly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Feature was made defunct
