### ISSUE TITLE
Automatic highest quality playback

### ISSUE THREAD

**Issue by Sc0o0p** [aniyomiorg/aniyomi#408]
### Describe your suggested feature

Most of the time the default quality for an episode is the lowest. Adding this would change it so you won't need to change manually the quality everytime you watch a new episode.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ahmedgamal17** [comment]
in extensions setting there is prefered quality settings you can change

**Comment by Sc0o0p** [comment]
Yes, but sometimes your preferred quality isn't in the player, mostly because the video is down on that server.
