### ISSUE TITLE
Cannot open any episode of any anime

### ISSUE THREAD

**Issue by AbdullahYf** [aniyomiorg/aniyomi#411]
### Steps to reproduce

1. I open the app
2. Open the anime 
3. Select the episode no. which I want to watch

### Expected behavior

The epsiode should open in media player

### Actual behavior

Episode does not open and it shows this when I open
'The location https:// vidstreamingcdn.com/cdn36 /c751bab1939a2b83020565e1ac 242896/EP.1009.v0.1644114782 .1080p.mp4?mac-2m1W+XpCrl ///+EhN3vwo/ /WBhYxWRDODf036TnM82w =&vip=2405:201:5c11:a885 4d1c:774f:b66b:621a&expiry =1645477475049 cannot be played.'

### Crash logs

![Screenshot_2022-02-22-00-38-38-631_xyz jmir tachiyomi mi debug](https://user-images.githubusercontent.com/100160729/155014885-6bb3cd3b-8243-4f2a-a029-45105ad03178.jpg)

### Aniyomi version

0.12.3.6-4507

### Android version

Android 10

### Device

Redmi 9 Power

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Chanishyt** [comment]
Please fix this issue because i am currently facing the same problem with me
