### ISSUE TITLE
Downloaded videos can't play with external player

### ISSUE THREAD

**Issue by Lokey478** [aniyomiorg/aniyomi#427]
### Steps to reproduce

1. Downloaded anime
2. Go to watch Anime with external player
3. App crashes

### Expected behavior

Anime should have played

### Actual behavior

The app crashes

### Aniyomi version

0.12. 3.6

### Android version

Android 11

### Device

Oppo reno 3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Pervases** [comment]
I can confirm this.

Version: 0.12.3.6
Android 11
RedMagic 6S Pro

The external player crashes as soon as you tap on the video within Aniyomi.

**Comment by gbf-dtb** [comment]
This is a problem with scoped storage and permissions, just go to Options and choose a custom directory instead of the default one, and you can choose the same folder as the default one (the action of choosing a custom folder is just to give the app permissions) and it'll work fine.

**Comment by juniornff** [comment]
> This is a problem with scoped storage and permissions, just go to Options and choose a custom directory instead of the default one, and you can choose the same folder as the default one (the action of choosing a custom folder is just to give the app permissions) and it'll work fine.

I tried and it worked. Thank you.

But I think it is something that should be indicated to the user when choosing an external player in the app

**Comment by tatacaw13** [comment]
@gbf-dtb it worked. THANK YOU!!

**Comment by tatacaw13** [comment]
@gbf-dtb THANK YOU!!
