### ISSUE TITLE
Extensions not working with Cellular Data

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#429]
### Steps to reproduce

Hey Everyone !!! I have Got an Issue in The 9anime and AnimeKisa Extensions. It is Just that The Videos won't Play with Cellular Data but Only with WiFi in these Two Extensions. 

### Expected behavior

Videos must be Played with Cellular Data too as They are Played with WiFi Connection in These Extensions (9anime and Animekisa).

### Actual behavior

Instead, it Shows Me "404 error code" like Something in A Prompt.

### Aniyomi version

0.12.3.6

### Android version

11

### Device

Oppo A55

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raeespulikkal** [comment]
I hav doubts but I t probably might be due to restrictions of the isp. Have you tried vpns?

**Comment by Anime-ika** [comment]
I am having the same issue with every extension. Videos won't play if I'm using my cellular data.

**Comment by Quickdesh** [comment]
This depends on your isp
