### ISSUE TITLE
Can't download any Anime Extensions

### ISSUE THREAD

**Issue by jakuqar** [aniyomiorg/aniyomi#449]
### Steps to reproduce

When I tap on install, it just says "pending".
Tried downloading every extension, but every single one of them just said "pending".

![Screenshot](https://user-images.githubusercontent.com/61877280/159184543-58cbf5aa-cb16-436c-a1f1-1eb194e6947c.png)

I'm running Android 12

### Expected behavior

Downloaded extensions

### Actual behavior

Extensions didn't download

### Aniyomi version

0.12.3.6

### Android version

Android 12

### Device

Xiaomi Mi 10T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by pokurt** [comment]
issue is with your downloads app if you are using a skinned android. uninstall updates of downloads app and clear data of it. it happened to me on miui

**Comment by Pervases** [comment]
Happened to me. Just install and reinstall app.

Tip: when installing Extensions DO NOT change screen. Stay on the Extensions page and wait for the Install dialog. Otherwise you won't see the dialog and the Extension will not be installed.

**Comment by spidy2356** [comment]
> issue is with your downloads app if you are using a skinned android. uninstall updates of downloads app and clear data of it. it happened to me on miui

Thanks bro...your tips help me to solve out the problem in miui😊😊

**Comment by luysgames18-coder** [comment]
I'm with the same problem! have you found a solution?
