### ISSUE TITLE
[Feature Request] Mark as seen popup on closing internal player

### ISSUE THREAD

**Issue by LordFoogThe4rd** [aniyomiorg/aniyomi#457]
### Describe your suggested feature

When you have watched past a chosen point in the episode, pressing the back button should show a popup and ask if you'd like to mark the episode as seen. Press yes to mark the episode as seen and no to save progress

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
i don't see the use case.
It seems more like a bloat feature
