### ISSUE TITLE
[Feature Request] Percentage Tracking on External Player

### ISSUE THREAD

**Issue by SecretiveBastard** [aniyomiorg/aniyomi#47]
## Why/User Benefit/User Problem
This can benefit the users (who most likely download) episodes they are watching and use external player to play video on their favorite media player (which they could even use to cast onto bigger screen, etc...). It is restricted to the video being played up to the last part until it registers to the trackers unlike on internal player so having the same functionality to work on both would be a huge help.

## What/Requirements
Nothing different except that it can track on the desired percentage (as configured in the settings).

**Comment by krispykiq** [comment]
In the most recent version, percentage tracking for external players only works for VLC. I've tested mpv-android, MX Player, KMPlayer, XPlayer, UPlayer and Mi Video, all of them don't work. I hope this gets improved.

**Comment by juniornff** [comment]
> In the most recent version, percentage tracking for external players only works for VLC. I've tested mpv-android, MX Player, KMPlayer, XPlayer, UPlayer and Mi Video, all of them don't work. I hope this gets improved.

That depends of the player and the information that can send after closing a video. VLC works because it send that information to the app

**Comment by Quickdesh** [comment]
Its as Juniorn said, it depends on whether the app send the information back to aniyomi or not
