### ISSUE TITLE
Blue appearance

### ISSUE THREAD

**Issue by 123ErenYeaguh** [aniyomiorg/aniyomi#470]
### Describe your suggested feature

I want to suggest to add an additional appearance with a dark blue accent theme .

### Other details

It was available in r42587 or something of that sort .
![W2JooJ7](https://user-images.githubusercontent.com/98630477/160405438-b03ed8c3-f3a8-4fc8-8282-35bb57ee2392.jpg)
 
Is the desired color I want

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
not enough details
