### ISSUE TITLE
Expand List Functionality ( Two way syncing)

### ISSUE THREAD

**Issue by kpowers1028** [aniyomiorg/aniyomi#501]
### Describe your suggested feature

 I wanna say I have been enjoying the app very much, and thank very much for your efforts in creating and maintaining it. Like any app improvements can always be made when possible. As it stands I have to search and ad my MAL list one by one and I’m sure this may have come up before and honestly this is my first time doing this so please forgive my ignorance. There are other apps where you can either import your MAL list or even better use your credentials to sign into MAL and bingo list is there. You are then free to update it how you see fit. Obviously connecting directly to MAL is more seamless.  So I guess I’m suggesting, since your already part way there why not close the deal so to speak and make it so it’s two way syncing with list import capabilities. Of course if that is even possible. Once again I don’t know how realistic this is, but one can dream. Ha! I also hope I was able to convey what I’m hoping to have happen. I thank you for your time and consideration, be well and stay safe.

### Other details

Obviously this would apply to any of the lists really, I just started off with MAL.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Jjjggh** [comment]
I think it will be very helpful

**Comment by kpowers1028** [comment]
Dunno if this is possible but what integrating MAL Sync extension?

https://github.com/MALSync/MALSync

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/381
