### ISSUE TITLE
Download All Episodes in One Folder

### ISSUE THREAD

**Issue by Pervases** [aniyomiorg/aniyomi#521]
### Describe your suggested feature

Currently, downloading anime will save each episodes in different directories, making playing with external Video Players extremely problematic as it will not play them successively. Could you please make an option to save all episodes under one directory per Anime? Or make it do this by default?

### Other details

![Screenshot_2022-04-15-12-29-02-370](https://user-images.githubusercontent.com/103200096/163518639-c0c41fa3-c45c-4b03-bbdd-c69c5e3632ed.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by juniornff** [comment]
You can use a external player as default in the app. There is a problem with that but can be fix easily with this comment [Here](https://github.com/jmir1/aniyomi/issues/427#issuecomment-1207860980) so you can use external player in the app (I recommend VLC)

**Comment by warior456** [comment]
fr we need this to be the case (or at least group them)

**Comment by SandeepKarukayil** [comment]
totally agree

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/188
