### ISSUE TITLE
Category only filter

### ISSUE THREAD

**Issue by Lukyzzz** [aniyomiorg/aniyomi#525]
### Describe your suggested feature

Simple, if possible, I would like the filter option to be category only, just like the "Sort" option is

### Other details

Like Category 1 get the filter "Unseen" only and Category 2 get the filter "completed" only

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/87
Would follow a similar idea to this
