### ISSUE TITLE
"Clean" option on Update tab or filters applying for titles already on the library

### ISSUE THREAD

**Issue by Lukyzzz** [aniyomiorg/aniyomi#526]
### Describe your suggested feature

Simple, if possible I would like to just add a opinion to "Clean" the tab, resetting and removing all chapters/episodes from the update tab

Or the filters from the option "Library > Global update > Anime/Manga categories " to apply for the titles already on the library, like if I excluded one category from the Global update, next time I update, it would remove the titles on that category from the update tab

### Other details

I have a lot of titles on my library so even after excluding the categories it shows up on the "update" tab, it stay there anyway, I wanna use that tab but it's 999+ with all the manga and animes on my Plan to Watch/Read category

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ikecudd** [comment]
I Love this idea! Same problem happens to me. there's so much titles in my update tab ;-;

**Comment by Quickdesh** [comment]
This has been fixed/added in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"
