### ISSUE TITLE
Reading mode category only

### ISSUE THREAD

**Issue by Lukyzzz** [aniyomiorg/aniyomi#527]
### Describe your suggested feature

Simple, if possible, I would like the "reading mode" option to be category only, just like the "Sort" option is

### Other details

Like Category 1 get the reading mode "Webtoon" and Category 2 get the reading mode "manga"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
would not be a feasible feature to add
