### ISSUE TITLE
Animes series in order

### ISSUE THREAD

**Issue by Spikebinger99** [aniyomiorg/aniyomi#531]
### Describe your suggested feature

Like put animes OVAs and movies and put all them inorder.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by elvistony** [comment]
If you mean ordering them based on release date, that might be challenging, as many sources don't provide a year of release.

**Comment by Spikebinger99** [comment]
> If you mean ordering them based on release date, that might be challenging, as many sources don't provide a year of release.

Yes something like that or like bakemonogatari series putting them in an actual order or something ya know I mean?

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/127
