### ISSUE TITLE
It can't download anime in SD Card

### ISSUE THREAD

**Issue by DizGuy13** [aniyomiorg/aniyomi#534]
### Steps to reproduce

1. I set up my download location to internal storage after that i tried to download anime and manga it works perfectly
2. I change my download location to SD Card after that i tried to download some anime and manga but only the manga works perfectly fine
3. The issue is all the anime that i tried to download only comes out error i tried and tried it again i still can't download it only says error 

### Expected behavior

All i want is that i can download any anime and manga in sd card that works perfectly fine

### Actual behavior

The issue is all the anime that i tried to download only comes out error i tried and tried it again i still can't download it only says error 

### Crash logs

--------- beginning of crash
04-16 11:08:35.898  2133  2133 E AndroidRuntime: FATAL EXCEPTION: main
04-16 11:08:35.898  2133  2133 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 2133
04-16 11:08:35.898  2133  2133 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.anime.track.SetTrackStatusDialog$$ExternalSyntheticLambda0.onClick(Unknown Source:8)
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:264)
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7663)
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-16 11:08:35.898  2133  2133 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: FATAL EXCEPTION: main
04-17 04:08:50.815 20274 20274 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 20274
04-17 04:08:50.815 20274 20274 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.anime.track.SetTrackStatusDialog$$ExternalSyntheticLambda0.onClick(Unknown Source:8)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:264)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7663)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-17 04:08:50.815 20274 20274 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
--------- beginning of main
04-18 01:03:33.044 27406 27406 E ir.tachiyomi.m: Not starting debugger since process cannot load the jdwp agent.
04-18 01:03:34.955 27406 27482 E SQLiteLog: (284) automatic index on C(anime_id)
04-18 01:03:34.955 27406 27482 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
--------- beginning of system
04-18 01:03:37.413 27406 27488 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.413 27406 27503 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.413 27406 27490 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.413 27406 27504 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.413 27406 27489 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.413 27406 27506 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.438 27406 27504 E ion     : ioctl c0044901 failed with code -1: Invalid argument
04-18 01:03:37.447 27406 27505 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.447 27406 27509 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.468 27406 27508 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.486 27406 27506 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.487 27406 27490 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.488 27406 27508 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.488 27406 27505 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.489 27406 27504 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.502 27406 27518 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.504 27406 27488 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.504 27406 27511 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.505 27406 27513 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.505 27406 27512 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.505 27406 27509 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.505 27406 27489 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.506 27406 27490 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.510 27406 27507 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.511 27406 27503 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.512 27406 27510 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.514 27406 27506 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.514 27406 27515 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.523 27406 27508 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.526 27406 27505 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:03:37.554 27406 27519 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
04-18 01:04:24.414 27406 27497 E DatabaseUtils: Writing exception to parcel
04-18 01:04:24.414 27406 27497 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://xyz.jmir.tachiyomi.mi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=27740, uid=1000 requires the provider be exported, or grantUriPermission()
04-18 01:04:24.414 27406 27497 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
04-18 01:04:24.414 27406 27497 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
04-18 01:04:24.414 27406 27497 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
04-18 01:04:24.414 27406 27497 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
04-18 01:04:24.414 27406 27497 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1038)
04-18 01:04:24.414 27406 27497 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:997)
App version: 0.12.3.6 (standard, 67c506d, 72, 2022-01-06T02:47Z)
Android version: 10 (SDK 29)
Android build ID: KE6j-H6215GH-Q-GL-220215V289
Device brand: TECNO
Device manufacturer: TECNO MOBILE LIMITED
Device name: TECNO-KE6j
Device model: TECNO KE6j
Device product name: KE6j-GL

### Aniyomi version

0.12.3.6

### Android version

Android 10

### Device

Tecno Spark 6 Air

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Feature has been added in the beta, wait for update to stable
