### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by Cinnaberyl** [aniyomiorg/aniyomi#538]
### Steps to reproduce

Click on an Anime from any source. 
Click the Download button next to anime episode, or from the top.

### Expected behavior

When i click download, the episode(s) should download to my device easily. 

### Actual behavior

When i click download, it shows it as downloading for a second, and then a red exclamation appears. It does this for the following episodes if i download multiple at once. If i try again, the same issue occurs. I have uninstalled and reinstalled, tried the preview version, but nothing works. 

### Aniyomi version

0.12.3.6

### Android version

Android 11

### Device

Moto G Stylus 5G

### Other details

I had a friend try this and it worked find for them. Not sure what the issue is, or if its my device. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Jayrudra** [comment]
Me to did you find a solution
