### ISSUE TITLE
Failed to download episodes from gogoanime

### ISSUE THREAD

**Issue by lasersPew** [aniyomiorg/aniyomi#584]
### Steps to reproduce

1. Select a random series from gogoanime.
2. Click the download button beside a random episode 
3. Wait

### Expected behavior

Should download that episode

### Actual behavior

The download will fail and the notification will have the subtext of Download Completed.

### Crash logs

--------- beginning of system
05-15 21:08:19.837 19406 19406 E ActivityThread: Failed to find provider info for downloads
05-15 21:08:45.336 19406 19406 E ActivityThread: Failed to find provider info for downloads
--------- beginning of main
App version: 0.12.3.6 (standard, 67c506d, 72, 2022-01-06T02:47Z)
Android version: 7.1.2 (SDK 25)
Android build ID: N2G47H
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: rolex
Device model: Redmi 4A
Device product name: rolex

### Aniyomi version

0.12.3.6

### Android version

Android 7

### Device

Xiaomi Redmi 4a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BruhNye** [comment]
same problem here

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
