### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by Marsavis5** [aniyomiorg/aniyomi#595]
### Describe your suggested feature

There are subtitles available in the website it just isn't there with the player. Please add this feature

### Other details

Already different resolutions are available. Just add subtitles option too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by osamahg** [comment]
It would be great

**Comment by abdallahmehiz** [comment]
This feature is available in [Aniyomi Preview].
