### ISSUE TITLE
Notification bar gets stuck

### ISSUE THREAD

**Issue by Elixir76** [aniyomiorg/aniyomi#608]
## Device information
* Aniyomi version: 0.12.3.6
* Android version: 8.1.0
* Device: Samsung Galaxy Tab A6 (10.1)

## Steps to reproduce
Click settings during playing a video or go to recent apps/other spp then back to video

## Issue/Request
notification bar appears and gets stuck on top of screen, only fix is to go back to episode list and open episode again

## Other details
Might be worth noting that the device has hardware buttons (back, home and recents apps) instead of the usual software buttons

![Screenshot_20220601-053535_Aniyomi](https://user-images.githubusercontent.com/63611149/171323435-3af08205-0f23-4a55-88ba-14f85ac25f5e.jpg)

**Comment by Likver** [comment]
Yeah, same problem here.
I have an Xperia L3 with Android 8.1
And the version its the same (0.12.3.6)

**Comment by Quickdesh** [comment]
Already been fixed in the beta. Wait for an update to stable
