### ISSUE TITLE
Add a toggle option to disable completely the manga section

### ISSUE THREAD

**Issue by Palloxin** [aniyomiorg/aniyomi#613]
### Describe your suggested feature

toggle option to disable completely the manga section on aniyomi leaving only video/anime related content.

### Other details

I use mainly a fork of tachiyomi together with aniyomi and i don't need a manga section on aniyomi at all:manga extensions, manga migrate, manga sources, manga settings just take space. Also, without the manga section the app should re-place the History button in the middle of the main screen like tachiyomi (see the image at tge bottom) i just want a clean aniyomi just to watch anime.
I am aware of a fork of aniyomi with only anime but i don't want to change between forks if possible and follow the main fork. You could take that fork as a reference and implement it in aniyomi.

![IMG_20220616_130209](https://user-images.githubusercontent.com/75091899/174056602-83e22994-8905-4bdf-a8b5-b4887d030202.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
there is already a setting to replace the bottom manga tab with the history.
the other stuff is possible, too, i guess.

**Comment by katagirii** [comment]
> there is already a setting to replace the bottom manga tab with the history.
> the other stuff is possible, too, i guess.

Could You tell the Steps to Replace the Manga Tab with History Tab ? I am Unable to Find that Option.

**Comment by jmir1** [comment]
This feature is only available in the beta version right now.
The setting is in general > bottom navigation style

**Comment by katagirii** [comment]
> This feature is only available in the beta version right now.
> The setting is in general > bottom navigation style

Hope it will be provided in the Stable Version Soon. Thanks for Providing such an Amazing App.

**Comment by Blackklegend** [comment]
> This feature is only available in the beta version right now.
> The setting is in general > bottom navigation style

Hmmm, I can't seem to find that option, was it removed? I'm on App version: 0.12.3.8-4515 (standard, d62c6a17c, 72, 2022-08-25T23:28Z) A11

**Comment by jmir1** [comment]
> > This feature is only available in the beta version right now.
> > The setting is in general > bottom navigation style
> 
> Hmmm, I can't seem to find that option, was it removed? I'm on App version: 0.12.3.8-4515 (standard, d62c6a17c, 72, 2022-08-25T23:28Z) A11

Like the comment said, you need the beta version and 0.12.3.8 is not the beta version.

You can get it from here: https://github.com/jmir1/aniyomi-mpv-beta/releases/latest

**Comment by Illythia** [comment]
I can't find this feature anymore since the new update

**Comment by Quickdesh** [comment]
> I can't find this feature anymore since the new update

https://github.com/aniyomiorg/aniyomi/issues/1247
