### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by ChinmayChadha** [aniyomiorg/aniyomi#615]
### Steps to reproduce

Not able to download any anime or movie 

### Expected behavior

Download should start 

### Actual behavior

Download starts and stick to 0 Percent 

### Aniyomi version

0.12.3.6

### Android version

Android 11

### Device

Phone Vivo v15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arun912-ux** [comment]
I'm facing the same issue.. Videos are downloading when download location is Internal storage but fails when storage is set to external sd card.
