### ISSUE TITLE
Error "Element class kotlinx.serialization.json.JsonNull 

### ISSUE THREAD

**Issue by A-1K** [aniyomiorg/aniyomi#632]
### Steps to reproduce

1. Add One Piece through 9anime
2. View episodes 992-994 
3. Shows the error in title

### Expected behavior

The episodes before and after this work normally but getting the error on 992,993,994 specifically. When I view the episodes through webview, they work fine.

### Actual behavior
After pressing on the episode, the viewer closes and shows the error
Element class kotlinx.serialization.json.JsonNull JsonNull is not a JsonObject

![image](https://user-images.githubusercontent.com/15345426/176440451-5e53c8a9-aa9c-4569-b7c9-88be88d15694.png)

### Aniyomi version

0.12.3.6

### Android version

Android 12

### Device

Samsung A71

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
