### ISSUE TITLE
How to fix needs authorization 

### ISSUE THREAD

**Issue by mustafa895** [aniyomiorg/aniyomi#636]
https://github.com/jmir1/aniyomi/releases/download/v0.12.3.6/aniyomi-arm64-v8a-v0.12.3.6.apk

**Comment by Dynamicflare99** [comment]
> Let me know If you found any solution

Bro there is solution

**Comment by Dynamicflare99** [comment]
I'm the guy named mustafa

**Comment by Divejang** [comment]
Any solution for this?

**Comment by Dynamicflare99** [comment]
> Any solution for this?

Yeah kinda solution

**Comment by flawrrz** [comment]
So what's the solution?

**Comment by Quickdesh** [comment]
The solution is to use another browser, also shouldn't happen with new updates
