### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by kunal1234523** [aniyomiorg/aniyomi#637]
### Describe your suggested feature

Could you create a Aniyomi desktop app, or a web application or anything which will work on my Linux Desktop.
I tried the tachiyomi webui - tachidesk , but it doesn't have anime extensions.
So is it possible to create a aniyomi webui?

Other things to mentions in android app:
1. Subtitles options not available in the internal player, even though the CC is available on respective extensions's website. Well, you can also copy the a feature from mxplayer, that is online subtitle, it searches the subtitle in opensubtitle.org

2. You have to go in setting to change the player from internal to external. If you could do it in a better way.
3. Some manga extension has very low download speed. like e-h*ntai

Thank you developer(s) for this fantastic app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
* If you want to use Aniyomi on a desktop, either emulate android on your PC and use Aniyomi in that or dual boot with Android-x86, I will suggest dual booting fydeOS for Android.
Otherwise no other way.
* Extensions will get updated to display subtitles too but first Aniyomi has to release its MPV version update.
>You have to go into the setting to change the player from internal to external. If you could do it in a better way.
* If you have a better way in mind feel free to share it and if it's good and doable then maybe you will see it implemented in the app
* And no one can do anything about the extension speeds except that website itself

**Comment by osamahg** [comment]
> 

What is mpv version and when it will come

**Comment by 12ohit** [comment]
> What is mpv version and when it will come

Aniyomi will have a new internal player based on MPV-android, no one can give you ETA when it will come but I can assure you we are close to getting an update now.

**Comment by WindowsRefundDay** [comment]
> * If you want to use Aniyomi on a desktop, either emulate android on your PC and use Aniyomi in that or dual boot with Android-x86, I will suggest dual booting fydeOS for Android.
>   Otherwise no other way.
Also you can try the Chrome Archon Custom Runti for windows but not 100% sure if it will work.

**Comment by Adamekka** [comment]
If you want to watch anime on a desktop, then try ani-cli, it works on Linux, Win and macOS, but you'll need to use it in the command line, it doesn't have a GUI

**Comment by kunal1234523** [comment]
> If you want to watch anime on a desktop, then try ani-cli, it works on Linux, Win and macOS, but you'll need to use it in the command line, it doesn't have a GUI

Thanks, it worked.

**Comment by Quickdesh** [comment]
#717
