### ISSUE TITLE
Crash when changing brightness before episode time & title is loaded to player

### ISSUE THREAD

**Issue by Samfun75** [aniyomiorg/aniyomi#646]
### Steps to reproduce

1. Play any episode
2. Before episode time and title is loaded to player keep changing brightness until playback starts
3. When playback starts the player UI crashes and the video plays in the background or sometime the whole app crashes

### Expected behavior

The app shouldn't crash if brightness is being adjusted when playback starts 

### Actual behavior

The player UI crashes and the video plays in the background or sometime the whole app crashes

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/jmir1/aniyomi/files/9054278/aniyomi_crash_logs.txt)

### Aniyomi version

Preview r5143

### Android version

Android 11

### Device

Samsung A21s

### Other details

The app is built from a fork of aniyomi-mpv-beta

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Fixed
