### ISSUE TITLE
Player Visual Enhancement

### ISSUE THREAD

**Issue by lasersPew** [aniyomiorg/aniyomi#649]
### Describe your suggested feature

To make the Video Player look good, I suggest to copy the layout from netflix's player or LagraDost/CloudStream-3.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Swadhin05** [comment]
You can try using Aniyomi MPV Beta. It has a better video player UI

**Comment by WindowsRefundDay** [comment]
how can I get it?

**Comment by Samfun75** [comment]
> how can I get it?

https://github.com/jmir1/aniyomi-mpv-beta/releases
