### ISSUE TITLE
1 bug(on emulator pc) 1 feature request

### ISSUE THREAD

**Issue by FlowDownTheRiver** [aniyomiorg/aniyomi#663]
### Steps to reproduce

Hi there
I installed aniyomi on my phone and it is working great.But I wanted to try it on pc.So I installed mumu player(android emulator) 32 bit(64 bit didn't work on my pc even though I have 64 bit os cos of my cpu is old) . I installed aniyomi x86 [v0.12.3.7] and I also tried  [v0.12.3.6] versions.Installation went smooth.The app works.

### Expected behavior

I was expecting the app works like on arm version but it didn't happen.

### Actual behavior

Unfortunately both anime and manga extensions when I try to install on the emulator says "pending" and after "reload". They don't install. I went into the settings and checked the advanced settings and tried all 3 installers.legacy,default and the one that requires root access.Downloaded that installer and set the emulator to rooted mode,still extensions doesn't install and stays in the "reload" state. I tried vpn as well just in case even though on my phone from the same network without vpn works but still nothing.

### Crash logs

I don't have any crash logs.

### Aniyomi version

0.12.3.7 and 0.12.3.6

### Android version

For mumu player ,I guess it is android 9,and for my phone it is android 9

### Device

mumu player and huawei mate 9

### Other details

For the feature request is it possible for you to add Turkish Language for the extensions? Tachiyomi offers Turkish extensions but aniyomi doesn't. I really would appreciate if you can add this feature. I don't have any problems on my phone, but emulator on pc has a problem installing extensions.I am on windows 10 as a side note.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [ ] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form. 

Edit - Update : I went to here : https://aniyomi.jmir.xyz/extensions/ and downloaded,installed extensions manually which worked but installer options in the app didn't work.
Note : I didn't open the issue in the extensions repo because it is installation problem,not the extensions themselves.

**Comment by Quickdesh** [comment]
Should work in new version
