### ISSUE TITLE
Add Manganato in Tracking

### ISSUE THREAD

**Issue by rednecksea** [aniyomiorg/aniyomi#664]
### Describe your suggested feature

Manganato has this bookmark feature to save your manga and the progress. I'm hoping that this app would be able to do so as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by WindowsRefundDay** [comment]
shouldn't this be an tachiyomi problem?
