### ISSUE TITLE
Fire TV Stick remote doesn't pause a video playing in Aniyomi

### ISSUE THREAD

**Issue by WindowsRefundDay** [aniyomiorg/aniyomi#665]
### Steps to reproduce

1. Go to any anime in aniyomi
2. Play it
3. Press the pause button

### Expected behavior

It should pause the video

### Actual behavior

Aniyomi ignores it and proceeds with the video.

### Aniyomi version

0.12.3.7

### Android version

FireOS 8 aka Android 11 with API level 30

### Device

Fire TV Stick 4K Max (2022)

### Other details

There are two workarounds to this:
1. Press the home button and open the app back up again without actually closing it. (Although when you are at the home menu, the video will continue playing for about 3-4 seconds)
2. Press the back button. (This will take you back to the anime page where you have to go back to the episode and when it's loading the little purple bar with the controls will show up and then navigate to the pause icon and click it)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by WindowsRefundDay** [comment]
This takes affect on Aniyomi-MPV too.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/162
