### ISSUE TITLE
Failed to bypass  cloudflare 

### ISSUE THREAD

**Issue by Ay-rakib** [aniyomiorg/aniyomi#673]
### Steps to reproduce

Example -
1.open  the apk 
2. Click an anime source (exp- 9anime)
3. Choose  an anime
4. Click any  episode 
5. Episode loading . After some time it shows failed to bypass cloudflare

### Expected behavior

Vedio should be played as expected 

### Actual behavior

I am  Trying to play the vedio  from different  source.  1 st i tried  to play  epi on 9anime, after  taking  some loading  it shows failed  to bypass  cloudflare.then i tried to I am  Try ing to play the vedio  from different  source.  1 st i tried  to play  epi on 9anime, after  taking  some loading  it shows failed  to bypass  cloudflare.  Then i tried  on different  anime source but result is the same!

### Aniyomi version

aniyomi-armeabi-v7a-v0.12.3.7.apk

### Android version

7.0

### Device

Walton smart tv.  model-WE4DH32BY220

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Adamekka** [comment]
Try Animixplay, it works for me

**Comment by DEVIL0325** [comment]
Animixplay is also no working.It is showing error

**Comment by Adamekka** [comment]
Show me the error

**Comment by DEVIL0325** [comment]
the error is some anime are not streaming.

**Comment by Adamekka** [comment]
Try installing all extensions and try all extensions until one works for you

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
