### ISSUE TITLE
[🧸ET] Standardize video quality options

### ISSUE THREAD

**Issue by nasib-mohammad-cs** [aniyomiorg/aniyomi#674]
### Describe your suggested feature

We currently have a working functionality to set the video quality of our need for each videos. 
But when anyone comes back to the player it seem that it's been reset to the default. 
I am wondering if  the player remain persistent on the video quality one has set earlier instead of being reset to default would make more sense. 
We have two options here. One, we can keep the users new action for all over the app ( for any anime, But they are not same sources). Or we can keep the new action value for the particular anime one is watching by keeping the default settings to other. 
I don't know if that sounds good or I'm just being myself. Either way thanks for reading. 

### Other details

![Screenshot_20220720-113337](https://user-images.githubusercontent.com/87854710/179906065-64ef83d9-9be2-409e-a6b9-e2d208bed2bd.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by aswinnnn** [comment]
commenting on this, aniyomi desperately needs a **"automatic (persistent) quality select"** option.
Since every source is different (i reckon from how each stream is worded) I figure simple regex for "360","1080","720" might make it easy for the devs. The profiling thing mentioned by you is real, and I think its nicer for it to be globally persistent since its easy to do so and I do not see why someone would change the quality between sources.

**Comment by Secozzi** [comment]
The majority of extensions have a setting to set preferred video quality, and some also have preferred video server + more. You can access it from `Browse -> Anime extension -> scroll to the extension and click "settings" -> click the gear for the language you want to change`

**Comment by aswinnnn** [comment]
That is honestly cool and didnt know it was possible, thanks.
