### ISSUE TITLE
Otakudesu not working

### ISSUE THREAD

**Issue by FathiRaihan** [aniyomiorg/aniyomi#677]
### Steps to reproduce

1. Open otakudesu extension
2. Select the title you want to play
3. After that wait a while and the title will not be able to play. Almost all titles are like this 
![Uploading Screenshot_2022-07-21-16-58-28-301_xyz.jmir.tachiyomi.mi.jpg…]()

### Expected behavior

Normal as usual 
![Screenshot_2022-07-21-16-57-21-854_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/107458534/180186914-ef9fbe6d-0968-42f6-aa2f-174c06b8bd15.jpg)
![Uploading Screenshot_2022-07-21-16-57-59-921_xyz.jmir.tachiyomi.mi.jpg…]()

### Actual behavior

In fact this is what happened 
![Screenshot_2022-07-21-16-57-21-854_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/107458534/180187106-1e96cf24-2d2b-4668-80a7-7633fd991c89.jpg)

### Crash logs

--------- beginning of system
--------- beginning of main
07-21 17:00:07.056 32358 32358 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
07-21 17:00:07.079 32358 32358 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
07-21 17:00:07.081 32358 32358 E libc    : Access denied finding property "ro.vendor.pref_scale_resolution"
07-21 17:00:07.159 32358 32358 E ir.tachiyomi.m: Invalid ID 0x00000000.
07-21 17:00:07.161 32358 32358 E ir.tachiyomi.m: Invalid ID 0x00000000.
App version: 0.12.3.7 (standard, 24c1ba6, 72, 2022-07-09T09:48Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.011
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: merlin
Device model: M2003J15SC
Device product name: merlin_id

### Aniyomi version

Aniyomi 0.12.3.7

### Android version

Android 11

### Device

Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
