### ISSUE TITLE
Can't watch Anime, can't find the error anywhere else either

### ISSUE THREAD

**Issue by BaakaFate** [aniyomiorg/aniyomi#678]
### Steps to reproduce

Essentially I was watching One Piece when the title, producer and status was either Unknown or Blank, whenever I tried watching anime it would show the error shown below. I waited for when it would show the title, producer etc. etc. again but ended up with the same error, it's been around 24 Hours since then.

### Expected behavior

I did expect it to have an error but once it was back to normal I expected things to be fine

### Actual behavior

I am unable to watch the anime or any other anime involving 9anime
![Screenshot_2022-07-22-14-49-48-15_423fe07c33ed17f15a4e92e5e3a15972](https://user-images.githubusercontent.com/109786579/180382011-6ee17ef7-0286-40ef-93dd-77acd6f28390.jpg)

### Aniyomi version

App version: 0.12.3.6-4507 (standard, 28301d09b, 72, 2022-02-02T20:30Z) Android version: 11 (SDK 30) Android build ID: CPH2325_11_A.18 Device brand: OPPO Device manufacturer: OPPO Device name: OP5303 Device model: CPH2325 Device product name: CPH2325T2

### Android version

Android 11

### Device

Oppo A55 

### Other details

All animes I have from 9anime no longer work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
9anime changed its website layout, that's why the extension is not working anymore so wait for someone to update the 9anime extension.

Next time open extension related issues in [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
