### ISSUE TITLE
Japscan don't work 

### ISSUE THREAD

**Issue by Geenzao** [aniyomiorg/aniyomi#679]
The extension named japscan in french don't work. I mean that I can't read and download with this extension. It is problematic because I have 80 mangas in this extension and I can't read any of them.

---

## Device information
* Aniyomi version: 0.12.3.7
* Android version: 11
* Device: Oppo Reno 4Z

## Steps to reproduce
1. Download japscan in french 
2. Add a manga in your library
3. Try to read or download some chapter 

## Issue/Request
you can't read and download anymore on japscan 

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by kuya-carlo** [comment]
report these on jmir1/aniyomi-extensions
