### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fratilescu** [aniyomiorg/aniyomi#680]
### Steps to reproduce

Tried to watch anime like usual and the error popped on this extension.

### Expected behavior

Start anime

### Actual behavior

Error

### Crash logs

![Screenshot_20220723-174032_Aniyomi](https://user-images.githubusercontent.com/35491517/180610088-f68c9b57-5d26-4401-8c28-815bc0f4be15.jpg)

### Aniyomi version

0.12.3.7

### Android version

Android 12 . Ui 4.1

### Device

S21 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
This is an issue related to an extension please open it in [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
