### ISSUE TITLE
9Anime not working!!!

### ISSUE THREAD

**Issue by Ken0016** [aniyomiorg/aniyomi#681]
### Steps to reproduce

![Screenshot_20220724-112700_Aniyomi](https://user-images.githubusercontent.com/105406502/180634596-65e54a46-e652-42b6-8106-26d977c0b1b1.jpg)

### Expected behavior

This used to open like other plugins but now it doesn't work anymore

### Actual behavior

![Screenshot_20220724-112700_Aniyomi](https://user-images.githubusercontent.com/105406502/180634604-36a16ac9-b7ef-42d6-9989-2add7259000f.jpg)

### Aniyomi version

0.12.3.7  

### Android version

Android 11

### Device

SAMSUNG GALAXY F12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Acion-don** [comment]
Same trouble

**Comment by Acion-don** [comment]
> ### Steps to reproduce
> ![Screenshot_20220724-112700_Aniyomi](https://user-images.githubusercontent.com/105406502/180634596-65e54a46-e652-42b6-8106-26d977c0b1b1.jpg)
> 
> ### Expected behavior
> This used to open like other plugins but now it doesn't work anymore
> 
> ### Actual behavior
> ![Screenshot_20220724-112700_Aniyomi](https://user-images.githubusercontent.com/105406502/180634604-36a16ac9-b7ef-42d6-9989-2add7259000f.jpg)
> 
> ### Crash logs
> _No response_
> 
> ### Aniyomi version
> 0.12.3.7
> 
> ### Android version
> Android 11
> 
> ### Device
> SAMSUNG GALAXY F12
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
> * [x]  I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
> * [x]  I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I will fill out all of the requested information in this form.

**Comment by kuya-carlo** [comment]
Open the issue here: https://github.com/jmir1/aniyomi-extensions

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
