### ISSUE TITLE
Add subtitles in movies and tv shows

### ISSUE THREAD

**Issue by Weeebo7** [aniyomiorg/aniyomi#682]
### Describe your suggested feature

I think adding subtitles in tv shows like game of thrones, sex education, the boys, and many more movie and tv shows. It will make the app more enjoyable 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Added in the beta
