### ISSUE TITLE
I request you to add 1 anime extension

### ISSUE THREAD

**Issue by IrespeX** [aniyomiorg/aniyomi#685]
### Describe your suggested feature

You can add "allanime.site/anime" since it is daily update. If rejected, its fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kuya-carlo** [comment]
Open a issue here: https://github.com/jmir1/aniyomi-extension

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
