### ISSUE TITLE
Contribution wiki for Aniyomi

### ISSUE THREAD

**Issue by kuya-carlo** [aniyomiorg/aniyomi#687]
### Describe your suggested feature

Since I know some Android development stuff, I would like to help in this repository but just like anyone first time  contributing to this repository, I don't know which libraries are needed for coding the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Contributing.md exista

**Comment by GABIlopez** [comment]
https://github.com/anshumanv/awesome-anime-sources
