### ISSUE TITLE
Skip intro option 

### ISSUE THREAD

**Issue by DeltaK17** [aniyomiorg/aniyomi#688]
### Describe your suggested feature

![images](https://user-images.githubusercontent.com/99571140/181159258-f9aa3b2b-b89d-4726-a2d1-e7fc02795b8d.png)

### Other details

Hello sir please try to add skip intro option in next update. Aniyomi app is great but add some useful features make it best app...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by sinnghabhay80** [comment]
The +85 sec minute is , I think, specifically for that. Probably explore the player(that is not a lot) a little.

**Comment by DeltaK17** [comment]
Ok thanks i will check it out

**Comment by DeltaK17** [comment]
> The +85 sec minute is , I think, specifically for that. Probably explore the player(that is not a lot) a little.

Hello Try this application :- https://github.com/saikou-app/saikou/releases/tag/v1.2.0.17 . I use this app to watch latest anime movies.

**Comment by sinnghabhay80** [comment]
> > The +85 sec minute is , I think, specifically for that. Probably explore the player(that is not a lot) a little.
> 
> Hello Try this application :- https://github.com/saikou-app/saikou/releases/tag/v1.2.0.17 . I use this app to watch latest anime movies.

Saikou has a great UI but I still don't get what you mean as it also has the same +85 seconds button
![Screenshot_2022-07-30-14-16-20-66_8fdea02c47a76e0fe7eccbf0ee9f2748.jpg](https://user-images.githubusercontent.com/55084281/181902916-8ada4c7f-9516-437b-9a40-4d7049fd1df0.jpg)

**Comment by Johnny5sword** [comment]
Possible references:
- https://github.com/jonbarrow/open-anime-timestamps
- https://anime-skip.com/
[API documentation](https://anime-skip.com/docs/api)
[Github](https://github.com/anime-skip)

**Comment by Quickdesh** [comment]
This has been fixed/added in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"
