### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by player2403** [aniyomiorg/aniyomi#695]
### Steps to reproduce

1. Download anime from animepahe.
2. Finished downloading.
3. Video not playing always stuck on this screen.
![Screenshot_20220728-233448_Aniyomi](https://user-images.githubusercontent.com/97405381/181578696-aec61a60-bf73-4a82-8156-3ae0957ffd89.jpg)

### Expected behavior

Video should play.

### Actual behavior

Video not playing

### Aniyomi version

0.12.3.7

### Android version

Android 11

### Device

Samsung Galaxy A20s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by sinnghabhay80** [comment]
This happens sometimes when the downloaded file gets corrupt while downloading or due to some other issue.

**Comment by Grafcube** [comment]
I am experiencing the exact same issue (same source and everything). The video isn't corrupt because I am able to manually play the file with VLC from where it's downloaded to.

I also noticed that it crashes if I click "play externally" from the app though this happens with all downloaded episodes so it might be a separate issue.

**Comment by tk2xottuc** [comment]
So like is there a fix to this because i cant watch nothing
