### ISSUE TITLE
Pause not working properly 

### ISSUE THREAD

**Issue by DeltaK17** [aniyomiorg/aniyomi#697]
### Steps to reproduce

There is a problem when you pause any anime episode download it will start from 0% .

### Expected behavior

Please Fix this issue in next update 

### Actual behavior

![Screenshot_2022-07-28-22-49-35-45_dd604340c1d7941d42aee14dd16e00e8](https://user-images.githubusercontent.com/99571140/181599575-7e259c77-5a27-493a-9027-74c2ff605a46.jpg)

https://user-images.githubusercontent.com/99571140/181599958-58910632-f20d-4202-974a-d94f53f35279.mp4

### Aniyomi version

0.12.3.7

### Android version

Android 11

### Device

Oppo F11 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/218
