### ISSUE TITLE
Chance of Adding Lavender theme 

### ISSUE THREAD

**Issue by Solovertical** [aniyomiorg/aniyomi#700]
### Describe your suggested feature
From the tachiyomi version 

Dark mode off
![Screenshot_2022-07-30-16-48-36-371_eu kanade tachiyomi](https://user-images.githubusercontent.com/109901807/181908539-25f3c22f-ccac-4aaf-b323-e9d2e07328c5.png)

Dark mode on
![Screenshot_2022-07-30-16-51-15-895_eu kanade tachiyomi](https://user-images.githubusercontent.com/109901807/181908620-e2d8243d-8e64-4144-b961-9440df56974b.png)

### Other details

This theme look good if it get added it would be best .
Thank for this awesome app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
This has been fixed/added in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"
