### ISSUE TITLE
Most extensions problem 

### ISSUE THREAD

**Issue by Raven0770** [aniyomiorg/aniyomi#705]
I have all latest version of aniyomi and extension
When I play any anime by 9Anime it shows like this
https://user-images.githubusercontent.com/109021433/182745606-f78c7228-1799-4dc7-82b5-7770c1b34731.mp4
https://user-images.githubusercontent.com/109021433/182745739-8991c000-50fc-485c-9c0b-b7f3cc3de611.mp4

Please help out

**Comment by DRoz200** [comment]
Same

**Comment by 12ohit** [comment]
If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
