### ISSUE TITLE
Another 9anime problem

### ISSUE THREAD

**Issue by Nintenstation** [aniyomiorg/aniyomi#706]
Hello!! I want to thank the team for updating 9anime. However it suffered the exact same issue it did a few hours ago, which is this:
![Screenshot_2022-08-04-15-12-33-926.jpeg](https://user-images.githubusercontent.com/110612128/182855497-441d22d4-a723-4048-ba5a-ed93b387a077.jpeg)

I apologize if I seem too hasty since maybe I'm putting pressure on the team. However 9anime has been having many of these problems later and I want to address them. I also wonder about how many others have the same issue. Thanks in advance!

**Comment by Raven0770** [comment]
I'm also facing same problem
And also please release update quickly

**Comment by Raven0770** [comment]
> I'm also facing same problem
> And also please release update quickly 

I know it's a lot of issues but i know you can do it

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
