### ISSUE TITLE
9anime playing problem 

### ISSUE THREAD

**Issue by Raven0770** [aniyomiorg/aniyomi#708]
I have all latest version of aniyomi and extension but still receive the problem shown in photo
![Screenshot_20220805_103316.jpg](https://user-images.githubusercontent.com/109021433/183005246-8e17fec0-a04d-4d3d-95a1-2a3a0f721894.jpg)
![Screenshot_20220805_103321.jpg](https://user-images.githubusercontent.com/109021433/183005269-9ac3e213-a9d7-40f6-9c94-2d10321973fb.jpg)
![Screenshot_20220805_103326.jpg](https://user-images.githubusercontent.com/109021433/183005295-f8c713f0-261e-4fb0-a2c3-b7744117bb51.jpg)
Please help

**Comment by Sathvik8** [comment]
Yes same here

**Comment by Skcyte** [comment]
If it works before seems like we're playing mouse game with 9anime. Worst case scenario just use another source.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
