### ISSUE TITLE
describe error: there is an issue parcing the package

### ISSUE THREAD

**Issue by DemonLordDiablo** [aniyomiorg/aniyomi#710]
### Steps to reproduce

download the apks

### Expected behavior

install

### Actual behavior

i get
describe error: there is an issue parcing the package

### Aniyomi version

both 0.12.2.3 and 0.12.3.7

### Android version

5.1.1

### Device

idk

### Other details

this happens for all 8 apks; the 4 on newest and the 4 on oldest. all give the same error when i try to install them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Download the apk with biggest size then see if you still get the error

**Comment by DemonLordDiablo** [comment]
> Download the apk with biggest size then see if you still get the error

i've allready tried it with all 4 newest and oldest apks, all give the same error.

**Comment by Quickdesh** [comment]
Should work with new update
