### ISSUE TITLE
DoubleTap to play/pause episode in the anime player not working

### ISSUE THREAD

**Issue by argav304** [aniyomiorg/aniyomi#712]
### Steps to reproduce

Run any episode and try to play/pause by double tapping the screen in the center. It doesn't work .

### Expected behavior

Should pause on double tapping the center of the screen whilst viewing the episode mp4 playing in the player

### Actual behavior

Doesn't pause on double tap

### Aniyomi version

0.12.3.7

### Android version

12

### Device

Samsung M21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
This feature has been added in beta, not in stable

http://github.com/jmir1/aniyomi-mpv-beta/releases/latest
