### ISSUE TITLE
Downloading size not showing 

### ISSUE THREAD

**Issue by Solovertical** [aniyomiorg/aniyomi#713]
### Steps to reproduce

On downloading ep
There is no size shown

### Expected behavior

If it show the size then it will be helpful 

### Actual behavior

Its not showing showing sometimes it cross 1gb size
![Screenshot_2022-08-07-07-32-53-869_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/109901807/183272034-e3ffc618-701e-4972-829d-eddc0215214b.jpg)

### Aniyomi version

0.12.3.7

### Android version

11

### Device

Mi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/238
