### ISSUE TITLE
9anime cannot play 

### ISSUE THREAD

**Issue by Rohan-Somadder** [aniyomiorg/aniyomi#720]
### Steps to reproduce

Try to play any episode for any anime with the source as 9anime 

### Expected behavior

Should play anime normally

### Actual behavior

![pic](https://photos.app.goo.gl/sDqS48ED9x4DQejm7)

https://photos.app.goo.gl/sDqS48ED9x4DQejm7

Error - 
Expected start of the object '{', but had 'EOF'
instead
JSON input: .....et.js#pubid =ra-62cc6bf4fa910743"></
script>
</body>
</html>

### Aniyomi version

Stable 0.12.3.7

### Android version

Android 12

### Device

Realme 9 pro 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Guice55** [comment]
I alos have the same thing, It shows up in every anime in animepahe

**Comment by Guice55** [comment]
Its the same for me but its on every anime in animepahe

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
