### ISSUE TITLE
Indicator for working extensions

### ISSUE THREAD

**Issue by Vikranttiw** [aniyomiorg/aniyomi#723]
### Describe your suggested feature

Most of the extensions doesn't work and are down and without installing I found no way to confirme which is working or not pls add a indicator that tells which are working extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Join Aniyomi's Discord server https://discord.com/invite/F32UjdJZrR
There are two channels called **anime-extension-status** & **manga-extension-status** they always have all the list of down sources.
