### ISSUE TITLE
[⭐FR] Don't show favorites in sources

### ISSUE THREAD

**Issue by MarshallJpn** [aniyomiorg/aniyomi#725]
### Describe your suggested feature

I see that when checking manga sources, there is an option to "Show favorites only", I would like it if there was an option to invert this, to show me only NEW stuff that I might haven't read yet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Settings -> browse -> hide anime/manga entries already in library
