### ISSUE TITLE
Failed to Bypass Cloudflare on Mangafreak

### ISSUE THREAD

**Issue by MikaelaMuller** [aniyomiorg/aniyomi#726]
### Steps to reproduce

Right so, get Mangafreak extension and open it, plain and simple.

### Expected behavior

Right, The expected behavior should be that a list of the latest manga should be displayed.

### Actual behavior

![Screenshot_20220816-224021_Trebuchet](https://user-images.githubusercontent.com/91151184/184908857-531157c4-374a-4f75-834d-f1d52dc594ce.png)
Well it reports that it failed to bypass Cloudflare

I tried the following guides on tachiyomi website
Clear cache
Update webview
Cloudflare bypass Guide on the website

And none of it worked, when openiny the website on webview, captcha screen doesn't appear but instead it takes me directly to the website which is weird.

### Aniyomi version

0.12.3.7

### Android version

Android 12

### Device

Samsung Galaxy A5 2017

### Other details

Im running on a custom rom. 
Lineage OS 19.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).

**Comment by 12ohit** [comment]
Ok first of all try doing this https://aniyomi.jmir.xyz/help/guides/troubleshooting/#solving-the-cloudflare-issue maybe it will help and second of all it is an issue with the extension so you gotta open it on extension repository.

**Comment by MikaelaMuller** [comment]
> Ok first of all try doing this https://aniyomi.jmir.xyz/help/guides/troubleshooting/#solving-the-cloudflare-issue maybe it will help and second of all it is an issue with the extension so you gotta open it on extension repository.

I followed this guide already, didn't work, the guide 2 doesn't work because it doesn't show a "Solve Captcha" when i open it in webview and in another browser
