### ISSUE TITLE
Random screen blackouts

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#730]
## Device information
* Aniyomi version: 0.12.3.7
* Android version: 9 (SDK 28)
* Device: Samsung (using LD player emulator on PC)

## Steps to reproduce
I was playing the show usually but randomly the screen blacks out and goes black. I would just rewind the part before the screen goes black and it looks like it is okay and back to normal. When the screen goes black I can still hear audio.

## Issue/Request
I would like to know the cause so I can fix the random black screens when watching anime/kdramas.

## Other details
I am not sure if it is because I am using an older version of android (due to LD player) or something else thank you for the help.

**Comment by clxf12** [comment]
Same i used WSA version 2307

android 13

**Comment by abdallahmehiz** [comment]
might be an issue with hw decoding
try watching with sw
