### ISSUE TITLE
Extensions issue

### ISSUE THREAD

**Issue by DRoz200** [aniyomiorg/aniyomi#733]
### Steps to reproduce

1-Open an extension (like 9anime for example)
2-open any anime episode
3-shows a black screen and dosnt work

### Expected behavior

The extensions should work perfectly 

### Actual behavior

What happened instead that all of the anime extensions just don't work when I open an episode it doesn't open and it gives me a black screen

### Aniyomi version

0.12.3.7

### Android version

Android 11

### Device

Samsung tab 17 2019

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
