### ISSUE TITLE
[ Feature Request ] Anime Torrent Streaming.

### ISSUE THREAD

**Issue by 8227846265** [aniyomiorg/aniyomi#734]
### Describe your suggested feature

Please add the capability to stream anime torrents, like sources as https://nyaa.si/

Similar to how https://www.stremio.com/ does it.

**GitHub of Stremio:**
https://github.com/Stremio

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Torrents will not be implemented
