### ISSUE TITLE
Add new anime sources

### ISSUE THREAD

**Issue by yutubeare456** [aniyomiorg/aniyomi#735]
### Describe your suggested feature

Add more anime sources like animension and allanime to make the app more better cause many extension right now is not working it's always failed to bypass Cloudflare.

### Other details

Animension link : https://animension.to/
Allanime link : https://allanime.site/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
>If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
