### ISSUE TITLE
Download Location

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#736]
### Describe your suggested feature

Can you give one more option for download tht stores files in app itself and not in phone storage.
One for storing in phone and one for storing in app itself.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Thats not how this works
