### ISSUE TITLE
Slow Anime/Manga Library Cover Showing Up

### ISSUE THREAD

**Issue by IrespeX** [aniyomiorg/aniyomi#739]
### Steps to reproduce

Idk if this is really how aniyomi works but recently the process of showing anime/manga covers are so slow and it's kinda tiresome to wait even thou you have a strong wifi or phone it is just the same.

### Expected behavior

In future outcome of the app. The expectation is that it won't affect the library cover (even you have a huge anime/manga library) while updates are happening on each series. 

p.s adjustment on how to make the process faster. 

### Actual behavior

Navigating or the process of updating your own aniyomi library is so slow.

### Aniyomi version

0.12.3.7

### Android version

Android 11

### Device

Infinix hot 11s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
It sometimes just take a while for covers to load depending on your device
