### ISSUE TITLE
Notification bar not disappearing once you open settings 

### ISSUE THREAD

**Issue by joelschmol** [aniyomiorg/aniyomi#741]
### Steps to reproduce

1. Play any video
2. Tap the settings button
3. Return to the video
4. Notification bar doesn't disappear

### Expected behavior

Normally when u tap screen during video playback, it shows the duration and controls for the media player. You can also see the notification bar by sliding down which disappears after a while. If someone changes the settings during video playback, it should get back to normal

### Actual behavior

When u access settings during video playback for changing playback speed or duration (you don't have to change something in the settings for this to happen. Just opening the settings is enough to cause this issue), the notification bar appears which doesn't go away even when u close the settings and return to the player. The same thing happens if u go back to home screen while a video is playing and then come back to the app

### Aniyomi version

0.12.3.7

### Android version

8

### Device

Huawei Y7 Prime 2018 (LDN-L21)

### Other details

![Screenshot_20220826-030410](https://user-images.githubusercontent.com/88237375/186777850-b1c68a21-3503-4f77-835b-e3e09983e724.jpg)
Like this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DuckedGuy** [comment]
Experiencing the same thing, it's such a minor thing, but it really bothers me

**Comment by joelrole** [comment]
> Experiencing the same thing, it's such a minor thing, but it really bothers me

I switched to mpv beta and it doesn't happen there

**Comment by 12ohit** [comment]
It may already have been fixed in beta, I will suggest to try it out https://github.com/jmir1/aniyomi-mpv-beta/releases/latest

**Comment by joelrole** [comment]
> It may already have been fixed in beta, I will suggest to try it out https://github.com/jmir1/aniyomi-mpv-beta/releases/latest

Yep. I switched like a week ago and it is fixed there
