### ISSUE TITLE
Add or Replace Source

### ISSUE THREAD

**Issue by Adbc3949** [aniyomiorg/aniyomi#743]
### Describe your suggested feature

Replace 9anime.to with 9anime.id as 9anime.to is ISP blocked in many places or add 9anime.id separately.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
