### ISSUE TITLE
External downloader not working for 1dm

### ISSUE THREAD

**Issue by Airiito** [aniyomiorg/aniyomi#744]
### Steps to reproduce

1 Open download settings
2. Chose ' Always use external downloader for anime'
3. Chose 1dm
4. Nothing happens, downloading didn't start in 1dm

### Expected behavior

When click on download button it should start in 1dm

### Actual behavior

Nothing happens it shows exclamation mark on download button 

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Device

Redmi note 10 pro

### Other details

I installed ADM but there is no option for ADM to choose 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by logickoder** [comment]
Have you tried downloading with the internal downloader first?

I use 1DM and it works well
