### ISSUE TITLE
Error: "Expected URL scheme 'http' or 'https' but no colon was found"

### ISSUE THREAD

**Issue by AngelaVilladiego** [aniyomiorg/aniyomi#748]
### Steps to reproduce

1. Go to anime sources (animixomay and 9anime produced this for me if "bruh" error wasn't present)
2. Globally search anime
3. Add anime to library
4. Attempt to download episode of anime

Also happens if attempting to download directly from library page

### Expected behavior

Would expect the download to work properly (or for more experienced users to be able to resolve the issue by fixing a potential typo in the fetch link)

### Actual behavior

Download "loads" for a long time before producing notification that "Expected URL scheme 'http' or 'https' but no colon was found"

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Device

Samsung S21 5g

### Other details

This occured in the past version of aniyomi as well and as far as I can see across multiple animes and extensions. Will update should I find an extension that doesn't produce this error for either of the animes that I am attempting to download (Monster and Texhnolyze)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
