### ISSUE TITLE
android tv support

### ISSUE THREAD

**Issue by RDisOP** [aniyomiorg/aniyomi#751]
### Describe your suggested feature

aniyomi on a android tv doenst properly work
do u have a android tv version planned? if not then you might consider releasing one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by SolarAquarion** [comment]
https://github.com/jmir1/aniyomi/issues/162 it's here already

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/162
