### ISSUE TITLE
Library not updating properly

### ISSUE THREAD

**Issue by battlewolf101** [aniyomiorg/aniyomi#752]
## Device information
* Aniyomi version: 0.12.3.8
* Android version: 12
* Device: Realms pad x

## Steps to reproduce
1. Library taking very very long time to update
2. Some times stops updating for hours in between and then continues after long.
3. Slow extentions
4. Many manga cover not showing 

## Issue/Request
 Please do fix the issues fast as it has been happening since the update for me 

## Other details
No additional details

**Comment by breaking-loss** [comment]
Same for me

https://user-images.githubusercontent.com/110153010/188485099-74314198-04c0-4d2a-9089-26bb1511ae41.mp4

**Comment by battlewolf101** [comment]
And now for the first time after a long time I was trying to search for a manga and it took more than a half hour.. a half freakin hour to load. Please check and do something about it.

**Comment by Quickdesh** [comment]
Should be fixed
