### ISSUE TITLE
manga doesn't update in the update section 

### ISSUE THREAD

**Issue by Chrqme** [aniyomiorg/aniyomi#753]
### Steps to reproduce

when i go to the updates section and refresh the manga page
it only updates like 10 of my manga
and i have to update the others manually by refreshing them

### Expected behavior

when i go to the updates section and refresh the manga page, all the manga in my library should update 

### Actual behavior

https://user-images.githubusercontent.com/112913777/188529462-f7c64a9f-f7d2-4a53-a855-1c0ea9d312ff.mp4

### Aniyomi version

App version: 0.12.3.8 (standard, dc8d1af, 72, 2022-08-25T23:30Z) Android version: 10 (SDK 29) Android build ID: MAR-L21MEB 10.0.0.273(C185E3R3P1) Device brand: HUAWEI Device manufacturer: HUAWEI Device name: HWMAR Device model: MAR-LX1A Device product name: MAR-LX1A

### Android version

Android version: 10 (SDK 29)

### Device

Android build ID: MAR-L21MEB 10.0.0.273(C185E3R3P1) Device brand: HUAWEI Device manufacturer: HUAWEI Device name: HWMAR Device model: MAR-LX1A Device 

### Other details

Anime updates normally 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by JemEm27** [comment]
Ooh, that's because the other mangas that's on your library are unread. It will only update the mangas that you've completed reading all the recent chapters, otherwise you need to manually update it. Idk why but that's how it is.

**Comment by Jnweeb** [comment]
Try turning off your smart update in the settings
