### ISSUE TITLE
download quality

### ISSUE THREAD

**Issue by Orionv1** [aniyomiorg/aniyomi#758]
### Describe your suggested feature

Choose the quality of episodes to download.  The app saves on download quality, and I can't select the quality I want.  It would greatly improve the app if it had that option.  Hug!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Browse -> Anime Extensions -> Settings(of the extension you using) -> Settings icon present on language name -> Preferred quality

Select the quality there and that will be preferred when making and episode offline.

**Comment by Orionv1** [comment]
oh ok. thanks!
