### ISSUE TITLE
[Feature Request] Subfolders / Anime Grouping

### ISSUE THREAD

**Issue by xGlitchette** [aniyomiorg/aniyomi#759]
## Issue/Request
A way to group anime into subfolders (inside of categories) would be nice to have for shows with a lot of spinoffs / specials etc, so you can have a folder with thumbnail such as "Chuunibyou" that then has all the anime a user put in them. (such as season 1, season 2, the movie, the OVAs, etc) Currently categories exist, and using them for this purpose would be quite awful hence im making this request

**Comment by Lukyzzz** [comment]
👀

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/127
