### ISSUE TITLE
Allow external readers for manga

### ISSUE THREAD

**Issue by AlphaDestroyer10** [aniyomiorg/aniyomi#762]
### Describe your suggested feature

Similarly to how anime can be played in an external player with a default player selectable, allow for manga to be read in an external reader with a default reader selectable.

### Other details

I'm suggesting this because the native reader is lacking, often having misaligned pages that make for a frustrating reading experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
It will not work with external readers, if you have features that you want in the reader create issues for those
