### ISSUE TITLE
After changing Video Quality, the Navigation and Notification bar stays fixed

### ISSUE THREAD

**Issue by HarshSinha11** [aniyomiorg/aniyomi#764]
### Steps to reproduce

1. Open an Episode
2. Click on Playback Options
3. Change Video quality

### Expected behavior

The Navigation and Notification bar should not be visible in full-screen

### Actual behavior

When play back options are changed the Notification and Navigation bar becomes visible
![Screenshot_2022-09-12-11-15-51-951_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/49302749/189582370-ae923c0f-4a68-4a7b-9d76-74dde036faf7.jpg)

### Aniyomi version

0.12.3.8

### Android version

Android 10

### Device

Redmi 7A

### Other details

This does not happen in Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by RyuOnigami** [comment]
Is there any solution for this

**Comment by HarshSinha11** [comment]
> Is there any solution for this

You can use Aniyomi-MPV beta instead of Aniyomi

**Comment by anonforceuser** [comment]
same thing happens to me. I am using a Fire 7 9th gen
![tachiyomi error full screen](https://user-images.githubusercontent.com/73724363/196682624-79f6a2c7-53bd-439f-82fe-7b342665ca0e.jpeg)
