### ISSUE TITLE
Episode download resets when cancelling soon to be downloaded episodes (in queue)

### ISSUE THREAD

**Issue by kaishshaikh376** [aniyomiorg/aniyomi#765]
### Steps to reproduce

1. Put 2 episodes to download
2. 2. Cancel the next episode to be downloaded
3.  The episode currently downing will reset to 0%

### Expected behavior

The episode which is currently downloading will continue to be downloaded.

### Actual behavior

The episode resets to 0% downloaded and starts downloading from start again.

### Aniyomi version

0.12.3.8

### Android version

Android 11

### Device

OnePlus 7 pro 

### Other details

![Screenshot_20220913-215221](https://user-images.githubusercontent.com/72914712/189955103-7a2a3eaa-6f4e-415b-9a53-5f8567a42017.jpg)
![Screenshot_20220913-215225](https://user-images.githubusercontent.com/72914712/189955127-5e32131e-4132-4607-b412-aec3029346b1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/218
