### ISSUE TITLE
[🚀DL] Multithreaded downloading

### ISSUE THREAD

**Issue by KianBrose** [aniyomiorg/aniyomi#773]
### Describe your suggested feature

I noticed that often times when downloading from any given source, the source speed is slower than the local Internet speed.

The way the app currently works with the "queue" is it downloads things one at a time, but would it be possible to allow for multiple downloads to occur simultaneously to take advantage of better bandwidths?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
closed by 55fedef4ad31d86042001690a01c47f1863c7eaa
