### ISSUE TITLE
'package installer' keeps stopping

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#779]
### Steps to reproduce

1. Pressing and holding aniyomi app.
2. A delete button pops up.
3. Pressing delete the app.
4. Nothing happens but a text 'package installer keeps stopping' pops up.
5. Unable to delete this app.

### Expected behavior

I expected for aniyomi app to be deleted from my phone.

### Actual behavior

After I press delete the app nothing happens but after a few tries 'package installer keeps stopping' message pops up.

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Device

Galaxy S10

### Other details

I saw that there is a solution to this problem and it said that I have to remove MicroSD and uninstall, but I don't have MicroSD card in my phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [x] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by prismacolorgold** [comment]
I too experience the same issue.

**Comment by Quickdesh** [comment]
Should be fixed with update
