### ISSUE TITLE
Video reader vertical mode has some parts that needs to be realigned

### ISSUE THREAD

**Issue by Palloxin** [aniyomiorg/aniyomi#781]
### Steps to reproduce

set vertical mode on the video reader of the app.
![IMG_20221001_015355](https://user-images.githubusercontent.com/75091899/193370380-9910ef5a-06cd-420d-abb0-5ae07c0c5ef2.jpg)

### Expected behavior

Parts aligned

### Actual behavior

parts not aligned

### Aniyomi version

r5237

### Android version

Android 8, Miui 8

### Device

Huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Sushmitayadav1234567** [comment]
Your issue will be solved soon

**Comment by Quickdesh** [comment]
Has been Fixed by making icons smaller
