### ISSUE TITLE
[▶️PL] Remember previous orientation of player

### ISSUE THREAD

**Issue by Palloxin** [aniyomiorg/aniyomi#782]
### Describe your suggested feature

This orientation option should work this way:
basically it should be in a fixed state (except landscape and reverse landscape that should adapt based on sensor, obviously).
Every time the user changes the orientation with this button on the player..
![IMG_20221001_075856](https://user-images.githubusercontent.com/75091899/193395075-a81fe495-bfb6-481c-a2a7-8641b5c1ee77.jpg)
the app should open other episodes of every anime with that orientation until the user presses the button again changing the default one.
Personally, the reason why i am asking this is that sometimes when i am tired on the bed i like to  watch anime in this position
![IMG_20221001_080333](https://user-images.githubusercontent.com/75091899/193395306-18c9b7b0-68f4-4da9-9b8d-ad5e73fdd0e4.jpg)
(image from the internet)
in this way watching an anine would be more comfortable. i am sure i am not the only who does this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
For that you can go in player settings and set default orientation as vertical

**Comment by Palloxin** [comment]
this is a QoL suggestion @12ohit

**Comment by 12ohit** [comment]
The rotation button in the player works keeping in mind that you temporarily want to change the video rotation, if that's not the case then you can go to settings and make orientation default to vertical and whenever you are done change it back. At least that's how I think QuickDev thought it should work. So if any dev want to change it like the way you want it then good for you.

**Comment by Palloxin** [comment]
@12ohit since i switch quite often the orientation i would like to keep the last one i set with that button, so yes, the suggestion is about an option that would make that button apply not a temporary change to the orientation but a permanent one until changed in the same way

**Comment by JM150JM150** [comment]
En mi opinión, debería de funcionar solamente cuando reproduces el vídeo, cuando salgas del reproductor que se restablezca a lo normal, eso es todo, muchos reproductores añaden esto, que no lo tenga Aniyomi, es triste...

**Comment by Quickdesh** [comment]
> @12ohit since i switch quite often the orientation i would like to keep the last one i set with that button, so yes, the suggestion is about an option that would make that button apply not a temporary change to the orientation but a permanent one until changed in the same way

this makes sense, ill code this is in for my next PR

**Comment by Quickdesh** [comment]
though I need to make sure @Palloxin, is this for watching episodes from different anime, or episodes within the same anime, as in by just pressing next episode?

**Comment by Palloxin** [comment]
> though I need to make sure @Palloxin, is this for watching episodes from different anime, or episodes within the same anime, as in by just pressing next episode?

i guess the easiest way is all epiosdes of all anime @Quickdesh
