### ISSUE TITLE
Delete last watched episode after manual marking

### ISSUE THREAD

**Issue by pavonismc** [aniyomiorg/aniyomi#788]
### Steps to reproduce

Download any anime episode
Mark episode as read manually or by watching

### Expected behavior

Watched episode should be deleted

### Actual behavior

It isn't delete

### Aniyomi version

0.12.3.8

### Android version

Android 11

### Device

Oppo reno5 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by pavonismc** [comment]
> Problem with this is that some people would still want their downloaded episodes, maybe for a re-watch. And I don't believe deleting or mass deleting of episodes is a hassle

The thing is I turned on the feature in settings but it still doesn't work

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/1154
