### ISSUE TITLE
Quick Resume button like in TachiyomiJ2K

### ISSUE THREAD

**Issue by TyranitarTar** [aniyomiorg/aniyomi#793]
### Describe your suggested feature

TachiyomiJ2K has a great feature where you can resume reading a manga where you left off directly from the library page by clicking a small "Resume" icon next to the entry in the library.

I think porting it should be easy as TachiyomiJ2K and Aniyome are both based on the same open source project.

I've included a screenshot from TachiyomiJ2K with a circle around how the resume icon looks.

![Screenshot_20221009-231312_TachiyomiJ2K](https://user-images.githubusercontent.com/35216227/194779839-316482a0-59b0-4e00-beb1-24443f5e4ec6.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Added
