### ISSUE TITLE
Extension Request

### ISSUE THREAD

**Issue by MonomoySama** [aniyomiorg/aniyomi#806]
### Describe your suggested feature

I just installed this app and was amazed by how this is an all in one app. This is so convenient for me. I saw there were some Movies/Web series extensions so i want to request some "HINDI" Language extensions for "HINDI" language Shows and Movies that are Dubbed in Hindi. If you add it.. it will be such a perfect app for me. 
Thank you for making such a app ♥️

### Other details

Thank you again for your hard work ♥️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
