### ISSUE TITLE
Extension problem

### ISSUE THREAD

**Issue by MonomoySama** [aniyomiorg/aniyomi#807]
### Steps to reproduce

1. Opening Animixplay & Gogoanime Extension
2. Clicking on any Anime

### Expected behavior

I want them to stay in English names

### Actual behavior

Before opening any anime in Animixplay & Gogoanime extension it's name is in English but after opening it will be in Japanese permanently. This is a great problem for library. I don't remember japanese names so can't search them

### Aniyomi version

0.12.3.8

### Android version

Android 10

### Device

Realme 7 Pro/ RMX2170

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
