### ISSUE TITLE
New Extension

### ISSUE THREAD

**Issue by Nieclypes** [aniyomiorg/aniyomi#810]
### Discussed in https://github.com/jmir1/aniyomi/discussions/798

<div type='discussions-op-text'>

<sup>Originally posted by **Nieclypes** October 15, 2022</sup>
You should add a MoviesJoy.to extension to the app it works really well and has alot of anime and even some tv shows

https://moviesjoy.to/</div>

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
