### ISSUE TITLE
Animixplay error

### ISSUE THREAD

**Issue by Redowansky** [aniyomiorg/aniyomi#816]
### Steps to reproduce

After selecting any anime when i tap play after loading some time it says cloudflare bypass error

### Expected behavior

Any anime would play 

### Actual behavior

cloudflare bypass error

### Aniyomi version

0.12.3.8

### Android version

Android 9

### Device

Itel vision 1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GMRobo** [comment]
"If this is an issue with an extension, I should be opening an issue in the extension repository." Wrong place mate

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
