### ISSUE TITLE
Playback Refreshes when input device connects/disconnects

### ISSUE THREAD

**Issue by djsleahy** [aniyomiorg/aniyomi#820]
### Steps to reproduce

1) Connect an external control device to device playing video with aniyomi.
2) Attempt some input with external device.
  You should see playback dump all buffered data and reconnect/rebuffer.
3) Wait for playback to restart.
4) Disconnect external device.
  You should see playback dump all buffered data and reconnect/rebuffer.

Connection/Disconnection will also cause playback to resume when paused.

### Expected behavior

Playback should continue uninterrrupted when connecting/disconnecting devices.

Paused playback should not resume when connecting/disconnecting devices.

### Actual behavior

Playback was interrrupted when connecting/disconnecting external devices due to buffer dumping and reloading/reconnecting/rebuffering.

Paused playback resumed when connecting/disconnecting external devices.

### Aniyomi version

0.12.3.8

### Android version

Android TV 4.9.118

### Device

Android TV (JVC)

### Other details

Connecting and disconnecting USB Mouse for control.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Should be fixed
