### ISSUE TITLE
"Unable to bypass cloudflare" 

### ISSUE THREAD

**Issue by ShuraTon** [aniyomiorg/aniyomi#826]
### Steps to reproduce

The steps to reproduce the issue are as follows:
 1. Choose any extension that requires bypassing of cloudflare in order to access it. (Kissmanga.in, mangafreak)
 2. The "Unable to bypass cloudflare" text will appear.

### Expected behavior

Expected behaviour :
1. The app (aniyomi) should be able to bypass the cloudflare with no issues.
2. If it does not bypass it on the first try, it should at least be able to do so after using the "web view" option and immediately going back to the extension.

### Actual behavior

Actual behaviour : 
1. The app (aniyomi) fails to bypass the cloudflare after multiple attempts for over a week.
2. Using the "web view" option allows us to bypass the cloudflare, but will send us back to the bypassing screen when we try to read any manga/manhwa/manhua (Mangafreak)
3. Even in "web view", bypassing cloudflare on kissmanga.in does not work, repeatedly refreshing itself while it checks the security of our connection.

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Device

Vivo V2152

### Other details

I know mangafreak and nhentai.net had been resolved in the current update, and mangafreak worked fine for a month and half, but it has been having issues again for a while now, and kissmanga.in had been working fine until recently.

![Screenshot_20221113_185009](https://user-images.githubusercontent.com/118112307/201524596-3f0bb1cc-bf73-4b0e-8033-5625b2965171.jpg)

![Screenshot_20221113_184902](https://user-images.githubusercontent.com/118112307/201524603-6d53891a-ccfe-45ad-80b5-ef97fcaffb92.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jadereveler** [comment]
Is there a fix cuz I've run into the same problem

**Comment by abdallahmehiz** [comment]
![Screenshot_20231016-103338_Chrome](https://github.com/aniyomiorg/aniyomi/assets/54363735/83885304-76df-4a43-94cc-a5379aa8f4c0)
You clearly haven't read the troubleshooting guide
