### ISSUE TITLE
Wcofun domain issue

### ISSUE THREAD

**Issue by PheonixMaster57** [aniyomiorg/aniyomi#832]
### Steps to reproduce

Anytime I try to play a video from this source, the message no address associated with this extension pops up. Web view still works though. 

### Expected behavior

Any video from the above extension doesn't play directly from the app. 

### Actual behavior

Videos from the above source don't play directly from the app. 

### Aniyomi version

Latest  version 

### Android version

Latest version 

### Device

Galaxy Z fold 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
