### ISSUE TITLE
Expected url scheme but no colon was found 

### ISSUE THREAD

**Issue by 11KOFFIE11** [aniyomiorg/aniyomi#834]
### Steps to reproduce

Install extension
Find anime
Try to watch a episode
Error Expected url scheme but no colon was found.
Only gogoanime works everything else gives a error like this.
![Screenshot_2022-11-20-13-39-13-565_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/118665157/202899955-4eebcc58-cffd-4942-a8cb-dba98abd4061.jpg)

### Expected behavior

Anime should load

### Actual behavior

Anime not loading 

### Aniyomi version

0.12.3.8

### Android version

Android 11

### Device

Xiaomi mi note 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MhmdSheref** [comment]
Having the same problem here

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
