### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by meesuman123** [aniyomiorg/aniyomi#843]
### Steps to reproduce

1. open aniyomi
2. open browse
3. extension are failed to load

### Expected behavior

This should expect to happen that all extension are working smoothly 

### Actual behavior

Installed extensions are working properly but other extensions are failed to load

### Aniyomi version

0.12.3.8

### Android version

Android 9

### Device

Xaomi Redmi note 5 pro 

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by meesuman123** [comment]
Yes...but existing extensions are properly working...

**Comment by Sudip909** [comment]
Yes but gogo anime is not working properly 🙃🙃

**Comment by meesuman123** [comment]
this is very frustrating

**Comment by Quicksolverr** [comment]
Bruh try using vpn like thunder and warp(available in play store) and then update or install extensions it will help guess so

**Comment by Omkarpatil-21** [comment]
![Screenshot_20240616-012539](https://github.com/aniyomiorg/aniyomi/assets/172744334/bdf0ff35-7e4d-4211-be2e-7f8927a47f88)



The episode in library list not updating or not showing any episode.
