### ISSUE TITLE
Can't get any extensions 

### ISSUE THREAD

**Issue by shu9474s** [aniyomiorg/aniyomi#844]
### Steps to reproduce

1.Open app
2.Go to browse option
3.then go to Anime extensions
4.try to reload the extensions 

### Expected behavior

After going to the anime extension page simply all extensions which are available should show up and can be downloaded or updated as wished.

### Actual behavior

Here in that case when I open the anime extension page there is nothing but my pre existing extensions and even those aren't working well.Everytime I refresh that page there is always a single statement "Failed to get extension list"

### Aniyomi version

"0.12.3.8"

### Android version

Android 12

### Device

Poco M4 pro 4g

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by shu9474s** [comment]
Please fix it ASAP

**Comment by PeasAnt97** [comment]
Have reinstall aniyomi itself? It worked once for me.

**Comment by shu9474s** [comment]
> Yeah bro I tried to do that too but instead of Getting fix even my pre existing extensions are also gone now and they haven't even fixed it yet

**Comment by shu9474s** [comment]
> Have you tried reinstalling aniyomi itself? It worked once for me.

It's that universal released version right?

**Comment by jazz1510** [comment]
I am also facing the same issue

**Comment by PeasAnt97** [comment]
> > Have you tried reinstalling aniyomi itself? It worked once for me.
> 
> It's that universal released version right?

I've tried to recreate your issues. As far as I'm concerned, only a slow and/or bad connection to the internet could recreate it.

Also if need be, try downloading the largest size apk one 114MB from the official site.

Rog 5s here

**Comment by sewaks2297** [comment]
> Please fix it ASAP

Yeah its bothering

**Comment by sumitsingh3359** [comment]
> > > Have you tried reinstalling aniyomi itself? It worked once for me.
> > 
> > 
> > It's that universal released version right?
> 
> I've tried to recreate your issues. As far as I'm concerned, only a slow and/or bad connection to the internet could recreate it.
> 
> Also if need be, try downloading the largest size apk one 114MB ver 12.3.8 from the official site.
> 
> Rog 5s here

I'm getting the same issue in that version too in Android 11 phones and one Android 7 phone

**Comment by nezh-anime** [comment]
The problem is mostly occuring on Android 12 please fix this

**Comment by ShadowGuy01234** [comment]
Same problem is happening with me I changed my DNS to Google then got the extension liat but they are not updating

**Comment by jazz1510** [comment]
> 

Bro Thank you so much, you solved the problem for me ❤️

**Comment by Cypher272704H** [comment]
Not working same problem

**Comment by Jayrudra** [comment]
Plz fix this

**Comment by MadMaXxx02** [comment]
Was facing the same issue. Try using the 1.1.1.1 Warp app(available on playstore). Worked for me, and I managed to install the extensions as well

**Comment by ShadowGuy01234** [comment]
I found a workaround that by connecting to a vpn I can download or update the extensions so i have been doing that

**Comment by DevRko** [comment]
Same problem here with Android 11 too..

For the last 2 days, I've been facing this issue. Unable to download or view new extensions ( both anime and manga ) from the extensions section of the app..

I've already used the uninstallation and installation trick, but that didn't work out.

Also I backed-up and restored my Libraries and app data, cleared caches, cookies..😟!

[Uploading q4{7b645a7} (934f7bd1-716e-46c7-b47d-24032625a8eb id=0x7f0a0401 tag=BaseCommentFragment) …]()

**Comment by sewaks2297** [comment]
Use vpn trick mentioned it will resolve the issue

**Comment by Quicksolverr** [comment]
Use vpn like thunder and warp and then try reinstalling extensions it will definitely work.

**Comment by Dannywannabe** [comment]
I know a way follow the steps below:
Download super VPN
Open aniyomi app
It'll show extensions
Download all you want
Turn off VPN and enjoy

**Comment by riseofthehood** [comment]
Folks there is an easy fix no external apps needed !

# Goto Aniyomi>More tab>Settings>Advanced
# Under advanced goto Network section
# Click on DNS over HTTPS
# use Google

VOILA ! Problem solved.
Once you install extensions try using it, if its buggy or slow revert the fix.

Enjoy

**Comment by Joker9009009** [comment]
After updating extensions they are now missing. It shows failed to extension list.

**Comment by Airiito** [comment]
Same problem here from yesterday, please fix

**Comment by hexacyy** [comment]
did the vpn trick and still failed to get extensions for manga.

**Comment by Nigmare3478** [comment]
La extención pelisflix/seriesflix no funciona, puedo como tal agregar películas o series que solo se encuentran en esa extensión pero no me deja verlos

**Comment by Quickdesh** [comment]
This issue/feature has been fixed/added in the preview version of Aniyomi. You may update using backup and restore. 

https://github.com/aniyomiorg/aniyomi-preview/releases

The update to stable will take a while so please do wait for that.

**Comment by Quickdesh** [comment]
🫡
