### ISSUE TITLE
Failed to get anime as well as manga extensions 

### ISSUE THREAD

**Issue by dhruvik1239** [aniyomiorg/aniyomi#845]
### Steps to reproduce

1.Open app
2.Go to browse option
3.then go to Anime extensions
4.try to reload the extensions

### Expected behavior

After going to the anime extension page simply all extensions which are available should show up and can be downloaded or updated as wished.

### Actual behavior

Here in that case when I open the anime extension page there is nothing but my pre existing extensions and even those aren't working well.Everytime I refresh that page there is always a single statement "Failed to get extension list"

### Crash logs

No response

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Device

Xiaomi 11x pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cl0udrecesses** [comment]
dns over https could be disabled.  go to settings andthen advanced. under network dns pver https choose any one
i chose adguard and anime extensions appeared for me
still unable to install any of those extensions though

**Comment by ShadowGuy01234** [comment]
> dns over https could be disabled. go to settings andthen advanced. under network dns pver https choose any one i chose adguard and anime extensions appeared for me still unable to install any of those extensions though

Same with me

**Comment by adhudragonslayer** [comment]
Even I am unable to download it

**Comment by cl0udrecesses** [comment]
for some reason, i am having this issue only on android tablet. android phone is working fine. all of the tachi forks are having the same problem on tablet
