### ISSUE TITLE
Player does not work with VLC

### ISSUE THREAD

**Issue by bruhgod69** [aniyomiorg/aniyomi#846]
### Steps to reproduce

1. Download the newest version of VLC
2. Set it as external player
3. Try playing any episode
4. Get the error message

### Expected behavior

Video should stream

### Actual behavior

I get this grey bubble notification message:

Unalbe to find explicit activity class
{org.videolan.vlc/org.videolan.vlc.gui.video...

### Aniyomi version

0.12.3.8

### Android version

Android 13 (CalyxOS)

### Device

Google pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by brodiebear** [comment]
Can confirm this is happening to me also

**Comment by lucfig** [comment]
Seems to be an Android 13 issue
https://code.videolan.org/videolan/vlc-android/-/issues/2776

**Comment by Quickdesh** [comment]
Fixed
