### ISSUE TITLE
[Aesthetic flaw] +85 appearance is delayed when opening episodes

### ISSUE THREAD

**Issue by Palloxin** [aniyomiorg/aniyomi#847]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/205527948-00553d08-2565-4465-9ab3-73a48cf11be4.mp4

I don't really know how to trigger it but i had my phone vertically orientated.

### Expected behavior

+85 should appear right away

### Actual behavior

the appearance of "+85" is delayed so its "box" looks empty at first

### Aniyomi version

r5846

### Android version

android 8

### Device

huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
It's not a bug but a feature, it is waiting for the episode's streaming links to load before allowing you to skip 85 seconds

**Comment by Palloxin** [comment]
Isn't there a better way to display that effect? Like turned off effect applied to the buttom instead of a +85 that appears late?
