### ISSUE TITLE
'hanime.tv' anime extension video not playing

### ISSUE THREAD

**Issue by spidy2356** [aniyomiorg/aniyomi#849]
### Steps to reproduce

step1: I open the aniyomi app.
step2: go to browse and open hanime.tv and play any one of the video.
Step3: video buffers and after few times stop buffers but video not playing at all.

### Expected behavior

it should play video after few seconds buffering.

### Actual behavior

video not playing no more in hanime.tv

### Aniyomi version

0.12.3.8

### Android version

android 11

### Device

poco x2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by HyperBhavik28** [comment]
Working for me on lenovo tab 4 10, can you make sure that this issue happens with all the videos or just some of them

**Comment by spidy2356** [comment]
> Working for me on lenovo tab 4 10, can you make sure that this issue happens with all the videos or just some of them

yes, this issue happens with all videos

**Comment by GMRobo** [comment]
"If this is an issue with an extension, I should be opening an issue in the extension repository." Wrong place mate

**Comment by spidy2356** [comment]
this issue already solved. plz close it. thank you

> "If this is an issue with an extension, I should be opening an issue in the extension repository." Wrong place mate
