### ISSUE TITLE
Android TV support 

### ISSUE THREAD

**Issue by gofirst2220** [aniyomiorg/aniyomi#854]
### Describe your suggested feature

I managed to install Aniyomi onto my Android TV and I would like some support for it to be used on it. However, my Android TV is based on a Fire OS used in smart TV.

### Other details

How do I do it? I used the downloader app to navigate to this repo and sideload it onto it.

It works fine partially, some remote controls won't work if the video controls overlay isn't visible

Here's the system info about it

Software Version: Fire OS 7.6.0.8 (PS7608/3614)

Fire TV Home (Launcher) Version: 6410028.1

Model: INSIGNIA_NS-55DF710NA21

#751 is also part of this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kamanabc123** [comment]
this would be wonderful to have.

**Comment by hvroun1** [comment]
I was able to make it work properly by installing mouse cursor for clicking, scrolling and dragging. that's all that you need.

**Comment by gofirst2220** [comment]
> I was able to make it work properly by installing mouse cursor for clicking, scrolling and dragging. that's all that you need.

True. I was going for native control stuff like forward/reverse and play, etc. I'm pretty sure you can't actually interact with the built-in controls when the control overlays hides from view.  Right now, I'm using the third-party video player to get around the issue in the meantime.

But yeah, I used mouse cursor to switch the aniyomi app to tablet mode, from there I don't need the cursor unless I actually need to.

**Comment by hvroun1** [comment]
Actually you can interact with the built-in controls when the control
overlays hides from view. Just tap on the screen with a cursor and it shows
up. You can even double tap right and left side of the screen to forward or
reverse 10sec. I have forgotten the cursor app name but if you want I can
let you know and you can try it out for yourself.

**Comment by hvroun1** [comment]
@gofirst2220 the mouse cursor I'm using is called mouse for Android tv toggle (MATVT). Works just like touchscreen on phones. With this you can use aniyomi without 3rd party video players. 
There's a video on YouTube on how to install it if you run into any issues.

**Comment by anthonym01** [comment]
You can use a Bluetooth mouse/keyboard to be able to use it like normal

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/162
