### ISSUE TITLE
Stat Update for Aniyomi 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [aniyomiorg/aniyomi#857]
### Describe your suggested feature

Update stat details page by allowing the following for aniyomi users: 

Tapping on a stat now either opens the manga (when checking read duration) or a filtered library screen with your filtered stat(s) selected

Display the read duration dates in locale standard.

Change read duration total to include all history.

When setting a date range to read duration, using the arrows now moves by the entire date range, instead of just a week.

Improve stats being slightly inaccurate sometimes when some manga are in multiple categories
General optimizations

Improve stats being slightly inaccurate sometimes when some manga are in multiple categories

### Other details

Smooth detailed stats like this, amazes me everyday since the results is quite accurate. 

![Screenshot_20221219_060754](https://user-images.githubusercontent.com/104534608/208422372-2464cf57-ce52-449c-990c-5a6ec4c987ce.png)
![Screenshot_20221219_060745](https://user-images.githubusercontent.com/104534608/208422376-ebdd5344-95fd-468e-b5ca-f00bf852c08f.png)
![Screenshot_20221219_060712](https://user-images.githubusercontent.com/104534608/208422377-1d8287ca-1de6-482d-8ae0-17eec4fc1423.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Exists in a different form
