### ISSUE TITLE
Aniyomi (latest version) Restore error. 

### ISSUE THREAD

**Issue by JazzterSG** [aniyomiorg/aniyomi#858]
### Steps to reproduce

1. create backup file.
2. use backup file using restore. 

### Expected behavior

restoring backup file created by aniyomi must be seamless and must not have errors. 

### Actual behavior

instead, the app wont let me restore its own backup file which holds all my lists of mangas and animes. 

### Crash logs

--------- beginning of main
12-26 00:16:35.986 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:16:36.005 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:19:44.843 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:19:44.879 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:19:52.411 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:19:52.422 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:20:00.787 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:20:00.807 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:20:03.614 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:20:03.628 30313 31562 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:24:50.355 30318 30318 E ir.tachiyomi.mi: Not starting debugger since process cannot load the jdwp agent.
12-26 00:24:50.893 30318  2587 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:26:00.759 30318  2587 E OpenGLRenderer: Unable to match the desired swap behavior.
12-26 00:26:12.116 30318  2587 E OpenGLRenderer: Unable to match the desired swap behavior.
App version: 0.12.3.8 (standard, dc8d1af, 72, 2022-08-25T23:30Z)
Android version: 13 (SDK 33)
Android build ID: TQ1A.221205.011 release-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: spes
Device model: 2201117TG
Device product name: lineage_spes

### Aniyomi version

0.12.3.8

### Android version

android 13

### Device

redmi note 11

### Other details

custom rom "crdroid" december update. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Should be fixed
