### ISSUE TITLE
add subtitle options 

### ISSUE THREAD

**Issue by AKBEHERA793** [aniyomiorg/aniyomi#862]
### Describe your suggested feature

please can you add subtitle options for some extentions like super stream or dopebox and if you can add watchfree.tv as extention it would be great too or change the video player lil bit that it can allow the subtitle options like when we watch in web

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by hvroun1** [comment]
Aniyomi beta version(MVP) has subtitles. Although just when streaming just like when you watch it on web, You can try it out before the stable version gets updated.

**Comment by ugwapings** [comment]
what if i download the movie the wants a subtitle where can i get those?

**Comment by ugwapings** [comment]
> @AKBEHERA793 Aniyomi beta version(MVP) has subtitles when streaming, just like how you watch it on the web, You can try it out before the stable version gets updated.

what if i download the movie the wants a subtitle where can i get those?

**Comment by hvroun1** [comment]
You can't, atleast for now. If you want subtitles then you better download from torrent which already have embedded subtitles, put it in specific extension folder then you can watch it on aniyomi with subtitles.

**Comment by dvamshidhar** [comment]
> @AKBEHERA793 Aniyomi beta version(MVP) has subtitles when streaming, just like how you watch it on the web, You can try it out before the stable version gets updated.

beta version had bugs
