### ISSUE TITLE
Unfinished episodes being deleted

### ISSUE THREAD

**Issue by BrunoPascoa76** [aniyomiorg/aniyomi#863]
### Steps to reproduce

1. Download an episode
2. Try to play it on an external player (VLC, in my case)
3. Return as soon as it starts
4. Wait a few seconds.

### Expected behavior

For the episode to remain downloaded

### Actual behavior

The episode no longer appears downloaded, the episode is still marked as unwatched. It's downloaded when you try to watch it the first time without wifi, but if you keave mid-episode, you can't continue because you need to download ot again.
Confirmed that it's not cause by the "mark watched" ir "delete automatically" options.

### Aniyomi version

0.12.3.8

### Android version

Android 9

### Device

Huawey P Smart 2020

### Other details

My storage location is a custom location set to the same folder as the default (it was a fix from another issue, otherwise VLC would crash on downloaded episode)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrunoPascoa76** [comment]
I

**Comment by BrunoPascoa76** [comment]
Just to add, I've confirmed that this doesn't happen on the manga and the episode truly gets deleted (i.e. the folder no longer exists if you try to look for it with a file manager)

**Comment by Quickdesh** [comment]
Should be fixed in the latest version
