### ISSUE TITLE
Network 

### ISSUE THREAD

**Issue by Mukul9876** [aniyomiorg/aniyomi#864]
### Steps to reproduce

I am getting the problem in aniyomi is that , the video plays properly when using wifi. But when i started to use mobile data , the video stuck and not playing the anime. As a result I am unable to use aniyomi while i am travelling or get out of my home.

### Expected behavior

There should be same response of video playing while using wifi or mobile data. And not getting the problem by using mobile data.

### Actual behavior

The video not played and just its buffering again and again while using mobile data but not get a problem while using wifi. 

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Device

Realme GT Master Edition

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mohammed-Shoaib01** [comment]
Is the source you're trying to download from restricted for your mobile data provider?

**Comment by Manish061104** [comment]
I also have the same problem with gogoanime for a few days now

**Comment by ShubhShahu** [comment]
same with zoro

**Comment by abdallahmehiz** [comment]
this seems like a service problem (your mobile internet provider) rather than an app problem
