### ISSUE TITLE
extension BetterAnime is the broken

### ISSUE THREAD

**Issue by whyakari** [aniyomiorg/aniyomi#865]
### Steps to reproduce

``Attempt to invoke virtual method 'java. lang.String orgjsoup.nodes.Element. attr(java.lang. String)' on a null object reference``

### Expected behavior

Should show the animes that contains at Betteranime 

### Actual behavior

When I try to access Betteranime extension does not work 

### Aniyomi version

0.12.3.8

### Android version

Android 12.1

### Device

Redmi Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GMRobo** [comment]
"If this is an issue with an extension, I should be opening an issue in the extension repository."

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
