### ISSUE TITLE
Old player instead the "new"

### ISSUE THREAD

**Issue by edmxn** [aniyomiorg/aniyomi#879]
### Describe your suggested feature

Wasn't there a new player? I get the old one but I am on the latest version (both stable and preview)

### Other details

![Screenshot_20230131_110716_Aniyomi](https://user-images.githubusercontent.com/101371218/215832912-28619506-42d0-4e85-87b4-bc6b71db2644.jpg)

When opening an ep the old one comes out clearly, that's what I mean. Here I attach the configuration.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
the new one is in the beta, not the preview
www.github.com/jmir1/aniyomi-mpv-beta/releases/latest

**Comment by edmxn** [comment]
> the new one is in the beta, not the preview [www.github.com/jmir1/aniyomi-mpv-beta/releases/latest](http://www.github.com/jmir1/aniyomi-mpv-beta/releases/latest)

I'm sure I ever used it in stable ver, did they remove it or am I imagining things?
