### ISSUE TITLE
Batch-add to library 

### ISSUE THREAD

**Issue by 3bdullah-3bdeen** [aniyomiorg/aniyomi#881]
### Describe your suggested feature

Batch-add anime from certain sources like 9anime's list to library like how tachiyomisy does with mangadex

### Other details

![Screenshot_20230202_202037_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/119709287/216415594-5dabd7a4-467c-4b4a-8faf-7718c84f70c6.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Extensions will not get support
