### ISSUE TITLE
Can we get Aniyomi safe mode

### ISSUE THREAD

**Issue by minonine** [aniyomiorg/aniyomi#883]
### Describe your suggested feature

If you can just remove the possibility to access to hentai content 

### Other details

For people addictive to hentai, who are trying to stop watching that sh*t, can we get an app without +18 extensions please 
Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TheGoldenSun** [comment]
I love this, yes.

**Comment by Solovertical** [comment]
There already an option just go to more^Browse^ off the nsfw source

**Comment by minonine** [comment]
> There already an option just go to more^Browse^ off the nsfw source 

I know,  it's easy to turn it on as well

**Comment by Shah741** [comment]
Kinda late but what's really irreversible is breaking your router. Good day.
