### ISSUE TITLE
VLC and other external players time/watched not updated

### ISSUE THREAD

**Issue by warior456** [aniyomiorg/aniyomi#887]
### Steps to reproduce

Use vlc as external player (default settings in vlc) and go back, the episode watched time isnt updated or marked as watched 

### Expected behavior

Like the built in player it should mark the time of where you left of in an  episode

### Actual behavior

The time doesnt update or the episode doesnt get marked as watched (also atm vlc doesnt work for non downloaded it seems, and downloaded only work when the prefered is none)

### Aniyomi version

0.12.3.10

### Android version

13

### Device

Galaxy a52s 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Fixed
