### ISSUE TITLE
An Option To Download Multiple Things

### ISSUE THREAD

**Issue by saifkaral** [aniyomiorg/aniyomi#890]
### Describe your suggested feature

So, Right now when say for example you want to download an anime it downloads like this 1 ep the.n 2 ep etc..
I think it would be cool to give an option to download 2 or 3 episodes at the same time or something 

### Other details

Maybe it is not possible idk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by dvamshidhar** [comment]
use external download manager
