### ISSUE TITLE
Downloading error

### ISSUE THREAD

**Issue by Mohul-Gaikwad** [aniyomiorg/aniyomi#891]
### Steps to reproduce

1.open aniyomi normally
2.select any anime in library to download
3. Click on download
4.aniyomi processing to download
5.and hear is the error 'failed to download'

### Expected behavior

Fix this thing up as soon as possible it's annoying.

### Actual behavior

Whenever I try to download any anime, aniyomi just create a temp file and show download failed in application. And also it showing me failed to get extension list this is so annoying.

### Crash logs

[log.txt](https://github.com/jmir1/aniyomi/files/10739202/log.txt)

### Aniyomi version

v0.12.3.10

### Android version

Android 11

### Device

Redmi Note 8 Pro

### Other details

-

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Alixante** [comment]
Foe anyone that is reading this, I have a fast solution that worked for me. So stop all of the downloads from downloads in configuration, go to archives and eliminate the temp files of the chapter, go back to aniyomy and try to download. It should work

**Comment by BornAsSlayer** [comment]
Guys do you have any other workaround for this issue. I was not able to fix it through the above workaround. Btw where is the archive, I deleted the temp files from the file manager and it doesn't seem to help.

**Comment by Alixante** [comment]
> Guys do you have any other workaround for this issue. I was not able to fix it through the above workaround. Btw where is the archive, I deleted the temp files from the file manager and it doesn't seem to help.

So you have to go to the aniyomi folder in your phone, go to downloads and to the source. Then search for the anime you want and the specific episode. If there is a big archive, what you think is tye size of the video, it probably did download. Change its name to the name of the episode without the temp and eliminate the rest. If not, just eliminate all of the archives inside the folder and change its name to the episode de without temp

**Comment by DentyTxR** [comment]
quite a old issue, but in my case I used a different streaming server

select anime -> three dots -> settings -> preferred server

this does depend on the extension and if it supports/allows the changing of the streaming server, so if you aren't able to do the above try another extension
(had this issue with gogoanime extension)
