### ISSUE TITLE
Resolution error

### ISSUE THREAD

**Issue by JustAnOtaku178** [aniyomiorg/aniyomi#892]
### Steps to reproduce

Example not needed here.

### Expected behavior

I am a mobile data user so i prefer downloading at 720p so i expect a episode of 20-22 min to be the size of 100-200 mb.

### Actual behavior

Actually in extensions like consumeyol and allanime
When i downloaded in 720p instead of downloading in 720x1280 it is downloading in 1280x720 resulting in a size of 600mb per episode!!

### Crash logs

There is no crash log it just has a higher resolution

![Screenshot_2023_0215_191551](https://user-images.githubusercontent.com/125470858/219044389-ebdeec46-17de-4a67-8e0d-712eecd3b7bd.jpg)

### Aniyomi version

0.12.3.8

### Android version

Android 11

### Device

Vivo Y21T

### Other details

I expect such a major issue to be fixed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
most anime is made with the aspect ratio of 16:9 meaning 1280x720 should be the correct resolution
also i don't see how downloading 720x1280 would affect size since mathematically 1280x720 = 1280x720
i see this issue as just a misunderstanding
