### ISSUE TITLE
Aniyomi update

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#893]
### Steps to reproduce

Update the stable version of aniyomi with new video player which supports subtitles and app with new ui similar to tachiyomi.

### Expected behavior

Aniyomi Update to 13.4.1

### Actual behavior

I hope the app updated version releases soon

### Aniyomi version

0.12.3.10

### Android version

Andriod 13

### Device

Samsung Galaxy F23 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
rejoice
