### ISSUE TITLE
Aniyomi can't get any manga extensions

### ISSUE THREAD

**Issue by YouSummoner** [aniyomiorg/aniyomi#894]
### Steps to reproduce

1. Open Aniyomi
2. Go to browse tab
3. Go to manga extensions tab

### Expected behavior

All manga extensions should load

### Actual behavior

An error pops up saying "failed to get extensions list"

### Aniyomi version

0.12.3.10

### Android version

Android 12.1

### Device

Realme XT 

### Other details

I've tried installing Tachiyomi and Tachiyomi J2K.
Both apps are loading manga extensions properly.
Also Aniyomi is able to load all anime extensions properly.
When I updated manganato extension through Tachiyomi, it stopped showing in Aniyomi altogether.
Please push an update to the app ASAP.
![Screenshot_20230216-223543_Aniyomi](https://user-images.githubusercontent.com/107224555/219439750-c6b4b10a-64ed-4fe2-be65-5777dff87af7.png)
![Screenshot_20230216-221916_TachiyomiJ2K](https://user-images.githubusercontent.com/107224555/219439759-84ca4563-cad4-4fc0-9eaa-229515cf3c41.png)
![Screenshot_20230216-224725_Aniyomi](https://user-images.githubusercontent.com/107224555/219439952-a1ba4ca4-4b15-4610-877c-408e76f5bf51.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MikaelaMuller** [comment]
I have this same issue!

**Comment by FNickUzumaki** [comment]
I have the same Issue. also my aunt reads manga and has the same Issue.

**Comment by Ankurrawat-12** [comment]
Same issue

**Comment by Jiane15** [comment]
Same here 😔😔

**Comment by MrUNKNOWNN7** [comment]
Facing the same issue here as well. But I also checked Tachiyomi official app and it's working just fine there.

**Comment by FNickUzumaki** [comment]
Hope we can get a patch soon 😔😔

**Comment by JhDeLy-WB** [comment]
Que tengo hacer?

**Comment by Lassarcoste** [comment]
looks like the developers are still working on this problem, hoping for fixing the problem Asap 🥹

**Comment by JadenF** [comment]
same issue here

**Comment by SeekerP2** [comment]
All of you did you fix it? Im waiting for the new chapters

**Comment by KingVam** [comment]
> I have the same Issue. also my aunt reads manga and has the same Issue.

I don't think anyone in my family knows what manga is, so this is shocking.

**Comment by AbdulAziz144** [comment]
I have the same problem with manga extension saying "failed to get extension list". 
Phone Samsung galaxy J6 2018

**Comment by 360pWatcher** [comment]
Same Problem

**Comment by DRACOO7** [comment]
Same problem

**Comment by Rinka-Sei** [comment]
me too
device: Tecno Spark Go 2023
tried both stable and preview release

**Comment by FNickUzumaki** [comment]
beta build works for me, join their discord, the link its on the updates
chanel its the last comment.

**Comment by brodiebear** [comment]
Is there a fix for this ? I cant read my manga :(

**Comment by Koekiekoekie04** [comment]
Same, i still have this issue

**Comment by sreggopjb** [comment]
Also had this issue on the two devices I tried: Nothing Phone 1 and OnePlus 7 Pro

**Comment by Rinka-Sei** [comment]
Latest update on preview r6145 just fixed this issue, I can now read and watch on the same app

**Comment by Shivghadage** [comment]
Use this website and download manga extension externaly download it like apk and chack manga list of aniyomi you will find the extantion there https://tachiyomi.org/extensions/

**Comment by Shivghadage** [comment]
Use this Wedsite and download the extantion like apk you will find the extantion in your aniyomi manga extantion list 
https://tachiyomi.org/extensions/ 
And use the tor browser to load this website

**Comment by Quickdesh** [comment]
Duplicate of #844

**Comment by manjisama1** [comment]
I think its because tachiyomi is down

**Comment by Aaagaa** [comment]
نفس المشكلة لقد جربت جميع الاصدارات و فيها نفس الشيء

**Comment by Astrag17** [comment]
I can only see 4 extensions, and neither of them are loading. Please fix the issue asap.

**Comment by Secozzi** [comment]
There isn't any issue, the extension list [has been purged](https://tachiyomi.org/news/2024-01-13-goodbye). The fact that only 4 extensions show up is intended behaviour. Besides, which manga extensions are available are beyond our control regardless.

**Comment by kingBelmont** [comment]
I can't find asura scan anymore that's going on
