### ISSUE TITLE
Aniyomi Allanime extension fix 

### ISSUE THREAD

**Issue by Ashish7738** [aniyomiorg/aniyomi#895]
### Steps to reproduce

Don't know what it's mean

### Expected behavior

Show anime working fine

### Actual behavior

Not showing anime 

### Crash logs

domain name change

### Aniyomi version

0.12.3.8

### Android version

Android 11

### Device

Mi A2

### Other details

Here is fix :

https://drive.google.com/file/d/1b0AtdN5Yq7gu3r1JMPQwbesE4oRJnyze/view?usp=drivesdk

My blog update :   ***. Read this first  ***

https://1sciencetechnews.blogspot.com/2023/02/aniyomi-allanime-extension-fix.html

I have requested
Please support my YouTube channel
https://youtube.com/@animeedition2545

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Rohit0125** [comment]
It says you need to permission to access the file. Kindly give it since I cannot use allanime as well because of domain change. One more thing does the link leads to a modified version of aniyome?

**Comment by Ashish7738** [comment]
Now you can download

**Comment by Ashish7738** [comment]
I have requested

Please support my YouTube channel

***@***.***

**Comment by Rohit0125** [comment]
I will definitely support

**Comment by Ashish7738** [comment]
> allanime.site   

> To

> allanime.to

**Comment by ridoy829** [comment]
Thanks it's working. With original one it keeps showing field data error but this one seems working perfectly so far

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
