### ISSUE TITLE
Choose video quality before download or open on external player

### ISSUE THREAD

**Issue by GamingMajd** [aniyomiorg/aniyomi#896]
### Describe your suggested feature

Hello 
Please can you add an option to choose the quality before downloading and before opening the episode with an external player?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Hold download icon
