### ISSUE TITLE
Downloading manga and trying to install new sources doesn't work

### ISSUE THREAD

**Issue by Ringo1234ni** [aniyomiorg/aniyomi#910]
### Steps to reproduce

> Open anyomi

> To manga - open any manga download using the download icon or manually 

### Expected behavior

The download gets queued and gets downloaded.
The extension page loads the uninstalled extensions

### Actual behavior

The download gets queued but the download bar doesn't move I can't download new extension for manga the manga extension page doesn't lose new / not installed extensions.

### Aniyomi version

App version: 0.12.3.10 (standard, 7722361, 72, 2023-02-09T10:47Z) Android version: 12 (SDK 31) Android build ID: SKQ1.211103.001 test-keys Device brand: Redmi Device manufacturer: Xiaomi Device name: spes Device model: 2201117TG Device product name: spes_global

### Android version

Android 12

### Device

Redmi note 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AshishThakurashish** [comment]
There isn't any manga new sources of manga sites, only installed sources are showing. I accedently delete one source and now I don't able to reinstall it . 💀

**Comment by Jumpy85Plays** [comment]
Same with this but the app is still using storage for the previous downloads but I cant access any of the manga i have downloaded

**Comment by Ringo1234ni** [comment]
The manga download doesn't work but the anime download works
