### ISSUE TITLE
Please add 4anime.is source if possible 🙏🙏🙏🙏

### ISSUE THREAD

**Issue by RuDru-OP** [aniyomiorg/aniyomi#929]
### Describe your suggested feature

4anime.is is a good website after The OG 4anime died

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
It's just a zoro.to clone

**Comment by RuDru-OP** [comment]
> 

Its true but now zoro.to doesn't add anime episodes as fast as they used to

**Comment by Quickdesh** [comment]
plz add hindi anime and movie extensions to the app as there is no source for watching something in Hindi. there is currently only 1 hindi expansion which also doesn't work. some great extensions could be like katmoviehd, worldfree4u, raretoonsindia, deadtoonsindia etc.

**Comment by RuDru-OP** [comment]
> plz add hindi anime and movie extensions to the app as there is no source for watching something in Hindi. there is currently only 1 hindi expansion which also doesn't work. some great extensions could be like katmoviehd, worldfree4u, raretoonsindia, deadtoonsindia etc.

why did you close the issue which extension has been added for Hindi movies??

**Comment by Quickdesh** [comment]
Read the comment I sent

**Comment by Quickdesh** [comment]
Did it twice now god dammit
I am little dumb 
Sorry seriously
