### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by demon456blade** [aniyomiorg/aniyomi#931]
### Steps to reproduce

First you go to categories
Then switch from one to the other
The bug comes

### Expected behavior

What actually should happen is nothing like this error

### Actual behavior

The bug comes and ruins everything 

### Aniyomi version

0.14.3-6132

### Android version

Android 12

### Device

Red magic 7s pro

### Other details

![Screenshot_2023-03-07-19-47-58-411](https://user-images.githubusercontent.com/82254389/223590195-e805c915-84cb-4b2d-bb26-30bf2ecb00ba.jpg)
![Screenshot_2023-03-07-19-47-24-273](https://user-images.githubusercontent.com/82254389/223590205-108404e9-be8c-410e-aa0b-c60c76e9873b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by khonkhortisan** [comment]
Looks like this is fixed in r6141
