### ISSUE TITLE
Migration of multiple anime at the same time. 

### ISSUE THREAD

**Issue by Bhedant** [aniyomiorg/aniyomi#932]
### Describe your suggested feature

I wanted to migrate multiple of my anime from gogo to zoro but i have to individually click on the anime and then the three dots and migrate. I wish we could migrate multiple anime at the same time by selecting the one's we want to. This could help us save time and is overall more efficient.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/777

**Comment by boredSage** [comment]
@quickdesh I understand TachiyomiSY (or other forks) can be used for the migration, however that's only for manga. AFAIK there isn't such an alternative for anime
