### ISSUE TITLE
Downloads very slow or don't finish properly 

### ISSUE THREAD

**Issue by Ayanelixer** [aniyomiorg/aniyomi#943]
### Steps to reproduce

1)go to an anime from Library (gogoanime source frequently does this issue)
2) Bulk Download more than 1 episode
3)wait 20 minutes for a single 100MB episode despite internet having a 100mbps speed
4) watch episode and realise only 2 out 24 minutes downloaded 

### Expected behavior

The episode finishes is 3-4 minutes (like it used to)
The episode should be viewable in full

### Actual behavior

Partial episode downloaded
3-4 minute download time

### Aniyomi version

0.12.3.10

### Android version

Android 12

### Device

Samsung S10e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lonewolf0211** [comment]
The slow download issue is likely server throttling due to excessive bandwidth usage. I've noticed speeds slowing as well.

I have also experienced broken downloads and video corruption. Sometimes videos don't play at all and other times some small sections have to be skipped like a bad dvd. 

Sometimes redownloading vids will fix.
