### ISSUE TITLE
Can't watch any anime extension gogoanime isn't loding anime

### ISSUE THREAD

**Issue by 2067manishkulkarni** [aniyomiorg/aniyomi#946]
### Steps to reproduce

Open anime 
Start episode 
Error*

### Expected behavior

After starting to watch the episode it should load without any problems if you have good internet connection
 

### Actual behavior

After starting the episode it keeps loding forever even when I have good internet connection

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Device

Vivo Y15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 2067manishkulkarni** [comment]
![Screenshot_20230317_232214](https://user-images.githubusercontent.com/103825195/226203543-fdfbe7bb-41bf-44d1-ba78-93cb0c780a14.jpg)

**Comment by 2067manishkulkarni** [comment]
Also even though I can see the extension list it is showing me a "cannot show extension list" error
Please fix these issues as quickly as possible
THANK YOU

**Comment by Jayrudra** [comment]
Me to

**Comment by Tomhurtz1i7** [comment]
This is happening to me too

**Comment by Coop04** [comment]
Same here

**Comment by Dark-Knight987** [comment]
It isn't even loading all video qualities and nor it is downloading most of the animes.
