### ISSUE TITLE
Copy stream link

### ISSUE THREAD

**Issue by venkat2305** [aniyomiorg/aniyomi#948]
### Describe your suggested feature

Ability to copy the stream link which we can use to download/stream ( like in cloudstream)

https://user-images.githubusercontent.com/55329452/226178623-2217152d-87fb-4516-b90c-8fca3b30d93c.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Helpful-Neko** [comment]
What app is that 🤔

**Comment by venkat2305** [comment]
Cloudstream

**Comment by SiriosDev** [comment]
I see that this issue shows as completed, but how? there doesn't seem to be anything to copy, maybe it was to be closed as not planned?

**Comment by fakebhai** [comment]
> I see that this issue shows as completed, but how? there doesn't seem to be anything to copy, maybe it was to be closed as not planned?

long press on download button

**Comment by SiriosDev** [comment]
> > I see that this issue shows as completed, but how? there doesn't seem to be anything to copy, maybe it was to be closed as not planned?
> 
> long press on download button

oh perfect! that was the one long click I missed, I had tried on the bottom bar buttons that appears during selection but nothing happened besides the button name. Btw now having figured it out it all works 👌
