### ISSUE TITLE
External downloader doesn't download any episode with Anitube, Anime Fire, Animension, Gogoanime, Haho.moe, zoro.to, Hentai mamaextensions

### ISSUE THREAD

**Issue by ghost** [aniyomiorg/aniyomi#949]
### Steps to reproduce

1. Press download button for 2 seconds
2. Select external downloader
3. The episode doesn't download

### Expected behavior

The episode should been downloaded using external downloader 1DM+

### Actual behavior

The app says the download is concluded,but the download doesn't start, 

Animension extension the download doesn't say it's conclude, but as well doesn't start

### Crash logs

App version: 0.12.3.10 (standard, 7722361, 72, 2023-02-09T10:47Z)
Android version: 12 (SDK 31)
Android build ID: S0RCS32.41-10-19-12
Device brand: motorola
Device manufacturer: motorola
Device name: caprip
Device model: moto g(30)
Device product name: caprip_retail

### Aniyomi version

0.12.3.10

### Android version

Android 12 S

### Device

Moto G30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by pa672** [comment]
Same problem
