### ISSUE TITLE
Superstream no new episodes or movies since Dec 2022

### ISSUE THREAD

**Issue by hvroun1** [aniyomiorg/aniyomi#953]
### Steps to reproduce

Clicking on any new episode wont load.

### Expected behavior

Clicking on any new episode should stream\download.

### Actual behavior

No new episodes or movies since Dec last year. it shows info for the shows but trying to open it results in no links found. 

### Aniyomi version

0.12.3.10

### Android version

13

### Device

mi a1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
