### ISSUE TITLE
Please add hindi extensions

### ISSUE THREAD

**Issue by ErenMFYeager** [aniyomiorg/aniyomi#955]
### Describe your suggested feature

plz add hindi anime and movie extensions to the app as there is no source for watching something in Hindi. there is currently only 1 hindi expansion which also doesn't work. some great extensions could be like katmoviehd, worldfree4u, raretoonsindia, deadtoonsindia etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by cbpt** [comment]
I think the extensions are created by third party and not aniyomi developer

**Comment by Quickdesh** [comment]
To add/fix extensions, make a github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
