### ISSUE TITLE
The latest vertion manga system Didn't working Know

### ISSUE THREAD

**Issue by MdOmarHossen** [aniyomiorg/aniyomi#958]
### Steps to reproduce

![Screenshot_2023-03-27-23-47-57-65_dd604340c1d7941d42aee14dd16e00e8](https://user-images.githubusercontent.com/121655978/228024301-431411b7-d5cf-4dc6-81ec-f970a50a7242.jpg)

### Expected behavior

Didn’t Know

### Actual behavior

The latest vertion manga system Didn't working Know

### Crash logs

![Screenshot_2023-03-27-23-47-57-65_dd604340c1d7941d42aee14dd16e00e8](https://user-images.githubusercontent.com/121655978/228025030-9025a4dd-d65f-4315-9c8c-19c09c1f0ac8.jpg)

### Aniyomi version

0.12.3.10

### Android version

12

### Device

Realme C25s

### Other details

The latest vertion manga system Didn't working Know

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by gfrdev** [comment]
after trying other versions, it's proven to be the server itself - as in tachiyomi has updated their sources data formatting and aniyomi is behind a commit or two on this

it cannot be solved by end users without editing the source code to change the URL referenced for this API, or changing the formatting for the API's data

luckily, it should be a simple enough fix once the issue line is found

**Comment by abdallahmehiz** [comment]
not enough details
