### ISSUE TITLE
Player skips 5seconds randomly

### ISSUE THREAD

**Issue by Shah741** [aniyomiorg/aniyomi#959]
### Steps to reproduce

1. Get a extension. I had Yomiroll.
2. Download an anime episode. I downloaded ep1 from The Vampire Does In No Time.
3. Play the episode. Randomly the player skips about 5 seconds from the playback and even when you rewind, the same part won't be played but skipped.

### Expected behavior

It should play continuously.

### Actual behavior

It skipped a few seconds.

### Aniyomi version

App version: 0.12.3.10 (standard, 7722361, 72, 2023-02-09T10:47Z) 

### Android version

Android version: 11 (SDK 30) Android build ID: RP1A.200720.011 

### Device

Redmi Note 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lexeloi** [comment]
bump. i have the same issue but with aniwave.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/914
