### ISSUE TITLE
Unable to Uninstall in samsung mobiles

### ISSUE THREAD

**Issue by cozian1** [aniyomiorg/aniyomi#964]
### Steps to reproduce

After installing in samsung even if you don't have a memory card you won't be able to uninstall it 

Tried putting memory card still unable to uninstall 

### Expected behavior

App should uninstall

### Actual behavior

Not uninstalling

### Aniyomi version

0.12.3.10

### Android version

12

### Device

Samsung f23

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by cozian1** [comment]
No the app I can uninstall the extentions but the unable to install the app

**Comment by shiroaes** [comment]
Please send a screenshot of what you see, I can't understand what you mean by "can't uninstall the app", that's just impossible, I'm 100% Aniyomi is not a pre-installed app.

**Comment by shiroaes** [comment]
Please send a screenshot of what you see, I can't understand what you mean by "can't uninstall the app", I'm 100% Aniyomi is not a pre-installed app.

**Comment by shiroaes** [comment]
Never seen this before. Have you tried adb uninstall? 

1. Connect your device through USB and enable USB debugging mode.

3. Run:

```shell
$ adb devices
List of devices attached
<your-device-id>        device

$ adb -s <your-device-id> uninstall xyz.jmir.tachiyomi.mi
```

Please run these commands above and provide the output.

If nothing works, restart your phone and try again.

---

1. Is your device rooted?
2. Are you using a custom One UI ROM?

---

- https://forum.xda-developers.com/t/uninstall-any-apps-via-adb-no-root.3738105/
- https://android.stackexchange.com/questions/179575/how-to-uninstall-a-system-app-using-adb-uninstall-command-not-remove-via-rm-or

**Comment by cozian1** [comment]
No my device is not rooted and I am not using an custom rom 

Ok app is Uninstalled with adb platform tools 

Thanks
