### ISSUE TITLE
Subtitles size control

### ISSUE THREAD

**Issue by some1onLSD** [aniyomiorg/aniyomi#967]
### Describe your suggested feature

Add option to control the subtitle size in the player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Added in 7f9255b51391f6e9816a28f9d5ccef0a35c358f4
