### ISSUE TITLE
Option to compensate phone motion by moving the image during e.g. car rides.

### ISSUE THREAD

**Issue by Asmageddon** [aniyomiorg/aniyomi#969]
### Describe your suggested feature

For example, when the phone is jilted left a bit, the image would move right. This would have to be 1) high-pass filtered so that less chaotic, purposeful movements aren't compensated, but the random and sudden jitter is, and 2) buffered so that small movements are fully compensated, but big ones don't move the image offscreen.

Throughout the process, the image should slowly drift back into the center of the view, with the aim being to reduce the sudden motions that make it difficult to read or tell what's going in a scene.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Not feasible

**Comment by Asmageddon** [comment]
@Quickdesh If I may ask, why not? It's possible to get sensor data fast enough, and while to do it perfectly you'd need to track the head-device spatial relationship, a naive implementation should still increase watch/read-ability massively.

**Comment by Quickdesh** [comment]
- It's such a very high cost very low return type of feature. 
- For the most part it is just going to annoy users
- Lower end devices will not be able to benefit from it at all
