### ISSUE TITLE
Thumbnail and title for every episode 

### ISSUE THREAD

**Issue by rks2000** [aniyomiorg/aniyomi#971]
### Describe your suggested feature

There should be thumbnail for every anime episodes and Titles for the episodes. I know some extension does have episode titles but some doesn't have.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Thumbnails are not going to be added as it puts stress on the sources. 

Episode titles are provided by the source. If they don't provide it then they can't be shown on aniyomi
