### ISSUE TITLE
add local subtitle button

### ISSUE THREAD

**Issue by Imon24** [aniyomiorg/aniyomi#974]
### Describe your suggested feature

The beta version (r-6145) is pretty good. But sometimes it crashes. I think it will be fixed in the upcoming stable version.🥰
 Most of the website don’t allow us to watch dubbed anime with subtitle so please add an option to add local subtitle from our mobile storage.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by abdallahmehiz** [comment]
Add in #1206
