### ISSUE TITLE
🔺🔹( Feature Request )🔹🔺Very Important 🙏

### ISSUE THREAD

**Issue by Unknown07070** [aniyomiorg/aniyomi#979]
### Describe your suggested feature

![Screenshot_2023-04-24-20-18-25-24_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/131685490/234024449-03fa7f28-e2d7-4c64-905e-2118e0f68dc8.jpg)

((( I want Features Like TachiJ2k Apk ))) 
Edit 👉👉👉👉👉👉 Profile, Titles,  Status Everything Customizable > For Aniyomi Apk. ▫️▫️▫️▪️▪️▪️▪️🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺

### Other details

((( I want Features Like TachiJ2k Apk ))) 
Edit 👉👉👉👉👉👉 Profile, Titles,  Status Everything Customizable > For Aniyomi Apk. ▫️▫️▫️▪️▪️▪️▪️🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
![Screenshot_2023-04-24-20-18-25-24_5901a79de973a50c74cff4cbb6149856](https://user-images.githubusercontent.com/131685490/234025692-7ba44290-22f6-4d81-8766-076edaf9ea64.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by RuDru-OP** [comment]
Bro What even Is that feature. You already have the reset cover, but yeah i get it you want a fully custom cover from your own gallery right?

**Comment by Unknown07070** [comment]
> Bro What even Is that feature. You already have the reset cover, but yeah i get it you want a fully custom cover from your own gallery right?

Bro i want everything customizable name, statue everything just download tachij2k👈 apk and check it out 🙏

**Comment by Unknown07070** [comment]
Bro i want everything customizable name, statue everything just download tachij2k👈 apk and check it out 🙏

**Comment by Unknown07070** [comment]
Bro i want everything customizable name, statue everything just download tachij2k👈 apk and check it out 🙏

**Comment by RuDru-OP** [comment]
You were right bro the ui of this app is way better. I wonder when it will be implemented

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/237
