### ISSUE TITLE
Google drive index issue

### ISSUE THREAD

**Issue by itzswagking** [aniyomiorg/aniyomi#987]
### Steps to reproduce

1. Put in two paths separated by a comma 

### Expected behavior

This should show all the folder in  both gdrive index 

### Actual behavior

This showed only the folders in first gdrive index

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Device

Samsung s20 fe 5g

### Other details

![Screenshot_20230501_205343_Aniyomi](https://user-images.githubusercontent.com/121341738/235477360-af12b4c8-9f28-4ac9-9177-f1eab85fdf5b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
To add extensions, make a Github issue here if it does not exist already

https://github.com/aniyomiorg/aniyomi-extensions
