### ISSUE TITLE
Misma firma

### ISSUE THREAD

**Issue by Pokoma** [aniyomiorg/aniyomi#990]
### Steps to reproduce

Al tener las dos apps "Tachiyomi y Aniyomi" que tienen la misma firma de paquete, al tener que conectar MyAnimeList me lleva a hacia Tachiyomi y no a Aniyomi

### Expected behavior

Iniciar sesión en MyAnimeList en Aniyomi

### Actual behavior

Me lleva hacia Tachiyomi donde ya tengo sesión iniciado

### Aniyomi version

0.12.3.10

### Android version

Android 13

### Device

Samsung A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Android Settings --> Apps --> Tachiyomi --> Remove the option for open links by default for MAL
