### ISSUE TITLE
[⭐FR] Add non-cancellable loading dialog for external player

### ISSUE THREAD

**Issue by kairusds** [aniyomiorg/aniyomi#998]
### Describe your suggested feature

Add a dialog that's non-cancellable and has a loading progress to indicate the status of loading the anime for the external player since it's not clear if it's really loading it or not.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Sounds like a Issue, which varies with each external player.
Because VLC shows a loading screen.

**Comment by abdallahmehiz** [comment]
This is more of an external players issue than an Aniyomi one.
