### ISSUE TITLE
Manga Extension Issue 

### ISSUE THREAD

**Issue by Rarnoz** [aniyomiorg/aniyomi#999]
### Steps to reproduce

Failed To Get Extension List

### Expected behavior

It should display the extension list

### Actual behavior

![Screenshot_2023-05-17-14-54-21-78_dd604340c1d7941d42aee14dd16e00e8](https://github.com/jmir1/aniyomi/assets/94232411/9066d706-239b-46bf-a22d-d516bf466732)

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Device

RealMe UI 2.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Bruh-Man14** [comment]
I also have the issue. Same android version.

**Comment by Lyiidayooo** [comment]
same problem on android 12

**Comment by Henryy7y** [comment]
> same here on Android13

Same here

**Comment by niraj-kumar-r** [comment]
Same problem on Android 13, Realme ui 4

**Comment by Secozzi** [comment]
For everyone having this problem, you can fix it by downloading preview from [the website](https://aniyomi.org/download/)

**Comment by Quickdesh** [comment]
Duplicate of #844
